-- Expand the Elite Prompt Library: 3 more prompts per existing subcategory
-- (from 2 to 5), rounding out the difficulty range with 'advanced' entries and
-- leaning into prompts that push toward better results: iteration, critique,
-- diagnosis, and refinement, not just first-draft generation.
insert into public.prompts (subcategory_id, title, body, swap_note, difficulty, sort_order)
select s.id, x.title, x.body, x.swap_note, x.difficulty, x.sort_order
from public.prompt_subcategories s
join public.prompt_categories c on c.id = s.category_id
join (values
  -- writing / academic
  ('writing', 'academic', 'Strengthen a thesis statement', 'Here is my thesis statement: [paste it]. Make it more specific and arguable, and tell me what is currently too vague about it.', 'swap: ask for 3 alternative phrasings if the first rewrite still feels flat.', 'beginner', 3),
  ('writing', 'academic', 'Find counterarguments to your position', 'My argument is: [paste your argument]. Give me the 3 strongest counterarguments a skeptical reader would raise, so I can address them.', 'swap: ask it to rank the counterarguments by how damaging they are to your case.', 'intermediate', 4),
  ('writing', 'academic', 'Tighten an academic paragraph', 'Rewrite this paragraph to be 30 percent shorter without losing any of the argument, keeping the academic tone: [paste paragraph]', 'swap: ask for a version that also improves the topic sentence.', 'advanced', 5),
  -- writing / professional
  ('writing', 'professional', 'Rewrite a message to be more direct', 'Rewrite this message to get to the point in the first sentence, cut the hedging, and keep it polite: [paste message]', 'swap: ask for a version 50 percent shorter if it is still too long.', 'beginner', 3),
  ('writing', 'professional', 'Prepare talking points for a meeting', 'I have a meeting about [topic] with [who]. Give me 4 talking points and one question I should ask.', 'swap: add the outcome you want from the meeting so the points build toward it.', 'intermediate', 4),
  ('writing', 'professional', 'Turn a complaint into a constructive message', 'I am frustrated about [situation]. Help me turn this into a calm, constructive message that states the problem and asks for a specific fix.', 'swap: ask for a version that also acknowledges the other side.', 'advanced', 5),
  -- writing / social
  ('writing', 'social', 'Write 5 hook variations for one idea', 'Write 5 different opening lines for a post about [topic], each using a different angle: a question, a stat, a story, a bold claim, a relatable moment.', 'swap: ask which one it thinks would perform best and why.', 'beginner', 3),
  ('writing', 'social', 'Rewrite a caption for a different platform', 'Rewrite this caption for [platform], matching the tone and length that platform expects: [paste caption]', 'swap: ask what specifically changed and why, so you learn the pattern.', 'intermediate', 4),
  ('writing', 'social', 'Audit a post before you publish it', 'Review this post before I publish it: [paste post]. Tell me the weakest line, the strongest line, and one specific edit that would improve it most.', 'swap: ask it to rewrite only the weakest line, not the whole post.', 'advanced', 5),
  -- writing / creative
  ('writing', 'creative', 'Develop a flat character', 'This character feels flat: [describe character]. Give me 3 specific details, a fear, a habit, a contradiction, that would make them feel real.', 'swap: ask how those details would change one scene they are in.', 'beginner', 3),
  ('writing', 'creative', 'Write dialogue that reveals character', 'Write a short exchange between [character A] and [character B] about [topic] where neither says exactly what they mean.', 'swap: ask for a version where the subtext is even less obvious.', 'intermediate', 4),
  ('writing', 'creative', 'Diagnose why a scene feels flat', 'This scene feels flat to me: [paste scene]. Tell me specifically what is missing: tension, stakes, sensory detail, or something else.', 'swap: ask for one rewritten line that fixes the biggest issue.', 'advanced', 5),
  -- writing / technical
  ('writing', 'technical', 'Explain what a piece of code does, line by line', 'Go through this code line by line and explain what each part does in plain English: [paste code]', 'swap: ask it to only explain the parts you flag as confusing, not the whole thing.', 'beginner', 3),
  ('writing', 'technical', 'Get a second opinion on an approach', 'I am planning to solve [problem] by doing [your approach]. What are the tradeoffs, and is there a simpler way?', 'swap: ask specifically about edge cases your approach might miss.', 'intermediate', 4),
  ('writing', 'technical', 'Review code for a specific concern', 'Review this code specifically for [performance, security, or readability]: [paste code]. Do not comment on anything else.', 'swap: run it again for a second concern once the first pass is fixed.', 'advanced', 5),

  -- image / generation
  ('image', 'generation', 'Iterate toward a specific result', 'Here is what I got: [describe the result]. Here is what I actually wanted: [describe the goal]. What should I change in the prompt to close that gap?', 'swap: paste the exact prompt you used so the suggestion is more precise.', 'beginner', 3),
  ('image', 'generation', 'Combine two references into one style', 'A [subject], combining the color palette of [reference A] with the composition style of [reference B].', 'swap: swap which reference controls color versus composition.', 'intermediate', 4),
  ('image', 'generation', 'Diagnose a muddled generation', 'This image came out muddled and unclear: [describe what is wrong]. Which part of the prompt is most likely causing that, and how do I fix it?', 'swap: ask for a simplified version of the prompt with fewer competing ideas.', 'advanced', 5),
  -- image / graphic-design
  ('image', 'graphic-design', 'Get feedback on a design direction', 'Here are 2 logo directions: [describe direction A and B]. Which one is more memorable and why?', 'swap: ask which one would work better in black and white only.', 'beginner', 3),
  ('image', 'graphic-design', 'Adapt one design across formats', 'I have a design for [format A]. Describe how to adapt the same look for [format B] without losing the brand feel.', 'swap: ask what has to change versus what should stay identical.', 'intermediate', 4),
  ('image', 'graphic-design', 'Critique a design before shipping it', 'Critique this design like a senior designer would: [describe the design]. What is the first thing a viewer notices, and is that the right thing?', 'swap: ask for one specific change that would improve hierarchy.', 'advanced', 5),
  -- image / editing
  ('image', 'editing', 'Match the edit style of a reference photo', 'Edit this photo to match the color and contrast style of [describe reference], without changing the subject.', 'swap: describe the reference in terms of warm/cool and high/low contrast if you do not have an example.', 'beginner', 3),
  ('image', 'editing', 'Fix a specific flaw without overcorrecting', 'This photo has [specific issue: too dark, too flat, color cast]. Fix only that issue and keep everything else the same.', 'swap: ask for a subtle and a strong version so you can compare.', 'intermediate', 4),
  ('image', 'editing', 'Get a second opinion on an edit', 'Here is what I changed: [describe edit]. Does this look natural, or does it look over-edited? Be specific about what gives it away.', 'swap: ask for the one adjustment that would fix it if it looks over-edited.', 'advanced', 5),
  -- image / photography-styles
  ('image', 'photography-styles', 'Describe a style you cannot name', 'I like photos that feel [describe the feeling, not a technical term]. What photography style or technique usually creates that feeling?', 'swap: ask for 2 reference photographers whose work matches that feeling.', 'beginner', 3),
  ('image', 'photography-styles', 'Blend two photography styles', 'A photo of [subject], blending [style A] with [style B]. Describe which style should dominate the lighting and which should dominate the composition.', 'swap: try the opposite dominance to see which reads better.', 'intermediate', 4),
  ('image', 'photography-styles', 'Push a style further than the obvious version', 'This result is technically [style], but it feels generic: [describe result]. What would make it feel like a more distinctive example of that style?', 'swap: ask for one specific, unexpected detail to add.', 'advanced', 5),
  -- image / text-in-image
  ('image', 'text-in-image', 'Fix text that rendered wrong', 'The text in this image came out garbled or misspelled. What usually causes that, and how do I prompt to avoid it next time?', 'swap: try shortening the text to 3 words or fewer if it keeps failing.', 'beginner', 3),
  ('image', 'text-in-image', 'Balance text and image so neither competes', 'An image with the text "[your text]" where the text is clearly readable but does not dominate the image. Describe the right size and placement.', 'swap: ask for a version with the text as a smaller, secondary element instead.', 'intermediate', 4),
  ('image', 'text-in-image', 'Design text for a specific mood', 'A graphic with the text "[your text]", where the lettering style itself should feel [urgent, calm, playful]. Describe the letterforms, not just the words.', 'swap: ask for 2 different letterform directions to compare.', 'advanced', 5),

  -- video / shot-types-camera-angles
  ('video', 'shot-types-camera-angles', 'Choose the right shot for the emotion', 'I want this moment to feel [emotion]: [describe the moment]. Which shot type and angle would support that feeling, and why?', 'swap: ask what shot type would undercut that feeling, so you know what to avoid.', 'beginner', 3),
  ('video', 'shot-types-camera-angles', 'Build shot variety into a sequence', 'I have 3 shots that are all the same type: [describe them]. Suggest how to vary the shot types so the sequence does not feel flat.', 'swap: ask which single shot should be the visual anchor of the sequence.', 'intermediate', 4),
  ('video', 'shot-types-camera-angles', 'Justify a shot choice like a director would', 'I am choosing between [shot option A] and [shot option B] for this moment: [describe moment]. Argue for each option, then tell me which you would pick.', 'swap: ask what a different genre would typically choose here.', 'advanced', 5),
  -- video / camera-movement
  ('video', 'camera-movement', 'Match movement to pacing', 'This moment should feel [slow and heavy / quick and energetic]: [describe the moment]. What camera movement fits that pacing?', 'swap: ask for a static, no-movement option too, for comparison.', 'beginner', 3),
  ('video', 'camera-movement', 'Avoid movement that feels arbitrary', 'I am using [camera movement] in this shot: [describe shot]. Does that movement serve the story, or does it feel decorative? Be direct.', 'swap: ask for the simplest movement that would still serve the story.', 'intermediate', 4),
  ('video', 'camera-movement', 'Plan a movement that builds across a scene', 'Describe how the camera movement should evolve across this scene, from the first beat to the last: [describe the scenes beats].', 'swap: ask which single moment should have the most dramatic movement.', 'advanced', 5),
  -- video / lighting
  ('video', 'lighting', 'Diagnose flat-looking lighting', 'This shot feels flat and lacks depth: [describe the lighting setup]. What is likely missing?', 'swap: ask for the single cheapest fix if you cannot add more lights.', 'beginner', 3),
  ('video', 'lighting', 'Light for a specific emotional read', 'I want this scene to feel [emotion]: [describe scene]. Describe a lighting setup, including direction and hardness, that supports that.', 'swap: ask how the same setup would need to change for the opposite emotion.', 'intermediate', 4),
  ('video', 'lighting', 'Reverse-engineer a lighting style', 'I want to recreate the lighting feel of [describe a reference]. Break down what is likely happening: key light, fill, contrast ratio.', 'swap: ask for a simplified version achievable with just one or two lights.', 'advanced', 5),
  -- video / drone-aerial
  ('video', 'drone-aerial', 'Plan a flight path for a story beat', 'I want an aerial shot that reveals [what you want revealed]. Describe a simple flight path that would accomplish that.', 'swap: ask for a version that reveals it more gradually versus all at once.', 'beginner', 3),
  ('video', 'drone-aerial', 'Choose altitude for the right feeling', 'This aerial shot should feel [intimate and close / vast and small]: [describe subject]. What altitude and distance fits that?', 'swap: ask how changing the time of day would change the feeling.', 'intermediate', 4),
  ('video', 'drone-aerial', 'Avoid a generic drone shot', 'This aerial shot idea feels generic: [describe the shot]. What would make it feel more specific to this location or story?', 'swap: ask for one unexpected element to include in frame.', 'advanced', 5),
  -- video / style-mood
  ('video', 'style-mood', 'Translate a mood into visual choices', 'The mood I want is [describe mood]. Translate that into specific choices: color temperature, contrast, and pace.', 'swap: ask for a mood board description you could show a collaborator.', 'beginner', 3),
  ('video', 'style-mood', 'Keep style consistent across multiple shots', 'I have established this style: [describe it]. Here is a new shot I am planning: [describe shot]. Does it fit, or would it break consistency?', 'swap: ask what small adjustment would make it fit better.', 'intermediate', 4),
  ('video', 'style-mood', 'Push a style past the obvious reference', 'My style reference is [describe reference], but I do not want it to feel like a copy. What can I change while keeping the core feeling?', 'swap: ask for 2 specific ways to make it more original.', 'advanced', 5),
  -- video / motion-pacing
  ('video', 'motion-pacing', 'Fix pacing that drags', 'This sequence feels like it drags: [describe the sequence]. What is the likely cause, and what is the simplest fix?', 'swap: ask for the exact point where you should cut in.', 'beginner', 3),
  ('video', 'motion-pacing', 'Build a rhythm across a sequence', 'Describe a cutting rhythm for this sequence that starts steady and builds to a peak: [describe the sequences beats].', 'swap: ask where the peak should land relative to the total length.', 'intermediate', 4),
  ('video', 'motion-pacing', 'Match pacing to music without music', 'I do not have the music yet, but I want this edit to feel like it is building to a beat drop. Describe the pacing pattern that would support that.', 'swap: ask for a version that builds more gradually, in case the music is more subtle.', 'advanced', 5),

  -- agents-automation / building-agents
  ('agents-automation', 'building-agents', 'Stress-test agent instructions', 'Here are the instructions I gave my agent: [paste instructions]. What edge case or ambiguous input would most likely break this?', 'swap: ask it to suggest the fix for the edge case it found.', 'beginner', 3),
  ('agents-automation', 'building-agents', 'Scope an agent that is trying to do too much', 'My agent is supposed to do all of this: [list tasks]. Which of these should be split into a separate agent, and why?', 'swap: ask which single task is most essential to keep if you had to cut the rest.', 'intermediate', 4),
  ('agents-automation', 'building-agents', 'Design a fallback for when an agent fails', 'My agent does [task] and sometimes fails at [specific point]. Design a fallback behavior for that failure so it does not just break silently.', 'swap: ask how the fallback should communicate the failure to a human.', 'advanced', 5),
  -- agents-automation / workflows
  ('agents-automation', 'workflows', 'Find the highest-value step to automate', 'Here are the steps in my process: [list them]. Which single step would save the most time if automated first?', 'swap: ask which step would be the easiest to automate, which may not be the same answer.', 'beginner', 3),
  ('agents-automation', 'workflows', 'Simplify an overcomplicated workflow', 'Here is my current workflow: [describe it]. Where are the unnecessary steps, and how would you simplify it?', 'swap: ask what would break if you removed the step it flags as unnecessary.', 'intermediate', 4),
  ('agents-automation', 'workflows', 'Design for the failure case, not just the happy path', 'This workflow assumes everything goes right: [describe it]. What is most likely to go wrong, and how should the workflow handle it?', 'swap: ask for the single most important error to handle first.', 'advanced', 5),
  -- agents-automation / integrations
  ('agents-automation', 'integrations', 'Decide if an integration is worth building', 'I am considering connecting [tool A] and [tool B] to save [describe the manual work]. Is this worth building, or is the manual work actually faster?', 'swap: give it your actual time estimate for the manual work so the comparison is accurate.', 'beginner', 3),
  ('agents-automation', 'integrations', 'Plan for an integration that might break', 'This integration between [tool A] and [tool B] depends on [what it depends on]. What would break it, and how would I notice?', 'swap: ask how urgently each failure mode would need to be fixed.', 'intermediate', 4),
  ('agents-automation', 'integrations', 'Choose the simplest integration approach', 'I am choosing between [approach A] and [approach B] to connect [tool A] and [tool B]. Which is simpler to maintain long-term, not just to build?', 'swap: ask what happens to each approach if one of the tools changes its interface.', 'advanced', 5),

  -- learning / self-teaching
  ('learning', 'self-teaching', 'Identify what to learn next', 'I just learned [topic]. Based on that, what is the most useful next thing to learn, and why does it build on what I know?', 'swap: ask for the thing you should NOT learn next, because it is a common distraction.', 'beginner', 3),
  ('learning', 'self-teaching', 'Turn a mistake into a lesson', 'I got this wrong: [describe the mistake]. Explain why it was wrong in a way that helps me avoid the same mistake in a different situation.', 'swap: ask for one other situation where the same mistake commonly happens.', 'intermediate', 4),
  ('learning', 'self-teaching', 'Test whether you actually understand something', 'I think I understand [topic] well enough to explain it. Ask me to explain it, then tell me honestly where my explanation was weak or vague.', 'swap: ask it to explain the same topic back to you first as a model answer.', 'advanced', 5),
  -- learning / quizzing-yourself
  ('learning', 'quizzing-yourself', 'Get quizzed with real-world scenarios', 'Instead of definitions, quiz me on [topic] using real scenarios where I have to apply it, not just recall it.', 'swap: ask for the scenarios to get progressively harder.', 'beginner', 3),
  ('learning', 'quizzing-yourself', 'Find your weakest area in a topic', 'Quiz me on [topic] across its different sub-areas, and track which sub-area I get wrong most often.', 'swap: once you know the weak area, ask for a quiz focused only on that.', 'intermediate', 4),
  ('learning', 'quizzing-yourself', 'Simulate a real exam or interview', 'Simulate a [exam/interview] on [topic], including follow-up questions if my first answer is incomplete, the way a real examiner would.', 'swap: ask for feedback on your answers only at the end, not after each one, to simulate real pressure.', 'advanced', 5),
  -- learning / explaining-hard-concepts
  ('learning', 'explaining-hard-concepts', 'Explain the same concept three ways', 'Explain [concept] three different ways: as a simple analogy, as a step-by-step process, and as a real example.', 'swap: ask which of the three explanations is easiest to misunderstand, so you can be careful there.', 'beginner', 3),
  ('learning', 'explaining-hard-concepts', 'Find the one idea a concept depends on', 'For [concept], what is the one underlying idea that, if I understand it, makes everything else make sense?', 'swap: ask for a simple test question that checks whether you actually understand that core idea.', 'intermediate', 4),
  ('learning', 'explaining-hard-concepts', 'Explain where a concept breaks down', 'Explain [concept], and also explain the edge case or exception where the simple version of it stops being true.', 'swap: ask why most explanations leave that exception out.', 'advanced', 5),

  -- money-work / freelancing
  ('money-work', 'freelancing', 'Decide whether to take on a project', 'Here is a project I am considering: [describe it]. Given [your situation, e.g. current workload, goals], should I take it?', 'swap: mention your rate and the project budget so the advice accounts for money too.', 'beginner', 3),
  ('money-work', 'freelancing', 'Handle scope creep professionally', 'A client is asking for more than we originally agreed on: [describe the extra ask]. Help me write a message that addresses it without sounding difficult.', 'swap: decide first whether you actually mind doing it for free, since that changes the message.', 'intermediate', 4),
  ('money-work', 'freelancing', 'Build a system instead of one-off decisions', 'I keep making ad hoc decisions about [recurring situation, e.g. rush jobs, revisions]. Help me turn this into a simple policy I can apply consistently.', 'swap: ask for the policy in one sentence you could literally put in a contract.', 'advanced', 5),
  -- money-work / proposals
  ('money-work', 'proposals', 'Make a generic proposal specific', 'This proposal feels generic: [paste it]. What would make it feel written specifically for this client?', 'swap: give it one real detail about the client so it can show you exactly how to weave it in.', 'beginner', 3),
  ('money-work', 'proposals', 'Lead with the outcome, not the process', 'This proposal describes what I will do, but not what the client gets. Rewrite it to lead with the outcome: [paste proposal]', 'swap: ask for a one-sentence version of the outcome you could use as an opening line.', 'intermediate', 4),
  ('money-work', 'proposals', 'Anticipate objections in a proposal', 'Here is my proposal: [paste it]. What objection is this client most likely to have, and how could the proposal address it before they ask?', 'swap: ask for 2 objections, ranked by how likely each one is.', 'advanced', 5),
  -- money-work / pricing
  ('money-work', 'pricing', 'Justify a price without over-explaining', 'I need to state my price for [project] without sounding apologetic or over-explaining. Help me write one confident sentence.', 'swap: ask for a version that includes a brief reason, for clients who expect one.', 'beginner', 3),
  ('money-work', 'pricing', 'Decide what is included at a given price', 'At [price], what should reasonably be included for [type of project], and what should count as a paid extra?', 'swap: ask how this changes at a lower and a higher price point.', 'intermediate', 4),
  ('money-work', 'pricing', 'Handle a client who says your price is too high', 'A client said my price is too high for [project]. Help me think through whether to hold the price, adjust scope, or walk away, and draft the response.', 'swap: tell it your walk-away point so the advice is not just theoretical.', 'advanced', 5),
  -- money-work / finding-clients
  ('money-work', 'finding-clients', 'Turn past work into proof that attracts clients', 'Here is a project I finished: [describe it]. Help me turn it into a short case study that would attract similar clients.', 'swap: ask for a one-line version you could use in a bio or profile.', 'beginner', 3),
  ('money-work', 'finding-clients', 'Identify your most valuable past client', 'Here are the clients I have worked with: [list them briefly]. Which type was most valuable, not just by pay but by fit, and how do I find more like them?', 'swap: separate "most valuable" by pay versus by how enjoyable the work was, since they may differ.', 'intermediate', 4),
  ('money-work', 'finding-clients', 'Diagnose why outreach is not converting', 'My outreach messages are not getting replies. Here is a typical one: [paste message]. What is the most likely reason it is being ignored?', 'swap: ask for the single change most likely to improve the reply rate.', 'advanced', 5),

  -- audio / voiceover
  ('audio', 'voiceover', 'Fix a script that sounds unnatural read aloud', 'This script sounds stiff when read aloud: [paste script]. Rewrite it to sound like natural speech.', 'swap: read the rewrite aloud yourself to check it actually sounds better.', 'beginner', 3),
  ('audio', 'voiceover', 'Match pacing to the visual it accompanies', 'This voiceover needs to match [describe the pacing of the visual, e.g. quick cuts, a slow reveal]. Adjust the scripts rhythm and sentence length to fit.', 'swap: ask for a version with shorter sentences if it still feels too dense.', 'intermediate', 4),
  ('audio', 'voiceover', 'Direct a specific vocal performance', 'I want this line delivered with [specific quality, e.g. restrained confidence, quiet urgency]: [paste line]. Describe the delivery the way a director would give notes: pace, emphasis, pauses.', 'swap: ask for a contrasting delivery too, so you can compare which fits better.', 'advanced', 5),
  -- audio / sound-design
  ('audio', 'sound-design', 'Decide what sound is missing', 'This scene feels incomplete without sound: [describe scene]. What sound is most likely missing that would make it feel real?', 'swap: ask which sound would have the biggest impact if you can only add one.', 'beginner', 3),
  ('audio', 'sound-design', 'Use silence intentionally', 'Where in this scene would silence, or near-silence, be more effective than sound: [describe the scenes moments]?', 'swap: ask what should immediately follow the silence to make it land.', 'intermediate', 4),
  ('audio', 'sound-design', 'Layer sound for depth without clutter', 'I want this scene to feel layered, not empty, but I am worried about it sounding cluttered: [describe scene]. How many sound layers is reasonable, and how do I keep them from competing?', 'swap: ask which layer should be quietest so the others have room.', 'advanced', 5),
  -- audio / music
  ('audio', 'music', 'Match music to a scene that lacks direction', 'I am not sure what music this scene needs: [describe scene]. Ask me questions that would help narrow it down.', 'swap: answer its questions, then ask for the description again with that context.', 'beginner', 3),
  ('audio', 'music', 'Avoid music that fights the dialogue', 'This scene has dialogue and I do not want the music to compete with it: [describe scene]. What kind of music would support the scene without pulling focus?', 'swap: ask specifically how the music should change during the dialogue versus around it.', 'intermediate', 4),
  ('audio', 'music', 'Use music to signal a turning point', 'This is the turning point of the piece: [describe the moment]. How should the music shift here to signal that change to the audience?', 'swap: ask how subtle or obvious that shift should be, given the tone of the piece.', 'advanced', 5)
) as x(cat_slug, sub_slug, title, body, swap_note, difficulty, sort_order)
  on x.cat_slug = c.slug and x.sub_slug = s.slug;
