-- AI agents & automation, Basic tier (days 1-30). Authored content, UNPUBLISHED until a person reviews it in Admin.
insert into public.day
  (track_id, tier_id, day_number, title, objective, lesson_md, skill_focus, assignment_md, rubric,
   est_minutes, is_published, credit_budget, submission_type, ai_evaluate, requires_review)
select t.id, ti.id, v.n, v.title, v.objective, v.lesson_md, v.skill_focus, v.assignment_md, v.rubric,
       v.est_minutes, false, null, v.submission_type, v.ai_evaluate, v.requires_review
from public.track t
join public.tier ti on ti.track_id = t.id and ti.slug = 'basic'
cross join (values
  (1, $t1a$Agents vs chatbots vs automations$t1a$, $t1b$Tell the three apart and choose the right one for a task.$t1b$, $t1c$A **chatbot** answers when you ask. An **automation** runs fixed steps when something happens (a form is filled, an email arrives). An **agent** is given a goal, decides which steps and tools to use, and adapts along the way.

Rule of thumb: if the steps never change, use an automation. If judgment is needed, use an agent, with limits. [CREAO](https://agent.creao.ai/@Sonofpeace) (referral link) is our recommended place to build and run agents; others include Zapier, Make and n8n.$t1c$, $t1d$Agents vs chatbots vs automations$t1d$, $t1e$List five tasks from your life or work. For each, say chatbot, automation or agent and why, in one sentence.$t1e$, $t1f$[{"criterion": "Correct classification", "max_points": 45, "guidance": "Choices match the definitions."}, {"criterion": "Reasons are specific", "max_points": 35, "guidance": "Not generic."}, {"criterion": "Realistic tasks", "max_points": 20, "guidance": "Real examples."}]$t1f$::jsonb, 15, 'text', false, false),
  (2, $t2a$Map a workflow before automating it$t2a$, $t2b$Draw the current steps, then find what to automate.$t2b$, $t2c$Never automate a mess. Write the workflow as steps: trigger, inputs, decisions, outputs, who is involved. Mark steps that are repetitive, rule-based or slow. Those are candidates.$t2c$, $t2d$Map a workflow before automating it$t2d$, $t2e$Map one real workflow (six to twelve steps). Mark which steps to automate and which stay human, with reasons.$t2e$, $t2f$[{"criterion": "Workflow is clear", "max_points": 35, "guidance": "Steps are complete."}, {"criterion": "Candidates chosen well", "max_points": 35, "guidance": "Sensible."}, {"criterion": "Human steps protected", "max_points": 30, "guidance": "Judgment stays human."}]$t2f$::jsonb, 20, 'text', false, false),
  (3, $t3a$Write an agent's job description$t3a$, $t3b$Give an agent a role, goal, limits and output format.$t3b$, $t3c$A good agent brief has: **role**, **goal**, **inputs it receives**, **tools it may use**, **rules and limits**, **output format** and **when to stop and ask a human**. Vague briefs cause vague behaviour.$t3c$, $t3d$Write an agent's job description$t3d$, $t3e$Write a job description for one agent (about 200 words) covering all seven parts.$t3e$, $t3f$[{"criterion": "All parts present", "max_points": 40, "guidance": "Seven parts."}, {"criterion": "Limits are concrete", "max_points": 35, "guidance": "Clear rules."}, {"criterion": "Escalation defined", "max_points": 25, "guidance": "When to stop and ask."}]$t3f$::jsonb, 20, 'text', false, false),
  (4, $t4a$Your first agent$t4a$, $t4b$Build a simple agent that completes one task.$t4b$, $t4c$Build the simplest useful agent: for example one that turns messy notes into a tidy summary and action list. Run it five times on different inputs. Record what works and what does not.$t4c$, $t4d$Your first agent$t4d$, $t4e$Build your first agent. Submit its brief, five test inputs with outputs (short excerpts), and a list of failures.

**Evidence:** paste *direct* links to screenshots (ending .png/.jpg/.webp), one per line, and describe what they show.$t4e$, $t4f$[{"criterion": "Agent does the task", "max_points": 40, "guidance": "Outputs are useful."}, {"criterion": "Tested on five inputs", "max_points": 35, "guidance": "Variety."}, {"criterion": "Failures noted", "max_points": 25, "guidance": "Honest."}]$t4f$::jsonb, 40, 'link', false, false),
  (5, $t5a$Tools and permissions: least privilege$t5a$, $t5b$Give an agent only what it needs.$t5b$, $t5c$Agents can read email, edit files, send messages, spend money. Each tool is a risk. Give **read-only** where possible, require approval for sending or deleting, and log actions. Never share passwords with an agent.$t5c$, $t5d$Tools and permissions: least privilege$t5d$, $t5e$For your agent, list every tool/permission it has, why it needs it and which need human approval.$t5e$, $t5f$[{"criterion": "Permissions justified", "max_points": 40, "guidance": "Each has a reason."}, {"criterion": "Least privilege", "max_points": 35, "guidance": "Minimal access."}, {"criterion": "Approvals defined", "max_points": 25, "guidance": "For risky actions."}]$t5f$::jsonb, 20, 'text', false, false),
  (6, $t6a$Module project: a supervised single-task agent$t6a$, $t6b$Deliver an agent with a brief, limits and test evidence.$t6b$, $t6c$Show Module 1. Deliver a **single-task agent** with a clear brief, least-privilege tools, human approval for risky steps and tested on ten inputs.

Your work is scored on the rubric below. You can revise and resubmit.$t6c$, $t6d$Module project: a supervised single-task agent$t6d$, $t6e$Submit: the agent brief, permissions table, ten test cases with results, and what you would fix next.

**Evidence:** paste *direct* links to screenshots (ending .png/.jpg/.webp), one per line, and describe what they show.$t6e$, $t6f$[{"criterion": "Brief is clear", "max_points": 25, "guidance": "All parts."}, {"criterion": "Permissions safe", "max_points": 25, "guidance": "Least privilege."}, {"criterion": "Testing", "max_points": 30, "guidance": "Ten cases honestly reported."}, {"criterion": "Reflection", "max_points": 20, "guidance": "Real next steps."}]$t6f$::jsonb, 60, 'link', true, false),
  (7, $t7a$Instructions that agents follow$t7a$, $t7b$Write instructions with examples and edge cases.$t7b$, $t7c$Give the agent a role, steps, examples of good and bad output and what to do when unsure. Put critical rules first. Test the instructions like code: change one line at a time.$t7c$, $t7d$Instructions that agents follow$t7d$, $t7e$Improve your agent's instructions across three versions. Submit each version's key change and the test result.$t7e$, $t7f$[{"criterion": "Changes are deliberate", "max_points": 40, "guidance": "One change at a time."}, {"criterion": "Results compared", "max_points": 35, "guidance": "Evidence."}, {"criterion": "Examples included", "max_points": 25, "guidance": "Good and bad."}]$t7f$::jsonb, 20, 'text', false, false),
  (8, $t8a$Memory and context$t8a$, $t8b$Decide what an agent should remember.$t8b$, $t8c$Agents forget unless you give context. Options: paste it, attach files, or store notes. Keep memory small, relevant and free of secrets. Decide what to forget.$t8c$, $t8d$Memory and context$t8d$, $t8e$Design the memory for your agent: what it stores, where, for how long, and what it must not store.$t8e$, $t8f$[{"criterion": "Useful memory", "max_points": 35, "guidance": "Supports the task."}, {"criterion": "Privacy considered", "max_points": 40, "guidance": "No secrets or personal data."}, {"criterion": "Expiry defined", "max_points": 25, "guidance": "How long."}]$t8f$::jsonb, 20, 'text', false, false),
  (9, $t9a$Triggers and schedules$t9a$, $t9b$Start agents at the right moment.$t9b$, $t9c$Triggers: a schedule, an incoming email, a form, a webhook. Choose the least frequent trigger that meets the need. Avoid loops where one agent triggers itself.$t9c$, $t9d$Triggers and schedules$t9d$, $t9e$Define the trigger for your agent, its frequency, and how you prevent loops or floods.$t9e$, $t9f$[{"criterion": "Trigger fits the need", "max_points": 40, "guidance": "Sensible."}, {"criterion": "Frequency reasoned", "max_points": 30, "guidance": "Not excessive."}, {"criterion": "Loop protection", "max_points": 30, "guidance": "Considered."}]$t9f$::jsonb, 20, 'text', false, false),
  (10, $t10a$Using data and documents$t10a$, $t10b$Give an agent trusted information to work from.$t10b$, $t10c$Agents are better when they read your documents instead of guessing. Give clean, current sources and tell the agent to cite them and say when the answer is not in them.$t10c$, $t10d$Using data and documents$t10d$, $t10e$Set up an agent that answers from three documents. Submit three test questions with cited answers and one question it correctly could not answer.

**Evidence:** paste *direct* links to screenshots (ending .png/.jpg/.webp), one per line, and describe what they show.$t10e$, $t10f$[{"criterion": "Answers use sources", "max_points": 45, "guidance": "Cited."}, {"criterion": "Handles missing info", "max_points": 35, "guidance": "Says it does not know."}, {"criterion": "Sources are good", "max_points": 20, "guidance": "Relevant."}]$t10f$::jsonb, 20, 'link', false, false),
  (11, $t11a$Checking an agent's work$t11a$, $t11b$Verify outputs before anyone relies on them.$t11b$, $t11c$Agents make confident mistakes. Add checks: a checklist, a second review, spot-checks of 10 percent, and a place to report errors. High-stakes outputs need a human.$t11c$, $t11d$Checking an agent's work$t11d$, $t11e$Design a quality check for your agent: what is checked, how often, by whom and what happens on failure.$t11e$, $t11f$[{"criterion": "Checks are concrete", "max_points": 40, "guidance": "Specific."}, {"criterion": "Proportional to risk", "max_points": 30, "guidance": "Higher risk, more checking."}, {"criterion": "Failure path", "max_points": 30, "guidance": "Defined."}]$t11f$::jsonb, 20, 'text', false, false),
  (12, $t12a$Module project: an agent that uses knowledge and tools$t12a$, $t12b$Build an agent that uses documents and one tool safely.$t12b$, $t12c$Show Module 2. Deliver an agent using documents and one tool, with a memory plan, trigger and quality checks.

Your work is scored on the rubric below. You can revise and resubmit.$t12c$, $t12d$Module project: an agent that uses knowledge and tools$t12d$, $t12e$Submit the brief, memory design, trigger, quality check plan and evidence of five runs.

**Evidence:** paste *direct* links to screenshots (ending .png/.jpg/.webp), one per line, and describe what they show.$t12e$, $t12f$[{"criterion": "Uses knowledge correctly", "max_points": 30, "guidance": "Cited answers."}, {"criterion": "Safe tool use", "max_points": 25, "guidance": "Permissions and approvals."}, {"criterion": "Quality checks", "max_points": 25, "guidance": "Defined and used."}, {"criterion": "Evidence of runs", "max_points": 20, "guidance": "Five runs."}]$t12f$::jsonb, 70, 'link', true, false),
  (13, $t13a$Chaining steps$t13a$, $t13b$Break a job into a reliable sequence.$t13b$, $t13c$Long tasks fail when done in one step. Split into stages with a clear input and output for each and check between stages. Keep each stage simple.$t13c$, $t13d$Chaining steps$t13d$, $t13e$Design a three-stage workflow with the input, output and check between each stage.$t13e$, $t13f$[{"criterion": "Stages are clear", "max_points": 40, "guidance": "Inputs and outputs."}, {"criterion": "Checks between", "max_points": 35, "guidance": "Present."}, {"criterion": "Simple stages", "max_points": 25, "guidance": "Single purpose."}]$t13f$::jsonb, 20, 'text', false, false),
  (14, $t14a$Branching and decisions$t14a$, $t14b$Route work by rules.$t14b$, $t14c$Use rules for clear cases (if the invoice is over 500, ask approval) and AI judgment for fuzzy ones. Always include a default path for anything unexpected.$t14c$, $t14d$Branching and decisions$t14d$, $t14e$Add branching to your workflow: list the rules and the default path, and test three cases.$t14e$, $t14f$[{"criterion": "Rules clear", "max_points": 35, "guidance": "Precise."}, {"criterion": "Default path", "max_points": 30, "guidance": "Handles unexpected."}, {"criterion": "Tested", "max_points": 35, "guidance": "Three cases."}]$t14f$::jsonb, 20, 'text', false, false),
  (15, $t15a$Human in the loop$t15a$, $t15b$Put approvals where they matter.$t15b$, $t15c$Ask a human to approve actions that are hard to undo: sending to customers, spending money, deleting. Make approvals easy: show what will happen and one-click approve or reject.$t15c$, $t15d$Human in the loop$t15d$, $t15e$Add an approval step. Submit what the human sees, and what happens on approve and reject.

**Evidence:** paste *direct* links to screenshots (ending .png/.jpg/.webp), one per line, and describe what they show.$t15e$, $t15f$[{"criterion": "Approval at the right place", "max_points": 40, "guidance": "Risky actions."}, {"criterion": "Clear for the human", "max_points": 35, "guidance": "Understandable."}, {"criterion": "Both outcomes handled", "max_points": 25, "guidance": "Approve and reject."}]$t15f$::jsonb, 20, 'link', false, false),
  (16, $t16a$Failure handling and logs$t16a$, $t16b$Know when something failed and why.$t16b$, $t16c$Things fail: a service is down, an input is odd. Plan retries, alerts and logs. A log should record when, what input, what action and the result.$t16c$, $t16d$Failure handling and logs$t16d$, $t16e$Define failure handling and logging for your workflow. Submit a sample log entry and an alert rule.$t16e$, $t16f$[{"criterion": "Failure cases considered", "max_points": 40, "guidance": "Realistic."}, {"criterion": "Logs useful", "max_points": 35, "guidance": "Enough to debug."}, {"criterion": "Alerts sensible", "max_points": 25, "guidance": "Not noisy."}]$t16f$::jsonb, 20, 'text', false, false),
  (17, $t17a$Costs and limits$t17a$, $t17b$Control spend and runaway loops.$t17b$, $t17c$AI calls and tools cost money or credits. Set budgets, per-run limits, a maximum number of steps and a kill switch. Measure one run's cost.$t17c$, $t17d$Costs and limits$t17d$, $t17e$Measure the cost of one run, project a month of use and set limits.$t17e$, $t17f$[{"criterion": "Real measurement", "max_points": 40, "guidance": "Actual run."}, {"criterion": "Projection reasoned", "max_points": 30, "guidance": "Sensible."}, {"criterion": "Limits and kill switch", "max_points": 30, "guidance": "Defined."}]$t17f$::jsonb, 20, 'text', false, false),
  (18, $t18a$Module project: a multi-step workflow with approvals$t18a$, $t18b$Deliver a reliable workflow with checks and limits.$t18b$, $t18c$Show Module 3. Deliver a multi-step workflow with branching, a human approval, failure handling and cost limits.

Your work is scored on the rubric below. You can revise and resubmit.$t18c$, $t18d$Module project: a multi-step workflow with approvals$t18d$, $t18e$Submit the workflow diagram, rules, approval design, failure plan, cost measurement and evidence of test runs.

**Evidence:** paste *direct* links to screenshots (ending .png/.jpg/.webp), one per line, and describe what they show.$t18e$, $t18f$[{"criterion": "Workflow design", "max_points": 25, "guidance": "Clear stages."}, {"criterion": "Human approval", "max_points": 25, "guidance": "Right place."}, {"criterion": "Failure and cost control", "max_points": 30, "guidance": "Handled."}, {"criterion": "Tested", "max_points": 20, "guidance": "Evidence."}]$t18f$::jsonb, 75, 'link', true, false),
  (19, $t19a$Agents for email and inbox triage$t19a$, $t19b$Sort and draft, never send blind.$t19b$, $t19c$Triage agents label, summarise and draft replies. Keep sending manual. Never let an agent read or send messages beyond what you approved.$t19c$, $t19d$Agents for email and inbox triage$t19d$, $t19e$Design an inbox triage agent: categories, what it drafts, and what always needs you.$t19e$, $t19f$[{"criterion": "Categories useful", "max_points": 35, "guidance": "Practical."}, {"criterion": "Drafts not sends", "max_points": 40, "guidance": "Human sends."}, {"criterion": "Privacy considered", "max_points": 25, "guidance": "Scope limited."}]$t19f$::jsonb, 20, 'text', false, false),
  (20, $t20a$Agents for research and reports$t20a$, $t20b$Gather, compare and cite.$t20b$, $t20c$A research agent should list its sources, separate facts from guesses and flag uncertainty. Verify key claims yourself.$t20c$, $t20d$Agents for research and reports$t20d$, $t20e$Run a research agent on a question. Submit the question, the report excerpt with sources, and three claims you verified.$t20e$, $t20f$[{"criterion": "Sources listed", "max_points": 35, "guidance": "Real."}, {"criterion": "Claims verified", "max_points": 40, "guidance": "Three checks."}, {"criterion": "Uncertainty flagged", "max_points": 25, "guidance": "Honest."}]$t20f$::jsonb, 20, 'text', false, false),
  (21, $t21a$Agents for customer support$t21a$, $t21b$Answer common questions and hand off the rest.$t21b$, $t21c$Support agents answer from your approved content, hand off to a person when unsure or upset, and never invent policies or promise refunds.$t21c$, $t21d$Agents for customer support$t21d$, $t21e$Design a support agent: allowed topics, sources, tone, handoff rules and three example replies.$t21e$, $t21f$[{"criterion": "Grounded in sources", "max_points": 35, "guidance": "No invention."}, {"criterion": "Handoff rules", "max_points": 40, "guidance": "Clear."}, {"criterion": "Tone appropriate", "max_points": 25, "guidance": "Helpful."}]$t21f$::jsonb, 20, 'text', false, false),
  (22, $t22a$Agents for content and social$t22a$, $t22b$Plan and draft with approval.$t22b$, $t22c$A content agent drafts from your voice guide and calendar. You approve before anything posts. Track what worked.$t22c$, $t22d$Agents for content and social$t22d$, $t22e$Design a content agent: inputs, voice guide, approval step and a weekly review.$t22e$, $t22f$[{"criterion": "Uses a voice guide", "max_points": 35, "guidance": "Consistent."}, {"criterion": "Approval before posting", "max_points": 40, "guidance": "Human gate."}, {"criterion": "Review loop", "max_points": 25, "guidance": "Measures results."}]$t22f$::jsonb, 20, 'text', false, false),
  (23, $t23a$Agents for data entry and reporting$t23a$, $t23b$Move and summarise data accurately.$t23b$, $t23c$Data agents copy, clean and summarise. Validate: totals match, no duplicates, formats correct. Keep the original data untouched.$t23c$, $t23d$Agents for data entry and reporting$t23d$, $t23e$Design a data-cleaning workflow with three validations and a test on sample data.$t23e$, $t23f$[{"criterion": "Validations real", "max_points": 40, "guidance": "Three checks."}, {"criterion": "Original preserved", "max_points": 30, "guidance": "Safe."}, {"criterion": "Tested", "max_points": 30, "guidance": "Sample data."}]$t23f$::jsonb, 20, 'text', false, false),
  (24, $t24a$Module project: an agent that saves real time$t24a$, $t24b$Deliver an agent that does a real job and prove the saving.$t24b$, $t24c$Show Module 4. Pick a real job from this module, build it and measure the time saved over five runs.

Your work is scored on the rubric below. You can revise and resubmit.$t24c$, $t24d$Module project: an agent that saves real time$t24d$, $t24e$Submit: the job, agent brief, permissions, five run results, time before and after, and errors found.

**Evidence:** paste *direct* links to screenshots (ending .png/.jpg/.webp), one per line, and describe what they show.$t24e$, $t24f$[{"criterion": "Solves a real job", "max_points": 30, "guidance": "Practical."}, {"criterion": "Measured saving", "max_points": 25, "guidance": "Numbers."}, {"criterion": "Safety and limits", "max_points": 25, "guidance": "Handled."}, {"criterion": "Honest errors", "max_points": 20, "guidance": "Reported."}]$t24f$::jsonb, 75, 'link', true, false),
  (25, $t25a$Capstone 1: choose a workflow worth automating$t25a$, $t25b$Pick a real recurring workflow.$t25b$, $t25c$Choose a workflow you or someone else does at least weekly. Time it for a week.$t25c$, $t25d$Capstone 1: choose a workflow worth automating$t25d$, $t25e$Submit the workflow, who does it, how often, time per run and the cost of getting it wrong.$t25e$, $t25f$[{"criterion": "Real and recurring", "max_points": 40, "guidance": "Specific."}, {"criterion": "Time measured", "max_points": 30, "guidance": "Numbers."}, {"criterion": "Risk considered", "max_points": 30, "guidance": "Cost of errors."}]$t25f$::jsonb, 20, 'text', false, false),
  (26, $t26a$Capstone 2: design the agent system$t26a$, $t26b$Plan roles, tools, approvals and limits.$t26b$, $t26c$Design the system: stages, agents, tools, approvals, memory, failures and cost limits.$t26c$, $t26d$Capstone 2: design the agent system$t26d$, $t26e$Submit the design (diagram link or text) and a risk table.

**Evidence:** paste *direct* links to screenshots (ending .png/.jpg/.webp), one per line, and describe what they show.$t26e$, $t26f$[{"criterion": "Complete design", "max_points": 40, "guidance": "All parts."}, {"criterion": "Risks handled", "max_points": 35, "guidance": "Table."}, {"criterion": "Simple enough", "max_points": 25, "guidance": "Not overbuilt."}]$t26f$::jsonb, 20, 'link', false, false),
  (27, $t27a$Capstone 3: build and test$t27a$, $t27b$Build the core and test on real examples.$t27b$, $t27c$Build it. Test on at least ten real examples. Record accuracy and problems.$t27c$, $t27d$Capstone 3: build and test$t27d$, $t27e$Submit ten test results and a list of problems.

**Evidence:** paste *direct* links to screenshots (ending .png/.jpg/.webp), one per line, and describe what they show.$t27e$, $t27f$[{"criterion": "Works on real examples", "max_points": 45, "guidance": "Evidence."}, {"criterion": "Accuracy recorded", "max_points": 30, "guidance": "Numbers."}, {"criterion": "Problems honest", "max_points": 25, "guidance": "Not hidden."}]$t27f$::jsonb, 60, 'link', false, false),
  (28, $t28a$Capstone 4: add safety and monitoring$t28a$, $t28b$Add approvals, logs, alerts and limits.$t28b$, $t28c$Add human approvals, logging, failure handling, alerts and cost limits.$t28c$, $t28d$Capstone 4: add safety and monitoring$t28d$, $t28e$Submit screenshots or descriptions of each safety feature and a sample log.

**Evidence:** paste *direct* links to screenshots (ending .png/.jpg/.webp), one per line, and describe what they show.$t28e$, $t28f$[{"criterion": "Safety features present", "max_points": 45, "guidance": "All five."}, {"criterion": "Logs useful", "max_points": 30, "guidance": "Clear."}, {"criterion": "Tested", "max_points": 25, "guidance": "Failure simulated."}]$t28f$::jsonb, 20, 'link', false, false),
  (29, $t29a$Capstone 5: pilot with a real user$t29a$, $t29b$Run it for a week with a real person.$t29b$, $t29c$Let a real person use it for a week. Collect their feedback and the time saved.$t29c$, $t29d$Capstone 5: pilot with a real user$t29d$, $t29e$Submit a week's summary: runs, errors, time saved and feedback.$t29e$, $t29f$[{"criterion": "Real pilot", "max_points": 40, "guidance": "A real week."}, {"criterion": "Results measured", "max_points": 35, "guidance": "Numbers."}, {"criterion": "Feedback used", "max_points": 25, "guidance": "Improvements."}]$t29f$::jsonb, 20, 'text', false, false),
  (30, $t30a$Capstone 6: case study and handover$t30a$, $t30b$Document the system so others can run it.$t30b$, $t30c$Write a case study and a one-page handover: what it does, how to run it, what can go wrong, who to contact. Share in the Discord and ask for one piece of feedback.

Your work is scored on the rubric below. You can revise and resubmit.$t30c$, $t30d$Capstone 6: case study and handover$t30d$, $t30e$Submit: the case study (problem, design, results, lessons) and the handover page.$t30e$, $t30f$[{"criterion": "Results and honesty", "max_points": 30, "guidance": "Numbers and limits."}, {"criterion": "Safety and control", "max_points": 30, "guidance": "Approvals, limits."}, {"criterion": "Handover usable", "max_points": 20, "guidance": "Others could run it."}, {"criterion": "Clarity", "max_points": 20, "guidance": "Well written."}]$t30f$::jsonb, 75, 'text', true, false)
) as v(n, title, objective, lesson_md, skill_focus, assignment_md, rubric, est_minutes, submission_type, ai_evaluate, requires_review)
where t.slug = 'agents'
on conflict (track_id, day_number) do nothing;
