-- Graphics & design, Pro tier (days 31-60). Authored content, UNPUBLISHED until a person reviews it in Admin.
insert into public.day
  (track_id, tier_id, day_number, title, objective, lesson_md, skill_focus, assignment_md, rubric,
   est_minutes, is_published, credit_budget, submission_type, ai_evaluate, requires_review)
select t.id, ti.id, v.n, v.title, v.objective, v.lesson_md, v.skill_focus, v.assignment_md, v.rubric,
       v.est_minutes, false, null, v.submission_type, v.ai_evaluate, v.requires_review
from public.track t
join public.tier ti on ti.track_id = t.id and ti.slug = 'pro'
cross join (values
  (31, $t31a$What a brand identity is$t31a$, $t31b$Translate a business into visual choices.$t31b$, $t31c$A brand identity is a set of visual decisions that make a business recognisable: logo, colours, type, imagery style, layout rules. It starts with words: what the brand stands for, who it serves and how it should feel.

Write three brand adjectives and three things it is **not** (for example friendly, honest, practical; not corporate, flashy or childish). Every visual choice should trace back to these.

**Sharing images:** paste *direct* links ending in .png, .jpg or .webp, one per line.$t31c$, $t31d$Brand direction$t31d$, $t31e$For a real or made-up small business, submit: a two-sentence description, three brand adjectives, three "not" words, and the audience.$t31e$, $t31f$[{"criterion": "Direction is specific", "max_points": 40, "guidance": "Adjectives and nots are usable."}, {"criterion": "Audience is clear", "max_points": 30, "guidance": "A real reader is named."}, {"criterion": "Distinct from generic", "max_points": 30, "guidance": "Could not fit any business."}]$t31f$::jsonb, 25, 'link', false, false),
  (32, $t32a$Logo exploration with AI: concepts, not finals$t32a$, $t32b$Generate and judge logo directions responsibly.$t32b$, $t32c$AI is good for **exploring** logo directions fast, but its files are often raster, text is unreliable and outputs may resemble existing marks. Use it for ideas, then redraw or vectorise a chosen concept and check that it is not too similar to a known brand.

Judge a mark by: simple, memorable, works small, works in one colour.

**Sharing images:** paste *direct* links ending in .png, .jpg or .webp, one per line.$t32c$, $t32d$Logo exploration$t32d$, $t32e$Generate at least 12 concept images. Submit direct links to your best six, the prompts, your top pick, and how it passes the small-size and one-colour tests.$t32e$, $t32f$[{"criterion": "Range of concepts", "max_points": 30, "guidance": "Six different directions."}, {"criterion": "Judged by criteria", "max_points": 40, "guidance": "Applies small-size and one-colour tests."}, {"criterion": "Originality check", "max_points": 30, "guidance": "Says how you checked for lookalikes."}]$t32f$::jsonb, 30, 'link', false, false),
  (33, $t33a$Colour systems that work$t33a$, $t33b$Build a palette with roles and contrast.$t33b$, $t33c$A working palette has roles: a primary, an accent, a background, a text colour and two neutrals. Check **contrast** so text is readable (aim for at least 4.5:1 for body text). Give each colour a name and hex code.

Test on real layouts, in light and dark.

**Sharing images:** paste *direct* links ending in .png, .jpg or .webp, one per line.$t33c$, $t33d$Palette and contrast$t33d$, $t33e$Submit your palette with hex codes and roles, the contrast ratios of your text/background pairs, and a link to a sample layout.$t33e$, $t33f$[{"criterion": "Roles and codes given", "max_points": 30, "guidance": "Each colour has a job."}, {"criterion": "Contrast checked", "max_points": 40, "guidance": "Actual ratios are stated."}, {"criterion": "Sample shows it works", "max_points": 30, "guidance": "Readable in use."}]$t33f$::jsonb, 30, 'link', false, false),
  (34, $t34a$Typography pairs and hierarchy$t34a$, $t34b$Choose fonts that fit and set a type scale.$t34b$, $t34c$Pick two fonts: one for headings, one for body (or one family in two weights). Set a scale: for example 48/32/20/16. Match the font's personality to the brand.

Use fonts with a licence that covers your use (many Google Fonts are free for commercial use).

**Sharing images:** paste *direct* links ending in .png, .jpg or .webp, one per line.$t34c$, $t34d$Type system$t34d$, $t34e$Submit your font choices with reasons, your scale, and a link to a typographic specimen or layout.$t34e$, $t34f$[{"criterion": "Fonts fit the brand", "max_points": 35, "guidance": "Reasons tie to the adjectives."}, {"criterion": "Scale is clear", "max_points": 35, "guidance": "Sizes for each level."}, {"criterion": "Licence checked", "max_points": 30, "guidance": "Says you can use them."}]$t34f$::jsonb, 30, 'link', false, false),
  (35, $t35a$Imagery style and art direction rules$t35a$, $t35b$Write rules that keep all images on-brand.$t35b$, $t35c$Define an imagery style: subject, light, colour treatment, framing, what to avoid. Write it as a reusable prompt block and three do/don't examples.

This is what stops every image looking different.

**Sharing images:** paste *direct* links ending in .png, .jpg or .webp, one per line.$t35c$, $t35d$Imagery rules$t35d$, $t35e$Submit the style block, three do and three don't image links, and one sentence on each don't.$t35e$, $t35f$[{"criterion": "Rules are actionable", "max_points": 40, "guidance": "Someone else could use them."}, {"criterion": "Examples match rules", "max_points": 35, "guidance": "Do vs don't is clear."}, {"criterion": "Prompt block is reusable", "max_points": 25, "guidance": "Works across subjects."}]$t35f$::jsonb, 30, 'link', false, false),
  (36, $t36a$Module project: a mini brand kit$t36a$, $t36b$Package logo direction, colours, type and imagery rules.$t36b$, $t36c$Show Module 1. Produce a **one-page brand kit** for one brand: logo concept, palette with roles and contrast, fonts and scale, imagery rules and two sample applications.

Success looks like a stranger could make an on-brand post from it.

Your work is scored on the rubric below. You can revise and resubmit.

**Sharing images:** paste *direct* links ending in .png, .jpg or .webp, one per line.$t36c$, $t36d$Brand kit$t36d$, $t36e$Submit direct links to the brand kit page and the two sample applications, plus the brand adjectives and how you checked licence and lookalikes.$t36e$, $t36f$[{"criterion": "Kit is complete and usable", "max_points": 35, "guidance": "Covers every part."}, {"criterion": "Consistent look", "max_points": 30, "guidance": "Applications match the kit."}, {"criterion": "Legibility and contrast", "max_points": 20, "guidance": "Readable."}, {"criterion": "Rights and originality", "max_points": 15, "guidance": "Checks are explained."}]$t36f$::jsonb, 70, 'link', true, false),
  (37, $t37a$Product imagery: what to prompt and what to photograph$t37a$, $t37b$Decide when AI imagery is honest and when it is not.$t37b$, $t37c$AI can make believable scenes, but a product image must show the **real product**. Misleading customers with an AI image of a product that looks different is deceptive and may be illegal.

Use real photos of the product and AI for backgrounds, mood and concept art. Label heavily edited or AI-generated images where required.

**Sharing images:** paste *direct* links ending in .png, .jpg or .webp, one per line.$t37c$, $t37d$Honest product imagery$t37d$, $t37e$Choose an everyday object. Submit a real photo of it, an AI-made background or scene for it, and a note on what is real and what is generated.$t37e$, $t37f$[{"criterion": "Real product shown", "max_points": 35, "guidance": "The object is accurate."}, {"criterion": "Scene is convincing", "max_points": 35, "guidance": "Light and style fit."}, {"criterion": "Honesty note", "max_points": 30, "guidance": "Clear about what is generated."}]$t37f$::jsonb, 30, 'link', false, false),
  (38, $t38a$Lighting a product: consistent shadows and reflections$t38a$, $t38b$Place a product in a scene so it looks physically right.$t38b$, $t38c$Match the direction, softness and colour of light. Add a contact shadow and, if the surface is glossy, a faint reflection. Keep the scale believable.

Compare with real photography: where does the light come from?

**Sharing images:** paste *direct* links ending in .png, .jpg or .webp, one per line.$t38c$, $t38d$Believable compositing$t38d$, $t38e$Composite a product on two backgrounds. Submit both links and note the light direction you matched.$t38e$, $t38f$[{"criterion": "Light matches", "max_points": 45, "guidance": "Direction and colour fit."}, {"criterion": "Shadows and grounding", "max_points": 35, "guidance": "Not floating."}, {"criterion": "Two backgrounds shown", "max_points": 20, "guidance": "Both shared."}]$t38f$::jsonb, 30, 'link', false, false),
  (39, $t39a$Mockups and context shots$t39a$, $t39b$Show a design in use on a screen, packaging or a wall.$t39b$, $t39c$Mockups show a design in context: phone, poster, packaging. Use mockup templates from your design tool, check that your design is not distorted, and keep the surrounding scene simple so the design is the hero.

**Sharing images:** paste *direct* links ending in .png, .jpg or .webp, one per line.$t39c$, $t39d$Mockups$t39d$, $t39e$Submit two mockups of one design (for example a phone screen and a poster) and note any distortion you fixed.$t39e$, $t39f$[{"criterion": "Design remains accurate", "max_points": 40, "guidance": "Not warped or cropped."}, {"criterion": "Context helps", "max_points": 30, "guidance": "Scene supports the design."}, {"criterion": "Two formats", "max_points": 30, "guidance": "Both shown."}]$t39f$::jsonb, 30, 'link', false, false),
  (40, $t40a$People in images: consent and care$t40a$, $t40b$Handle images of people responsibly.$t40b$, $t40c$Do not generate or edit a real person's likeness without consent. Avoid stereotypes, keep representation thoughtful and never create misleading images of real events.

For illustrative people, prefer diverse, non-specific characters and check for odd hands, teeth and jewellery.$t40c$, $t40d$Responsible people imagery$t40d$, $t40e$Write a short set of five rules for people in your images, and generate one example that follows them. Submit the rules and the example link.$t40e$, $t40f$[{"criterion": "Rules are concrete", "max_points": 40, "guidance": "Real, followable."}, {"criterion": "Example follows rules", "max_points": 35, "guidance": "Shows care."}, {"criterion": "Covers consent and misleading use", "max_points": 25, "guidance": "Mentions both."}]$t40f$::jsonb, 30, 'link', false, false),
  (41, $t41a$Seasonal and campaign variations$t41a$, $t41b$Create variations without losing the brand.$t41b$, $t41c$Campaigns need variations: a seasonal version, a sale version, a launch version. Change only what must change and keep the grid, type and palette.

Build one master layout, then duplicate.

**Sharing images:** paste *direct* links ending in .png, .jpg or .webp, one per line.$t41c$, $t41d$Variation systems$t41d$, $t41e$Submit a master layout and three variations, listing what changed.$t41e$, $t41f$[{"criterion": "Brand stays intact", "max_points": 40, "guidance": "Recognisably same."}, {"criterion": "Changes are purposeful", "max_points": 35, "guidance": "Only what was needed."}, {"criterion": "Master reused", "max_points": 25, "guidance": "Efficient system."}]$t41f$::jsonb, 30, 'link', false, false),
  (42, $t42a$Module project: a product launch image set$t42a$, $t42b$Create a coherent set for a launch.$t42b$, $t42c$Show Module 2. Produce **four images** for a product launch: a hero image, a lifestyle scene, a mockup and a variation. Honest, on-brand and consistent.

Your work is scored on the rubric below. You can revise and resubmit.

**Sharing images:** paste *direct* links ending in .png, .jpg or .webp, one per line.$t42c$, $t42d$Launch imagery$t42d$, $t42e$Submit direct links to the four images, the brand kit link, and a note on what is real versus generated.$t42e$, $t42f$[{"criterion": "On-brand and consistent", "max_points": 30, "guidance": "One system."}, {"criterion": "Honest product depiction", "max_points": 25, "guidance": "Real product is not misrepresented."}, {"criterion": "Composition and light", "max_points": 25, "guidance": "Believable."}, {"criterion": "Variety with purpose", "max_points": 20, "guidance": "Each image has a job."}]$t42f$::jsonb, 70, 'link', true, false),
  (43, $t43a$Inpainting and local edits$t43a$, $t43b$Change part of an image without touching the rest.$t43b$, $t43c$Inpainting changes a masked area. Keep masks slightly larger than the object, describe what should appear, and match the surroundings' light. Iterate in small steps.

**Sharing images:** paste *direct* links ending in .png, .jpg or .webp, one per line.$t43c$, $t43d$Inpainting$t43d$, $t43e$Make three local edits to one image. Submit the original, the final, and the mask idea and prompt for each edit.$t43e$, $t43f$[{"criterion": "Edits are local", "max_points": 35, "guidance": "Rest unchanged."}, {"criterion": "Blends naturally", "max_points": 40, "guidance": "Light and edges match."}, {"criterion": "Process documented", "max_points": 25, "guidance": "Prompts and steps."}]$t43f$::jsonb, 30, 'link', false, false),
  (44, $t44a$Reference images and style transfer$t44a$, $t44b$Steer results with references.$t44b$, $t44c$Reference images guide composition, colour or style. State what to take from each reference ("use the palette, not the subject"). Only use references you own or have the right to use.

**Sharing images:** paste *direct* links ending in .png, .jpg or .webp, one per line.$t44c$, $t44d$Reference-guided generation$t44d$, $t44e$Use two references. Submit them (or describe them), the outputs, and what you took from each.$t44e$, $t44f$[{"criterion": "Reference used purposefully", "max_points": 40, "guidance": "Clear instructions."}, {"criterion": "Output reflects the reference", "max_points": 35, "guidance": "Visible influence."}, {"criterion": "Rights considered", "max_points": 25, "guidance": "Own or licensed."}]$t44f$::jsonb, 30, 'link', false, false),
  (45, $t45a$Consistent characters and mascots$t45a$, $t45b$Keep a character recognisable across scenes.$t45b$, $t45c$Consistency needs a **character sheet**: fixed description, reference image, and repeated wording. Generate the character in different poses and scenes and compare.

Fix drift by regenerating with the reference and stronger constraints.

**Sharing images:** paste *direct* links ending in .png, .jpg or .webp, one per line.$t45c$, $t45d$Character consistency$t45d$, $t45e$Create a character and show it in four scenes. Submit the sheet, links, and what drift you fixed.$t45e$, $t45f$[{"criterion": "Recognisable across scenes", "max_points": 45, "guidance": "Same character."}, {"criterion": "Character sheet is usable", "max_points": 30, "guidance": "Fixed details."}, {"criterion": "Drift handled", "max_points": 25, "guidance": "Explains fixes."}]$t45f$::jsonb, 30, 'link', false, false),
  (46, $t46a$Compositing and layers$t46a$, $t46b$Combine elements in layers for full control.$t46b$, $t46c$Layers let you move, scale and adjust each piece separately: background, subject, effects, text. Keep layers named, use masks not erasing, and save the layered file.

**Sharing images:** paste *direct* links ending in .png, .jpg or .webp, one per line.$t46c$, $t46d$Layered compositing$t46d$, $t46e$Build a layered composite. Submit the final link, a screenshot of the layer panel, and a list of at least five named layers.$t46e$, $t46f$[{"criterion": "Layers are organised", "max_points": 35, "guidance": "Named, masked."}, {"criterion": "Composite looks unified", "max_points": 40, "guidance": "Consistent light and colour."}, {"criterion": "Non-destructive workflow", "max_points": 25, "guidance": "Uses masks and adjustments."}]$t46f$::jsonb, 30, 'link', false, false),
  (47, $t47a$Vector and scalable graphics$t47a$, $t47b$Turn a raster concept into a scalable vector.$t47b$, $t47c$Vectors scale without blur, important for logos and icons. Use an auto-trace tool, then clean nodes, reduce colours and test at tiny and huge sizes. Keep the original.

**Sharing images:** paste *direct* links ending in .png, .jpg or .webp, one per line.$t47c$, $t47d$Vectorising$t47d$, $t47e$Vectorise one concept. Submit both versions, the number of colours, and small- and large-size tests.$t47e$, $t47f$[{"criterion": "Clean result", "max_points": 40, "guidance": "Smooth, few artefacts."}, {"criterion": "Simplified sensibly", "max_points": 30, "guidance": "Reduced colours."}, {"criterion": "Scale tests shown", "max_points": 30, "guidance": "Tiny and huge."}]$t47f$::jsonb, 30, 'link', false, false),
  (48, $t48a$Module project: retouch and rebuild$t48a$, $t48b$Transform a weak image into a polished, layered piece.$t48b$, $t48c$Show Module 3. Start with a weak image and produce a polished result using inpainting, references, compositing and correction, keeping a layered file.

Your work is scored on the rubric below. You can revise and resubmit.

**Sharing images:** paste *direct* links ending in .png, .jpg or .webp, one per line.$t48c$, $t48d$Advanced editing$t48d$, $t48e$Submit before and after links, a layer list, the prompts and steps, and what you would do with more time.$t48e$, $t48f$[{"criterion": "Clear improvement", "max_points": 35, "guidance": "After is much stronger."}, {"criterion": "Natural blending", "max_points": 30, "guidance": "No seams."}, {"criterion": "Process is documented", "max_points": 20, "guidance": "Steps are clear."}, {"criterion": "Non-destructive", "max_points": 15, "guidance": "Layered and reversible."}]$t48f$::jsonb, 70, 'link', true, false),
  (49, $t49a$Grids and layout systems$t49a$, $t49b$Use a grid so layouts feel intentional.$t49b$, $t49c$A grid (columns and margins) aligns everything. Choose a grid per format and keep margins consistent. Break the grid only on purpose.

**Sharing images:** paste *direct* links ending in .png, .jpg or .webp, one per line.$t49c$, $t49d$Grids$t49d$, $t49e$Design one layout on a visible grid. Submit the layout with grid overlay and one intentional break explained.$t49e$, $t49f$[{"criterion": "Grid used well", "max_points": 40, "guidance": "Alignment is clear."}, {"criterion": "Margins consistent", "max_points": 30, "guidance": "Even spacing."}, {"criterion": "Break is intentional", "max_points": 30, "guidance": "Explained."}]$t49f$::jsonb, 30, 'link', false, false),
  (50, $t50a$Carousels and multi-slide stories$t50a$, $t50b$Design a swipeable sequence.$t50b$, $t50c$A carousel is a story: a strong first slide, one idea per slide, a consistent template, and a closing call to action. Keep text large and short.

**Sharing images:** paste *direct* links ending in .png, .jpg or .webp, one per line.$t50c$, $t50d$Carousel design$t50d$, $t50e$Design a five-slide carousel. Submit direct links to all slides and the story in one sentence.$t50e$, $t50f$[{"criterion": "Story flows", "max_points": 30, "guidance": "Sequence makes sense."}, {"criterion": "Consistent template", "max_points": 35, "guidance": "Same system."}, {"criterion": "Text readable", "max_points": 35, "guidance": "Large, short."}]$t50f$::jsonb, 30, 'link', false, false),
  (51, $t51a$Ads that respect rules$t51a$, $t51b$Design ads within platform limits.$t51b$, $t51c$Ads have rules: text limits, prohibited claims and image guidelines vary by platform and change over time. Check the current policy, keep one message, and make the call to action clear.

**Sharing images:** paste *direct* links ending in .png, .jpg or .webp, one per line.$t51c$, $t51d$Ad design$t51d$, $t51e$Design two ad variants for one offer. Submit both links, the policy you checked, and the one message of each.$t51e$, $t51f$[{"criterion": "One clear message", "max_points": 35, "guidance": "Focused."}, {"criterion": "Policy checked", "max_points": 35, "guidance": "Names the current rule."}, {"criterion": "Variants differ on purpose", "max_points": 30, "guidance": "A real test."}]$t51f$::jsonb, 30, 'link', false, false),
  (52, $t52a$Print basics: bleed, margins, colour$t52a$, $t52b$Prepare a file a printer can use.$t52b$, $t52c$Print needs bleed (extra area beyond the trim), safe margins, enough resolution (about 300 dpi) and often CMYK colour. Export a PDF and ask the printer for its spec.

**Sharing images:** paste *direct* links ending in .png, .jpg or .webp, one per line.$t52c$, $t52d$Print preparation$t52d$, $t52e$Prepare a poster or flyer for print. Submit the preview link, the size and resolution, bleed and margin values, and one issue you fixed.$t52e$, $t52f$[{"criterion": "Bleed and margins correct", "max_points": 40, "guidance": "Values are given and sensible."}, {"criterion": "Resolution adequate", "max_points": 30, "guidance": "About 300 dpi."}, {"criterion": "Issue handled", "max_points": 30, "guidance": "A real fix."}]$t52f$::jsonb, 30, 'link', false, false),
  (53, $t53a$Feedback and iteration$t53a$, $t53b$Improve a design from real critique.$t53b$, $t53c$Ask three people specific questions ("What do you see first?", "What is unclear?"). Record feedback, decide, revise. Compare versions.

**Sharing images:** paste *direct* links ending in .png, .jpg or .webp, one per line.$t53c$, $t53d$Iterating on feedback$t53d$, $t53e$Submit version one, feedback from three people, and version two with what changed.$t53e$, $t53f$[{"criterion": "Feedback is real and specific", "max_points": 35, "guidance": "Three responses."}, {"criterion": "Changes respond to it", "max_points": 40, "guidance": "Visible improvement."}, {"criterion": "Decisions explained", "max_points": 25, "guidance": "Why you accepted or ignored."}]$t53f$::jsonb, 30, 'link', false, false),
  (54, $t54a$Module project: a campaign system$t54a$, $t54b$Deliver a carousel, an ad pair and a print piece from one system.$t54b$, $t54c$Show Module 4. Create a **campaign system**: a five-slide carousel, two ad variants and one print piece, all from one grid and brand kit.

Your work is scored on the rubric below. You can revise and resubmit.

**Sharing images:** paste *direct* links ending in .png, .jpg or .webp, one per line.$t54c$, $t54d$Campaign system$t54d$, $t54e$Submit direct links to all pieces, the grid notes, and the feedback you used.$t54e$, $t54f$[{"criterion": "Consistent system", "max_points": 35, "guidance": "One brand."}, {"criterion": "Layout quality", "max_points": 25, "guidance": "Grid and hierarchy."}, {"criterion": "Technical readiness", "max_points": 20, "guidance": "Sizes, bleed, formats."}, {"criterion": "Feedback used", "max_points": 20, "guidance": "Improved by critique."}]$t54f$::jsonb, 80, 'link', true, false),
  (55, $t55a$Pro capstone 1: client brief$t55a$, $t55b$Write a brief for a real or made-up small business.$t55b$, $t55c$Write a one-page brief: business, audience, goals, deliverables, tone, constraints, deadline.$t55c$, $t55d$Scoping design work$t55d$, $t55e$Submit the brief.$t55e$, $t55f$[{"criterion": "Brief is specific", "max_points": 45, "guidance": "All parts filled."}, {"criterion": "Deliverables realistic", "max_points": 30, "guidance": "Doable."}, {"criterion": "Goals measurable", "max_points": 25, "guidance": "A real metric."}]$t55f$::jsonb, 25, 'text', false, false),
  (56, $t56a$Pro capstone 2: brand kit and moodboard$t56a$, $t56b$Create the visual foundation.$t56b$, $t56c$Build the brand kit (logo direction, palette, type, imagery rules) and a moodboard.

**Sharing images:** paste *direct* links ending in .png, .jpg or .webp, one per line.$t56c$, $t56d$Visual foundation$t56d$, $t56e$Submit direct links to the kit and moodboard.$t56e$, $t56f$[{"criterion": "Kit complete", "max_points": 45, "guidance": "Every part."}, {"criterion": "Moodboard focused", "max_points": 30, "guidance": "Clear direction."}, {"criterion": "Fits the brief", "max_points": 25, "guidance": "Matches the audience."}]$t56f$::jsonb, 60, 'link', false, false),
  (57, $t57a$Pro capstone 3: hero assets$t57a$, $t57b$Produce the hero image and logo application.$t57b$, $t57c$Create the hero image and apply your logo concept on it. Check contrast, legibility and honesty.

**Sharing images:** paste *direct* links ending in .png, .jpg or .webp, one per line.$t57c$, $t57d$Hero assets$t57d$, $t57e$Submit direct links and the prompts used.$t57e$, $t57f$[{"criterion": "On-brand", "max_points": 35, "guidance": "Matches the kit."}, {"criterion": "Composition and legibility", "max_points": 40, "guidance": "Clear."}, {"criterion": "Honest and checked", "max_points": 25, "guidance": "No misleading depictions."}]$t57f$::jsonb, 60, 'link', false, false),
  (58, $t58a$Pro capstone 4: the campaign set$t58a$, $t58b$Create the carousel, ad pair and social set.$t58b$, $t58c$Produce the remaining deliverables from your master layouts.

**Sharing images:** paste *direct* links ending in .png, .jpg or .webp, one per line.$t58c$, $t58d$Campaign production$t58d$, $t58e$Submit direct links to every deliverable.$t58e$, $t58f$[{"criterion": "Complete set", "max_points": 35, "guidance": "All deliverables."}, {"criterion": "Consistent", "max_points": 40, "guidance": "One system."}, {"criterion": "Correct sizes", "max_points": 25, "guidance": "Platform-ready."}]$t58f$::jsonb, 75, 'link', false, false),
  (59, $t59a$Pro capstone 5: review and polish$t59a$, $t59b$Get feedback and finish.$t59b$, $t59c$Collect feedback from three people, revise and run final quality checks: flaws, text, sizes, rights.

**Sharing images:** paste *direct* links ending in .png, .jpg or .webp, one per line.$t59c$, $t59d$Finishing$t59d$, $t59e$Submit the feedback, changes, and final links.$t59e$, $t59f$[{"criterion": "Feedback used", "max_points": 40, "guidance": "Real changes."}, {"criterion": "Quality checks done", "max_points": 35, "guidance": "Flaws and text."}, {"criterion": "Rights check", "max_points": 25, "guidance": "Licences and consent."}]$t59f$::jsonb, 45, 'link', false, false),
  (60, $t60a$Pro capstone 6: deliver the brand package$t60a$, $t60b$Present the full package as if to a client.$t60b$, $t60c$Assemble the brief, brand kit, hero assets, campaign set and usage notes into one presentation. Explain your decisions.

Your work is scored on the rubric below. You can revise and resubmit.

**Sharing images:** paste *direct* links ending in .png, .jpg or .webp, one per line.$t60c$, $t60d$Client-ready delivery$t60d$, $t60e$Submit: direct links to the final deliverables (one per line), the brief, the brand kit link, and a short cover note (5 sentences) explaining your key decisions.$t60e$, $t60f$[{"criterion": "Fits the brief", "max_points": 25, "guidance": "Serves the stated goals."}, {"criterion": "Visual quality and hierarchy", "max_points": 25, "guidance": "Professional composition."}, {"criterion": "Consistency across the package", "max_points": 25, "guidance": "One brand system."}, {"criterion": "Technical readiness and honesty", "max_points": 25, "guidance": "Right formats; no misleading imagery."}]$t60f$::jsonb, 90, 'link', true, false)
) as v(n, title, objective, lesson_md, skill_focus, assignment_md, rubric, est_minutes, submission_type, ai_evaluate, requires_review)
where t.slug = 'graphics'
on conflict (track_id, day_number) do nothing;
