-- AI agents & automation, Pro tier (days 31-60). Authored content, UNPUBLISHED until a person reviews it in Admin.
insert into public.day
  (track_id, tier_id, day_number, title, objective, lesson_md, skill_focus, assignment_md, rubric,
   est_minutes, is_published, credit_budget, submission_type, ai_evaluate, requires_review)
select t.id, ti.id, v.n, v.title, v.objective, v.lesson_md, v.skill_focus, v.assignment_md, v.rubric,
       v.est_minutes, false, null, v.submission_type, v.ai_evaluate, v.requires_review
from public.track t
join public.tier ti on ti.track_id = t.id and ti.slug = 'pro'
cross join (values
  (31, $t31a$Single agent or many?$t31a$, $t31b$Choose the simplest architecture that works.$t31b$, $t31c$Start with one agent. Split into several only when tasks need different tools, permissions or expertise, or one context gets too crowded. More agents mean more cost, more failure points and harder debugging.$t31c$, $t31d$Single agent or many?$t31d$, $t31e$For a real workflow, argue for one agent or several. Include cost, risk and debugging.$t31e$, $t31f$[{"criterion": "Reasoned choice", "max_points": 45, "guidance": "Trade-offs."}, {"criterion": "Simplicity valued", "max_points": 30, "guidance": "Not overbuilt."}, {"criterion": "Risks named", "max_points": 25, "guidance": "Failure points."}]$t31f$::jsonb, 25, 'text', false, false),
  (32, $t32a$Planner, worker, checker$t32a$, $t32b$Use roles to improve reliability.$t32b$, $t32c$A common pattern: a planner breaks the goal into steps, workers do each step, a checker reviews against the brief. The checker must have clear pass/fail criteria and the power to send work back.$t32c$, $t32d$Planner, worker, checker$t32d$, $t32e$Design a planner/worker/checker flow for one job with the checker's criteria.$t32e$, $t32f$[{"criterion": "Roles distinct", "max_points": 35, "guidance": "Clear."}, {"criterion": "Checker criteria", "max_points": 40, "guidance": "Pass/fail."}, {"criterion": "Loop limits", "max_points": 25, "guidance": "Max retries."}]$t32f$::jsonb, 20, 'text', false, false),
  (33, $t33a$Structured outputs$t33a$, $t33b$Make agent output machine-readable.$t33b$, $t33c$Ask for a fixed format (JSON with named fields) so the next step can rely on it. Validate the output; if it fails, retry once or send to a person.$t33c$, $t33d$Structured outputs$t33d$, $t33e$Define an output schema for a step, test it on ten inputs and report the validity rate.$t33e$, $t33f$[{"criterion": "Schema clear", "max_points": 30, "guidance": "Fields."}, {"criterion": "Ten tests", "max_points": 40, "guidance": "Real."}, {"criterion": "Failure handling", "max_points": 30, "guidance": "Retry or human."}]$t33f$::jsonb, 20, 'text', false, false),
  (34, $t34a$Grounding: retrieval and citations$t34a$, $t34b$Make agents answer from sources.$t34b$, $t34c$Give the agent the relevant documents (retrieval), require quotes or references, and instruct it to say "not found" rather than guess. Test with questions that are not in the sources.$t34c$, $t34d$Grounding: retrieval and citations$t34d$, $t34e$Build a grounded Q and A over five documents. Submit ten questions (three unanswerable) with results.$t34e$, $t34f$[{"criterion": "Grounded answers", "max_points": 40, "guidance": "Cited."}, {"criterion": "Unanswerable handled", "max_points": 40, "guidance": "Says not found."}, {"criterion": "Sources good", "max_points": 20, "guidance": "Relevant."}]$t34f$::jsonb, 20, 'text', false, false),
  (35, $t35a$Tool design and error messages$t35a$, $t35b$Make tools easy for agents to use correctly.$t35b$, $t35c$Tools need clear names, descriptions, typed inputs and useful errors ("date must be YYYY-MM-DD") so the agent can recover. Fewer, well-described tools beat many vague ones.$t35c$, $t35d$Tool design and error messages$t35d$, $t35e$Specify three tools (name, description, inputs, outputs, errors) for an agent.$t35e$, $t35f$[{"criterion": "Descriptions clear", "max_points": 40, "guidance": "Usable."}, {"criterion": "Errors helpful", "max_points": 35, "guidance": "Recoverable."}, {"criterion": "Few tools", "max_points": 25, "guidance": "Focused."}]$t35f$::jsonb, 20, 'text', false, false),
  (36, $t36a$Module project: a planner-worker-checker system$t36a$, $t36b$Deliver a reliable multi-role workflow.$t36b$, $t36c$Show Module 1. Deliver a **role-based workflow** with structured outputs, grounding and a checker.

Your work is scored on the rubric below. You can revise and resubmit.$t36c$, $t36d$Module project: a planner-worker-checker system$t36d$, $t36e$Submit the design, schemas, tool specs, and results from ten test runs including failures.

**Evidence:** paste *direct* links to screenshots (ending .png/.jpg/.webp), one per line, and describe them.$t36e$, $t36f$[{"criterion": "Design sound", "max_points": 25, "guidance": "Roles."}, {"criterion": "Structured and grounded", "max_points": 30, "guidance": "Works."}, {"criterion": "Checker effective", "max_points": 25, "guidance": "Catches errors."}, {"criterion": "Honest results", "max_points": 20, "guidance": "Failures."}]$t36f$::jsonb, 80, 'link', true, false),
  (37, $t37a$Test sets for agents$t37a$, $t37b$Build a repeatable test set.$t37b$, $t37c$Collect 20 to 30 realistic tasks with expected outcomes, including edge cases and traps. Re-run after every change so you notice regressions.$t37c$, $t37d$Test sets for agents$t37d$, $t37e$Create a test set of 20 tasks with expected results and difficulty tags.$t37e$, $t37f$[{"criterion": "Realistic tasks", "max_points": 35, "guidance": "Real."}, {"criterion": "Edge cases", "max_points": 35, "guidance": "Traps."}, {"criterion": "Expected results clear", "max_points": 30, "guidance": "Checkable."}]$t37f$::jsonb, 40, 'text', false, false),
  (38, $t38a$Measuring success$t38a$, $t38b$Choose metrics that matter.$t38b$, $t38c$Track task success rate, error severity, time saved, cost per task and human interventions. One number rarely tells the story; separate small mistakes from harmful ones.$t38c$, $t38d$Measuring success$t38d$, $t38e$Run your test set and report five metrics with a short interpretation.$t38e$, $t38f$[{"criterion": "Metrics relevant", "max_points": 30, "guidance": "Five."}, {"criterion": "Numbers real", "max_points": 40, "guidance": "From runs."}, {"criterion": "Interpretation honest", "max_points": 30, "guidance": "Nuanced."}]$t38f$::jsonb, 20, 'text', false, false),
  (39, $t39a$Debugging agent failures$t39a$, $t39b$Find why an agent failed.$t39b$, $t39c$Read the trace: what did it see, decide and do? Common causes: unclear instruction, missing context, wrong tool, no stop rule. Fix the root cause, then re-test.$t39c$, $t39d$Debugging agent failures$t39d$, $t39e$Diagnose three failures: symptom, cause, fix and re-test result.$t39e$, $t39f$[{"criterion": "Root causes found", "max_points": 45, "guidance": "Not symptoms."}, {"criterion": "Fixes work", "max_points": 35, "guidance": "Re-tested."}, {"criterion": "Honest", "max_points": 20, "guidance": "Includes non-fixes."}]$t39f$::jsonb, 20, 'text', false, false),
  (40, $t40a$Prompt injection and untrusted content$t40a$, $t40b$Defend against hostile instructions in data.$t40b$, $t40c$Content an agent reads (emails, web pages, files) can contain instructions. Treat it as data, not commands: separate it clearly, limit tool powers, require approval for risky actions and never let it trigger sending or deleting on its own.$t40c$, $t40d$Prompt injection and untrusted content$t40d$, $t40e$Test your agent with three documents containing hidden instructions. Submit results and defences.$t40e$, $t40f$[{"criterion": "Tests realistic", "max_points": 35, "guidance": "Three."}, {"criterion": "Defences concrete", "max_points": 45, "guidance": "Applied."}, {"criterion": "Honest results", "max_points": 20, "guidance": "Failures."}]$t40f$::jsonb, 20, 'text', false, false),
  (41, $t41a$Privacy, data and compliance$t41a$, $t41b$Handle personal data lawfully.$t41b$, $t41c$Minimise personal data, keep it out of prompts where possible, know where vendors store data, set retention limits and record consent. Rules vary by country; get advice for sensitive uses.$t41c$, $t41d$Privacy, data and compliance$t41d$, $t41e$Write a data map for your agent (data in, where it goes, retention, who sees it).$t41e$, $t41f$[{"criterion": "Map complete", "max_points": 45, "guidance": "Flows."}, {"criterion": "Minimisation", "max_points": 30, "guidance": "Reduced."}, {"criterion": "Retention", "max_points": 25, "guidance": "Defined."}]$t41f$::jsonb, 20, 'text', false, false),
  (42, $t42a$Module project: a tested, defended agent$t42a$, $t42b$Prove your agent works and resists misuse.$t42b$, $t42c$Show Module 2. Deliver an agent with a **test set, metrics, injection defences and a data map**.

Your work is scored on the rubric below. You can revise and resubmit.$t42c$, $t42d$Module project: a tested, defended agent$t42d$, $t42e$Submit the test set summary, metrics, injection test results and data map.$t42e$, $t42f$[{"criterion": "Testing rigour", "max_points": 30, "guidance": "Real."}, {"criterion": "Security", "max_points": 30, "guidance": "Injection handled."}, {"criterion": "Privacy", "max_points": 20, "guidance": "Mapped."}, {"criterion": "Honest limits", "max_points": 20, "guidance": "Stated."}]$t42f$::jsonb, 85, 'text', true, false),
  (43, $t43a$Working with email and calendars$t43a$, $t43b$Automate scheduling safely.$t43b$, $t43c$Read-only access first, drafts not sends, and confirmations before booking. Handle time zones and conflicts. Log every action.$t43c$, $t43d$Working with email and calendars$t43d$, $t43e$Design a scheduling assistant: permissions, drafts, confirmations, conflict handling.$t43e$, $t43f$[{"criterion": "Permissions safe", "max_points": 40, "guidance": "Least privilege."}, {"criterion": "Confirmations", "max_points": 35, "guidance": "Human."}, {"criterion": "Edge cases", "max_points": 25, "guidance": "Time zones."}]$t43f$::jsonb, 20, 'text', false, false),
  (44, $t44a$Spreadsheets and databases$t44a$, $t44b$Let agents read and write data carefully.$t44b$, $t44c$Give write access to one table or sheet, validate inputs, keep a change history and a backup. Never give delete rights by default.$t44c$, $t44d$Spreadsheets and databases$t44d$, $t44e$Design an agent that updates a tracker: fields, validation, history and backup.$t44e$, $t44f$[{"criterion": "Validation", "max_points": 40, "guidance": "Rules."}, {"criterion": "History and backup", "max_points": 35, "guidance": "Recoverable."}, {"criterion": "Scope limited", "max_points": 25, "guidance": "One table."}]$t44f$::jsonb, 20, 'text', false, false),
  (45, $t45a$Webhooks and event-driven flows$t45a$, $t45b$React to events reliably.$t45b$, $t45c$Webhooks send events to your workflow. Verify the sender, handle duplicates (idempotency), retries and out-of-order events.$t45c$, $t45d$Webhooks and event-driven flows$t45d$, $t45e$Describe an event-driven flow and how you handle duplicates, retries and verification.$t45e$, $t45f$[{"criterion": "Verification", "max_points": 35, "guidance": "Sender checked."}, {"criterion": "Duplicates handled", "max_points": 40, "guidance": "Idempotent."}, {"criterion": "Retries", "max_points": 25, "guidance": "Defined."}]$t45f$::jsonb, 20, 'text', false, false),
  (46, $t46a$Browsing and computer-use agents$t46a$, $t46b$Understand the limits and risks.$t46b$, $t46c$Agents that operate websites or apps are slower and riskier. Use official APIs when possible, run in sandboxes, restrict sites and require approval for payments or accounts. Respect site terms.$t46c$, $t46d$Browsing and computer-use agents$t46d$, $t46e$Decide when to use an API vs a browsing agent for three tasks and list safeguards.$t46e$, $t46f$[{"criterion": "API-first thinking", "max_points": 35, "guidance": "Reasoned."}, {"criterion": "Safeguards", "max_points": 40, "guidance": "Concrete."}, {"criterion": "Terms respected", "max_points": 25, "guidance": "Considered."}]$t46f$::jsonb, 20, 'text', false, false),
  (47, $t47a$Notifications and human handoffs$t47a$, $t47b$Involve people at the right time.$t47b$, $t47c$Send concise, actionable messages with the context needed to decide. Escalate by urgency and confidence; avoid alert fatigue.$t47c$, $t47d$Notifications and human handoffs$t47d$, $t47e$Write three handoff messages (low, medium, high urgency) with the decision the human must make.$t47e$, $t47f$[{"criterion": "Actionable", "max_points": 40, "guidance": "Clear ask."}, {"criterion": "Context enough", "max_points": 35, "guidance": "Complete."}, {"criterion": "Urgency levels", "max_points": 25, "guidance": "Distinct."}]$t47f$::jsonb, 20, 'text', false, false),
  (48, $t48a$Module project: an integrated workflow$t48a$, $t48b$Connect agents to real tools safely.$t48b$, $t48c$Show Module 3. Deliver a workflow integrating **two tools** with permissions, approvals, logging and event handling.

Your work is scored on the rubric below. You can revise and resubmit.$t48c$, $t48d$Module project: an integrated workflow$t48d$, $t48e$Submit the workflow design, permissions, approval points, sample logs and test results.

**Evidence:** paste *direct* links to screenshots (ending .png/.jpg/.webp), one per line, and describe them.$t48e$, $t48f$[{"criterion": "Integration works", "max_points": 30, "guidance": "Evidence."}, {"criterion": "Least privilege", "max_points": 25, "guidance": "Safe."}, {"criterion": "Approvals and logs", "max_points": 25, "guidance": "Present."}, {"criterion": "Tested", "max_points": 20, "guidance": "Results."}]$t48f$::jsonb, 90, 'link', true, false),
  (49, $t49a$Monitoring in production$t49a$, $t49b$Watch agents after launch.$t49b$, $t49c$Track success rate, failures, cost, latency and interventions on a simple dashboard. Alert on thresholds. Review samples weekly.$t49c$, $t49d$Monitoring in production$t49d$, $t49e$Define a dashboard (six metrics) with alert thresholds.$t49e$, $t49f$[{"criterion": "Metrics useful", "max_points": 40, "guidance": "Six."}, {"criterion": "Thresholds sensible", "max_points": 35, "guidance": "Reasoned."}, {"criterion": "Review routine", "max_points": 25, "guidance": "Weekly."}]$t49f$::jsonb, 20, 'text', false, false),
  (50, $t50a$Versioning and safe rollout$t50a$, $t50b$Change agents without surprises.$t50b$, $t50c$Version prompts and configs, test on the test set, roll out to a few users first and keep a rollback.$t50c$, $t50d$Versioning and safe rollout$t50d$, $t50e$Write a rollout plan for a prompt change with test gates and rollback.$t50e$, $t50f$[{"criterion": "Test gates", "max_points": 40, "guidance": "Defined."}, {"criterion": "Staged rollout", "max_points": 35, "guidance": "Small first."}, {"criterion": "Rollback", "max_points": 25, "guidance": "Ready."}]$t50f$::jsonb, 20, 'text', false, false),
  (51, $t51a$Cost and scale$t51a$, $t51b$Keep spend under control at volume.$t51b$, $t51c$Estimate cost at 10x usage, cache, batch, use cheaper models for easy steps and set budgets with alerts.$t51c$, $t51d$Cost and scale$t51d$, $t51e$Model costs at 1x, 10x and 100x usage with three saving measures.$t51e$, $t51f$[{"criterion": "Model sensible", "max_points": 40, "guidance": "Numbers."}, {"criterion": "Savings realistic", "max_points": 40, "guidance": "Three."}, {"criterion": "Budget alerts", "max_points": 20, "guidance": "Defined."}]$t51f$::jsonb, 20, 'text', false, false),
  (52, $t52a$Accountability and audit trails$t52a$, $t52b$Be able to explain what happened.$t52b$, $t52c$Log inputs, decisions, actions, approvals and versions. Keep records as long as needed and no longer. Be ready to explain any action to the person affected.$t52c$, $t52d$Accountability and audit trails$t52d$, $t52e$Design an audit log format and show a sample entry for a consequential action.$t52e$, $t52f$[{"criterion": "Log complete", "max_points": 45, "guidance": "Fields."}, {"criterion": "Sample realistic", "max_points": 30, "guidance": "Clear."}, {"criterion": "Retention", "max_points": 25, "guidance": "Defined."}]$t52f$::jsonb, 20, 'text', false, false),
  (53, $t53a$Communicating about agents to users$t53a$, $t53b$Be honest about what the agent does.$t53b$, $t53c$Tell users when they are dealing with an agent, what it can and cannot do, how to reach a human and how their data is used.$t53c$, $t53d$Communicating about agents to users$t53d$, $t53e$Write user-facing disclosure and help text for your agent.$t53e$, $t53f$[{"criterion": "Honest disclosure", "max_points": 40, "guidance": "Clear."}, {"criterion": "Limits stated", "max_points": 30, "guidance": "Explicit."}, {"criterion": "Human route", "max_points": 30, "guidance": "Easy."}]$t53f$::jsonb, 20, 'text', false, false),
  (54, $t54a$Module project: a production-ready agent$t54a$, $t54b$Deliver an operable, monitored agent.$t54b$, $t54c$Show Module 4. Deliver an agent with **monitoring, rollout plan, cost model, audit log and user disclosure**.

Your work is scored on the rubric below. You can revise and resubmit.$t54c$, $t54d$Module project: a production-ready agent$t54d$, $t54e$Submit the dashboard definition, rollout plan, cost model, audit sample and disclosure.$t54e$, $t54f$[{"criterion": "Operable", "max_points": 30, "guidance": "Monitoring."}, {"criterion": "Cost controlled", "max_points": 20, "guidance": "Modelled."}, {"criterion": "Accountable", "max_points": 30, "guidance": "Audit."}, {"criterion": "Honest to users", "max_points": 20, "guidance": "Disclosure."}]$t54f$::jsonb, 90, 'text', true, false),
  (55, $t55a$Pro capstone 1: choose a client workflow$t55a$, $t55b$Scope a real automation with measurable value.$t55b$, $t55c$Choose a real workflow for a person or business, measure the current time and error rate for a week.$t55c$, $t55d$Pro capstone 1: choose a client workflow$t55d$, $t55e$Submit baseline measurements and the scope.$t55e$, $t55f$[{"criterion": "Baseline real", "max_points": 45, "guidance": "Measured."}, {"criterion": "Scope clear", "max_points": 30, "guidance": "Defined."}, {"criterion": "Value estimate", "max_points": 25, "guidance": "Reasoned."}]$t55f$::jsonb, 20, 'text', false, false),
  (56, $t56a$Pro capstone 2: architecture and risks$t56a$, $t56b$Design and review risks.$t56b$, $t56c$Design the system and a risk register: what could go wrong, impact, mitigation.$t56c$, $t56d$Pro capstone 2: architecture and risks$t56d$, $t56e$Submit architecture and risk register.

**Evidence:** paste *direct* links to screenshots (ending .png/.jpg/.webp), one per line, and describe them.$t56e$, $t56f$[{"criterion": "Architecture sound", "max_points": 40, "guidance": "Simple."}, {"criterion": "Risks realistic", "max_points": 40, "guidance": "Complete."}, {"criterion": "Mitigations", "max_points": 20, "guidance": "Concrete."}]$t56f$::jsonb, 20, 'link', false, false),
  (57, $t57a$Pro capstone 3: build and test$t57a$, $t57b$Build the system and test against a test set.$t57b$, $t57c$Build it and run a 20-task test set.$t57c$, $t57d$Pro capstone 3: build and test$t57d$, $t57e$Submit test results and fixes.$t57e$, $t57f$[{"criterion": "Works", "max_points": 40, "guidance": "Evidence."}, {"criterion": "Test set", "max_points": 35, "guidance": "Twenty."}, {"criterion": "Fixes", "max_points": 25, "guidance": "Applied."}]$t57f$::jsonb, 75, 'text', false, false),
  (58, $t58a$Pro capstone 4: security, privacy and approvals$t58a$, $t58b$Harden the system.$t58b$, $t58c$Add approvals, injection tests, data map and permissions review.$t58c$, $t58d$Pro capstone 4: security, privacy and approvals$t58d$, $t58e$Submit results for each.$t58e$, $t58f$[{"criterion": "Injection tested", "max_points": 35, "guidance": "Results."}, {"criterion": "Approvals right", "max_points": 35, "guidance": "Placed."}, {"criterion": "Data mapped", "max_points": 30, "guidance": "Complete."}]$t58f$::jsonb, 20, 'text', false, false),
  (59, $t59a$Pro capstone 5: pilot and measure$t59a$, $t59b$Run it for a real week.$t59b$, $t59c$Pilot with a real user for a week and measure time saved, errors and interventions.$t59c$, $t59d$Pro capstone 5: pilot and measure$t59d$, $t59e$Submit pilot results against baseline.$t59e$, $t59f$[{"criterion": "Real pilot", "max_points": 35, "guidance": "Evidence."}, {"criterion": "Improvement measured", "max_points": 40, "guidance": "Numbers."}, {"criterion": "Issues honest", "max_points": 25, "guidance": "Reported."}]$t59f$::jsonb, 20, 'text', false, false),
  (60, $t60a$Pro capstone 6: deliver the system$t60a$, $t60b$Hand over a documented, monitored automation.$t60b$, $t60c$Deliver documentation, monitoring, rollout and rollback plans, cost model and a client summary. Share in the Discord and ask for one piece of feedback.

Your work is scored on the rubric below. You can revise and resubmit.$t60c$, $t60d$Pro capstone 6: deliver the system$t60d$, $t60e$Submit the delivery pack and a one-page client summary with results.$t60e$, $t60f$[{"criterion": "Results vs baseline", "max_points": 30, "guidance": "Measured."}, {"criterion": "Safety and control", "max_points": 30, "guidance": "Approvals, audit."}, {"criterion": "Documentation", "max_points": 20, "guidance": "Usable."}, {"criterion": "Honesty", "max_points": 20, "guidance": "Limits."}]$t60f$::jsonb, 90, 'text', true, false)
) as v(n, title, objective, lesson_md, skill_focus, assignment_md, rubric, est_minutes, submission_type, ai_evaluate, requires_review)
where t.slug = 'agents'
on conflict (track_id, day_number) do nothing;
