-- Research & data, Expert tier (days 61-80). Authored content, UNPUBLISHED until a person reviews it in Admin.
insert into public.day
  (track_id, tier_id, day_number, title, objective, lesson_md, skill_focus, assignment_md, rubric,
   est_minutes, is_published, credit_budget, submission_type, ai_evaluate, requires_review)
select t.id, ti.id, v.n, v.title, v.objective, v.lesson_md, v.skill_focus, v.assignment_md, v.rubric,
       v.est_minutes, false, null, v.submission_type, v.ai_evaluate, v.requires_review
from public.track t
join public.tier ti on ti.track_id = t.id and ti.slug = 'expert'
cross join (values
  (61, $t61a$Study design and causal reasoning$t61a$, $t61b$Choose designs that can answer causal questions.$t61b$, $t61c$Experiments, natural experiments, matched comparisons and observational studies differ in what they can prove. Know confounders, selection and reverse causation, and state what your design cannot show.$t61c$, $t61d$Study design and causal reasoning$t61d$, $t61e$For three questions, choose a design, name the main threats and the strongest claim allowed.$t61e$, $t61f$[{"criterion": "Designs suited", "max_points": 40, "guidance": "Fit."}, {"criterion": "Threats named", "max_points": 35, "guidance": "Specific."}, {"criterion": "Claims scoped", "max_points": 25, "guidance": "Limited."}]$t61f$::jsonb, 45, 'text', false, false),
  (62, $t62a$Statistical inference in practice$t62a$, $t62b$Use intervals and effect sizes sensibly.$t62b$, $t62c$Report effect size with a confidence interval, not just a p-value. Understand power, multiple comparisons and why small samples mislead. Pre-register what you will test when possible.$t62c$, $t62d$Statistical inference in practice$t62d$, $t62e$Analyse a public dataset comparing two groups with effect size, interval and a plain-language conclusion.$t62e$, $t62f$[{"criterion": "Correct method", "max_points": 40, "guidance": "Sound."}, {"criterion": "Effect sizes", "max_points": 30, "guidance": "Reported."}, {"criterion": "Plain conclusion", "max_points": 30, "guidance": "Honest."}]$t62f$::jsonb, 60, 'text', false, false),
  (63, $t63a$Working with code for analysis$t63a$, $t63b$Make analysis repeatable.$t63b$, $t63c$Use a notebook or script, set seeds, record package versions and data source, and use AI to draft code that you read and test on known answers.$t63c$, $t63d$Working with code for analysis$t63d$, $t63e$Submit a reproducible analysis with a data source, code summary and three verification checks.$t63e$, $t63f$[{"criterion": "Reproducible", "max_points": 40, "guidance": "Steps."}, {"criterion": "Verified", "max_points": 35, "guidance": "Known-answer checks."}, {"criterion": "AI use noted", "max_points": 25, "guidance": "Recorded."}]$t63f$::jsonb, 60, 'text', false, false),
  (64, $t64a$Systematic review method$t64a$, $t64b$Review evidence rigorously.$t64b$, $t64c$Define inclusion criteria, search multiple sources, screen in two stages, extract data with a form and assess bias. Report the flow of studies.$t64c$, $t64d$Systematic review method$t64d$, $t64e$Run a mini systematic review of ten studies with criteria, flow counts and a bias assessment.$t64e$, $t64f$[{"criterion": "Criteria clear", "max_points": 30, "guidance": "Explicit."}, {"criterion": "Flow reported", "max_points": 35, "guidance": "Counts."}, {"criterion": "Bias assessed", "max_points": 35, "guidance": "Applied."}]$t64f$::jsonb, 90, 'text', false, false),
  (65, $t65a$Expert project 1: a rigorous evidence synthesis$t65a$, $t65b$Deliver a defensible review.$t65b$, $t65c$Show Module 1. Deliver an **evidence synthesis** with design reasoning, analysis, reproducibility and review method.

Your work is scored on the rubric below. You can revise and resubmit.$t65c$, $t65d$Expert project 1: a rigorous evidence synthesis$t65d$, $t65e$Submit the report and reproducibility pack.$t65e$, $t65f$[{"criterion": "Method rigour", "max_points": 30, "guidance": "Sound."}, {"criterion": "Analysis correct", "max_points": 25, "guidance": "Verified."}, {"criterion": "Reproducibility", "max_points": 25, "guidance": "Complete."}, {"criterion": "Honest limits", "max_points": 20, "guidance": "Stated."}]$t65f$::jsonb, 150, 'text', true, false),
  (66, $t66a$Modelling and forecasting$t66a$, $t66b$Build simple predictive models.$t66b$, $t66c$Split data into train and test, use a baseline, evaluate with sensible metrics, check for leakage and explain what drives predictions.$t66c$, $t66d$Modelling and forecasting$t66d$, $t66e$Build a simple model with a baseline, test metrics and a leakage check.$t66e$, $t66f$[{"criterion": "Baseline and split", "max_points": 35, "guidance": "Correct."}, {"criterion": "Metrics sensible", "max_points": 35, "guidance": "Fit."}, {"criterion": "Leakage checked", "max_points": 30, "guidance": "Done."}]$t66f$::jsonb, 60, 'text', false, false),
  (67, $t67a$Text and unstructured data analysis$t67a$, $t67b$Analyse documents at scale.$t67b$, $t67c$Use AI to classify or extract from many documents, then measure accuracy on a hand-labelled sample and report error rates.$t67c$, $t67d$Text and unstructured data analysis$t67d$, $t67e$Classify 50 documents with AI and report accuracy against 20 hand-labelled examples.$t67e$, $t67f$[{"criterion": "Sample labelled", "max_points": 35, "guidance": "Human."}, {"criterion": "Accuracy reported", "max_points": 40, "guidance": "Numbers."}, {"criterion": "Errors analysed", "max_points": 25, "guidance": "Insight."}]$t67f$::jsonb, 75, 'text', false, false),
  (68, $t68a$Data visualisation for decision-making$t68a$, $t68b$Design charts that change decisions.$t68b$, $t68c$Choose the chart for the question, reduce clutter, annotate the takeaway and test comprehension with a non-expert.$t68c$, $t68d$Data visualisation for decision-making$t68d$, $t68e$Produce three charts with takeaways and test one with a non-expert.$t68e$, $t68f$[{"criterion": "Right chart", "max_points": 35, "guidance": "Suited."}, {"criterion": "Takeaway clear", "max_points": 35, "guidance": "Annotated."}, {"criterion": "Tested", "max_points": 30, "guidance": "Non-expert."}]$t68f$::jsonb, 45, 'text', false, false),
  (69, $t69a$Bias, fairness and model audits$t69a$, $t69b$Audit an AI or model output.$t69b$, $t69c$Compare error rates across groups, check data representation and document mitigation. Fairness definitions can conflict; state your choice.$t69c$, $t69d$Bias, fairness and model audits$t69d$, $t69e$Audit a classifier or AI output across two groups and report differences.$t69e$, $t69f$[{"criterion": "Groups compared", "max_points": 40, "guidance": "Real."}, {"criterion": "Findings honest", "max_points": 35, "guidance": "Reported."}, {"criterion": "Mitigation", "max_points": 25, "guidance": "Considered."}]$t69f$::jsonb, 60, 'text', false, false),
  (70, $t70a$Expert project 2: a predictive or classification study$t70a$, $t70b$Deliver a tested analysis.$t70b$, $t70c$Show Module 2. Deliver a **study** with model or classification, evaluation, fairness audit and visuals.

Your work is scored on the rubric below. You can revise and resubmit.$t70c$, $t70d$Expert project 2: a predictive or classification study$t70d$, $t70e$Submit the study and code summary.$t70e$, $t70f$[{"criterion": "Method and evaluation", "max_points": 30, "guidance": "Sound."}, {"criterion": "Fairness audit", "max_points": 25, "guidance": "Done."}, {"criterion": "Communication", "max_points": 25, "guidance": "Clear."}, {"criterion": "Honesty", "max_points": 20, "guidance": "Limits."}]$t70f$::jsonb, 150, 'text', true, false),
  (71, $t71a$Research for organisations: needs assessment$t71a$, $t71b$Find what an organisation actually needs.$t71b$, $t71c$Stakeholder interviews, data audit and decision mapping. Separate what they ask for from what they need.$t71c$, $t71d$Research for organisations: needs assessment$t71d$, $t71e$Run a needs assessment for a real or realistic organisation; submit findings.$t71e$, $t71f$[{"criterion": "Stakeholders heard", "max_points": 35, "guidance": "Multiple."}, {"criterion": "Need vs ask", "max_points": 40, "guidance": "Insight."}, {"criterion": "Actionable", "max_points": 25, "guidance": "Clear."}]$t71f$::jsonb, 60, 'text', false, false),
  (72, $t72a$Evaluation of programmes and products$t72a$, $t72b$Measure whether something works.$t72b$, $t72c$Define outcomes, baseline, comparison and timeline. Use logic models and be honest about attribution.$t72c$, $t72d$Evaluation of programmes and products$t72d$, $t72e$Design an evaluation for a programme with outcomes, comparison and limits.$t72e$, $t72f$[{"criterion": "Outcomes measurable", "max_points": 35, "guidance": "Defined."}, {"criterion": "Comparison", "max_points": 35, "guidance": "Fair."}, {"criterion": "Attribution limits", "max_points": 30, "guidance": "Honest."}]$t72f$::jsonb, 45, 'text', false, false),
  (73, $t73a$Research ethics review$t73a$, $t73b$Prepare an ethics application.$t73b$, $t73c$Purpose, participants, consent, risks, data protection, benefits and withdrawal. Sensitive topics need extra care and often formal review.$t73c$, $t73d$Research ethics review$t73d$, $t73e$Write an ethics application for a study involving people.$t73e$, $t73f$[{"criterion": "Consent and risk", "max_points": 40, "guidance": "Clear."}, {"criterion": "Data protection", "max_points": 35, "guidance": "Concrete."}, {"criterion": "Withdrawal", "max_points": 25, "guidance": "Included."}]$t73f$::jsonb, 45, 'text', false, false),
  (74, $t74a$Communicating with policymakers and the public$t74a$, $t74b$Translate research for decisions.$t74b$, $t74c$Policy brief format, plain language, options and trade-offs, and confidence statements. Avoid advocacy disguised as evidence.$t74c$, $t74d$Communicating with policymakers and the public$t74d$, $t74e$Write a two-page policy brief with options and confidence.$t74e$, $t74f$[{"criterion": "Plain and structured", "max_points": 35, "guidance": "Clear."}, {"criterion": "Options fair", "max_points": 35, "guidance": "Balanced."}, {"criterion": "Confidence stated", "max_points": 30, "guidance": "Honest."}]$t74f$::jsonb, 45, 'text', false, false),
  (75, $t75a$Expert project 3: an evaluation and brief$t75a$, $t75b$Deliver evaluation with communication.$t75b$, $t75c$Show Module 3. Deliver a **programme evaluation** with needs assessment, ethics plan and policy brief.

Your work is scored on the rubric below. You can revise and resubmit.$t75c$, $t75d$Expert project 3: an evaluation and brief$t75d$, $t75e$Submit all parts.$t75e$, $t75f$[{"criterion": "Evaluation design", "max_points": 30, "guidance": "Sound."}, {"criterion": "Ethics", "max_points": 25, "guidance": "Handled."}, {"criterion": "Brief quality", "max_points": 25, "guidance": "Clear."}, {"criterion": "Honesty", "max_points": 20, "guidance": "Limits."}]$t75f$::jsonb, 150, 'text', true, false),
  (76, $t76a$Flagship: question and pre-registration$t76a$, $t76b$Commit to a plan before looking.$t76b$, $t76c$Write the question, hypotheses, methods and analysis plan before collecting data.$t76c$, $t76d$Flagship: question and pre-registration$t76d$, $t76e$Submit the pre-registration plan.$t76e$, $t76f$[{"criterion": "Question sharp", "max_points": 30, "guidance": "Specific."}, {"criterion": "Hypotheses testable", "max_points": 35, "guidance": "Clear."}, {"criterion": "Analysis plan", "max_points": 35, "guidance": "Defined."}]$t76f$::jsonb, 75, 'text', false, false),
  (77, $t77a$Flagship: collect and clean$t77a$, $t77b$Gather quality data.$t77b$, $t77c$Collect data or evidence with a log of decisions and quality checks.$t77c$, $t77d$Flagship: collect and clean$t77d$, $t77e$Submit data summary and quality log.$t77e$, $t77f$[{"criterion": "Quality checks", "max_points": 40, "guidance": "Real."}, {"criterion": "Log", "max_points": 35, "guidance": "Complete."}, {"criterion": "Ethics followed", "max_points": 25, "guidance": "Yes."}]$t77f$::jsonb, 90, 'text', false, false),
  (78, $t78a$Flagship: analyse and challenge$t78a$, $t78b$Test your own findings.$t78b$, $t78c$Run the planned analysis, then robustness checks and alternative explanations.$t78c$, $t78d$Flagship: analyse and challenge$t78d$, $t78e$Submit results, robustness checks and changes from plan (with reasons).$t78e$, $t78f$[{"criterion": "Follows plan", "max_points": 30, "guidance": "Faithful."}, {"criterion": "Robustness", "max_points": 40, "guidance": "Checks."}, {"criterion": "Deviations honest", "max_points": 30, "guidance": "Reported."}]$t78f$::jsonb, 90, 'text', false, false),
  (79, $t79a$Flagship: write and review$t79a$, $t79b$Draft and get expert critique.$t79b$, $t79c$Draft the report and obtain critique from one expert; respond in writing.$t79c$, $t79d$Flagship: write and review$t79d$, $t79e$Submit critique and response.$t79e$, $t79f$[{"criterion": "Critique real", "max_points": 35, "guidance": "Specific."}, {"criterion": "Response fair", "max_points": 40, "guidance": "Considered."}, {"criterion": "Improved", "max_points": 25, "guidance": "Better."}]$t79f$::jsonb, 60, 'text', false, false),
  (80, $t80a$Expert project 4: the flagship study$t80a$, $t80b$Deliver original, defensible research.$t80b$, $t80c$Show Module 4. Deliver the **flagship study**: plan, data, analysis, robustness, expert response and reproducibility pack.

Your work is scored on the rubric below. You can revise and resubmit.$t80c$, $t80d$Expert project 4: the flagship study$t80d$, $t80e$Submit the report and pack.$t80e$, $t80f$[{"criterion": "Rigour", "max_points": 30, "guidance": "High."}, {"criterion": "Honesty", "max_points": 25, "guidance": "Limits."}, {"criterion": "Reproducibility", "max_points": 20, "guidance": "Complete."}, {"criterion": "Communication", "max_points": 25, "guidance": "Clear."}]$t80f$::jsonb, 200, 'text', true, false)
) as v(n, title, objective, lesson_md, skill_focus, assignment_md, rubric, est_minutes, submission_type, ai_evaluate, requires_review)
where t.slug = 'research'
on conflict (track_id, day_number) do nothing;
