-- Motion graphics, Basic tier (days 1-30). Authored content, UNPUBLISHED until a person reviews it in Admin.
insert into public.day
  (track_id, tier_id, day_number, title, objective, lesson_md, skill_focus, assignment_md, rubric,
   est_minutes, is_published, credit_budget, submission_type, ai_evaluate, requires_review)
select t.id, ti.id, v.n, v.title, v.objective, v.lesson_md, v.skill_focus, v.assignment_md, v.rubric,
       v.est_minutes, false, null, v.submission_type, v.ai_evaluate, v.requires_review
from public.track t
join public.tier ti on ti.track_id = t.id and ti.slug = 'basic'
cross join (values
  (1, $t1a$What motion graphics are for$t1a$, $t1b$Explain when motion helps a message and when it hurts.$t1b$, $t1c$Motion graphics are designed movement: animated text, logos, charts and explainers. Use motion to **direct attention**, **explain change over time** and **add polish**. Do not use it to decorate.

Start where you are comfortable: [CREAO](https://agent.creao.ai/@Sonofpeace) (referral link) is our recommended first tool for generating assets and planning; Canva, CapCut, Jitter, LottieFiles and After Effects are good animators.$t1c$, $t1d$What motion graphics are for$t1d$, $t1e$Find three animated pieces you admire (describe or link). For each say what the motion does for the message.$t1e$, $t1f$[{"criterion": "Examples relevant", "max_points": 30, "guidance": "Real pieces."}, {"criterion": "Motion purpose identified", "max_points": 45, "guidance": "Attention, explanation or polish."}, {"criterion": "Critical eye", "max_points": 25, "guidance": "Notes what is unnecessary."}]$t1f$::jsonb, 15, 'text', false, false),
  (2, $t2a$Timing and easing$t2a$, $t2b$Understand why speed and acceleration change the feel.$t2b$, $t2c$Timing is how long; **easing** is how speed changes. Ease out (fast then slow) feels natural for things arriving; ease in for leaving. Linear feels robotic. Typical UI moves take 200 to 500 ms.$t2c$, $t2d$Timing and easing$t2d$, $t2e$Animate one shape moving across the screen three ways (linear, ease-in-out, bouncy). Submit the link and describe how each feels.

**Sharing:** upload the animation (MP4/GIF) somewhere viewable and paste the link. Animation is checked by a person.$t2e$, $t2f$[{"criterion": "Three versions", "max_points": 35, "guidance": "Distinct."}, {"criterion": "Descriptions accurate", "max_points": 40, "guidance": "Feel explained."}, {"criterion": "Timing sensible", "max_points": 25, "guidance": "Not too slow."}]$t2f$::jsonb, 20, 'link', false, true),
  (3, $t3a$Principles of animation for designers$t3a$, $t3b$Apply anticipation, follow-through and staging.$t3b$, $t3c$Anticipation (a small move back before a jump), follow-through (things settle), staging (one thing moves at a time) and appeal make motion readable. Fewer, clearer moves beat lots of movement.$t3c$, $t3d$Principles of animation for designers$t3d$, $t3e$Animate a simple object using two of these principles. Submit the link and name where each appears.

**Sharing:** upload the animation (MP4/GIF) somewhere viewable and paste the link. Animation is checked by a person.$t3e$, $t3f$[{"criterion": "Principles visible", "max_points": 50, "guidance": "Two applied."}, {"criterion": "Clean staging", "max_points": 30, "guidance": "One focus."}, {"criterion": "Named accurately", "max_points": 20, "guidance": "Correct."}]$t3f$::jsonb, 20, 'link', false, true),
  (4, $t4a$Storyboarding motion$t4a$, $t4b$Plan motion in frames before animating.$t4b$, $t4c$Sketch key frames: start, middle, end. Note duration and easing beside each. Storyboards prevent rework.$t4c$, $t4d$Storyboarding motion$t4d$, $t4e$Storyboard a 5-second animation with at least four frames and timing notes. Submit direct image links.

Paste *direct* image links ending .png/.jpg/.webp.$t4e$, $t4f$[{"criterion": "Key frames clear", "max_points": 45, "guidance": "Readable."}, {"criterion": "Timing noted", "max_points": 30, "guidance": "Durations."}, {"criterion": "Purposeful", "max_points": 25, "guidance": "Supports message."}]$t4f$::jsonb, 20, 'link', false, false),
  (5, $t5a$Your first animated title$t5a$, $t5b$Animate a short line of text well.$t5b$, $t5c$Animate a title: reveal, hold, exit. Keep it readable: 2 seconds to read a short line. Use contrast and one font.$t5c$, $t5d$Your first animated title$t5d$, $t5e$Animate a title (under 6 words). Submit the link and the timings (in, hold, out).

**Sharing:** upload the animation (MP4/GIF) somewhere viewable and paste the link. Animation is checked by a person.$t5e$, $t5f$[{"criterion": "Readable", "max_points": 40, "guidance": "Clear."}, {"criterion": "Timing appropriate", "max_points": 35, "guidance": "Sensible."}, {"criterion": "Polished", "max_points": 25, "guidance": "Clean."}]$t5f$::jsonb, 20, 'link', false, true),
  (6, $t6a$Module project: an animated title sequence$t6a$, $t6b$Deliver a 10-second title sequence.$t6b$, $t6c$Show Module 1. Create a **10-second animated title sequence** with a storyboard, purposeful easing and clear text.

A person reviews your work and can ask for revisions.$t6c$, $t6d$Module project: an animated title sequence$t6d$, $t6e$Submit the storyboard image links, the animation link and a note on your easing and timing choices.

**Sharing:** upload the animation (MP4/GIF) somewhere viewable and paste the link. Animation is checked by a person.$t6e$, $t6f$[{"criterion": "Readable and clear", "max_points": 30, "guidance": "Text works."}, {"criterion": "Easing and timing", "max_points": 30, "guidance": "Deliberate."}, {"criterion": "Planning", "max_points": 20, "guidance": "Storyboard."}, {"criterion": "Polish", "max_points": 20, "guidance": "Clean."}]$t6f$::jsonb, 60, 'link', false, true),
  (7, $t7a$Kinetic typography$t7a$, $t7b$Make words move with meaning.$t7b$, $t7c$Match motion to meaning: bold arrives with impact, soft with ease. Time word reveals to speech. Limit to one or two effects.$t7c$, $t7d$Kinetic typography$t7d$, $t7e$Animate a 15-word quote. Submit the link and how motion matches meaning.

**Sharing:** upload the animation (MP4/GIF) somewhere viewable and paste the link. Animation is checked by a person.$t7e$, $t7f$[{"criterion": "Motion matches words", "max_points": 45, "guidance": "Meaningful."}, {"criterion": "Legible", "max_points": 30, "guidance": "Readable."}, {"criterion": "Restraint", "max_points": 25, "guidance": "Few effects."}]$t7f$::jsonb, 20, 'link', false, true),
  (8, $t8a$Shape and icon animation$t8a$, $t8b$Animate simple graphics smoothly.$t8b$, $t8c$Icons can morph, draw on or pop. Keep them small and quick. Export lightweight formats (Lottie or GIF) for the web.$t8c$, $t8d$Shape and icon animation$t8d$, $t8e$Animate three icons. Submit links and the format and file size of each.

**Sharing:** upload the animation (MP4/GIF) somewhere viewable and paste the link. Animation is checked by a person.$t8e$, $t8f$[{"criterion": "Smooth", "max_points": 40, "guidance": "Clean motion."}, {"criterion": "Consistent style", "max_points": 30, "guidance": "Matching."}, {"criterion": "Lightweight", "max_points": 30, "guidance": "Sizes given."}]$t8f$::jsonb, 20, 'link', false, true),
  (9, $t9a$Charts and data in motion$t9a$, $t9b$Reveal data step by step.$t9b$, $t9c$Animated charts guide attention: show one series at a time, highlight the point. Never distort data for effect. Label clearly.$t9c$, $t9d$Charts and data in motion$t9d$, $t9e$Animate a simple chart with real data (cite it). Submit the link, source and the story it tells.

**Sharing:** upload the animation (MP4/GIF) somewhere viewable and paste the link. Animation is checked by a person.$t9e$, $t9f$[{"criterion": "Honest data", "max_points": 40, "guidance": "Accurate."}, {"criterion": "Reveal supports story", "max_points": 35, "guidance": "Purposeful."}, {"criterion": "Clear labels", "max_points": 25, "guidance": "Readable."}]$t9f$::jsonb, 20, 'link', false, true),
  (10, $t10a$Transitions and scene flow$t10a$, $t10b$Move between scenes without confusion.$t10b$, $t10c$Use transitions that match the story: a wipe for new sections, a match cut for continuity. Avoid flashy effects.$t10c$, $t10d$Transitions and scene flow$t10d$, $t10e$Create a three-scene piece with two transitions. Submit the link and why each transition fits.

**Sharing:** upload the animation (MP4/GIF) somewhere viewable and paste the link. Animation is checked by a person.$t10e$, $t10f$[{"criterion": "Transitions fit", "max_points": 45, "guidance": "Reasoned."}, {"criterion": "Flow clear", "max_points": 35, "guidance": "Easy to follow."}, {"criterion": "Restraint", "max_points": 20, "guidance": "Simple."}]$t10f$::jsonb, 20, 'link', false, true),
  (11, $t11a$Colour, brand and consistency in motion$t11a$, $t11b$Keep an animated set on brand.$t11b$, $t11c$Use the brand palette and fonts, the same easing family and consistent durations. Build a small motion style guide.$t11c$, $t11d$Colour, brand and consistency in motion$t11d$, $t11e$Write a one-page motion style guide (easing, durations, palette, fonts) and show one example.

**Sharing:** upload the animation (MP4/GIF) somewhere viewable and paste the link. Animation is checked by a person.$t11e$, $t11f$[{"criterion": "Guide is usable", "max_points": 50, "guidance": "Clear."}, {"criterion": "Example follows it", "max_points": 30, "guidance": "Consistent."}, {"criterion": "On brand", "max_points": 20, "guidance": "Matches."}]$t11f$::jsonb, 20, 'link', false, true),
  (12, $t12a$Module project: a 20-second animated message$t12a$, $t12b$Combine type, shapes and transitions.$t12b$, $t12c$Show Module 2. Create a **20-second animated message** with kinetic type, an icon or chart, transitions and a motion style guide.

A person reviews your work and can ask for revisions.$t12c$, $t12d$Module project: a 20-second animated message$t12d$, $t12e$Submit the link, storyboard links and your style guide.

**Sharing:** upload the animation (MP4/GIF) somewhere viewable and paste the link. Animation is checked by a person.$t12e$, $t12f$[{"criterion": "Message clear", "max_points": 30, "guidance": "Understandable."}, {"criterion": "Craft", "max_points": 30, "guidance": "Timing and easing."}, {"criterion": "Consistency", "max_points": 20, "guidance": "Guide followed."}, {"criterion": "Planning", "max_points": 20, "guidance": "Storyboard."}]$t12f$::jsonb, 80, 'link', false, true),
  (13, $t13a$Logo animation$t13a$, $t13b$Animate a logo reveal in under 4 seconds.$t13b$, $t13c$A logo sting should be short and clear: build, settle, hold. It must end on the static logo, readable. Prepare a clean vector logo.$t13c$, $t13d$Logo animation$t13d$, $t13e$Animate a logo reveal (2 to 4 seconds). Submit the link and the still end frame.

**Sharing:** upload the animation (MP4/GIF) somewhere viewable and paste the link. Animation is checked by a person.$t13e$, $t13f$[{"criterion": "Short and clear", "max_points": 40, "guidance": "Under 4 seconds."}, {"criterion": "Ends readable", "max_points": 35, "guidance": "Clean final frame."}, {"criterion": "Fits brand", "max_points": 25, "guidance": "Matches."}]$t13f$::jsonb, 20, 'link', false, true),
  (14, $t14a$Explainer basics$t14a$, $t14b$Structure a 30-second explainer.$t14b$, $t14c$Structure: problem, idea, how it works in three steps, result, call to action. Voiceover first, animation second. One idea per scene.$t14c$, $t14d$Explainer basics$t14d$, $t14e$Write a 30-second explainer script with scene breakdown. Submit the script and scene list.$t14e$, $t14f$[{"criterion": "Clear structure", "max_points": 40, "guidance": "Complete."}, {"criterion": "One idea per scene", "max_points": 30, "guidance": "Focused."}, {"criterion": "Simple language", "max_points": 30, "guidance": "Understandable."}]$t14f$::jsonb, 20, 'text', false, false),
  (15, $t15a$Using AI assets in motion$t15a$, $t15b$Generate and prepare images for animation.$t15b$, $t15c$Generate layered or separable assets: subject, background, effects. Remove backgrounds, keep consistent style, check licences. Parallax from layers is an easy win.$t15c$, $t15d$Using AI assets in motion$t15d$, $t15e$Create a three-layer parallax from AI images. Submit the layers (image links), the animation link and the licence notes.

**Sharing:** upload the animation (MP4/GIF) somewhere viewable and paste the link. Animation is checked by a person.$t15e$, $t15f$[{"criterion": "Layers separable", "max_points": 35, "guidance": "Clean cut-outs."}, {"criterion": "Parallax works", "max_points": 35, "guidance": "Depth."}, {"criterion": "Licences checked", "max_points": 30, "guidance": "Documented."}]$t15f$::jsonb, 20, 'link', false, true),
  (16, $t16a$Sound design for motion$t16a$, $t16b$Add sound that sells the motion.$t16b$, $t16c$Whooshes, clicks and hits should land exactly on movement. Keep volume low. Use licensed sound.$t16c$, $t16d$Sound design for motion$t16d$, $t16e$Add sound effects to an animation. Submit the link and sources with licences.

**Sharing:** upload the animation (MP4/GIF) somewhere viewable and paste the link. Animation is checked by a person.$t16e$, $t16f$[{"criterion": "Sync", "max_points": 40, "guidance": "On the beat."}, {"criterion": "Restrained", "max_points": 30, "guidance": "Not overdone."}, {"criterion": "Licences", "max_points": 30, "guidance": "Documented."}]$t16f$::jsonb, 20, 'link', false, true),
  (17, $t17a$Loops and social motion$t17a$, $t17b$Create a seamless loop.$t17b$, $t17c$Loops keep attention. Make the last frame match the first. Keep files small and check on a phone.$t17c$, $t17d$Loops and social motion$t17d$, $t17e$Create a 4-second loop. Submit the link and file size.

**Sharing:** upload the animation (MP4/GIF) somewhere viewable and paste the link. Animation is checked by a person.$t17e$, $t17f$[{"criterion": "Seamless", "max_points": 45, "guidance": "No jump."}, {"criterion": "Small file", "max_points": 25, "guidance": "Efficient."}, {"criterion": "Interesting", "max_points": 30, "guidance": "Worth looping."}]$t17f$::jsonb, 20, 'link', false, true),
  (18, $t18a$Module project: an animated explainer$t18a$, $t18b$Deliver a 30-second explainer.$t18b$, $t18c$Show Module 3. Produce a **30-second explainer** with script, storyboard, AI assets, animation and sound.

A person reviews your work and can ask for revisions.$t18c$, $t18d$Module project: an animated explainer$t18d$, $t18e$Submit the script, storyboard links, animation link and asset licence notes.

**Sharing:** upload the animation (MP4/GIF) somewhere viewable and paste the link. Animation is checked by a person.$t18e$, $t18f$[{"criterion": "Explains clearly", "max_points": 30, "guidance": "Understandable."}, {"criterion": "Craft and timing", "max_points": 25, "guidance": "Polished."}, {"criterion": "Assets and rights", "max_points": 20, "guidance": "Documented."}, {"criterion": "Sound", "max_points": 25, "guidance": "Supports."}]$t18f$::jsonb, 100, 'link', false, true),
  (19, $t19a$Export settings and formats$t19a$, $t19b$Export for each platform.$t19b$, $t19c$MP4 for video, GIF for short loops (large), WebM/Lottie for web, PNG sequence for editors. Match resolution, frame rate and codec to use.$t19c$, $t19d$Export settings and formats$t19d$, $t19e$Export one animation three ways and compare quality and file size. Submit the numbers and your choice.$t19e$, $t19f$[{"criterion": "Three exports", "max_points": 35, "guidance": "Distinct."}, {"criterion": "Numbers real", "max_points": 35, "guidance": "Sizes."}, {"criterion": "Choice reasoned", "max_points": 30, "guidance": "Use case."}]$t19f$::jsonb, 20, 'text', false, false),
  (20, $t20a$Accessibility and motion safety$t20a$, $t20b$Avoid harmful motion.$t20b$, $t20c$Avoid flashing more than three times per second (seizure risk), offer reduced-motion alternatives on the web, and never rely on motion alone to carry meaning.$t20c$, $t20d$Accessibility and motion safety$t20d$, $t20e$Audit an animation for accessibility and note three changes you would make.$t20e$, $t20f$[{"criterion": "Real issues found", "max_points": 45, "guidance": "Specific."}, {"criterion": "Changes practical", "max_points": 35, "guidance": "Actionable."}, {"criterion": "Flashing considered", "max_points": 20, "guidance": "Mentioned."}]$t20f$::jsonb, 20, 'text', false, false),
  (21, $t21a$Working efficiently$t21a$, $t21b$Build templates and reuse.$t21b$, $t21c$Templates, presets and naming save hours. Keep a library of easing, text animations and colour palettes.$t21c$, $t21d$Working efficiently$t21d$, $t21e$Create a reusable template and use it twice. Submit both links and what was reusable.

**Sharing:** upload the animation (MP4/GIF) somewhere viewable and paste the link. Animation is checked by a person.$t21e$, $t21f$[{"criterion": "Template reused", "max_points": 45, "guidance": "Two uses."}, {"criterion": "Time saved described", "max_points": 30, "guidance": "Estimate."}, {"criterion": "Consistent", "max_points": 25, "guidance": "Same system."}]$t21f$::jsonb, 20, 'link', false, true),
  (22, $t22a$Feedback and revisions$t22a$, $t22b$Take and give motion feedback.$t22b$, $t22c$Feedback should be specific: time codes and what to change. Keep versions. Decide which notes serve the goal.$t22c$, $t22d$Feedback and revisions$t22d$, $t22e$Get feedback with time codes from two people and show version one and two with the changes.

**Sharing:** upload the animation (MP4/GIF) somewhere viewable and paste the link. Animation is checked by a person.$t22e$, $t22f$[{"criterion": "Specific feedback", "max_points": 40, "guidance": "Time codes."}, {"criterion": "Changes made", "max_points": 35, "guidance": "Visible."}, {"criterion": "Decisions explained", "max_points": 25, "guidance": "Reasons."}]$t22f$::jsonb, 20, 'link', false, true),
  (23, $t23a$Pricing and delivering motion work$t23a$, $t23b$Scope a small paid job.$t23b$, $t23c$Scope by length, revisions and formats. Charge for revisions beyond the agreed rounds. Get approval on the storyboard before animating.$t23c$, $t23d$Pricing and delivering motion work$t23d$, $t23e$Write a scope for a 15-second animation: deliverables, revisions, timeline, price basis.$t23e$, $t23f$[{"criterion": "Scope clear", "max_points": 45, "guidance": "Complete."}, {"criterion": "Revisions defined", "max_points": 30, "guidance": "Rounds."}, {"criterion": "Price reasoned", "max_points": 25, "guidance": "Basis."}]$t23f$::jsonb, 20, 'text', false, false),
  (24, $t24a$Module project: a social motion set$t24a$, $t24b$Deliver a coordinated set of three animations.$t24b$, $t24c$Show Module 4. Produce a **set of three social animations** (different ratios) from one style guide, exported correctly and accessibility-checked.

A person reviews your work and can ask for revisions.$t24c$, $t24d$Module project: a social motion set$t24d$, $t24e$Submit links to all three, the style guide and your accessibility notes.

**Sharing:** upload the animation (MP4/GIF) somewhere viewable and paste the link. Animation is checked by a person.$t24e$, $t24f$[{"criterion": "Consistency", "max_points": 30, "guidance": "One system."}, {"criterion": "Technical readiness", "max_points": 25, "guidance": "Right formats."}, {"criterion": "Accessibility", "max_points": 20, "guidance": "Checked."}, {"criterion": "Craft", "max_points": 25, "guidance": "Polished."}]$t24f$::jsonb, 100, 'link', false, true),
  (25, $t25a$Capstone 1: brief$t25a$, $t25b$Plan an animated brand launch package.$t25b$, $t25c$Choose a real or made-up brand. Write the brief: audience, goal, deliverables (logo sting, explainer, social loop), tone.$t25c$, $t25d$Capstone 1: brief$t25d$, $t25e$Submit the brief and deliverables list.$t25e$, $t25f$[{"criterion": "Brief clear", "max_points": 50, "guidance": "Complete."}, {"criterion": "Deliverables realistic", "max_points": 30, "guidance": "Doable."}, {"criterion": "Goal measurable", "max_points": 20, "guidance": "A metric."}]$t25f$::jsonb, 20, 'text', false, false),
  (26, $t26a$Capstone 2: style guide and storyboards$t26a$, $t26b$Define the motion language.$t26b$, $t26c$Create the motion style guide and storyboards for all deliverables.$t26c$, $t26d$Capstone 2: style guide and storyboards$t26d$, $t26e$Submit the style guide and storyboard image links.

Paste *direct* image links.$t26e$, $t26f$[{"criterion": "Style guide usable", "max_points": 40, "guidance": "Clear."}, {"criterion": "Storyboards complete", "max_points": 35, "guidance": "All pieces."}, {"criterion": "On brand", "max_points": 25, "guidance": "Matches."}]$t26f$::jsonb, 20, 'link', false, false),
  (27, $t27a$Capstone 3: build the logo sting and loop$t27a$, $t27b$Animate the smaller pieces.$t27b$, $t27c$Animate the logo sting and social loop.$t27c$, $t27d$Capstone 3: build the logo sting and loop$t27d$, $t27e$Submit both links.

**Sharing:** upload the animation (MP4/GIF) somewhere viewable and paste the link. Animation is checked by a person.$t27e$, $t27f$[{"criterion": "Craft", "max_points": 40, "guidance": "Clean."}, {"criterion": "On style guide", "max_points": 35, "guidance": "Consistent."}, {"criterion": "Technical", "max_points": 25, "guidance": "Small files."}]$t27f$::jsonb, 70, 'link', false, true),
  (28, $t28a$Capstone 4: build the explainer$t28a$, $t28b$Animate the main piece.$t28b$, $t28c$Animate the 30-second explainer with sound.$t28c$, $t28d$Capstone 4: build the explainer$t28d$, $t28e$Submit the link, script and licences.

**Sharing:** upload the animation (MP4/GIF) somewhere viewable and paste the link. Animation is checked by a person.$t28e$, $t28f$[{"criterion": "Explains well", "max_points": 40, "guidance": "Clear."}, {"criterion": "Craft and sound", "max_points": 35, "guidance": "Polished."}, {"criterion": "Rights", "max_points": 25, "guidance": "Documented."}]$t28f$::jsonb, 90, 'link', false, true),
  (29, $t29a$Capstone 5: feedback and polish$t29a$, $t29b$Improve with critique and export.$t29b$, $t29c$Collect feedback, revise, and export all pieces in correct formats.$t29c$, $t29d$Capstone 5: feedback and polish$t29d$, $t29e$Submit feedback and the changes, plus export settings.$t29e$, $t29f$[{"criterion": "Feedback used", "max_points": 45, "guidance": "Real changes."}, {"criterion": "Exports correct", "max_points": 30, "guidance": "Right formats."}, {"criterion": "Accessibility check", "max_points": 25, "guidance": "Done."}]$t29f$::jsonb, 20, 'text', false, false),
  (30, $t30a$Capstone 6: deliver the package$t30a$, $t30b$Deliver and present the launch package.$t30b$, $t30c$Deliver all pieces with a short usage guide and present your decisions. Share in the Discord and ask for one piece of feedback.

A person reviews your work and can ask for revisions.$t30c$, $t30d$Capstone 6: deliver the package$t30d$, $t30e$Submit links to all pieces, the style guide, the usage guide and a cover note explaining your key decisions.

**Sharing:** upload the animation (MP4/GIF) somewhere viewable and paste the link. Animation is checked by a person.$t30e$, $t30f$[{"criterion": "Fits brief", "max_points": 25, "guidance": "Meets goals."}, {"criterion": "Craft", "max_points": 30, "guidance": "Polished."}, {"criterion": "Consistency", "max_points": 25, "guidance": "One system."}, {"criterion": "Delivery and rights", "max_points": 20, "guidance": "Ready to use."}]$t30f$::jsonb, 100, 'link', false, true)
) as v(n, title, objective, lesson_md, skill_focus, assignment_md, rubric, est_minutes, submission_type, ai_evaluate, requires_review)
where t.slug = 'motion'
on conflict (track_id, day_number) do nothing;
