-- Motion graphics, Pro tier (days 31-60). Authored content, UNPUBLISHED until a person reviews it in Admin.
insert into public.day
  (track_id, tier_id, day_number, title, objective, lesson_md, skill_focus, assignment_md, rubric,
   est_minutes, is_published, credit_budget, submission_type, ai_evaluate, requires_review)
select t.id, ti.id, v.n, v.title, v.objective, v.lesson_md, v.skill_focus, v.assignment_md, v.rubric,
       v.est_minutes, false, null, v.submission_type, v.ai_evaluate, v.requires_review
from public.track t
join public.tier ti on ti.track_id = t.id and ti.slug = 'pro'
cross join (values
  (31, $t31a$Motion systems: grids, rhythm, hierarchy$t31a$, $t31b$Design motion that follows a system.$t31b$, $t31c$Set a base timing unit (for example 100 ms), a small set of easings and a motion hierarchy: primary elements move most, secondary less. Systems make sets feel authored.$t31c$, $t31d$Motion systems: grids, rhythm, hierarchy$t31d$, $t31e$Define a motion system (durations, easings, hierarchy rules) and show one example.

**Sharing:** upload the animation and paste the link. Animation is checked by a person.$t31e$, $t31f$[{"criterion": "System usable", "max_points": 45, "guidance": "Clear rules."}, {"criterion": "Example follows", "max_points": 35, "guidance": "Consistent."}, {"criterion": "Hierarchy clear", "max_points": 20, "guidance": "Applied."}]$t31f$::jsonb, 35, 'link', false, false),
  (32, $t32a$Advanced easing and physics$t32a$, $t32b$Make movement feel physical.$t32b$, $t32c$Springs, overshoot and settle give weight. Mass and stiffness change feel: heavy things accelerate slowly. Keep overshoot small for professional feel.$t32c$, $t32d$Advanced easing and physics$t32d$, $t32e$Animate the same object as light, heavy and springy. Submit link and parameter notes.

**Sharing:** upload the animation and paste the link. Animation is checked by a person.$t32e$, $t32f$[{"criterion": "Three feels distinct", "max_points": 45, "guidance": "Clear."}, {"criterion": "Notes accurate", "max_points": 30, "guidance": "Parameters."}, {"criterion": "Restraint", "max_points": 25, "guidance": "Controlled."}]$t32f$::jsonb, 20, 'link', false, false),
  (33, $t33a$Masks, mattes and reveals$t33a$, $t33b$Use masks to reveal and transition.$t33b$, $t33c$Masks control what is visible. Animate mask shapes for reveals, use track mattes for text inside shapes and keep edges crisp.$t33c$, $t33d$Masks, mattes and reveals$t33d$, $t33e$Create three reveals using masks. Submit link and describe each.

**Sharing:** upload the animation and paste the link. Animation is checked by a person.$t33e$, $t33f$[{"criterion": "Clean reveals", "max_points": 45, "guidance": "Crisp."}, {"criterion": "Variety", "max_points": 25, "guidance": "Distinct."}, {"criterion": "Purposeful", "max_points": 30, "guidance": "Support the message."}]$t33f$::jsonb, 20, 'link', false, false),
  (34, $t34a$Typography in motion at a professional level$t34a$, $t34b$Animate text with legibility and character.$t34b$, $t34c$Stagger by word or line, keep reading time, match motion to tone and maintain hierarchy. Avoid animating body text.$t34c$, $t34d$Typography in motion at a professional level$t34d$, $t34e$Animate a headline and subhead with hierarchy. Submit link and read-time check.

**Sharing:** upload the animation and paste the link. Animation is checked by a person.$t34e$, $t34f$[{"criterion": "Legible", "max_points": 40, "guidance": "Read time."}, {"criterion": "Hierarchy", "max_points": 35, "guidance": "Clear."}, {"criterion": "Tone matched", "max_points": 25, "guidance": "Fits."}]$t34f$::jsonb, 20, 'link', false, false),
  (35, $t35a$Working with vector and Lottie$t35a$, $t35b$Ship lightweight web animation.$t35b$, $t35c$Lottie files are small vector animations for web and apps. Keep shapes simple, limit layers and test on device. Provide a static fallback and respect reduced-motion settings.$t35c$, $t35d$Working with vector and Lottie$t35d$, $t35e$Export an animation as Lottie or similar. Submit link, file size and fallback plan.

**Sharing:** upload the animation and paste the link. Animation is checked by a person.$t35e$, $t35f$[{"criterion": "Lightweight", "max_points": 35, "guidance": "Small."}, {"criterion": "Fallback and reduced-motion", "max_points": 40, "guidance": "Planned."}, {"criterion": "Works", "max_points": 25, "guidance": "Tested."}]$t35f$::jsonb, 20, 'link', false, false),
  (36, $t36a$Module project: a UI motion kit$t36a$, $t36b$Deliver a set of interface animations.$t36b$, $t36c$Show Module 1. Deliver a **UI motion kit** of five micro-interactions following your motion system with reduced-motion notes.

A person reviews your work and can ask for revisions.$t36c$, $t36d$Module project: a UI motion kit$t36d$, $t36e$Submit link, system definition and reduced-motion notes.

**Sharing:** upload the animation and paste the link. Animation is checked by a person.$t36e$, $t36f$[{"criterion": "System consistency", "max_points": 30, "guidance": "Followed."}, {"criterion": "Craft", "max_points": 30, "guidance": "Smooth."}, {"criterion": "Accessibility", "max_points": 20, "guidance": "Considered."}, {"criterion": "Usefulness", "max_points": 20, "guidance": "Practical."}]$t36f$::jsonb, 90, 'link', false, true),
  (37, $t37a$3D basics for motion designers$t37a$, $t37b$Add depth with simple 3D.$t37b$, $t37c$Use simple 3D shapes, lighting and camera moves. Keep scenes minimal. AI can generate assets or backgrounds; check licences.$t37c$, $t37d$3D basics for motion designers$t37d$, $t37e$Create a simple 3D-style animation with one light and a camera move. Submit link and notes.

**Sharing:** upload the animation and paste the link. Animation is checked by a person.$t37e$, $t37f$[{"criterion": "Depth convincing", "max_points": 40, "guidance": "Reads 3D."}, {"criterion": "Simple and clean", "max_points": 30, "guidance": "Controlled."}, {"criterion": "Licences", "max_points": 30, "guidance": "Checked."}]$t37f$::jsonb, 45, 'text', false, false),
  (38, $t38a$Compositing effects$t38a$, $t38b$Blend layers, glow and grain.$t38b$, $t38c$Use blend modes, blur, glow and grain to unify layers. Subtle beats heavy. Check on bright and dark displays.$t38c$, $t38d$Compositing effects$t38d$, $t38e$Composite three layers with effects. Submit link and settings.

**Sharing:** upload the animation and paste the link. Animation is checked by a person.$t38e$, $t38f$[{"criterion": "Unified", "max_points": 45, "guidance": "Cohesive."}, {"criterion": "Subtle", "max_points": 30, "guidance": "Restrained."}, {"criterion": "Settings noted", "max_points": 25, "guidance": "Listed."}]$t38f$::jsonb, 20, 'text', false, false),
  (39, $t39a$Data-driven motion$t39a$, $t39b$Animate real data clearly.$t39b$, $t39c$Animate charts and counters honestly; show change over time; label and source. Never exaggerate scale.$t39c$, $t39d$Data-driven motion$t39d$, $t39e$Animate a real data set (cited). Submit link and source.

**Sharing:** upload the animation and paste the link. Animation is checked by a person.$t39e$, $t39f$[{"criterion": "Honest scales", "max_points": 40, "guidance": "Accurate."}, {"criterion": "Clear story", "max_points": 35, "guidance": "Understandable."}, {"criterion": "Source", "max_points": 25, "guidance": "Cited."}]$t39f$::jsonb, 20, 'text', false, false),
  (40, $t40a$Character and mascot animation$t40a$, $t40b$Bring a simple character to life.$t40b$, $t40c$Keep characters simple: few shapes, clear poses, blinks and small idle moves. AI can help with designs; ensure you have rights and consistency.$t40c$, $t40d$Character and mascot animation$t40d$, $t40e$Animate a simple character with an idle and one action. Submit link and design rights notes.

**Sharing:** upload the animation and paste the link. Animation is checked by a person.$t40e$, $t40f$[{"criterion": "Life-like", "max_points": 40, "guidance": "Convincing."}, {"criterion": "Consistent design", "max_points": 30, "guidance": "Stable."}, {"criterion": "Rights", "max_points": 30, "guidance": "Documented."}]$t40f$::jsonb, 20, 'text', false, false),
  (41, $t41a$Audio-reactive and sync$t41a$, $t41b$Sync visuals with sound.$t41b$, $t41c$Mark beats, sync hits to sound and vary intensity. Test with the final audio and licence the track.$t41c$, $t41d$Audio-reactive and sync$t41d$, $t41e$Create a 15-second audio-synced piece. Submit link and licence.

**Sharing:** upload the animation and paste the link. Animation is checked by a person.$t41e$, $t41f$[{"criterion": "Tight sync", "max_points": 45, "guidance": "Precise."}, {"criterion": "Variation", "max_points": 30, "guidance": "Dynamic."}, {"criterion": "Licence", "max_points": 25, "guidance": "Documented."}]$t41f$::jsonb, 20, 'text', false, false),
  (42, $t42a$Module project: a 30-second brand animation$t42a$, $t42b$Deliver a polished brand animation.$t42b$, $t42c$Show Module 2. Deliver a **30-second brand animation** with depth, effects, sound and a motion system.

A person reviews your work and can ask for revisions.$t42c$, $t42d$Module project: a 30-second brand animation$t42d$, $t42e$Submit link, storyboard, system notes and licence list.

**Sharing:** upload the animation and paste the link. Animation is checked by a person.$t42e$, $t42f$[{"criterion": "Brand fit", "max_points": 25, "guidance": "Suits."}, {"criterion": "Craft and effects", "max_points": 35, "guidance": "Polished."}, {"criterion": "Sound", "max_points": 20, "guidance": "Synced."}, {"criterion": "Rights", "max_points": 20, "guidance": "Documented."}]$t42f$::jsonb, 120, 'link', false, true),
  (43, $t43a$Explainer video production$t43a$, $t43b$Produce a clear explainer end to end.$t43b$, $t43c$Script, voiceover, storyboard, animatic, animate, sound, review. Approve each stage before the next.$t43c$, $t43d$Explainer video production$t43d$, $t43e$Create an animatic (timed stills with voice) for a 45-second explainer. Submit link and script.

**Sharing:** upload the animation and paste the link. Animation is checked by a person.$t43e$, $t43f$[{"criterion": "Timing works", "max_points": 40, "guidance": "Paced."}, {"criterion": "Script clear", "max_points": 35, "guidance": "Simple."}, {"criterion": "Stage approvals", "max_points": 25, "guidance": "Planned."}]$t43f$::jsonb, 45, 'text', false, false),
  (44, $t44a$Social ad motion$t44a$, $t44b$Make thumb-stopping, compliant ads.$t44b$, $t44c$Hook in one second, big captions, sound-off friendly, clear CTA, correct ratios. Follow platform ad rules and avoid misleading claims.$t44c$, $t44d$Social ad motion$t44d$, $t44e$Create two 15-second ad variants with different hooks. Submit links and hook rationale.

**Sharing:** upload the animation and paste the link. Animation is checked by a person.$t44e$, $t44f$[{"criterion": "Hooks distinct", "max_points": 40, "guidance": "Different."}, {"criterion": "Sound-off works", "max_points": 30, "guidance": "Captions."}, {"criterion": "Rules and claims", "max_points": 30, "guidance": "Checked."}]$t44f$::jsonb, 20, 'text', false, false),
  (45, $t45a$Motion for presentations and product demos$t45a$, $t45b$Animate to explain a product.$t45b$, $t45c$Show, do not tell: highlight the feature, guide the eye, keep each scene under 5 seconds and end on the outcome.$t45c$, $t45d$Motion for presentations and product demos$t45d$, $t45e$Animate a 20-second product demo of a feature. Submit link and storyboard.

**Sharing:** upload the animation and paste the link. Animation is checked by a person.$t45e$, $t45f$[{"criterion": "Explains feature", "max_points": 45, "guidance": "Clear."}, {"criterion": "Eye guided", "max_points": 30, "guidance": "Focus."}, {"criterion": "Pace", "max_points": 25, "guidance": "Right."}]$t45f$::jsonb, 20, 'text', false, false),
  (46, $t46a$Templates and scalable production$t46a$, $t46b$Build reusable systems.$t46b$, $t46c$Create templates with placeholders, style controls and documentation so others can reuse them. Version and name carefully.$t46c$, $t46d$Templates and scalable production$t46d$, $t46e$Build a template and produce two variants. Submit links and usage notes.

**Sharing:** upload the animation and paste the link. Animation is checked by a person.$t46e$, $t46f$[{"criterion": "Template flexible", "max_points": 40, "guidance": "Reusable."}, {"criterion": "Two variants", "max_points": 30, "guidance": "Distinct."}, {"criterion": "Documentation", "max_points": 30, "guidance": "Clear."}]$t46f$::jsonb, 20, 'text', false, false),
  (47, $t47a$Pricing and scoping motion projects$t47a$, $t47b$Quote confidently.$t47b$, $t47c$Quote by finished second, complexity, revisions and formats; set milestone approvals; charge for rush and extra rounds.$t47c$, $t47d$Pricing and scoping motion projects$t47d$, $t47e$Write a quote and scope for a 30-second animation.$t47e$, $t47f$[{"criterion": "Scope clear", "max_points": 40, "guidance": "Precise."}, {"criterion": "Pricing logic", "max_points": 35, "guidance": "Reasoned."}, {"criterion": "Revisions", "max_points": 25, "guidance": "Limited."}]$t47f$::jsonb, 20, 'text', false, false),
  (48, $t48a$Module project: an explainer package$t48a$, $t48b$Deliver an explainer with variants.$t48b$, $t48c$Show Module 3. Deliver an **explainer package**: 45-second video, two ad cut-downs and a template.

A person reviews your work and can ask for revisions.$t48c$, $t48d$Module project: an explainer package$t48d$, $t48e$Submit links to all pieces, script, storyboard and licence list.

**Sharing:** upload the animation and paste the link. Animation is checked by a person.$t48e$, $t48f$[{"criterion": "Explains clearly", "max_points": 30, "guidance": "Clear."}, {"criterion": "Craft", "max_points": 25, "guidance": "Polished."}, {"criterion": "Variants and template", "max_points": 25, "guidance": "Useful."}, {"criterion": "Rights", "max_points": 20, "guidance": "Documented."}]$t48f$::jsonb, 150, 'link', false, true),
  (49, $t49a$Performance and optimisation$t49a$, $t49b$Keep animations fast.$t49b$, $t49c$Limit layers and effects, use vectors, test on low-end devices and provide compressed exports.$t49c$, $t49d$Performance and optimisation$t49d$, $t49e$Optimise one animation and report file size and playback before and after.$t49e$, $t49f$[{"criterion": "Measured improvement", "max_points": 50, "guidance": "Numbers."}, {"criterion": "Techniques named", "max_points": 30, "guidance": "Specific."}, {"criterion": "Quality kept", "max_points": 20, "guidance": "Maintained."}]$t49f$::jsonb, 35, 'text', false, false),
  (50, $t50a$Accessibility standards in motion$t50a$, $t50b$Follow accessibility guidance.$t50b$, $t50c$Avoid flashing, offer pause controls and reduced-motion variants, provide captions and audio description for meaningful animation.$t50c$, $t50d$Accessibility standards in motion$t50d$, $t50e$Write an accessibility checklist and apply it to one piece.$t50e$, $t50f$[{"criterion": "Checklist real", "max_points": 40, "guidance": "Specific."}, {"criterion": "Applied", "max_points": 35, "guidance": "Evidence."}, {"criterion": "Fixes", "max_points": 25, "guidance": "Made."}]$t50f$::jsonb, 20, 'text', false, false),
  (51, $t51a$Rights and licensing for motion assets$t51a$, $t51b$Clear every asset.$t51b$, $t51c$Fonts, music, stock, AI-generated assets and plugins all have terms. Keep a log with links and proofs.$t51c$, $t51d$Rights and licensing for motion assets$t51d$, $t51e$Create an asset licence log for one project.$t51e$, $t51f$[{"criterion": "Every asset listed", "max_points": 45, "guidance": "Complete."}, {"criterion": "Terms understood", "max_points": 35, "guidance": "Correct."}, {"criterion": "Proof kept", "max_points": 20, "guidance": "Links."}]$t51f$::jsonb, 20, 'text', false, false),
  (52, $t52a$Portfolio and reel$t52a$, $t52b$Present your best work.$t52b$, $t52c$Curate 3 to 5 strong pieces, lead with the best, show process, credit tools honestly and keep the reel under 60 seconds.$t52c$, $t52d$Portfolio and reel$t52d$, $t52e$Plan a reel: pieces, order and process notes.$t52e$, $t52f$[{"criterion": "Curated", "max_points": 40, "guidance": "Selective."}, {"criterion": "Process shown", "max_points": 30, "guidance": "Included."}, {"criterion": "Honest credits", "max_points": 30, "guidance": "Tools named."}]$t52f$::jsonb, 20, 'text', false, false),
  (53, $t53a$Critique and revision culture$t53a$, $t53b$Improve through structured feedback.$t53b$, $t53c$Ask for feedback on clarity, pace and polish, collect time-coded notes and respond with a version log.$t53c$, $t53d$Critique and revision culture$t53d$, $t53e$Run a critique with three people and submit the version log.

**Sharing:** upload the animation and paste the link. Animation is checked by a person.$t53e$, $t53f$[{"criterion": "Specific feedback", "max_points": 35, "guidance": "Time-coded."}, {"criterion": "Version log", "max_points": 35, "guidance": "Clear."}, {"criterion": "Improvement", "max_points": 30, "guidance": "Visible."}]$t53f$::jsonb, 20, 'link', false, false),
  (54, $t54a$Module project: a motion reel and asset log$t54a$, $t54b$Deliver a reel with a clean rights record.$t54b$, $t54c$Show Module 4. Deliver a **30 to 60 second reel** with process notes, accessibility check and licence log.

A person reviews your work and can ask for revisions.$t54c$, $t54d$Module project: a motion reel and asset log$t54d$, $t54e$Submit reel link, process notes, accessibility check and licence log.

**Sharing:** upload the animation and paste the link. Animation is checked by a person.$t54e$, $t54f$[{"criterion": "Work quality", "max_points": 35, "guidance": "Strong."}, {"criterion": "Accessibility", "max_points": 20, "guidance": "Checked."}, {"criterion": "Rights", "max_points": 25, "guidance": "Complete."}, {"criterion": "Presentation", "max_points": 20, "guidance": "Professional."}]$t54f$::jsonb, 120, 'link', false, true),
  (55, $t55a$Pro capstone 1: client brief$t55a$, $t55b$Scope a motion package.$t55b$, $t55c$Write a brief for a brand: goals, deliverables, formats, style and schedule.$t55c$, $t55d$Pro capstone 1: client brief$t55d$, $t55e$Submit the brief.$t55e$, $t55f$[{"criterion": "Brief clear", "max_points": 50, "guidance": "Complete."}, {"criterion": "Deliverables realistic", "max_points": 30, "guidance": "Doable."}, {"criterion": "Goals measurable", "max_points": 20, "guidance": "Metric."}]$t55f$::jsonb, 30, 'text', false, false),
  (56, $t56a$Pro capstone 2: motion system and boards$t56a$, $t56b$Design the system.$t56b$, $t56c$Create a motion system and storyboards for all deliverables.$t56c$, $t56d$Pro capstone 2: motion system and boards$t56d$, $t56e$Submit system and storyboard image links.

**Sharing:** upload the animation and paste the link. Animation is checked by a person.$t56e$, $t56f$[{"criterion": "System usable", "max_points": 40, "guidance": "Clear."}, {"criterion": "Boards complete", "max_points": 35, "guidance": "All pieces."}, {"criterion": "On brief", "max_points": 25, "guidance": "Aligned."}]$t56f$::jsonb, 20, 'link', false, false),
  (57, $t57a$Pro capstone 3: build core pieces$t57a$, $t57b$Animate the main pieces.$t57b$, $t57c$Animate the hero piece and one variant.$t57c$, $t57d$Pro capstone 3: build core pieces$t57d$, $t57e$Submit links.

**Sharing:** upload the animation and paste the link. Animation is checked by a person.$t57e$, $t57f$[{"criterion": "Craft", "max_points": 45, "guidance": "Polished."}, {"criterion": "On system", "max_points": 30, "guidance": "Consistent."}, {"criterion": "Technical", "max_points": 25, "guidance": "Right formats."}]$t57f$::jsonb, 120, 'text', false, false),
  (58, $t58a$Pro capstone 4: variants, sound and accessibility$t58a$, $t58b$Complete the set.$t58b$, $t58c$Produce remaining formats with sound, captions and reduced-motion versions.$t58c$, $t58d$Pro capstone 4: variants, sound and accessibility$t58d$, $t58e$Submit links and accessibility notes.

**Sharing:** upload the animation and paste the link. Animation is checked by a person.$t58e$, $t58f$[{"criterion": "Set complete", "max_points": 35, "guidance": "All pieces."}, {"criterion": "Accessibility", "max_points": 35, "guidance": "Done."}, {"criterion": "Sound", "max_points": 30, "guidance": "Clear."}]$t58f$::jsonb, 100, 'text', false, false),
  (59, $t59a$Pro capstone 5: critique and rights$t59a$, $t59b$Improve and clear.$t59b$, $t59c$Collect critique, revise and finish the licence log.$t59c$, $t59d$Pro capstone 5: critique and rights$t59d$, $t59e$Submit critique, version log and licence log.$t59e$, $t59f$[{"criterion": "Critique used", "max_points": 40, "guidance": "Changes."}, {"criterion": "Licence log", "max_points": 40, "guidance": "Complete."}, {"criterion": "Reflection", "max_points": 20, "guidance": "Honest."}]$t59f$::jsonb, 20, 'text', false, false),
  (60, $t60a$Pro capstone 6: deliver the package$t60a$, $t60b$Deliver and present.$t60b$, $t60c$Deliver all files, usage guide, licence log and a client summary. Share in the Discord and ask for one piece of feedback.

A person reviews your work and can ask for revisions.$t60c$, $t60d$Pro capstone 6: deliver the package$t60d$, $t60e$Submit links, usage guide, licence log and summary.

**Sharing:** upload the animation and paste the link. Animation is checked by a person.$t60e$, $t60f$[{"criterion": "Fits brief", "max_points": 25, "guidance": "Meets goals."}, {"criterion": "Craft", "max_points": 30, "guidance": "Polished."}, {"criterion": "Accessibility and rights", "max_points": 25, "guidance": "Handled."}, {"criterion": "Delivery", "max_points": 20, "guidance": "Organised."}]$t60f$::jsonb, 120, 'link', false, true)
) as v(n, title, objective, lesson_md, skill_focus, assignment_md, rubric, est_minutes, submission_type, ai_evaluate, requires_review)
where t.slug = 'motion'
on conflict (track_id, day_number) do nothing;
