-- Audio, music & voice, Expert tier (days 61-80). Authored content, UNPUBLISHED until a person reviews it in Admin.
insert into public.day
  (track_id, tier_id, day_number, title, objective, lesson_md, skill_focus, assignment_md, rubric,
   est_minutes, is_published, credit_budget, submission_type, ai_evaluate, requires_review)
select t.id, ti.id, v.n, v.title, v.objective, v.lesson_md, v.skill_focus, v.assignment_md, v.rubric,
       v.est_minutes, false, null, v.submission_type, v.ai_evaluate, v.requires_review
from public.track t
join public.tier ti on ti.track_id = t.id and ti.slug = 'expert'
cross join (values
  (61, $t61a$Sonic identity strategy$t61a$, $t61b$Define how a brand should sound.$t61b$, $t61c$A sonic identity covers voice, music style, sound logo, UI sounds and rules for use. Start from brand values and audience, then test options with listeners.$t61c$, $t61d$Sonic identity strategy$t61d$, $t61e$Write a sonic identity strategy with values, sound principles and three test options.$t61e$, $t61f$[{"criterion": "Principles clear", "max_points": 40, "guidance": "Specific."}, {"criterion": "Tied to brand", "max_points": 30, "guidance": "Reasoned."}, {"criterion": "Tested", "max_points": 30, "guidance": "Listeners."}]$t61f$::jsonb, 60, 'text', false, false),
  (62, $t62a$Advanced sound design and synthesis$t62a$, $t62b$Create original sounds.$t62b$, $t62c$Layer synthesis, sampling and processing. Document patches so sounds are reproducible and cleared.$t62c$, $t62d$Advanced sound design and synthesis$t62d$, $t62e$Create a set of six branded sounds with documentation.

**Sharing audio:** upload (unlisted) and paste the link. Audio is checked by a person.$t62e$, $t62f$[{"criterion": "Distinct set", "max_points": 40, "guidance": "Cohesive."}, {"criterion": "Documented", "max_points": 30, "guidance": "Reproducible."}, {"criterion": "Clean", "max_points": 30, "guidance": "Quality."}]$t62f$::jsonb, 90, 'link', false, false),
  (63, $t63a$Immersive and spatial audio$t63a$, $t63b$Design for space.$t63b$, $t63c$Binaural and multichannel mixes place sound in space. Check compatibility and fall back to stereo gracefully.$t63c$, $t63d$Immersive and spatial audio$t63d$, $t63e$Create a 30-second spatial scene with stereo fallback.

**Sharing audio:** upload (unlisted) and paste the link. Audio is checked by a person.$t63e$, $t63f$[{"criterion": "Space convincing", "max_points": 40, "guidance": "Placed."}, {"criterion": "Fallback", "max_points": 30, "guidance": "Works."}, {"criterion": "Notes", "max_points": 30, "guidance": "Documented."}]$t63f$::jsonb, 90, 'link', false, false),
  (64, $t64a$Mixing and mastering to spec$t64a$, $t64b$Meet professional standards.$t64b$, $t64c$Reference tracks, loudness targets, true peak, dynamic range and translation checks on many speakers.$t64c$, $t64d$Mixing and mastering to spec$t64d$, $t64e$Mix and master a track and provide a translation check report.

**Sharing audio:** upload (unlisted) and paste the link. Audio is checked by a person.$t64e$, $t64f$[{"criterion": "Clear mix", "max_points": 40, "guidance": "Balanced."}, {"criterion": "Specs met", "max_points": 30, "guidance": "Values."}, {"criterion": "Translation checked", "max_points": 30, "guidance": "Report."}]$t64f$::jsonb, 90, 'link', false, false),
  (65, $t65a$Expert project 1: a sonic identity system$t65a$, $t65b$Deliver strategy plus assets.$t65b$, $t65c$Show Module 1. Deliver a **sonic identity system**: strategy, sound logo, six UI sounds and a mastered anthem.

A person reviews your work and can ask for revisions.$t65c$, $t65d$Expert project 1: a sonic identity system$t65d$, $t65e$Submit all assets and documents.

**Sharing audio:** upload (unlisted) and paste the link. Audio is checked by a person.$t65e$, $t65f$[{"criterion": "Strategy and coherence", "max_points": 30, "guidance": "One identity."}, {"criterion": "Sound quality", "max_points": 30, "guidance": "Professional."}, {"criterion": "Documentation", "max_points": 20, "guidance": "Complete."}, {"criterion": "Rights", "max_points": 20, "guidance": "Clean."}]$t65f$::jsonb, 240, 'link', false, true),
  (66, $t66a$Composition and arrangement with AI$t66a$, $t66b$Use AI as a collaborator.$t66b$, $t66c$Sketch ideas with AI, then arrange, edit and perform or replace parts yourself. Know the terms on commercial use and originality checks.$t66c$, $t66d$Composition and arrangement with AI$t66d$, $t66e$Create a two-minute piece using AI sketches and your own edits; document what is yours.

**Sharing audio:** upload (unlisted) and paste the link. Audio is checked by a person.$t66e$, $t66f$[{"criterion": "Musical shape", "max_points": 35, "guidance": "Structured."}, {"criterion": "Human contribution", "max_points": 35, "guidance": "Clear."}, {"criterion": "Terms checked", "max_points": 30, "guidance": "Documented."}]$t66f$::jsonb, 120, 'link', false, false),
  (67, $t67a$Dialogue, ADR and voice direction at scale$t67a$, $t67b$Produce many voice lines.$t67b$, $t67c$Batch scripts, direction notes, consistent settings, naming and QC. Only use consented or licensed voices.$t67c$, $t67d$Dialogue, ADR and voice direction at scale$t67d$, $t67e$Produce 20 lines in a consistent voice with a QC log.

**Sharing audio:** upload (unlisted) and paste the link. Audio is checked by a person.$t67e$, $t67f$[{"criterion": "Consistent", "max_points": 40, "guidance": "Even."}, {"criterion": "QC log", "max_points": 30, "guidance": "Real."}, {"criterion": "Consent", "max_points": 30, "guidance": "Documented."}]$t67f$::jsonb, 90, 'link', false, false),
  (68, $t68a$Interactive and game audio$t68a$, $t68b$Design adaptive audio.$t68b$, $t68c$Layers, stingers, randomisation and states. Avoid repetition fatigue and test in context.$t68c$, $t68d$Interactive and game audio$t68d$, $t68e$Design an adaptive audio set for three game states.

**Sharing audio:** upload (unlisted) and paste the link. Audio is checked by a person.$t68e$, $t68f$[{"criterion": "States distinct", "max_points": 35, "guidance": "Clear."}, {"criterion": "Repetition handled", "max_points": 35, "guidance": "Varied."}, {"criterion": "Tested in context", "max_points": 30, "guidance": "Real."}]$t68f$::jsonb, 90, 'link', false, false),
  (69, $t69a$Podcast and radio production standards$t69a$, $t69b$Meet broadcast norms.$t69b$, $t69c$Loudness, clean edits, credits, music licensing and accessibility with transcripts.$t69c$, $t69d$Podcast and radio production standards$t69d$, $t69e$Deliver a 10-minute episode to specs with transcript.

**Sharing audio:** upload (unlisted) and paste the link. Audio is checked by a person.$t69e$, $t69f$[{"criterion": "Specs", "max_points": 35, "guidance": "Met."}, {"criterion": "Clean edit", "max_points": 35, "guidance": "Natural."}, {"criterion": "Transcript", "max_points": 30, "guidance": "Accurate."}]$t69f$::jsonb, 150, 'link', false, false),
  (70, $t70a$Expert project 2: a produced series pilot$t70a$, $t70b$Deliver a broadcast-ready pilot.$t70b$, $t70c$Show Module 2. Deliver a **series pilot** with composed music, voice lines, adaptive or spatial element and full documentation.

A person reviews your work and can ask for revisions.$t70c$, $t70d$Expert project 2: a produced series pilot$t70d$, $t70e$Submit audio, cue sheet, QC log and transcript.

**Sharing audio:** upload (unlisted) and paste the link. Audio is checked by a person.$t70e$, $t70f$[{"criterion": "Content and craft", "max_points": 35, "guidance": "Polished."}, {"criterion": "Technical", "max_points": 25, "guidance": "Correct."}, {"criterion": "Rights and consent", "max_points": 25, "guidance": "Clean."}, {"criterion": "Documentation", "max_points": 15, "guidance": "Complete."}]$t70f$::jsonb, 240, 'link', false, true),
  (71, $t71a$Copyright, publishing and royalties$t71a$, $t71b$Understand music rights.$t71b$, $t71c$Composition and recording rights, performing rights bodies, licences and split sheets. Get legal advice. This course is not legal advice.$t71c$, $t71d$Copyright, publishing and royalties$t71d$, $t71e$Create a split sheet and rights summary for a piece.$t71e$, $t71f$[{"criterion": "Rights understood", "max_points": 45, "guidance": "Correct."}, {"criterion": "Split sheet", "max_points": 30, "guidance": "Complete."}, {"criterion": "Advice noted", "max_points": 25, "guidance": "Limits."}]$t71f$::jsonb, 60, 'text', false, false),
  (72, $t72a$Voice likeness law, ethics and policy$t72a$, $t72b$Handle voice safely.$t72b$, $t72c$Right of publicity, consent, revocation, labelling and platform policies. Do not deceive.$t72c$, $t72d$Voice likeness law, ethics and policy$t72d$, $t72e$Write a voice-use policy with consent form and labelling rules.$t72e$, $t72f$[{"criterion": "Policy specific", "max_points": 40, "guidance": "Concrete."}, {"criterion": "Consent form", "max_points": 35, "guidance": "Usable."}, {"criterion": "Labelling", "max_points": 25, "guidance": "Clear."}]$t72f$::jsonb, 60, 'text', false, false),
  (73, $t73a$Business: pricing, contracts, and clients$t73a$, $t73b$Run audio work professionally.$t73b$, $t73c$Quote by minute or asset, define revisions, ownership and AI-tool use, invoice and manage clients.$t73c$, $t73d$Business: pricing, contracts, and clients$t73d$, $t73e$Write a quote, contract outline and revision policy.$t73e$, $t73f$[{"criterion": "Quote logic", "max_points": 35, "guidance": "Sound."}, {"criterion": "Contract", "max_points": 35, "guidance": "Fair."}, {"criterion": "Revisions", "max_points": 30, "guidance": "Limited."}]$t73f$::jsonb, 60, 'text', false, false),
  (74, $t74a$Audience, distribution and analytics$t74a$, $t74b$Grow listenership.$t74b$, $t74c$Publish schedules, retention analytics, promotion and community. Improve using data.$t74c$, $t74d$Audience, distribution and analytics$t74d$, $t74e$Create a 90-day growth plan with metrics.$t74e$, $t74f$[{"criterion": "Plan realistic", "max_points": 35, "guidance": "Feasible."}, {"criterion": "Metrics", "max_points": 35, "guidance": "Defined."}, {"criterion": "Honest titles", "max_points": 30, "guidance": "Not clickbait."}]$t74f$::jsonb, 60, 'text', false, false),
  (75, $t75a$Expert project 3: a professional practice pack$t75a$, $t75b$Deliver rights, policy and business documents.$t75b$, $t75c$Show Module 3. Deliver a **practice pack**: split sheet, voice policy, contract and growth plan.

A person reviews your work and can ask for revisions.$t75c$, $t75d$Expert project 3: a professional practice pack$t75d$, $t75e$Submit all documents.$t75e$, $t75f$[{"criterion": "Rights and policy", "max_points": 35, "guidance": "Sound."}, {"criterion": "Business documents", "max_points": 30, "guidance": "Professional."}, {"criterion": "Growth plan", "max_points": 20, "guidance": "Realistic."}, {"criterion": "Honesty", "max_points": 15, "guidance": "Clear."}]$t75f$::jsonb, 120, 'text', false, true),
  (76, $t76a$Flagship: concept and plan$t76a$, $t76b$Plan a flagship audio work.$t76b$, $t76c$Choose a series, album or brand sound project. Write brief, plan and rights map.$t76c$, $t76d$Flagship: concept and plan$t76d$, $t76e$Submit the documents.$t76e$, $t76f$[{"criterion": "Concept strong", "max_points": 35, "guidance": "Clear."}, {"criterion": "Plan", "max_points": 35, "guidance": "Feasible."}, {"criterion": "Rights map", "max_points": 30, "guidance": "Complete."}]$t76f$::jsonb, 75, 'text', false, false),
  (77, $t77a$Flagship: production$t77a$, $t77b$Create the core audio.$t77b$, $t77c$Record, compose and design the core pieces.$t77c$, $t77d$Flagship: production$t77d$, $t77e$Submit core assets.

**Sharing audio:** upload (unlisted) and paste the link. Audio is checked by a person.$t77e$, $t77f$[{"criterion": "Quality", "max_points": 45, "guidance": "High."}, {"criterion": "On concept", "max_points": 30, "guidance": "Faithful."}, {"criterion": "Rights", "max_points": 25, "guidance": "Clean."}]$t77f$::jsonb, 240, 'link', false, false),
  (78, $t78a$Flagship: mix, master and QC$t78a$, $t78b$Finish to spec.$t78b$, $t78c$Mix, master and QC across devices.$t78c$, $t78d$Flagship: mix, master and QC$t78d$, $t78e$Submit final mixes and QC report.

**Sharing audio:** upload (unlisted) and paste the link. Audio is checked by a person.$t78e$, $t78f$[{"criterion": "Mix quality", "max_points": 40, "guidance": "Clear."}, {"criterion": "Specs", "max_points": 30, "guidance": "Met."}, {"criterion": "QC", "max_points": 30, "guidance": "Documented."}]$t78f$::jsonb, 180, 'link', false, false),
  (79, $t79a$Flagship: release and listen$t79a$, $t79b$Release and gather response.$t79b$, $t79c$Release, collect listener feedback and metrics for two weeks.$t79c$, $t79d$Flagship: release and listen$t79d$, $t79e$Submit release links, feedback and metrics.

**Sharing audio:** upload (unlisted) and paste the link. Audio is checked by a person.$t79e$, $t79f$[{"criterion": "Released", "max_points": 30, "guidance": "Real."}, {"criterion": "Feedback", "max_points": 40, "guidance": "Collected."}, {"criterion": "Learning", "max_points": 30, "guidance": "Applied."}]$t79f$::jsonb, 90, 'link', false, false),
  (80, $t80a$Expert project 4: the flagship audio work$t80a$, $t80b$Deliver a complete, cleared work.$t80b$, $t80c$Show Module 4. Deliver the **flagship audio work** with documentation, rights, accessibility files and audience results.

A person reviews your work and can ask for revisions.$t80c$, $t80d$Expert project 4: the flagship audio work$t80d$, $t80e$Submit the work and package.

**Sharing audio:** upload (unlisted) and paste the link. Audio is checked by a person.$t80e$, $t80f$[{"criterion": "Craft", "max_points": 35, "guidance": "Excellent."}, {"criterion": "Rights and ethics", "max_points": 25, "guidance": "Clean."}, {"criterion": "Accessibility", "max_points": 20, "guidance": "Provided."}, {"criterion": "Results", "max_points": 20, "guidance": "Honest."}]$t80f$::jsonb, 300, 'link', false, true)
) as v(n, title, objective, lesson_md, skill_focus, assignment_md, rubric, est_minutes, submission_type, ai_evaluate, requires_review)
where t.slug = 'audio'
on conflict (track_id, day_number) do nothing;
