-- Apps & tools, Basic tier (days 1-30). Authored content, UNPUBLISHED until a person reviews it in Admin.
insert into public.day
  (track_id, tier_id, day_number, title, objective, lesson_md, skill_focus, assignment_md, rubric,
   est_minutes, is_published, credit_budget, submission_type, ai_evaluate, requires_review)
select t.id, ti.id, v.n, v.title, v.objective, v.lesson_md, v.skill_focus, v.assignment_md, v.rubric,
       v.est_minutes, false, null, v.submission_type, v.ai_evaluate, v.requires_review
from public.track t
join public.tier ti on ti.track_id = t.id and ti.slug = 'basic'
cross join (values
  (1, $t1a$What an app is (and what you can build without code)$t1a$, $t1b$Explain an app as inputs, logic and outputs, and pick a small tool worth building.$t1b$, $t1c$Every app does three things: takes **input** (a form, a click), applies **logic** (rules, calculations, AI), and shows **output** (a page, a message, a file). Most useful small tools are simple: a booking form, a price calculator, a checklist, a client tracker.

Start with a problem you or someone you know has every week. Tools like [CREAO](https://agent.creao.ai/@Sonofpeace) (referral link) let you describe a tool in plain language and get a working version. Others include Lovable, Bolt, Replit and Glide. The thinking is the same in all of them.$t1c$, $t1d$What an app is (and what you can build without code)$t1d$, $t1e$Pick one small problem. Submit: who has it, how often, the input, the logic and the output of the tool that would solve it, in 5 to 8 sentences.$t1e$, $t1f$[{"criterion": "Real problem", "max_points": 35, "guidance": "A specific person and situation."}, {"criterion": "Input, logic, output named", "max_points": 40, "guidance": "All three are described concretely."}, {"criterion": "Small enough to build", "max_points": 25, "guidance": "Could be a first version in an afternoon."}]$t1f$::jsonb, 15, 'text', false, false),
  (2, $t2a$Write a one-page product brief$t2a$, $t2b$Describe the tool so an AI builder cannot misunderstand it.$t2b$, $t2c$A brief has: **who** it is for, the **one job** it does, the **screens or steps**, the **data** it stores, and **what it must not do**. Keep to one job.

Write user stories: "As a [person] I want [action] so that [benefit]." Three is enough for a first version.$t2c$, $t2d$Write a one-page product brief$t2d$, $t2e$Submit a one-page brief: user, job, three user stories, screens, data fields, and two things it will not do in version one.$t2e$, $t2f$[{"criterion": "One clear job", "max_points": 30, "guidance": "Focused, not a wish list."}, {"criterion": "Stories and screens", "max_points": 40, "guidance": "Usable by a builder."}, {"criterion": "Boundaries stated", "max_points": 30, "guidance": "Explicit non-goals."}]$t2f$::jsonb, 20, 'text', false, false),
  (3, $t3a$Your first build$t3a$, $t3b$Turn the brief into a working first version with an AI builder.$t3b$, $t3c$Paste your brief and ask for the smallest version that works. Then use it: click everything, enter normal data and strange data. Write down what breaks. Build in **small steps**: one change per prompt, so you know what caused what.$t3c$, $t3d$Your first build$t3d$, $t3e$Build the first version. Submit screenshots of it working, your first prompt, and a list of three things that were wrong or missing.

**Evidence:** paste *direct* links to screenshots (ending .png/.jpg/.webp), one per line, and describe what they show. A link to the running app is welcome but the screenshots are what get scored.$t3e$, $t3f$[{"criterion": "It works for the main job", "max_points": 40, "guidance": "Screenshots show the core flow."}, {"criterion": "First prompt is clear", "max_points": 30, "guidance": "Says what to build."}, {"criterion": "Honest problem list", "max_points": 30, "guidance": "Specific defects."}]$t3f$::jsonb, 40, 'link', false, false),
  (4, $t4a$Prompting a builder: small, specific changes$t4a$, $t4b$Change an app with clear, one-step instructions.$t4b$, $t4c$Good instruction: "On the home page, move the Add button above the list and make it green." Bad: "make it better". Say **where**, **what** and **how it should look or behave**. If a change breaks something, undo and try a narrower request.$t4c$, $t4d$Prompting a builder: small, specific changes$t4d$, $t4e$Make five small changes, one at a time. Submit each prompt with a before-and-after screenshot pair (or one combined screenshot per change).

**Evidence:** paste *direct* links to screenshots (ending .png/.jpg/.webp), one per line, and describe what they show. A link to the running app is welcome but the screenshots are what get scored.$t4e$, $t4f$[{"criterion": "Prompts are specific", "max_points": 40, "guidance": "Where, what, how."}, {"criterion": "Each change worked or was handled", "max_points": 40, "guidance": "Evidence shown."}, {"criterion": "One change at a time", "max_points": 20, "guidance": "Small steps."}]$t4f$::jsonb, 35, 'link', false, false),
  (5, $t5a$Testing like a user$t5a$, $t5b$Find problems before anyone else does.$t5b$, $t5c$Test **happy path** (normal use), **edge cases** (empty, very long, wrong type) and **mistakes** (double-click, back button). Write a test list of ten checks with expected results, run them and record what happened.$t5c$, $t5d$Testing like a user$t5d$, $t5e$Submit your ten-check test list with expected and actual results, and what you fixed.$t5e$, $t5f$[{"criterion": "Range of checks", "max_points": 40, "guidance": "Happy, edge and mistake cases."}, {"criterion": "Results recorded honestly", "max_points": 35, "guidance": "Actual vs expected."}, {"criterion": "Fixes made", "max_points": 25, "guidance": "At least one improvement."}]$t5f$::jsonb, 20, 'text', false, false),
  (6, $t6a$Module project: a single-purpose tool that works$t6a$, $t6b$Ship a small tool that does one job for one real person.$t6b$, $t6c$Show Module 1. Build a **single-purpose tool** that solves the problem from day 1, test it with ten checks and give it to one real person to try.

Your work is scored on the rubric below. You can revise and resubmit.$t6c$, $t6d$Module project: a single-purpose tool that works$t6d$, $t6e$Submit: the brief, screenshots of the finished tool working, your test results, and a short note from the person who tried it (what they did and what confused them).

**Evidence:** paste *direct* links to screenshots (ending .png/.jpg/.webp), one per line, and describe what they show. A link to the running app is welcome but the screenshots are what get scored.$t6e$, $t6f$[{"criterion": "Solves the stated job", "max_points": 30, "guidance": "Screenshots show it working."}, {"criterion": "Tested properly", "max_points": 25, "guidance": "Test results are honest."}, {"criterion": "Real user feedback", "max_points": 25, "guidance": "Someone else actually tried it."}, {"criterion": "Brief and tool match", "max_points": 20, "guidance": "What was built fits the brief."}]$t6f$::jsonb, 60, 'link', true, false),
  (7, $t7a$Data: what your app remembers$t7a$, $t7b$Design the fields an app needs to store.$t7b$, $t7c$Apps remember things in **tables**: rows are records (a booking), columns are fields (name, date, status). Choose field types (text, number, date, yes/no, choice). Keep fields few and clear.

Never collect data you do not need. Personal data creates duty of care.$t7c$, $t7d$Data: what your app remembers$t7d$, $t7e$Design a table for your tool: list every field with its type and why you need it, and mark any personal data.$t7e$, $t7f$[{"criterion": "Fields have types and reasons", "max_points": 45, "guidance": "Each field justified."}, {"criterion": "Minimal data", "max_points": 30, "guidance": "No unnecessary collection."}, {"criterion": "Personal data identified", "max_points": 25, "guidance": "Flagged and considered."}]$t7f$::jsonb, 20, 'text', false, false),
  (8, $t8a$Forms and validation$t8a$, $t8b$Make forms that prevent bad input.$t8b$, $t8c$Good forms have clear labels, only required fields marked, helpful error messages and sensible limits (an email must look like an email). Validate in the app, not just in your head.$t8c$, $t8d$Forms and validation$t8d$, $t8e$Improve one form. Submit before and after screenshots and a list of validations you added.

**Evidence:** paste *direct* links to screenshots (ending .png/.jpg/.webp), one per line, and describe what they show. A link to the running app is welcome but the screenshots are what get scored.$t8e$, $t8f$[{"criterion": "Validation added", "max_points": 40, "guidance": "Real rules."}, {"criterion": "Clear labels and errors", "max_points": 35, "guidance": "Understandable."}, {"criterion": "Before/after shown", "max_points": 25, "guidance": "Evidence."}]$t8f$::jsonb, 20, 'link', false, false),
  (9, $t9a$Lists, search and filters$t9a$, $t9b$Help users find things in a growing list.$t9b$, $t9c$Once data grows, users need to sort, search and filter. Add a search box, a filter for status and a sensible default order. Test with 30 sample records.$t9c$, $t9d$Lists, search and filters$t9d$, $t9e$Add search and one filter with 30 sample records. Submit screenshots of the list, a search and a filtered view.

**Evidence:** paste *direct* links to screenshots (ending .png/.jpg/.webp), one per line, and describe what they show. A link to the running app is welcome but the screenshots are what get scored.$t9e$, $t9f$[{"criterion": "Search and filter work", "max_points": 50, "guidance": "Shown in screenshots."}, {"criterion": "Realistic sample data", "max_points": 25, "guidance": "About 30 records."}, {"criterion": "Sensible default order", "max_points": 25, "guidance": "Explained."}]$t9f$::jsonb, 30, 'link', false, false),
  (10, $t10a$Users and permissions$t10a$, $t10b$Decide who can see and change what.$t10b$, $t10c$Not everyone should see everything. Define roles (owner, member, visitor) and what each can view, add, edit and delete. Test by signing in as different users. Never rely on hiding a button as security.$t10c$, $t10d$Users and permissions$t10d$, $t10e$Write a permissions table for your tool (roles by actions) and describe how you tested one restriction.$t10e$, $t10f$[{"criterion": "Roles and actions clear", "max_points": 45, "guidance": "A complete table."}, {"criterion": "Least privilege", "max_points": 30, "guidance": "Minimal access by default."}, {"criterion": "Restriction tested", "max_points": 25, "guidance": "A real test."}]$t10f$::jsonb, 20, 'text', false, false),
  (11, $t11a$Making it look right$t11a$, $t11b$Apply basic layout and consistency.$t11b$, $t11c$Consistent spacing, one or two fonts, a small palette and clear buttons make an app feel trustworthy. Check it on a phone. Read it as a first-time user.$t11c$, $t11d$Making it look right$t11d$, $t11e$Improve the look of your tool. Submit before and after screenshots (desktop and phone) and five design changes.

**Evidence:** paste *direct* links to screenshots (ending .png/.jpg/.webp), one per line, and describe what they show. A link to the running app is welcome but the screenshots are what get scored.$t11e$, $t11f$[{"criterion": "Visible improvement", "max_points": 40, "guidance": "After is better."}, {"criterion": "Works on a phone", "max_points": 30, "guidance": "Phone screenshot."}, {"criterion": "Changes listed", "max_points": 30, "guidance": "Five specific changes."}]$t11f$::jsonb, 20, 'link', false, false),
  (12, $t12a$Module project: a data-driven tool$t12a$, $t12b$Build a tool with stored data, a form and search.$t12b$, $t12c$Show Module 2. Extend your tool (or build a new one) with a data table, a validated form, a searchable list and role-based access.

Your work is scored on the rubric below. You can revise and resubmit.$t12c$, $t12d$Module project: a data-driven tool$t12d$, $t12e$Submit: your table design, screenshots of form, list, search and a restricted view, and a short test log.

**Evidence:** paste *direct* links to screenshots (ending .png/.jpg/.webp), one per line, and describe what they show. A link to the running app is welcome but the screenshots are what get scored.$t12e$, $t12f$[{"criterion": "Data design", "max_points": 25, "guidance": "Fields and types make sense."}, {"criterion": "Form and validation", "max_points": 25, "guidance": "Works and prevents bad input."}, {"criterion": "Search and access", "max_points": 30, "guidance": "Both demonstrated."}, {"criterion": "Testing", "max_points": 20, "guidance": "Real test log."}]$t12f$::jsonb, 60, 'link', true, false),
  (13, $t13a$Rules and calculations$t13a$, $t13b$Add logic that saves the user's time.$t13b$, $t13c$Logic turns data into decisions: totals, statuses, reminders. Write the rule in plain words first ("If the balance is over 30 days old, mark as overdue"), then ask the builder to implement it and test with sample data.$t13c$, $t13d$Rules and calculations$t13d$, $t13e$Add one rule or calculation. Submit the rule in plain words, three test cases with expected and actual results.$t13e$, $t13f$[{"criterion": "Rule is precise", "max_points": 35, "guidance": "Unambiguous."}, {"criterion": "Test cases", "max_points": 40, "guidance": "Three with results."}, {"criterion": "Works as stated", "max_points": 25, "guidance": "Actual matches expected."}]$t13f$::jsonb, 20, 'text', false, false),
  (14, $t14a$Adding AI inside your app$t14a$, $t14b$Use AI for one job inside a tool.$t14b$, $t14c$AI can summarise, classify, draft or extract. Give it one narrow job, a clear instruction and a fallback when it is wrong. Show users the AI output as a suggestion they can edit. Never send private data to a tool you have not checked.$t14c$, $t14d$Adding AI inside your app$t14d$, $t14e$Add one AI feature. Submit the instruction it uses, an example input and output, and how a user corrects it.$t14e$, $t14f$[{"criterion": "Narrow job", "max_points": 30, "guidance": "One clear task."}, {"criterion": "Instruction and example", "max_points": 40, "guidance": "Shown."}, {"criterion": "Human can correct", "max_points": 30, "guidance": "Editable suggestion."}]$t14f$::jsonb, 20, 'text', false, false),
  (15, $t15a$Connecting other tools$t15a$, $t15b$Send data to and from another service.$t15b$, $t15c$Integrations connect your tool to email, calendars or spreadsheets. Start with the smallest link (for example send an email when a form is submitted). Store keys in the platform's secret settings, never in the page.$t15c$, $t15d$Connecting other tools$t15d$, $t15e$Connect one service. Submit what triggers it, what it sends, and where secrets are stored.

**Evidence:** paste *direct* links to screenshots (ending .png/.jpg/.webp), one per line, and describe what they show. A link to the running app is welcome but the screenshots are what get scored.$t15e$, $t15f$[{"criterion": "Working connection", "max_points": 40, "guidance": "Evidence it works."}, {"criterion": "Trigger and data described", "max_points": 30, "guidance": "Clear."}, {"criterion": "Secrets handled safely", "max_points": 30, "guidance": "Not exposed."}]$t15f$::jsonb, 20, 'link', false, false),
  (16, $t16a$Notifications and reminders$t16a$, $t16b$Tell users what they need to know, when they need to.$t16b$, $t16c$Good notifications are timely, rare and actionable. Decide: who is told, when and how (email, in-app). Let users opt out.$t16c$, $t16d$Notifications and reminders$t16d$, $t16e$Add one notification. Submit the rule, an example message and how a user turns it off.$t16e$, $t16f$[{"criterion": "Useful and timely", "max_points": 40, "guidance": "Actionable."}, {"criterion": "Message quality", "max_points": 30, "guidance": "Clear."}, {"criterion": "Opt-out", "max_points": 30, "guidance": "Available."}]$t16f$::jsonb, 20, 'text', false, false),
  (17, $t17a$Error handling and empty states$t17a$, $t17b$Design for when things go wrong or there is no data.$t17b$, $t17c$Show helpful messages: what happened and what to do. Empty lists should explain how to add the first item. Never show raw errors to users.$t17c$, $t17d$Error handling and empty states$t17d$, $t17e$Improve five screens or states (empty, loading, error, success, no permission). Submit screenshots or descriptions of each.

**Evidence:** paste *direct* links to screenshots (ending .png/.jpg/.webp), one per line, and describe what they show. A link to the running app is welcome but the screenshots are what get scored.$t17e$, $t17f$[{"criterion": "Five states covered", "max_points": 45, "guidance": "Each present."}, {"criterion": "Messages help", "max_points": 35, "guidance": "Tell users what to do."}, {"criterion": "No raw errors", "max_points": 20, "guidance": "Friendly."}]$t17f$::jsonb, 20, 'link', false, false),
  (18, $t18a$Module project: a tool with logic and one integration$t18a$, $t18b$Deliver a tool that automates something real.$t18b$, $t18c$Show Module 3. Ship a tool with at least one rule, one AI feature or integration, and proper error states.

Your work is scored on the rubric below. You can revise and resubmit.$t18c$, $t18d$Module project: a tool with logic and one integration$t18d$, $t18e$Submit screenshots of the rule in action, the AI or integration working, and error states, plus the plain-word rule and a test log.

**Evidence:** paste *direct* links to screenshots (ending .png/.jpg/.webp), one per line, and describe what they show. A link to the running app is welcome but the screenshots are what get scored.$t18e$, $t18f$[{"criterion": "Logic works", "max_points": 30, "guidance": "Rule shown with tests."}, {"criterion": "AI or integration works", "max_points": 30, "guidance": "Demonstrated."}, {"criterion": "Error states", "max_points": 20, "guidance": "Handled well."}, {"criterion": "Safety", "max_points": 20, "guidance": "Secrets and data handled."}]$t18f$::jsonb, 70, 'link', true, false),
  (19, $t19a$Privacy and safety basics$t19a$, $t19b$Handle user data responsibly.$t19b$, $t19c$Collect the minimum, explain why, protect it and let people delete it. Know the rules that apply (for example GDPR in Europe). Do not store passwords yourself; use the platform's sign-in.$t19c$, $t19d$Privacy and safety basics$t19d$, $t19e$Write a short privacy note for your tool (what you collect, why, who sees it, how to delete) and list three protections.$t19e$, $t19f$[{"criterion": "Accurate and clear note", "max_points": 40, "guidance": "Plain language."}, {"criterion": "Minimal collection", "max_points": 30, "guidance": "Justified."}, {"criterion": "Protections listed", "max_points": 30, "guidance": "Three real ones."}]$t19f$::jsonb, 20, 'text', false, false),
  (20, $t20a$Security mindset$t20a$, $t20b$Spot common ways apps get abused.$t20b$, $t20c$Common issues: exposed keys, no access checks, trusting user input, public links to private data. Ask: what could a curious stranger do? Test as one.$t20c$, $t20d$Security mindset$t20d$, $t20e$Run a five-point security check on your tool. Submit the checks, what you found and what you fixed.$t20e$, $t20f$[{"criterion": "Checks are real", "max_points": 40, "guidance": "Specific tests."}, {"criterion": "Findings honest", "max_points": 30, "guidance": "What actually happened."}, {"criterion": "Fixes made", "max_points": 30, "guidance": "Action taken."}]$t20f$::jsonb, 20, 'text', false, false),
  (21, $t21a$Performance and cost$t21a$, $t21b$Keep your tool fast and affordable.$t21b$, $t21c$Slow pages lose users. Check load time, limit large images, and know the credit or usage costs of AI features. Set a budget and a limit.$t21c$, $t21d$Performance and cost$t21d$, $t21e$Measure one page load, list your cost drivers (AI calls, storage) and set a monthly limit.$t21e$, $t21f$[{"criterion": "Measured, not guessed", "max_points": 40, "guidance": "A real measurement."}, {"criterion": "Costs identified", "max_points": 35, "guidance": "Named drivers."}, {"criterion": "Limit set", "max_points": 25, "guidance": "A number and a reason."}]$t21f$::jsonb, 20, 'text', false, false),
  (22, $t22a$Documentation users will read$t22a$, $t22b$Write a short guide and help text.$t22b$, $t22c$A one-page guide: what it does, how to start, three common tasks, and where to get help. Use screenshots.$t22c$, $t22d$Documentation users will read$t22d$, $t22e$Write a user guide for your tool with three tasks and two screenshots.

**Evidence:** paste *direct* links to screenshots (ending .png/.jpg/.webp), one per line, and describe what they show. A link to the running app is welcome but the screenshots are what get scored.$t22e$, $t22f$[{"criterion": "Tasks explained clearly", "max_points": 45, "guidance": "Step by step."}, {"criterion": "Screenshots help", "max_points": 30, "guidance": "Relevant."}, {"criterion": "Help route", "max_points": 25, "guidance": "Where to ask."}]$t22f$::jsonb, 20, 'link', false, false),
  (23, $t23a$Getting feedback and iterating$t23a$, $t23b$Learn from real users and improve.$t23b$, $t23c$Watch three people use your tool without helping. Note where they hesitate. Fix the top two issues and test again.$t23c$, $t23d$Getting feedback and iterating$t23d$, $t23e$Submit notes from three test users, the top two issues and what you changed.$t23e$, $t23f$[{"criterion": "Real user testing", "max_points": 40, "guidance": "Three people."}, {"criterion": "Issues prioritised", "max_points": 30, "guidance": "Top two."}, {"criterion": "Changes made", "max_points": 30, "guidance": "Specific."}]$t23f$::jsonb, 20, 'text', false, false),
  (24, $t24a$Module project: a launch-ready tool$t24a$, $t24b$Polish and document a tool for real users.$t24b$, $t24c$Show Module 4. Make your tool launch-ready: privacy note, security check, guide, feedback fixes.

Your work is scored on the rubric below. You can revise and resubmit.$t24c$, $t24d$Module project: a launch-ready tool$t24d$, $t24e$Submit screenshots, the privacy note, security check results, user guide and feedback log.

**Evidence:** paste *direct* links to screenshots (ending .png/.jpg/.webp), one per line, and describe what they show. A link to the running app is welcome but the screenshots are what get scored.$t24e$, $t24f$[{"criterion": "Privacy and security", "max_points": 30, "guidance": "Real checks."}, {"criterion": "Documentation", "max_points": 25, "guidance": "Usable guide."}, {"criterion": "Feedback acted on", "max_points": 25, "guidance": "Improvements."}, {"criterion": "Overall polish", "max_points": 20, "guidance": "Ready for users."}]$t24f$::jsonb, 70, 'link', true, false),
  (25, $t25a$Capstone 1: choose a real problem$t25a$, $t25b$Pick a problem for a real person and write the brief.$t25b$, $t25c$Choose a real person or group with a recurring problem. Interview them for 10 minutes. Write the brief.$t25c$, $t25d$Capstone 1: choose a real problem$t25d$, $t25e$Submit your interview notes (or summary) and the one-page brief.$t25e$, $t25f$[{"criterion": "Real person and problem", "max_points": 40, "guidance": "Specific."}, {"criterion": "Brief is complete", "max_points": 35, "guidance": "All parts."}, {"criterion": "Scope is realistic", "max_points": 25, "guidance": "Achievable."}]$t25f$::jsonb, 20, 'text', false, false),
  (26, $t26a$Capstone 2: design the data and screens$t26a$, $t26b$Plan before building.$t26b$, $t26c$Sketch the screens and the data table. Check the plan against the brief.$t26c$, $t26d$Capstone 2: design the data and screens$t26d$, $t26e$Submit your screen sketches (photo links) and data table.

**Evidence:** paste *direct* links to screenshots (ending .png/.jpg/.webp), one per line, and describe what they show. A link to the running app is welcome but the screenshots are what get scored.$t26e$, $t26f$[{"criterion": "Screens cover the job", "max_points": 40, "guidance": "Complete flow."}, {"criterion": "Data is sensible", "max_points": 35, "guidance": "Fields justified."}, {"criterion": "Matches brief", "max_points": 25, "guidance": "Consistent."}]$t26f$::jsonb, 20, 'link', false, false),
  (27, $t27a$Capstone 3: build version one$t27a$, $t27b$Build the working core.$t27b$, $t27c$Build the smallest version that does the main job. Test it with ten checks.$t27c$, $t27d$Capstone 3: build version one$t27d$, $t27e$Submit screenshots of the working core and your test results.

**Evidence:** paste *direct* links to screenshots (ending .png/.jpg/.webp), one per line, and describe what they show. A link to the running app is welcome but the screenshots are what get scored.$t27e$, $t27f$[{"criterion": "Core works", "max_points": 50, "guidance": "Shown."}, {"criterion": "Tested", "max_points": 30, "guidance": "Ten checks."}, {"criterion": "Matches design", "max_points": 20, "guidance": "Consistent."}]$t27f$::jsonb, 60, 'link', false, false),
  (28, $t28a$Capstone 4: add logic, AI or integration and polish$t28a$, $t28b$Add the feature that makes it genuinely useful.$t28b$, $t28c$Add one rule, AI feature or integration, plus error states and a phone-friendly layout.$t28c$, $t28d$Capstone 4: add logic, AI or integration and polish$t28d$, $t28e$Submit screenshots of the new feature and the polish changes.

**Evidence:** paste *direct* links to screenshots (ending .png/.jpg/.webp), one per line, and describe what they show. A link to the running app is welcome but the screenshots are what get scored.$t28e$, $t28f$[{"criterion": "Feature works", "max_points": 45, "guidance": "Shown."}, {"criterion": "Polish", "max_points": 30, "guidance": "Visible."}, {"criterion": "Safe handling", "max_points": 25, "guidance": "Secrets and data."}]$t28f$::jsonb, 60, 'link', false, false),
  (29, $t29a$Capstone 5: real user test and fixes$t29a$, $t29b$Test with the real person and fix.$t29b$, $t29c$Give the tool to your real person. Watch. Fix the top issues.$t29c$, $t29d$Capstone 5: real user test and fixes$t29d$, $t29e$Submit the feedback and your fixes with a screenshot of one fix.

**Evidence:** paste *direct* links to screenshots (ending .png/.jpg/.webp), one per line, and describe what they show. A link to the running app is welcome but the screenshots are what get scored.$t29e$, $t29f$[{"criterion": "Real test", "max_points": 40, "guidance": "The intended user."}, {"criterion": "Issues fixed", "max_points": 40, "guidance": "Specific."}, {"criterion": "Reflection", "max_points": 20, "guidance": "What you learned."}]$t29f$::jsonb, 20, 'link', false, false),
  (30, $t30a$Capstone 6: launch and present$t30a$, $t30b$Launch to your user and present what you built.$t30b$, $t30c$Publish the tool, share the guide, and write a case study: problem, solution, result and next steps. Share in the Discord and ask for one piece of feedback.

Your work is scored on the rubric below. You can revise and resubmit.$t30c$, $t30d$Capstone 6: launch and present$t30d$, $t30e$Submit: a case study (problem, what you built, result, next steps), screenshots of the launched tool, the guide and the privacy note.

**Evidence:** paste *direct* links to screenshots (ending .png/.jpg/.webp), one per line, and describe what they show. A link to the running app is welcome but the screenshots are what get scored.$t30e$, $t30f$[{"criterion": "Solves a real problem", "max_points": 30, "guidance": "Evidence of use."}, {"criterion": "Quality and reliability", "max_points": 25, "guidance": "Tested and works."}, {"criterion": "Safety and privacy", "max_points": 20, "guidance": "Handled."}, {"criterion": "Case study clarity", "max_points": 25, "guidance": "Clear and honest."}]$t30f$::jsonb, 75, 'link', true, false)
) as v(n, title, objective, lesson_md, skill_focus, assignment_md, rubric, est_minutes, submission_type, ai_evaluate, requires_review)
where t.slug = 'apps'
on conflict (track_id, day_number) do nothing;
