-- Content & writing, Grandmaster tier (days 81-90). Authored content, UNPUBLISHED until a person reviews it in Admin.
insert into public.day
  (track_id, tier_id, day_number, title, objective, lesson_md, skill_focus, assignment_md, rubric,
   est_minutes, is_published, credit_budget, submission_type, ai_evaluate, requires_review)
select t.id, ti.id, v.n, v.title, v.objective, v.lesson_md, v.skill_focus, v.assignment_md, v.rubric,
       v.est_minutes, false, null, v.submission_type, v.ai_evaluate, v.requires_review
from public.track t
join public.tier ti on ti.track_id = t.id and ti.slug = 'grandmaster'
cross join (values
  (81, $t81a$Teaching your craft: design a mini lesson$t81a$, $t81b$Explain a writing skill so a beginner can use it.$t81b$, $t81c$Teaching exposes gaps in your own understanding. Choose one skill (for example writing a brief). Write a lesson: goal, short explanation, worked example, practice task and a check for success.$t81c$, $t81d$Teaching your craft: design a mini lesson$t81d$, $t81e$Submit a one-page lesson with a worked example and practice task.$t81e$, $t81f$[{"criterion": "Clear explanation", "max_points": 35, "guidance": "Beginner-friendly."}, {"criterion": "Worked example", "max_points": 35, "guidance": "Real."}, {"criterion": "Practice and check", "max_points": 30, "guidance": "Usable."}]$t81f$::jsonb, 60, 'text', false, false),
  (82, $t82a$Critique clinic: give three expert critiques$t82a$, $t82b$Diagnose other writers' work precisely.$t82b$, $t82c$Take three pieces (with permission or public) and diagnose: what works, the top problem, the fix and an exercise. Prioritise; do not list everything.$t82c$, $t82d$Critique clinic: give three expert critiques$t82d$, $t82e$Submit three critiques (150 words each) with one prioritised fix each.$t82e$, $t82f$[{"criterion": "Diagnosis precise", "max_points": 40, "guidance": "Insightful."}, {"criterion": "Prioritised", "max_points": 30, "guidance": "Focused."}, {"criterion": "Constructive", "max_points": 30, "guidance": "Kind and useful."}]$t82f$::jsonb, 60, 'text', false, false),
  (83, $t83a$Original research piece$t83a$, $t83b$Create knowledge, not just content.$t83b$, $t83c$Run a small original study: survey, dataset analysis or test with clear method and limits. Publish the method so others can check.$t83c$, $t83d$Original research piece$t83d$, $t83e$Submit method, data summary, findings and limits.$t83e$, $t83f$[{"criterion": "Method sound", "max_points": 35, "guidance": "Transparent."}, {"criterion": "Findings honest", "max_points": 40, "guidance": "Limits."}, {"criterion": "Original", "max_points": 25, "guidance": "New."}]$t83f$::jsonb, 120, 'text', false, false),
  (84, $t84a$Case study: results and lessons$t84a$, $t84b$Document work honestly.$t84b$, $t84c$A case study states context, action, result and lessons, with real numbers and what did not work. Never inflate results.$t84c$, $t84d$Case study: results and lessons$t84d$, $t84e$Write a case study of a real project (yours or with permission).$t84e$, $t84f$[{"criterion": "Real numbers", "max_points": 40, "guidance": "Honest."}, {"criterion": "Lessons frank", "max_points": 30, "guidance": "Includes failures."}, {"criterion": "Clear story", "max_points": 30, "guidance": "Structured."}]$t84f$::jsonb, 60, 'text', false, false),
  (85, $t85a$Grandmaster project 1: a public body of work plan$t85a$, $t85b$Plan a visible portfolio with a point of view.$t85b$, $t85c$Show your direction. Deliver a **body-of-work plan**: your point of view, three flagship pieces, one teaching resource, one research piece and a 6-month schedule.

Your work is scored on the rubric below. You can revise and resubmit.$t85c$, $t85d$Grandmaster project 1: a public body of work plan$t85d$, $t85e$Submit the plan and how you will measure progress.$t85e$, $t85f$[{"criterion": "Point of view", "max_points": 30, "guidance": "Distinct."}, {"criterion": "Pieces valuable", "max_points": 30, "guidance": "Strong."}, {"criterion": "Schedule realistic", "max_points": 20, "guidance": "Feasible."}, {"criterion": "Measurement and honesty", "max_points": 20, "guidance": "Clear."}]$t85f$::jsonb, 90, 'text', true, false),
  (86, $t86a$Mentoring: review a peer's work$t86a$, $t86b$Help another writer improve using the rubric.$t86b$, $t86c$Pick a peer's submission (with permission). Score it against the rubric, explain each score with evidence and offer one exercise.$t86c$, $t86d$Mentoring: review a peer's work$t86d$, $t86e$Submit your scored review of a peer's piece with evidence per criterion.$t86e$, $t86f$[{"criterion": "Scores justified", "max_points": 40, "guidance": "Evidence."}, {"criterion": "Fair and kind", "max_points": 30, "guidance": "Balanced."}, {"criterion": "Exercise helpful", "max_points": 30, "guidance": "Practical."}]$t86f$::jsonb, 60, 'text', false, false),
  (87, $t87a$Build a course module$t87a$, $t87b$Package what you know into a teachable unit.$t87b$, $t87c$Design a module: outcomes, five lessons, practice tasks, a project and a rubric. Test with one learner.$t87c$, $t87d$Build a course module$t87d$, $t87e$Submit the module outline, one full lesson and learner feedback.$t87e$, $t87f$[{"criterion": "Outcomes clear", "max_points": 30, "guidance": "Measurable."}, {"criterion": "Lesson quality", "max_points": 40, "guidance": "Strong."}, {"criterion": "Tested", "max_points": 30, "guidance": "Real learner."}]$t87f$::jsonb, 120, 'text', false, false),
  (88, $t88a$Standards and ethics in the age of AI$t88a$, $t88b$State your principles publicly.$t88b$, $t88c$Write a public statement of how you use AI, verify facts, credit sources and handle errors. Publish corrections when needed.$t88c$, $t88d$Standards and ethics in the age of AI$t88d$, $t88e$Submit your public standards statement and an example of a correction policy.$t88e$, $t88f$[{"criterion": "Principles specific", "max_points": 40, "guidance": "Concrete."}, {"criterion": "Accountability", "max_points": 35, "guidance": "Corrections."}, {"criterion": "Honest about AI", "max_points": 25, "guidance": "Transparent."}]$t88f$::jsonb, 45, 'text', false, false),
  (89, $t89a$Impact audit$t89a$, $t89b$Measure what your work has done.$t89b$, $t89c$Collect evidence of impact: reader feedback, results, learner outcomes. Be honest about what cannot be shown.$t89c$, $t89d$Impact audit$t89d$, $t89e$Submit an impact report with evidence and limits.$t89e$, $t89f$[{"criterion": "Evidence real", "max_points": 45, "guidance": "Collected."}, {"criterion": "Analysis honest", "max_points": 35, "guidance": "Limits."}, {"criterion": "Next steps", "max_points": 20, "guidance": "Clear."}]$t89f$::jsonb, 60, 'text', false, false),
  (90, $t90a$Grandmaster capstone: portfolio, teaching and impact$t90a$, $t90b$Present a body of work that proves mastery.$t90b$, $t90c$The final assessment. Deliver a **Grandmaster portfolio**: a flagship piece, an original research piece, a teaching resource with learner feedback, a peer review, your standards statement and an impact report.

Your work is scored on the rubric below. You can revise and resubmit.$t90c$, $t90d$Grandmaster capstone: portfolio, teaching and impact$t90d$, $t90e$Submit the portfolio as one document with links, plus a one-page reflection on your growth and what you will do next.$t90e$, $t90f$[{"criterion": "Craft and originality", "max_points": 30, "guidance": "Excellent."}, {"criterion": "Rigour and honesty", "max_points": 25, "guidance": "Verified."}, {"criterion": "Teaching and mentoring", "max_points": 25, "guidance": "Effective."}, {"criterion": "Impact and reflection", "max_points": 20, "guidance": "Evidenced."}]$t90f$::jsonb, 180, 'text', true, false)
) as v(n, title, objective, lesson_md, skill_focus, assignment_md, rubric, est_minutes, submission_type, ai_evaluate, requires_review)
where t.slug = 'content'
on conflict (track_id, day_number) do nothing;
