-- Content & writing, Pro tier (days 31-60). Authored content, UNPUBLISHED until a person reviews it in Admin.
insert into public.day
  (track_id, tier_id, day_number, title, objective, lesson_md, skill_focus, assignment_md, rubric,
   est_minutes, is_published, credit_budget, submission_type, ai_evaluate, requires_review)
select t.id, ti.id, v.n, v.title, v.objective, v.lesson_md, v.skill_focus, v.assignment_md, v.rubric,
       v.est_minutes, false, null, v.submission_type, v.ai_evaluate, v.requires_review
from public.track t
join public.tier ti on ti.track_id = t.id and ti.slug = 'pro'
cross join (values
  (31, $t31a$Voice is a system, not a vibe$t31a$, $t31b$Describe a voice precisely enough that anyone (or any AI) can reproduce it.$t31b$, $t31c$A voice is a set of repeatable choices: sentence length, vocabulary, humour, how you open, how you close. "Friendly and professional" is not a voice; it is a mood.

Write a voice spec with: **3 traits** (each with a do and a don't), **5 words you use**, **5 words you avoid**, and **one sample paragraph**. Then test it: give the spec to your AI tool and ask for a short piece. Does it sound like your sample?$t31c$, $t31d$Voice specification$t31d$, $t31e$Write a voice spec for a real or made-up brand or for yourself. Submit the spec (traits with do/don't, words used and avoided) and the AI test paragraph, plus two sentences on where the AI missed.$t31e$, $t31f$[{"criterion": "Traits are concrete", "max_points": 35, "guidance": "Each trait has a usable do and don't."}, {"criterion": "Vocabulary lists are distinctive", "max_points": 25, "guidance": "Words are specific, not generic."}, {"criterion": "Test and honest critique", "max_points": 40, "guidance": "Shows the AI output and names where it missed."}]$t31f$::jsonb, 25, 'text', false, false),
  (32, $t32a$Show, do not tell: teaching AI a voice with examples$t32a$, $t32b$Use example passages to steer tone better than adjectives do.$t32b$, $t32c$Adjectives are weak; examples are strong. Paste two or three short passages you love (or wrote) and say "match the rhythm and word choice of these, not the topic."

Tips: use 100 to 300 words of examples, label them, and keep them on the same kind of writing. Only use text you wrote or have the right to use as a style guide.$t32c$, $t32d$Few-shot voice prompting$t32d$, $t32e$Run the same brief twice: once with adjectives, once with examples. Submit both prompts, both outputs, and a comparison of which sounds more like the target and why.$t32e$, $t32f$[{"criterion": "Fair comparison", "max_points": 30, "guidance": "Same brief, only the steering method differs."}, {"criterion": "Examples chosen well", "max_points": 30, "guidance": "Short, relevant, labelled."}, {"criterion": "Analysis is specific", "max_points": 40, "guidance": "Points to phrases, rhythm and word choice."}]$t32f$::jsonb, 25, 'text', false, false),
  (33, $t33a$Editing AI's habits out$t33a$, $t33b$Remove the tells that make text sound machine-made.$t33b$, $t33c$AI text has habits: stacks of adjectives, "in today's fast-paced world", tidy three-part lists, ending with a moral, over-explaining. Build a **kill list** of phrases you never want and give it to the AI, then edit by hand for the rest.

Read aloud. Anything you would never say goes.$t33c$, $t33d$De-slopping text$t33d$, $t33e$Take a 250-word AI draft. Submit the original, your kill list (at least 8 items), and the edited version with a short note on the three biggest changes.$t33e$, $t33f$[{"criterion": "Kill list is specific", "max_points": 30, "guidance": "Real phrases, not vague rules."}, {"criterion": "Edited version is clearly better", "max_points": 45, "guidance": "Sounds human and keeps the meaning."}, {"criterion": "Change notes", "max_points": 25, "guidance": "Explains the biggest edits."}]$t33f$::jsonb, 25, 'text', false, false),
  (34, $t34a$Rhythm and sentence craft$t34a$, $t34b$Vary sentence length and cut filler on purpose.$t34b$, $t34c$Rhythm keeps readers moving. Mix short and long sentences. Cut filler (very, really, just, in order to). Prefer strong verbs to adverbs. Put the key word at the end of the sentence.

Try the ladder: take a flat paragraph and rewrite it three times, each time cutting 20 percent.$t34c$, $t34d$Sentence-level editing$t34d$, $t34e$Submit a paragraph before and after your rewrite, with word counts, and mark two places where you changed rhythm on purpose and why.$t34e$, $t34f$[{"criterion": "Tighter without losing meaning", "max_points": 45, "guidance": "Fewer words, same message."}, {"criterion": "Rhythm varied", "max_points": 30, "guidance": "Short and long sentences are mixed."}, {"criterion": "Reasons given", "max_points": 25, "guidance": "Explains two deliberate choices."}]$t34f$::jsonb, 25, 'text', false, false),
  (35, $t35a$Voice for different channels$t35a$, $t35b$Adapt one message to email, social and a web page without losing the voice.$t35b$, $t35c$One voice, different rooms. Email is personal and short. Social is fast and skimmable. A web page must answer the question in seconds. Keep the traits, change the length and structure.

Write the core message first (one sentence), then adapt.$t35c$, $t35d$Channel adaptation$t35d$, $t35e$Take one core message and write it as an email (under 120 words), a social post (under 50) and a web-page intro (under 80). Submit all three, the core message, and what stayed constant.$t35e$, $t35f$[{"criterion": "Same voice across all three", "max_points": 40, "guidance": "Recognisably one writer."}, {"criterion": "Right shape for each channel", "max_points": 40, "guidance": "Length and structure fit."}, {"criterion": "Core message is clear", "max_points": 20, "guidance": "One sentence, stated."}]$t35f$::jsonb, 25, 'text', false, false),
  (36, $t36a$Module project: a brand voice guide with proof$t36a$, $t36b$Produce a one-page voice guide and prove it works.$t36b$, $t36c$Show Module 1. Write a **one-page voice guide** and three pieces written to it (different channels), tested with AI and edited by you. Include the kill list and the examples you gave the AI.

Success looks like a guide a stranger could follow and three pieces that clearly share one voice.

Your work is scored on the rubric below. You can revise and resubmit.$t36c$, $t36d$Building a voice guide$t36d$, $t36e$Submit: the voice guide (traits, words, kill list), three pieces in three channels, and a paragraph on how you tested and edited.$t36e$, $t36f$[{"criterion": "Guide is usable", "max_points": 30, "guidance": "Specific traits, words and rules."}, {"criterion": "Pieces share one voice", "max_points": 30, "guidance": "Recognisably consistent."}, {"criterion": "Human editing shows", "max_points": 20, "guidance": "Not raw AI output."}, {"criterion": "Testing described", "max_points": 20, "guidance": "Explains prompts and revisions."}]$t36f$::jsonb, 60, 'text', true, false),
  (37, $t37a$Structure before sentences$t37a$, $t37b$Plan a long piece with a spine and a promise.$t37b$, $t37c$Long-form works when it has a **spine**: one sentence that the whole piece proves. Write the promise to the reader, then list the sections each proving one part.

Ask AI for three different structures, then choose and combine. The choice is yours; that is the craft.$t37c$, $t37d$Outlining long-form$t37d$, $t37e$Pick a topic. Submit the spine sentence, the reader's promise, two alternative outlines from AI, and your final outline with reasons.$t37e$, $t37f$[{"criterion": "Spine is clear", "max_points": 35, "guidance": "One provable sentence."}, {"criterion": "Alternatives compared", "max_points": 30, "guidance": "Two outlines and a choice."}, {"criterion": "Final outline is logical", "max_points": 35, "guidance": "Sections build the argument."}]$t37f$::jsonb, 25, 'text', false, false),
  (38, $t38a$Hooks and openings$t38a$, $t38b$Write openings that earn the next paragraph.$t38b$, $t38c$Good openings: a surprising fact, a specific scene, a sharp question, or a bold claim you then prove. Bad ones: throat-clearing and definitions.

Write five openings for one piece, then test them on a friend: which one made them want more?$t38c$, $t38d$Writing hooks$t38d$, $t38e$Submit five openings for the same piece, the one you chose, and what a real reader (name or role) said about them.$t38e$, $t38f$[{"criterion": "Five distinct approaches", "max_points": 40, "guidance": "Different hook types."}, {"criterion": "Chosen with a reason", "max_points": 30, "guidance": "Explains the pick."}, {"criterion": "Reader feedback", "max_points": 30, "guidance": "A real reader's reaction."}]$t38f$::jsonb, 25, 'text', false, false),
  (39, $t39a$Evidence and examples$t39a$, $t39b$Back claims with concrete, checkable support.$t39b$, $t39c$Claims need proof: a number, a source, a story or an example. Use AI to suggest what kind of evidence fits, but you must find and check the sources.

Rule: every number or quote gets a source link you opened yourself.$t39c$, $t39d$Supporting claims$t39d$, $t39e$Take a draft with five claims. Submit each claim with its evidence and a working link, and mark any claim you softened or removed because you could not verify it.$t39e$, $t39f$[{"criterion": "Evidence fits the claim", "max_points": 35, "guidance": "Relevant and specific."}, {"criterion": "Sources are real and checked", "max_points": 45, "guidance": "Links work and were opened."}, {"criterion": "Unsupported claims handled", "max_points": 20, "guidance": "Softened or removed honestly."}]$t39f$::jsonb, 25, 'text', false, false),
  (40, $t40a$Transitions and flow$t40a$, $t40b$Make sections lead into each other.$t40b$, $t40c$Flow comes from each section handing the reader to the next: end with a question or a promise, start by picking it up. Read only the first sentences of each paragraph: do they tell the story?

Cut anything that does not serve the spine.$t40c$, $t40d$Flow and cohesion$t40d$, $t40e$Submit a 500-word draft with its first-sentence skeleton listed, and the revised version with one cut and one new transition explained.$t40e$, $t40f$[{"criterion": "Skeleton tells the story", "max_points": 40, "guidance": "First sentences alone make sense."}, {"criterion": "Transitions improved", "max_points": 35, "guidance": "Sections connect."}, {"criterion": "Cut with a reason", "max_points": 25, "guidance": "A justified deletion."}]$t40f$::jsonb, 25, 'text', false, false),
  (41, $t41a$Endings that land$t41a$, $t41b$Finish with a clear takeaway or action, not a summary.$t41b$, $t41c$A good ending returns to the promise, gives one memorable line and one next step. Avoid restating everything and avoid moralising.

Write three endings: a callback, a challenge and a next step. Pick the one that fits the reader.$t41c$, $t41d$Writing conclusions$t41d$, $t41e$Submit the piece's spine, three endings, your choice, and why it fits the reader.$t41e$, $t41f$[{"criterion": "Three real options", "max_points": 35, "guidance": "Different approaches."}, {"criterion": "Ending fits the spine", "max_points": 35, "guidance": "Returns to the promise."}, {"criterion": "Reader-centred reasoning", "max_points": 30, "guidance": "Explains why for this reader."}]$t41f$::jsonb, 25, 'text', false, false),
  (42, $t42a$Module project: a 900-word article$t42a$, $t42b$Write, edit and fact-check a complete article.$t42b$, $t42c$Show Module 2. Write a **900-word article** for a real audience with a clear spine, a strong opening, checked evidence and a landing ending.

Success looks like: a reader learns something specific, every fact has a source, and it reads like a person wrote it.

Your work is scored on the rubric below. You can revise and resubmit.$t42c$, $t42d$Long-form article$t42d$, $t42e$Submit the article, the spine and audience, a list of sources with links, and a note on what you changed from the AI draft.$t42e$, $t42f$[{"criterion": "Clear spine and structure", "max_points": 25, "guidance": "Easy to follow."}, {"criterion": "Evidence is checked", "max_points": 30, "guidance": "Real sources."}, {"criterion": "Voice and craft", "max_points": 25, "guidance": "Human, tight, varied."}, {"criterion": "Honest process note", "max_points": 20, "guidance": "Says what changed."}]$t42f$::jsonb, 75, 'text', true, false),
  (43, $t43a$Copy that sells: audience, problem, promise$t43a$, $t43b$Write persuasive copy that starts from the reader's problem.$t43b$, $t43c$Persuasion starts with the reader's problem, in their words. Structure: problem, promise, proof, next step. Do not lie, exaggerate or invent testimonials or statistics.

Interview a real person if you can and reuse their exact words.$t43c$, $t43d$Persuasive structure$t43d$, $t43e$Choose a real or made-up offer. Submit the reader's problem in their words, your promise, your proof (real or clearly labelled as example), and a 100-word piece of copy.$t43e$, $t43f$[{"criterion": "Starts from the reader", "max_points": 35, "guidance": "Problem in the reader's words."}, {"criterion": "Honest proof", "max_points": 35, "guidance": "Nothing invented or misleading."}, {"criterion": "Copy is clear", "max_points": 30, "guidance": "Promise and next step are obvious."}]$t43f$::jsonb, 25, 'text', false, false),
  (44, $t44a$Headlines and calls to action$t44a$, $t44b$Test many headlines and choose with evidence.$t44b$, $t44c$Generate 20 headlines, group by angle (benefit, curiosity, proof, urgency), and pick three to test. Calls to action should be one clear verb and a reason.

Real tests need real readers: use a poll, a two-version send or feedback.$t44c$, $t44d$Headline testing$t44d$, $t44e$Submit 20 headlines grouped by angle, three finalists, a call to action for each, and the result of a small real test.$t44e$, $t44f$[{"criterion": "Range of angles", "max_points": 30, "guidance": "Groups are distinct."}, {"criterion": "Finalists chosen well", "max_points": 30, "guidance": "Reasoned selection."}, {"criterion": "Test is real and reported", "max_points": 40, "guidance": "Actual results, honestly described."}]$t44f$::jsonb, 25, 'text', false, false),
  (45, $t45a$The email that gets read$t45a$, $t45b$Write a short email with a clear ask.$t45b$, $t45c$One email, one job. Short subject, personal first line, one idea, one ask. Read it on your phone. Remove anything that is not the ask.

Follow the law: honest sender, honest subject line and an unsubscribe for marketing email.$t45c$, $t45d$Email writing$t45d$, $t45e$Write a promotional or outreach email under 150 words. Submit the subject line options, the final email, and how it follows the one-idea rule.$t45e$, $t45f$[{"criterion": "One idea, one ask", "max_points": 40, "guidance": "Clear and focused."}, {"criterion": "Subject line quality", "max_points": 25, "guidance": "Honest and specific."}, {"criterion": "Tone and length", "max_points": 35, "guidance": "Personal, short, readable."}]$t45f$::jsonb, 25, 'text', false, false),
  (46, $t46a$Landing page copy$t46a$, $t46b$Write the sections of a simple landing page.$t46b$, $t46c$A landing page answers: what is it, who is it for, why should I trust it, what do I do next. Sections: headline, subhead, three benefits, proof, FAQ and a button.

Keep each section small. Write for scanning.$t46c$, $t46d$Landing page structure$t46d$, $t46e$Submit landing page copy with all sections for a real or made-up offer, and mark where you would add a real proof element.$t46e$, $t46f$[{"criterion": "All sections present", "max_points": 30, "guidance": "Headline to call to action."}, {"criterion": "Benefits over features", "max_points": 35, "guidance": "Explains what changes for the reader."}, {"criterion": "Scannable and honest", "max_points": 35, "guidance": "Short, clear, no invented claims."}]$t46f$::jsonb, 25, 'text', false, false),
  (47, $t47a$Objections and FAQs$t47a$, $t47b$Anticipate doubts and answer them honestly.$t47b$, $t47c$Readers hesitate: price, trust, time, fit. List the top five objections and answer each honestly, including who the offer is not for.

Honesty builds trust and improves conversions.$t47c$, $t47d$Handling objections$t47d$, $t47e$Submit five objections and your honest answers, plus one line on who this offer is not for.$t47e$, $t47f$[{"criterion": "Objections are real", "max_points": 35, "guidance": "Genuine reader doubts."}, {"criterion": "Answers are honest", "max_points": 40, "guidance": "No spin or false claims."}, {"criterion": "Says who it is not for", "max_points": 25, "guidance": "A real limit."}]$t47f$::jsonb, 25, 'text', false, false),
  (48, $t48a$Module project: an email and landing page pair$t48a$, $t48b$Create a consistent email plus landing page for one offer.$t48b$, $t48c$Show Module 3. Write **one email and one landing page** for the same offer, in your voice, with honest claims and a clear call to action.

Success looks like a stranger could understand the offer and act, and nothing is invented.

Your work is scored on the rubric below. You can revise and resubmit.$t48c$, $t48d$Persuasive writing$t48d$, $t48e$Submit the email, the landing page copy, the reader's problem, and a list of every claim with its source or a note that it is an example.$t48e$, $t48f$[{"criterion": "Clear offer and ask", "max_points": 30, "guidance": "Understandable in seconds."}, {"criterion": "Honest claims", "max_points": 30, "guidance": "Sourced or labelled."}, {"criterion": "Voice consistency", "max_points": 20, "guidance": "Email and page match."}, {"criterion": "Audience fit", "max_points": 20, "guidance": "Speaks to the reader's problem."}]$t48f$::jsonb, 75, 'text', true, false),
  (49, $t49a$One idea, many formats$t49a$, $t49b$Turn one article into a set of pieces without copying.$t49b$, $t49c$Repurposing is re-shaping, not pasting. From one article: a thread, a newsletter section, three quotes, a short script. Each needs its own opening and its own shape.

Keep one source of truth so facts stay consistent.$t49c$, $t49d$Repurposing content$t49d$, $t49e$Take your article and submit four derived pieces in four formats, marking the shared facts.$t49e$, $t49f$[{"criterion": "Different shapes", "max_points": 40, "guidance": "Not copy-paste."}, {"criterion": "Facts stay consistent", "max_points": 35, "guidance": "Matches the source."}, {"criterion": "Each piece stands alone", "max_points": 25, "guidance": "Opening and point are clear."}]$t49f$::jsonb, 25, 'text', false, false),
  (50, $t50a$Content calendar and cadence$t50a$, $t50b$Plan a month of content you can actually produce.$t50b$, $t50c$A calendar is a promise you can keep. Choose a cadence (for example two posts a week), themes, and a batch day. Use AI to draft options but keep the plan small.

Include buffer weeks and a review day.$t50c$, $t50d$Planning cadence$t50d$, $t50e$Submit a four-week calendar with themes, formats, dates, and how many hours it needs each week.$t50e$, $t50f$[{"criterion": "Realistic workload", "max_points": 40, "guidance": "Hours fit the plan."}, {"criterion": "Themes support the goal", "max_points": 30, "guidance": "Connected to the audience."}, {"criterion": "Buffer and review", "max_points": 30, "guidance": "Includes slack and checks."}]$t50f$::jsonb, 25, 'text', false, false),
  (51, $t51a$Summaries and briefings$t51a$, $t51b$Condense long material accurately.$t51b$, $t51c$Summaries lose meaning if you are careless. Give the AI the source, ask for a summary with quotes and page references, and check every claim against the source.

Never summarise text you cannot verify.$t51c$, $t51d$Accurate summarising$t51d$, $t51e$Take a public article. Submit its link, a 120-word summary, three verified quotes, and a note on one error the AI made or a check that passed.$t51e$, $t51f$[{"criterion": "Summary is accurate", "max_points": 40, "guidance": "Matches the source."}, {"criterion": "Quotes verified", "max_points": 35, "guidance": "Exact and attributed."}, {"criterion": "Verification described", "max_points": 25, "guidance": "Says what was checked."}]$t51f$::jsonb, 25, 'text', false, false),
  (52, $t52a$Working with an editor's eye: self-critique prompts$t52a$, $t52b$Use AI as a hard-nosed editor without losing your voice.$t52b$, $t52c$Ask AI to critique, not rewrite: "list the five weakest sentences and why", "what would a skeptical reader ask?" Then you decide which changes to make.

Keep a changelog so you can see what you accepted and rejected.$t52c$, $t52d$AI-assisted critique$t52d$, $t52e$Run a critique on a piece. Submit the critique prompt, the AI's points, which you accepted or rejected with reasons, and the revised paragraph.$t52e$, $t52f$[{"criterion": "Critique prompt is sharp", "max_points": 30, "guidance": "Asks for specific problems."}, {"criterion": "Accept/reject reasoning", "max_points": 40, "guidance": "You made real decisions."}, {"criterion": "Revision improves", "max_points": 30, "guidance": "Visible improvement."}]$t52f$::jsonb, 25, 'text', false, false),
  (53, $t53a$Accessibility and clarity$t53a$, $t53b$Make writing easy for everyone to read.$t53b$, $t53c$Plain words, short sentences, meaningful headings and descriptive link text. Add alt text to images. Aim for a reading level your audience finds easy.

Test with a screen-reader preview or by reading aloud.$t53c$, $t53d$Accessible writing$t53d$, $t53e$Take a piece and submit before and after versions with at least five accessibility changes listed, including alt text for one image.$t53e$, $t53f$[{"criterion": "Real changes made", "max_points": 40, "guidance": "Five listed changes."}, {"criterion": "Plain language", "max_points": 30, "guidance": "Simpler without losing meaning."}, {"criterion": "Alt text quality", "max_points": 30, "guidance": "Describes purpose, not just appearance."}]$t53f$::jsonb, 25, 'text', false, false),
  (54, $t54a$Module project: a four-piece content set$t54a$, $t54b$Deliver a coordinated set of four pieces from one source.$t54b$, $t54c$Show Module 4. From one source idea create **four pieces** in four formats, on a mini calendar, with facts checked and accessible writing.

Success looks like one clear idea, four well-shaped pieces and a plan to publish them.

Your work is scored on the rubric below. You can revise and resubmit.$t54c$, $t54d$Content set$t54d$, $t54e$Submit the source idea, four pieces, a one-week schedule, and a fact-check note listing sources.$t54e$, $t54f$[{"criterion": "One idea, four shapes", "max_points": 30, "guidance": "Pieces are distinct."}, {"criterion": "Facts checked", "max_points": 25, "guidance": "Sources listed."}, {"criterion": "Voice and clarity", "max_points": 25, "guidance": "Consistent and readable."}, {"criterion": "Realistic schedule", "max_points": 20, "guidance": "Can be produced."}]$t54f$::jsonb, 75, 'text', true, false),
  (55, $t55a$Pro capstone 1: choose a client and a goal$t55a$, $t55b$Define a realistic content project with a measurable goal.$t55b$, $t55c$Choose a real small business, project or cause (with permission) or a detailed made-up one. Write a one-page brief: audience, goal, one measurable result, channels, and constraints.$t55c$, $t55d$Scoping a project$t55d$, $t55e$Submit your brief and how you will know it worked.$t55e$, $t55f$[{"criterion": "Brief is specific", "max_points": 40, "guidance": "Audience, goal, channels."}, {"criterion": "Result is measurable", "max_points": 35, "guidance": "A real metric."}, {"criterion": "Scope is realistic", "max_points": 25, "guidance": "Doable in the time."}]$t55f$::jsonb, 25, 'text', false, false),
  (56, $t56a$Pro capstone 2: research and voice guide$t56a$, $t56b$Gather facts and set the voice.$t56b$, $t56c$Collect five to eight facts with sources, and write the voice guide (traits, words, kill list, examples).$t56c$, $t56d$Research and voice$t56d$, $t56e$Submit the sourced fact sheet and the voice guide.$t56e$, $t56f$[{"criterion": "Facts sourced", "max_points": 45, "guidance": "Working links."}, {"criterion": "Voice guide usable", "max_points": 35, "guidance": "Specific rules."}, {"criterion": "Relevant to the goal", "max_points": 20, "guidance": "Supports the brief."}]$t56f$::jsonb, 25, 'text', false, false),
  (57, $t57a$Pro capstone 3: the anchor piece$t57a$, $t57b$Write the main long-form piece.$t57b$, $t57c$Write the anchor: an article or guide of 800 to 1000 words with a spine, hook, checked evidence and ending.$t57c$, $t57d$Anchor content$t57d$, $t57e$Submit the anchor piece and its source list.$t57e$, $t57f$[{"criterion": "Structure and spine", "max_points": 35, "guidance": "Clear argument."}, {"criterion": "Evidence checked", "max_points": 35, "guidance": "Real sources."}, {"criterion": "Voice", "max_points": 30, "guidance": "Matches the guide."}]$t57f$::jsonb, 75, 'text', false, false),
  (58, $t58a$Pro capstone 4: the supporting pieces$t58a$, $t58b$Create the email, landing copy and social versions.$t58b$, $t58c$Repurpose the anchor into an email, a landing section and three social posts, each shaped for its channel.$t58c$, $t58d$Supporting content$t58d$, $t58e$Submit all five pieces.$t58e$, $t58f$[{"criterion": "Shaped for channel", "max_points": 40, "guidance": "Not pasted."}, {"criterion": "Consistent voice", "max_points": 30, "guidance": "One brand."}, {"criterion": "Clear calls to action", "max_points": 30, "guidance": "Each has one ask."}]$t58f$::jsonb, 60, 'text', false, false),
  (59, $t59a$Pro capstone 5: edit, fact-check and accessibility pass$t59a$, $t59b$Polish everything to a professional standard.$t59b$, $t59c$Read every piece aloud, remove AI habits, verify each fact and add accessibility improvements. Record your changelog.$t59c$, $t59d$Quality control$t59d$, $t59e$Submit the changelog and the final versions.$t59e$, $t59f$[{"criterion": "Edits visible", "max_points": 35, "guidance": "Clear improvements."}, {"criterion": "Facts verified", "max_points": 40, "guidance": "Checked against sources."}, {"criterion": "Accessibility done", "max_points": 25, "guidance": "Plain language, alt text."}]$t59f$::jsonb, 25, 'text', false, false),
  (60, $t60a$Pro capstone 6: deliver the content system$t60a$, $t60b$Deliver the full package with a publishing plan.$t60b$, $t60c$Assemble the package: brief, voice guide, fact sheet, anchor piece, supporting pieces, calendar and how you will measure results. Present it as if to a client.

Your work is scored on the rubric below. You can revise and resubmit.$t60c$, $t60d$Client-ready delivery$t60d$, $t60e$Submit the complete package in one document or linked pages, plus a short cover note (5 sentences) explaining the strategy.$t60e$, $t60f$[{"criterion": "Fits the brief and goal", "max_points": 25, "guidance": "Package serves the stated goal."}, {"criterion": "Quality of writing", "max_points": 25, "guidance": "Voice, clarity and craft."}, {"criterion": "Accuracy and honesty", "max_points": 25, "guidance": "Verified facts, no invented claims."}, {"criterion": "Professional presentation and plan", "max_points": 25, "guidance": "Organised with a measurable plan."}]$t60f$::jsonb, 90, 'text', true, false)
) as v(n, title, objective, lesson_md, skill_focus, assignment_md, rubric, est_minutes, submission_type, ai_evaluate, requires_review)
where t.slug = 'content'
on conflict (track_id, day_number) do nothing;
