-- Business & freelancing, Expert tier (days 61-80). Authored content, UNPUBLISHED until a person reviews it in Admin.
insert into public.day
  (track_id, tier_id, day_number, title, objective, lesson_md, skill_focus, assignment_md, rubric,
   est_minutes, is_published, credit_budget, submission_type, ai_evaluate, requires_review)
select t.id, ti.id, v.n, v.title, v.objective, v.lesson_md, v.skill_focus, v.assignment_md, v.rubric,
       v.est_minutes, false, null, v.submission_type, v.ai_evaluate, v.requires_review
from public.track t
join public.tier ti on ti.track_id = t.id and ti.slug = 'expert'
cross join (values
  (61, $t61a$Choosing a niche with evidence$t61a$, $t61b$Pick a segment where you can win.$t61b$, $t61c$Score segments on pain, budget, access and your advantage. Talk to buyers, not friends. Drop segments with no budget.$t61c$, $t61d$Choosing a niche with evidence$t61d$, $t61e$Score three niches with evidence from five buyer conversations and choose one.$t61e$, $t61f$[{"criterion": "Scoring reasoned", "max_points": 35, "guidance": "Criteria."}, {"criterion": "Real conversations", "max_points": 40, "guidance": "Five."}, {"criterion": "Decision clear", "max_points": 25, "guidance": "Justified."}]$t61f$::jsonb, 45, 'text', false, false),
  (62, $t62a$Building a repeatable delivery process$t62a$, $t62b$Turn ad-hoc work into a system.$t62b$, $t62c$Document steps, templates, quality checks, timings and handoffs so the work is consistent and could be delegated.$t62c$, $t62d$Building a repeatable delivery process$t62d$, $t62e$Write a delivery playbook for your main service.$t62e$, $t62f$[{"criterion": "Steps clear", "max_points": 40, "guidance": "Complete."}, {"criterion": "Quality checks", "max_points": 30, "guidance": "Built in."}, {"criterion": "Delegable", "max_points": 30, "guidance": "Others could use."}]$t62f$::jsonb, 45, 'text', false, false),
  (63, $t63a$Financial planning and pricing power$t63a$, $t63b$Plan cash and margins.$t63b$, $t63c$Forecast income, costs, tax and buffers for 12 months. Test price rises and a slow month. Get an accountant's advice. This is not financial advice.$t63c$, $t63d$Financial planning and pricing power$t63d$, $t63e$Build a 12-month cash forecast with a slow-month scenario.$t63e$, $t63f$[{"criterion": "Forecast complete", "max_points": 40, "guidance": "Realistic."}, {"criterion": "Scenario tested", "max_points": 35, "guidance": "Slow month."}, {"criterion": "Advice noted", "max_points": 25, "guidance": "Limits."}]$t63f$::jsonb, 60, 'text', false, false),
  (64, $t64a$Sales systems and pipelines$t64a$, $t64b$Track and improve conversion.$t64b$, $t64c$Define stages, track leads, conversion and time to close, and follow up on a schedule.$t64c$, $t64d$Sales systems and pipelines$t64d$, $t64e$Design a pipeline with stages, metrics and a follow-up cadence and log ten example leads.$t64e$, $t64f$[{"criterion": "Stages defined", "max_points": 35, "guidance": "Clear."}, {"criterion": "Metrics", "max_points": 35, "guidance": "Tracked."}, {"criterion": "Follow-up", "max_points": 30, "guidance": "Cadence."}]$t64f$::jsonb, 45, 'text', false, false),
  (65, $t65a$Expert project 1: an operating system for your business$t65a$, $t65b$Deliver niche, playbook, finance and sales system.$t65b$, $t65c$Show Module 1. Deliver your **business operating system**: niche evidence, delivery playbook, cash forecast and sales pipeline.

Your work is scored on the rubric below. You can revise and resubmit.$t65c$, $t65d$Expert project 1: an operating system for your business$t65d$, $t65e$Submit all four.$t65e$, $t65f$[{"criterion": "Niche evidence", "max_points": 25, "guidance": "Real."}, {"criterion": "Playbook", "max_points": 25, "guidance": "Usable."}, {"criterion": "Financial realism", "max_points": 25, "guidance": "Sound."}, {"criterion": "Sales system", "max_points": 25, "guidance": "Working."}]$t65f$::jsonb, 150, 'text', true, false),
  (66, $t66a$Positioning against competitors$t66a$, $t66b$Differentiate honestly.$t66b$, $t66c$Map competitors, their promise and price. Find a gap you can serve better and prove it, without disparaging others or exaggerating.$t66c$, $t66d$Positioning against competitors$t66d$, $t66e$Build a competitor map of five and a positioning statement with proof.$t66e$, $t66f$[{"criterion": "Map accurate", "max_points": 35, "guidance": "Sourced."}, {"criterion": "Gap real", "max_points": 35, "guidance": "Insight."}, {"criterion": "Claims honest", "max_points": 30, "guidance": "Provable."}]$t66f$::jsonb, 45, 'text', false, false),
  (67, $t67a$Content and authority$t67a$, $t67b$Build trust at scale.$t67b$, $t67c$Publish case studies, teaching and research-based content in a consistent voice. Track leads from content. No fake authority.$t67c$, $t67d$Content and authority$t67d$, $t67e$Plan a 90-day authority programme with expected leads and measures.$t67e$, $t67f$[{"criterion": "Programme realistic", "max_points": 35, "guidance": "Feasible."}, {"criterion": "Measures", "max_points": 35, "guidance": "Defined."}, {"criterion": "Integrity", "max_points": 30, "guidance": "Honest."}]$t67f$::jsonb, 45, 'text', false, false),
  (68, $t68a$Partnerships and channels$t68a$, $t68b$Grow through others.$t68b$, $t68c$Choose partner types, design win-win offers, agree written terms and track results.$t68c$, $t68d$Partnerships and channels$t68d$, $t68e$Design a partner programme with terms and metrics.$t68e$, $t68f$[{"criterion": "Win-win", "max_points": 35, "guidance": "Clear."}, {"criterion": "Terms written", "max_points": 35, "guidance": "Fair."}, {"criterion": "Metrics", "max_points": 30, "guidance": "Tracked."}]$t68f$::jsonb, 45, 'text', false, false),
  (69, $t69a$Pricing experiments and packaging$t69a$, $t69b$Test price and offer changes.$t69b$, $t69c$Change one thing, measure win rate and margin, and keep fairness to existing clients.$t69c$, $t69d$Pricing experiments and packaging$t69d$, $t69e$Run a small pricing experiment and report results.$t69e$, $t69f$[{"criterion": "Valid test", "max_points": 40, "guidance": "One change."}, {"criterion": "Results honest", "max_points": 35, "guidance": "Numbers."}, {"criterion": "Decision", "max_points": 25, "guidance": "Made."}]$t69f$::jsonb, 45, 'text', false, false),
  (70, $t70a$Expert project 2: a growth engine$t70a$, $t70b$Deliver positioning, authority, channels and a test.$t70b$, $t70c$Show Module 2. Deliver a **growth engine**: positioning, authority programme, partner programme and pricing test results.

Your work is scored on the rubric below. You can revise and resubmit.$t70c$, $t70d$Expert project 2: a growth engine$t70d$, $t70e$Submit all with evidence.$t70e$, $t70f$[{"criterion": "Positioning", "max_points": 25, "guidance": "Honest."}, {"criterion": "Programmes", "max_points": 30, "guidance": "Practical."}, {"criterion": "Test evidence", "max_points": 25, "guidance": "Real."}, {"criterion": "Ethics", "max_points": 20, "guidance": "Clean."}]$t70f$::jsonb, 150, 'text', true, false),
  (71, $t71a$Hiring and subcontracting$t71a$, $t71b$Add capacity carefully.$t71b$, $t71c$Write clear roles and briefs, trial tasks, fair pay, contracts and quality checks. You remain responsible to clients.$t71c$, $t71d$Hiring and subcontracting$t71d$, $t71e$Write a role brief, trial task and contract outline.$t71e$, $t71f$[{"criterion": "Brief clear", "max_points": 35, "guidance": "Precise."}, {"criterion": "Trial task", "max_points": 35, "guidance": "Fair."}, {"criterion": "Contract", "max_points": 30, "guidance": "Covers key terms."}]$t71f$::jsonb, 45, 'text', false, false),
  (72, $t72a$Legal structure, tax and insurance$t72a$, $t72b$Set up properly.$t72b$, $t72c$Sole trader, company and other structures differ by country. Understand liability, tax registration and insurance; get professional advice. This is not legal or tax advice.$t72c$, $t72d$Legal structure, tax and insurance$t72d$, $t72e$Compare two structures for your situation and list questions for an adviser.$t72e$, $t72f$[{"criterion": "Comparison sound", "max_points": 45, "guidance": "Accurate."}, {"criterion": "Questions good", "max_points": 30, "guidance": "Specific."}, {"criterion": "Advice noted", "max_points": 25, "guidance": "Limits."}]$t72f$::jsonb, 45, 'text', false, false),
  (73, $t73a$Client success and retention$t73a$, $t73b$Keep clients longer.$t73b$, $t73c$Onboarding, check-ins, results reviews and renewal conversations. Measure retention and satisfaction.$t73c$, $t73d$Client success and retention$t73d$, $t73e$Design a client success programme with metrics.$t73e$, $t73f$[{"criterion": "Touchpoints", "max_points": 40, "guidance": "Planned."}, {"criterion": "Metrics", "max_points": 35, "guidance": "Defined."}, {"criterion": "Renewal", "max_points": 25, "guidance": "Handled."}]$t73f$::jsonb, 45, 'text', false, false),
  (74, $t74a$Managing risk and reputation$t74a$, $t74b$Prepare for problems.$t74b$, $t74c$Contracts, backups, incident response and honest communication protect reputation. Prepare a crisis message.$t74c$, $t74d$Managing risk and reputation$t74d$, $t74e$Write a risk register and a crisis message.$t74e$, $t74f$[{"criterion": "Risks real", "max_points": 40, "guidance": "Specific."}, {"criterion": "Response ready", "max_points": 35, "guidance": "Plan."}, {"criterion": "Honest tone", "max_points": 25, "guidance": "Clear."}]$t74f$::jsonb, 45, 'text', false, false),
  (75, $t75a$Expert project 3: a scalable service business$t75a$, $t75b$Deliver hiring, legal, retention and risk plans.$t75b$, $t75c$Show Module 3. Deliver a **scale plan**: subcontracting kit, structure comparison, client success programme and risk plan.

Your work is scored on the rubric below. You can revise and resubmit.$t75c$, $t75d$Expert project 3: a scalable service business$t75d$, $t75e$Submit all parts.$t75e$, $t75f$[{"criterion": "Completeness", "max_points": 25, "guidance": "All parts."}, {"criterion": "Practicality", "max_points": 30, "guidance": "Usable."}, {"criterion": "Risk and legal awareness", "max_points": 25, "guidance": "Realistic."}, {"criterion": "Honesty", "max_points": 20, "guidance": "Limits."}]$t75f$::jsonb, 150, 'text', true, false),
  (76, $t76a$Flagship: define offer and revenue goal$t76a$, $t76b$Set a measurable target.$t76b$, $t76c$Define offer, target clients, revenue goal and timeline.$t76c$, $t76d$Flagship: define offer and revenue goal$t76d$, $t76e$Submit the plan.$t76e$, $t76f$[{"criterion": "Specific", "max_points": 40, "guidance": "Clear."}, {"criterion": "Goal measurable", "max_points": 35, "guidance": "Numbers."}, {"criterion": "Realistic", "max_points": 25, "guidance": "Feasible."}]$t76f$::jsonb, 60, 'text', false, false),
  (77, $t77a$Flagship: win clients$t77a$, $t77b$Run outreach and sales.$t77b$, $t77c$Execute outreach, calls and proposals for 30 days.$t77c$, $t77d$Flagship: win clients$t77d$, $t77e$Submit numbers and lessons.$t77e$, $t77f$[{"criterion": "Real activity", "max_points": 35, "guidance": "Numbers."}, {"criterion": "Conversion", "max_points": 35, "guidance": "Tracked."}, {"criterion": "Learning", "max_points": 30, "guidance": "Applied."}]$t77f$::jsonb, 90, 'text', false, false),
  (78, $t78a$Flagship: deliver and document$t78a$, $t78b$Deliver to clients with process.$t78b$, $t78c$Deliver at least one project with the playbook and record quality checks and feedback.$t78c$, $t78d$Flagship: deliver and document$t78d$, $t78e$Submit delivery evidence and client feedback.$t78e$, $t78f$[{"criterion": "Delivered", "max_points": 35, "guidance": "Done."}, {"criterion": "Quality checks", "max_points": 35, "guidance": "Recorded."}, {"criterion": "Feedback real", "max_points": 30, "guidance": "Client."}]$t78f$::jsonb, 90, 'text', false, false),
  (79, $t79a$Flagship: review the numbers$t79a$, $t79b$Learn from results.$t79b$, $t79c$Compare targets to actuals for revenue, margin, time and satisfaction.$t79c$, $t79d$Flagship: review the numbers$t79d$, $t79e$Submit the review and next actions.$t79e$, $t79f$[{"criterion": "Numbers real", "max_points": 40, "guidance": "Actuals."}, {"criterion": "Analysis honest", "max_points": 35, "guidance": "Frank."}, {"criterion": "Actions", "max_points": 25, "guidance": "Clear."}]$t79f$::jsonb, 60, 'text', false, false),
  (80, $t80a$Expert project 4: the flagship business result$t80a$, $t80b$Deliver a real result.$t80b$, $t80c$Show Module 4. Deliver a **business case study**: goal, actions, results, lessons and next 90 days.

Your work is scored on the rubric below. You can revise and resubmit.$t80c$, $t80d$Expert project 4: the flagship business result$t80d$, $t80e$Submit the case study with evidence.$t80e$, $t80f$[{"criterion": "Results vs goal", "max_points": 30, "guidance": "Measured."}, {"criterion": "Process and quality", "max_points": 25, "guidance": "Documented."}, {"criterion": "Ethics and honesty", "max_points": 25, "guidance": "Clean."}, {"criterion": "Next steps", "max_points": 20, "guidance": "Realistic."}]$t80f$::jsonb, 200, 'text', true, false)
) as v(n, title, objective, lesson_md, skill_focus, assignment_md, rubric, est_minutes, submission_type, ai_evaluate, requires_review)
where t.slug = 'business'
on conflict (track_id, day_number) do nothing;
