-- Business & freelancing, Basic tier (days 1-30). Authored content, UNPUBLISHED until a person reviews it in Admin.
insert into public.day
  (track_id, tier_id, day_number, title, objective, lesson_md, skill_focus, assignment_md, rubric,
   est_minutes, is_published, credit_budget, submission_type, ai_evaluate, requires_review)
select t.id, ti.id, v.n, v.title, v.objective, v.lesson_md, v.skill_focus, v.assignment_md, v.rubric,
       v.est_minutes, false, null, v.submission_type, v.ai_evaluate, v.requires_review
from public.track t
join public.tier ti on ti.track_id = t.id and ti.slug = 'basic'
cross join (values
  (1, $t1a$Turn a skill into an offer$t1a$, $t1b$Describe what you sell, to whom and what changes for them.$t1b$, $t1c$An offer is a specific result for a specific person at a clear price and time. "I make graphics" is a skill; "I make three social posts a week for local cafes" is an offer.

Use AI to speed up your work, not to hide it: be honest with clients about how you use it. [CREAO](https://agent.creao.ai/@Sonofpeace) (referral link) is our recommended tool for delivering and automating client work.$t1c$, $t1d$Turn a skill into an offer$t1d$, $t1e$Write your offer: who, the problem, the result, what is included, delivery time.$t1e$, $t1f$[{"criterion": "Specific person", "max_points": 30, "guidance": "Named."}, {"criterion": "Result clear", "max_points": 40, "guidance": "Outcome."}, {"criterion": "Scope defined", "max_points": 30, "guidance": "Inclusions."}]$t1f$::jsonb, 15, 'text', false, false),
  (2, $t2a$Know your customer$t2a$, $t2b$Understand one customer type deeply.$t2b$, $t2c$Describe one ideal client: role, goals, frustrations, where they look for help, what a good result is worth to them. Talk to three real people.$t2c$, $t2d$Know your customer$t2d$, $t2e$Submit a one-page customer profile and notes from three real conversations.$t2e$, $t2f$[{"criterion": "Profile specific", "max_points": 35, "guidance": "Real detail."}, {"criterion": "Real conversations", "max_points": 40, "guidance": "Three."}, {"criterion": "Insights used", "max_points": 25, "guidance": "Applied."}]$t2f$::jsonb, 20, 'text', false, false),
  (3, $t3a$Portfolio that proves it$t3a$, $t3b$Build three pieces of proof.$t3b$, $t3c$Show results, not activity: before and after, numbers, short client quotes (with permission). Three strong pieces beat ten weak ones. Be honest about what is practice work.$t3c$, $t3d$Portfolio that proves it$t3d$, $t3e$Plan a portfolio of three pieces: what each shows and how you will label practice work.$t3e$, $t3f$[{"criterion": "Pieces show results", "max_points": 40, "guidance": "Outcomes."}, {"criterion": "Honest labelling", "max_points": 35, "guidance": "Practice vs client."}, {"criterion": "Relevant to the offer", "max_points": 25, "guidance": "Aligned."}]$t3f$::jsonb, 20, 'text', false, false),
  (4, $t4a$Pricing basics$t4a$, $t4b$Price by value and cost.$t4b$, $t4c$Estimate hours, tool costs and value to the client. Choose fixed price for clear scopes, hourly for uncertain ones. Do not undercharge to win work: it attracts the wrong clients.$t4c$, $t4d$Pricing basics$t4d$, $t4e$Price your offer three ways (hourly, per project, monthly) and choose one with reasons.$t4e$, $t4f$[{"criterion": "Costs counted", "max_points": 35, "guidance": "Hours and tools."}, {"criterion": "Options compared", "max_points": 35, "guidance": "Three ways."}, {"criterion": "Choice reasoned", "max_points": 30, "guidance": "Justified."}]$t4f$::jsonb, 20, 'text', false, false),
  (5, $t5a$Finding clients honestly$t5a$, $t5b$Reach people who need your offer.$t5b$, $t5c$Start with people you know, communities and direct outreach with a useful, personal message. No spam, no fake reviews, no false claims. Follow platform rules.$t5c$, $t5d$Finding clients honestly$t5d$, $t5e$Write a short outreach message and a list of 10 real potential clients with a reason for each.$t5e$, $t5f$[{"criterion": "Message personal and honest", "max_points": 40, "guidance": "No spam."}, {"criterion": "List realistic", "max_points": 35, "guidance": "Reasons."}, {"criterion": "Follows rules", "max_points": 25, "guidance": "Compliant."}]$t5f$::jsonb, 20, 'text', false, false),
  (6, $t6a$Module project: your offer page$t6a$, $t6b$Deliver a clear one-page offer.$t6b$, $t6c$Show Module 1. Write a **one-page offer**: who it is for, problem, result, what is included, price, process and how to start.

Your work is scored on the rubric below. You can revise and resubmit.$t6c$, $t6d$Module project: your offer page$t6d$, $t6e$Submit the offer page text and your customer profile.$t6e$, $t6f$[{"criterion": "Clear offer", "max_points": 30, "guidance": "Specific."}, {"criterion": "Customer focus", "max_points": 25, "guidance": "Speaks to problem."}, {"criterion": "Honest claims", "max_points": 25, "guidance": "No invented proof."}, {"criterion": "Next step clear", "max_points": 20, "guidance": "Call to action."}]$t6f$::jsonb, 60, 'text', true, false),
  (7, $t7a$Proposals that win$t7a$, $t7b$Write a short proposal.$t7b$, $t7c$A proposal repeats their problem, proposes the solution, scope, timeline, price and next step. Keep to two pages.$t7c$, $t7d$Proposals that win$t7d$, $t7e$Write a proposal for a real or made-up client project.$t7e$, $t7f$[{"criterion": "Problem understood", "max_points": 30, "guidance": "Their words."}, {"criterion": "Scope and price clear", "max_points": 40, "guidance": "Precise."}, {"criterion": "Next step", "max_points": 30, "guidance": "Clear."}]$t7f$::jsonb, 20, 'text', false, false),
  (8, $t8a$Contracts and expectations$t8a$, $t8b$Protect both sides.$t8b$, $t8c$Agree in writing: scope, revisions, payment terms, ownership, confidentiality and AI use. Use a template and get legal advice for larger work. This course is not legal advice.$t8c$, $t8d$Contracts and expectations$t8d$, $t8e$List the terms your contract needs (ten items) with one line on why each matters.$t8e$, $t8f$[{"criterion": "Terms complete", "max_points": 45, "guidance": "Ten."}, {"criterion": "Reasons clear", "max_points": 30, "guidance": "Explained."}, {"criterion": "AI use and ownership", "max_points": 25, "guidance": "Covered."}]$t8f$::jsonb, 20, 'text', false, false),
  (9, $t9a$Onboarding and communication$t9a$, $t9b$Start projects smoothly.$t9b$, $t9c$Send a welcome message, questionnaire, timeline and how you communicate. Set response times. Confirm decisions in writing.$t9c$, $t9d$Onboarding and communication$t9d$, $t9e$Create an onboarding pack: welcome message, questionnaire (8 questions) and timeline.$t9e$, $t9f$[{"criterion": "Questionnaire useful", "max_points": 40, "guidance": "Relevant."}, {"criterion": "Timeline clear", "max_points": 30, "guidance": "Dates."}, {"criterion": "Tone professional", "max_points": 30, "guidance": "Warm and clear."}]$t9f$::jsonb, 20, 'text', false, false),
  (10, $t10a$Delivering with AI, honestly$t10a$, $t10b$Use AI to speed up work without harming quality or trust.$t10b$, $t10c$Use AI for drafts and options, then review, edit and check. Never put confidential client information into tools you have not vetted. Tell clients how you use it if it matters to them.$t10c$, $t10d$Delivering with AI, honestly$t10d$, $t10e$Write your AI use policy for clients (150 words) and your quality checklist (six items).$t10e$, $t10f$[{"criterion": "Policy honest", "max_points": 35, "guidance": "Clear."}, {"criterion": "Confidentiality", "max_points": 35, "guidance": "Protected."}, {"criterion": "Checklist real", "max_points": 30, "guidance": "Six."}]$t10f$::jsonb, 20, 'text', false, false),
  (11, $t11a$Managing revisions and feedback$t11a$, $t11b$Handle feedback calmly.$t11b$, $t11c$Limit rounds, ask for specific feedback, separate taste from goals and record approvals. Say no politely to scope creep and offer a paid option.$t11c$, $t11d$Managing revisions and feedback$t11d$, $t11e$Write three scripts: request specific feedback, decline scope creep, and offer a paid extra.$t11e$, $t11f$[{"criterion": "Scripts polite and clear", "max_points": 50, "guidance": "Useful."}, {"criterion": "Boundaries set", "max_points": 30, "guidance": "Firm."}, {"criterion": "Options offered", "max_points": 20, "guidance": "Constructive."}]$t11f$::jsonb, 20, 'text', false, false),
  (12, $t12a$Module project: a proposal pack$t12a$, $t12b$Deliver a proposal, terms and onboarding.$t12b$, $t12c$Show Module 2. Produce a **proposal pack**: proposal, key terms, onboarding and AI use note.

Your work is scored on the rubric below. You can revise and resubmit.$t12c$, $t12d$Module project: a proposal pack$t12d$, $t12e$Submit the proposal, terms list, onboarding pack and AI policy.$t12e$, $t12f$[{"criterion": "Proposal clear", "max_points": 30, "guidance": "Persuasive."}, {"criterion": "Terms protect both", "max_points": 25, "guidance": "Fair."}, {"criterion": "Onboarding", "max_points": 20, "guidance": "Useful."}, {"criterion": "AI honesty", "max_points": 25, "guidance": "Transparent."}]$t12f$::jsonb, 70, 'text', true, false),
  (13, $t13a$Time and money basics$t13a$, $t13b$Track hours, costs and profit.$t13b$, $t13c$Track time, tool costs and taxes. Keep a simple sheet: income, expenses, tax set-aside. Rules vary by country; check yours.$t13c$, $t13d$Time and money basics$t13d$, $t13e$Build a simple monthly income and cost sheet for your offer with example numbers.$t13e$, $t13f$[{"criterion": "Costs complete", "max_points": 40, "guidance": "All parts."}, {"criterion": "Tax set-aside", "max_points": 30, "guidance": "Considered."}, {"criterion": "Realistic", "max_points": 30, "guidance": "Plausible."}]$t13f$::jsonb, 20, 'text', false, false),
  (14, $t14a$Invoicing and getting paid$t14a$, $t14b$Bill clearly and on time.$t14b$, $t14c$Invoice promptly with clear items, due date and payment method. Ask for a deposit for larger work. Follow up politely.$t14c$, $t14d$Invoicing and getting paid$t14d$, $t14e$Create an invoice template and a three-step follow-up plan.$t14e$, $t14f$[{"criterion": "Invoice clear", "max_points": 45, "guidance": "Complete."}, {"criterion": "Deposit or terms", "max_points": 25, "guidance": "Defined."}, {"criterion": "Follow-up polite", "max_points": 30, "guidance": "Plan."}]$t14f$::jsonb, 20, 'text', false, false),
  (15, $t15a$Systems and templates$t15a$, $t15b$Make repeat work efficient.$t15b$, $t15c$Templates for proposals, briefs, checklists and emails save hours. Automate handoffs where safe.$t15c$, $t15d$Systems and templates$t15d$, $t15e$Build three templates you will reuse and estimate hours saved per month.$t15e$, $t15f$[{"criterion": "Templates useful", "max_points": 45, "guidance": "Practical."}, {"criterion": "Time saved estimated", "max_points": 30, "guidance": "Reasoned."}, {"criterion": "Quality kept", "max_points": 25, "guidance": "Reviewed."}]$t15f$::jsonb, 20, 'text', false, false),
  (16, $t16a$Reputation and referrals$t16a$, $t16b$Earn trust that brings work.$t16b$, $t16c$Deliver well, ask for a testimonial with permission, ask for referrals and share case studies honestly. Never fake reviews.$t16c$, $t16d$Reputation and referrals$t16d$, $t16e$Write a testimonial request and a case-study outline for one project.$t16e$, $t16f$[{"criterion": "Request polite", "max_points": 35, "guidance": "Clear."}, {"criterion": "Case study honest", "max_points": 40, "guidance": "Real."}, {"criterion": "Permission", "max_points": 25, "guidance": "Noted."}]$t16f$::jsonb, 20, 'text', false, false),
  (17, $t17a$Ethics and legal awareness$t17a$, $t17b$Stay on the right side of rules.$t17b$, $t17c$Respect copyright, privacy law, advertising rules and platform terms. Disclose sponsorships. Do not guarantee results you cannot control. Get professional advice for legal matters.$t17c$, $t17d$Ethics and legal awareness$t17d$, $t17e$Write a short risk list for your offer (five risks) with how you reduce each.$t17e$, $t17f$[{"criterion": "Risks real", "max_points": 45, "guidance": "Specific."}, {"criterion": "Mitigations sensible", "max_points": 35, "guidance": "Actionable."}, {"criterion": "Honest limits", "max_points": 20, "guidance": "Advice sought."}]$t17f$::jsonb, 20, 'text', false, false),
  (18, $t18a$Module project: a business in a folder$t18a$, $t18b$Assemble your working business kit.$t18b$, $t18c$Show Module 3. Assemble a **business kit**: offer, portfolio plan, pricing, contract terms, invoice, templates and risk list.

Your work is scored on the rubric below. You can revise and resubmit.$t18c$, $t18d$Module project: a business in a folder$t18d$, $t18e$Submit each part as text or a link to a document.$t18e$, $t18f$[{"criterion": "Completeness", "max_points": 30, "guidance": "All parts."}, {"criterion": "Professionalism", "max_points": 25, "guidance": "Clear."}, {"criterion": "Honesty and ethics", "max_points": 25, "guidance": "Handled."}, {"criterion": "Practicality", "max_points": 20, "guidance": "Usable."}]$t18f$::jsonb, 80, 'text', true, false),
  (19, $t19a$Marketing basics$t19a$, $t19b$Tell people what you do.$t19b$, $t19c$Pick one channel and post consistently: useful posts, examples, behind the scenes. Keep a simple calendar.$t19c$, $t19d$Marketing basics$t19d$, $t19e$Plan four weeks of posts for one channel with the purpose of each.$t19e$, $t19f$[{"criterion": "Purposeful posts", "max_points": 40, "guidance": "Aligned."}, {"criterion": "Realistic cadence", "max_points": 30, "guidance": "Doable."}, {"criterion": "Value for readers", "max_points": 30, "guidance": "Helpful."}]$t19f$::jsonb, 20, 'text', false, false),
  (20, $t20a$Sales conversations$t20a$, $t20b$Run a discovery call.$t20b$, $t20c$Ask about goals, constraints, past attempts, budget and timing. Listen more than you talk. Summarise and confirm next steps.$t20c$, $t20d$Sales conversations$t20d$, $t20e$Write a discovery call script (ten questions) and run a practice call. Submit notes.$t20e$, $t20f$[{"criterion": "Questions open", "max_points": 40, "guidance": "Good."}, {"criterion": "Practice done", "max_points": 35, "guidance": "Real."}, {"criterion": "Summary and next step", "max_points": 25, "guidance": "Clear."}]$t20f$::jsonb, 20, 'text', false, false),
  (21, $t21a$Handling mistakes$t21a$, $t21b$Fix errors and keep trust.$t21b$, $t21c$Tell the client early, own it, fix it and prevent it. Keep a log of lessons.$t21c$, $t21d$Handling mistakes$t21d$, $t21e$Write a message to a client about a missed deadline: honest, specific and with a fix.$t21e$, $t21f$[{"criterion": "Ownership", "max_points": 40, "guidance": "Honest."}, {"criterion": "Fix and timeline", "max_points": 35, "guidance": "Concrete."}, {"criterion": "Prevention", "max_points": 25, "guidance": "Stated."}]$t21f$::jsonb, 20, 'text', false, false),
  (22, $t22a$Growing: saying no and specialising$t22a$, $t22b$Focus to raise quality and price.$t22b$, $t22c$Say no to work that does not fit. Specialise in a client type or result. Raise prices gradually as demand grows.$t22c$, $t22d$Growing: saying no and specialising$t22d$, $t22e$Write your focus statement and three types of work you will decline.$t22e$, $t22f$[{"criterion": "Focus specific", "max_points": 45, "guidance": "Clear."}, {"criterion": "Decline list", "max_points": 30, "guidance": "Concrete."}, {"criterion": "Reasons", "max_points": 25, "guidance": "Explained."}]$t22f$::jsonb, 20, 'text', false, false),
  (23, $t23a$Working with others$t23a$, $t23b$Collaborate and subcontract.$t23b$, $t23c$Bring in others for skills you lack: clear briefs, fair pay, written agreements, credit. You remain responsible to the client.$t23c$, $t23d$Working with others$t23d$, $t23e$Write a brief for a subcontractor and the terms you would agree.$t23e$, $t23f$[{"criterion": "Brief clear", "max_points": 40, "guidance": "Complete."}, {"criterion": "Terms fair", "max_points": 35, "guidance": "Reasonable."}, {"criterion": "Responsibility clear", "max_points": 25, "guidance": "Owned."}]$t23f$::jsonb, 20, 'text', false, false),
  (24, $t24a$Module project: a first-clients plan$t24a$, $t24b$Plan your first 90 days.$t24b$, $t24c$Show Module 4. Write a **90-day plan** to win and deliver your first three clients: outreach, marketing, delivery, money and learning.

Your work is scored on the rubric below. You can revise and resubmit.$t24c$, $t24d$Module project: a first-clients plan$t24d$, $t24e$Submit the plan with weekly actions and measurable targets.$t24e$, $t24f$[{"criterion": "Actionable", "max_points": 30, "guidance": "Weekly actions."}, {"criterion": "Measurable targets", "max_points": 25, "guidance": "Numbers."}, {"criterion": "Realistic", "max_points": 25, "guidance": "Achievable."}, {"criterion": "Ethics and risk", "max_points": 20, "guidance": "Considered."}]$t24f$::jsonb, 70, 'text', true, false),
  (25, $t25a$Capstone 1: choose your offer and customer$t25a$, $t25b$Commit to a specific offer.$t25b$, $t25c$Choose your offer and one customer type. Validate with three conversations.$t25c$, $t25d$Capstone 1: choose your offer and customer$t25d$, $t25e$Submit the offer, customer and conversation notes.$t25e$, $t25f$[{"criterion": "Specific", "max_points": 40, "guidance": "Clear."}, {"criterion": "Validated", "max_points": 40, "guidance": "Real."}, {"criterion": "Viable", "max_points": 20, "guidance": "Feasible."}]$t25f$::jsonb, 20, 'text', false, false),
  (26, $t26a$Capstone 2: build proof$t26a$, $t26b$Create your best portfolio piece.$t26b$, $t26c$Create one strong portfolio piece for a real or made-up client, labelled honestly, with process and result.$t26c$, $t26d$Capstone 2: build proof$t26d$, $t26e$Submit the case study.$t26e$, $t26f$[{"criterion": "Result shown", "max_points": 40, "guidance": "Evidence."}, {"criterion": "Honest labelling", "max_points": 30, "guidance": "Clear."}, {"criterion": "Process explained", "max_points": 30, "guidance": "Steps."}]$t26f$::jsonb, 60, 'text', false, false),
  (27, $t27a$Capstone 3: price and paperwork$t27a$, $t27b$Prepare pricing and terms.$t27b$, $t27c$Set prices, write terms, create an invoice and onboarding.$t27c$, $t27d$Capstone 3: price and paperwork$t27d$, $t27e$Submit pricing sheet, terms, invoice and onboarding.$t27e$, $t27f$[{"criterion": "Pricing reasoned", "max_points": 35, "guidance": "Costs."}, {"criterion": "Terms complete", "max_points": 35, "guidance": "Protective."}, {"criterion": "Onboarding", "max_points": 30, "guidance": "Useful."}]$t27f$::jsonb, 50, 'text', false, false),
  (28, $t28a$Capstone 4: outreach test$t28a$, $t28b$Contact real prospects.$t28b$, $t28c$Send ten honest outreach messages and record results.$t28c$, $t28d$Capstone 4: outreach test$t28d$, $t28e$Submit messages, responses and what you learned.$t28e$, $t28f$[{"criterion": "Real outreach", "max_points": 40, "guidance": "Ten."}, {"criterion": "Honest results", "max_points": 30, "guidance": "Recorded."}, {"criterion": "Learning", "max_points": 30, "guidance": "Applied."}]$t28f$::jsonb, 20, 'text', false, false),
  (29, $t29a$Capstone 5: deliver a pilot project$t29a$, $t29b$Complete a small real project.$t29b$, $t29c$Deliver a small paid or free pilot with a proposal, delivery and feedback.$t29c$, $t29d$Capstone 5: deliver a pilot project$t29d$, $t29e$Submit the proposal, deliverable summary and client feedback.$t29e$, $t29f$[{"criterion": "Delivered", "max_points": 40, "guidance": "Completed."}, {"criterion": "Feedback real", "max_points": 30, "guidance": "Client."}, {"criterion": "Lessons", "max_points": 30, "guidance": "Learned."}]$t29f$::jsonb, 60, 'text', false, false),
  (30, $t30a$Capstone 6: launch pack and 90-day plan$t30a$, $t30b$Assemble your launch pack.$t30b$, $t30c$Assemble offer page, case study, pricing, terms, templates and your 90-day plan. Share in the Discord and ask for one piece of feedback.

Your work is scored on the rubric below. You can revise and resubmit.$t30c$, $t30d$Capstone 6: launch pack and 90-day plan$t30d$, $t30e$Submit the complete launch pack as text or linked documents.$t30e$, $t30f$[{"criterion": "Offer and proof", "max_points": 30, "guidance": "Strong."}, {"criterion": "Business readiness", "max_points": 25, "guidance": "Complete."}, {"criterion": "Ethics and honesty", "max_points": 25, "guidance": "Handled."}, {"criterion": "Plan quality", "max_points": 20, "guidance": "Actionable."}]$t30f$::jsonb, 90, 'text', true, false)
) as v(n, title, objective, lesson_md, skill_focus, assignment_md, rubric, est_minutes, submission_type, ai_evaluate, requires_review)
where t.slug = 'business'
on conflict (track_id, day_number) do nothing;
