-- Audio, music & voice, Pro tier (days 31-60). Authored content, UNPUBLISHED until a person reviews it in Admin.
insert into public.day
  (track_id, tier_id, day_number, title, objective, lesson_md, skill_focus, assignment_md, rubric,
   est_minutes, is_published, credit_budget, submission_type, ai_evaluate, requires_review)
select t.id, ti.id, v.n, v.title, v.objective, v.lesson_md, v.skill_focus, v.assignment_md, v.rubric,
       v.est_minutes, false, null, v.submission_type, v.ai_evaluate, v.requires_review
from public.track t
join public.tier ti on ti.track_id = t.id and ti.slug = 'pro'
cross join (values
  (31, $t31a$Voice direction and performance$t31a$, $t31b$Direct synthetic and human voices for emotion.$t31b$, $t31c$Write direction: tone, pace, emphasis, pauses. Give context lines and generate several takes. Choose takes by emotion fit, not just clarity.$t31c$, $t31d$Voice direction and performance$t31d$, $t31e$Create three takes of a 30-word line with different directions. Submit links and choose one with reasons.

**Sharing audio:** upload (unlisted) and paste the link. Audio is checked by a person.$t31e$, $t31f$[{"criterion": "Directions specific", "max_points": 35, "guidance": "Clear."}, {"criterion": "Takes distinct", "max_points": 35, "guidance": "Different."}, {"criterion": "Choice reasoned", "max_points": 30, "guidance": "Justified."}]$t31f$::jsonb, 35, 'link', false, false),
  (32, $t32a$Multi-voice dialogue and character voices$t32a$, $t32b$Create distinct voices in a scene.$t32b$, $t32c$Give each character a distinct voice, rhythm and vocabulary. Stagger lines, add breaths and overlap sparingly. Only use voices you have rights to.$t32c$, $t32d$Multi-voice dialogue and character voices$t32d$, $t32e$Produce a 45-second two-character scene. Submit link, script and voice rights.

**Sharing audio:** upload (unlisted) and paste the link. Audio is checked by a person.$t32e$, $t32f$[{"criterion": "Voices distinct", "max_points": 40, "guidance": "Clear."}, {"criterion": "Natural exchange", "max_points": 30, "guidance": "Timing."}, {"criterion": "Rights", "max_points": 30, "guidance": "Documented."}]$t32f$::jsonb, 20, 'link', false, false),
  (33, $t33a$Sound design fundamentals$t33a$, $t33b$Build sounds from layers.$t33b$, $t33c$Layer texture, impact and tail. Pitch, filter and reverb shape character. Record real sounds when you can: they beat generic effects.$t33c$, $t33d$Sound design fundamentals$t33d$, $t33e$Design three sounds (UI click, whoosh, impact) with layer notes. Submit links.

**Sharing audio:** upload (unlisted) and paste the link. Audio is checked by a person.$t33e$, $t33f$[{"criterion": "Sounds fit", "max_points": 40, "guidance": "Suitable."}, {"criterion": "Layers explained", "max_points": 30, "guidance": "Notes."}, {"criterion": "Clean", "max_points": 30, "guidance": "No artefacts."}]$t33f$::jsonb, 20, 'link', false, false),
  (34, $t34a$Music structure and arrangement$t34a$, $t34b$Understand how tracks develop.$t34b$, $t34c$Sections: intro, build, main, breakdown, outro. Contrast makes music interesting. When generating, describe sections and transitions, then edit the best parts together.$t34c$, $t34d$Music structure and arrangement$t34d$, $t34e$Create a 60-second track with a clear structure. Submit link, section map and licence.

**Sharing audio:** upload (unlisted) and paste the link. Audio is checked by a person.$t34e$, $t34f$[{"criterion": "Structure clear", "max_points": 40, "guidance": "Sections."}, {"criterion": "Edit smooth", "max_points": 30, "guidance": "Transitions."}, {"criterion": "Licence", "max_points": 30, "guidance": "Documented."}]$t34f$::jsonb, 20, 'link', false, false),
  (35, $t35a$Mixing: EQ, compression, space$t35a$, $t35b$Make a mix clear and balanced.$t35b$, $t35c$Cut clashing frequencies, control dynamics gently and place sounds with reverb and panning. Compare with a professional reference at the same loudness.$t35c$, $t35d$Mixing: EQ, compression, space$t35d$, $t35e$Mix a short piece and compare with a reference. Submit before and after links and notes.

**Sharing audio:** upload (unlisted) and paste the link. Audio is checked by a person.$t35e$, $t35f$[{"criterion": "Clear mix", "max_points": 40, "guidance": "Balanced."}, {"criterion": "Reference compared", "max_points": 30, "guidance": "Used."}, {"criterion": "Moves explained", "max_points": 30, "guidance": "Notes."}]$t35f$::jsonb, 20, 'link', false, false),
  (36, $t36a$Module project: a produced audio spot$t36a$, $t36b$Deliver a 30-second spot with voice, music, effects.$t36b$, $t36c$Show Module 1. Deliver a **30-second audio spot** with directed voice, sound design, music and a clean mix.

A person reviews your work and can ask for revisions.$t36c$, $t36d$Module project: a produced audio spot$t36d$, $t36e$Submit link, script, direction notes and licence list.

**Sharing audio:** upload (unlisted) and paste the link. Audio is checked by a person.$t36e$, $t36f$[{"criterion": "Message clear", "max_points": 25, "guidance": "Understood."}, {"criterion": "Mix quality", "max_points": 30, "guidance": "Clean."}, {"criterion": "Performance", "max_points": 25, "guidance": "Directed."}, {"criterion": "Rights", "max_points": 20, "guidance": "Documented."}]$t36f$::jsonb, 90, 'link', false, true),
  (37, $t37a$Podcast production workflow$t37a$, $t37b$Produce episodes consistently.$t37b$, $t37c$Batch: plan, record, edit, publish, promote. Use templates for outlines, intros and show notes. Keep files organised and backed up.$t37c$, $t37d$Podcast production workflow$t37d$, $t37e$Create a production checklist and time budget for one episode.$t37e$, $t37f$[{"criterion": "Checklist complete", "max_points": 40, "guidance": "Steps."}, {"criterion": "Time realistic", "max_points": 30, "guidance": "Hours."}, {"criterion": "Backups", "max_points": 30, "guidance": "Included."}]$t37f$::jsonb, 30, 'text', false, false),
  (38, $t38a$Interviewing and remote recording$t38a$, $t38b$Get great conversations.$t38b$, $t38c$Research guests, ask open questions, follow up, record separate tracks, and get consent to record and publish.$t38c$, $t38d$Interviewing and remote recording$t38d$, $t38e$Prepare an interview guide (eight questions) and a consent note.$t38e$, $t38f$[{"criterion": "Questions open", "max_points": 40, "guidance": "Good."}, {"criterion": "Consent", "max_points": 35, "guidance": "Clear."}, {"criterion": "Preparation", "max_points": 25, "guidance": "Researched."}]$t38f$::jsonb, 20, 'text', false, false),
  (39, $t39a$Editing for clarity and emotion$t39a$, $t39b$Edit conversations without changing meaning.$t39b$, $t39c$Remove filler and dead air but keep character. Edit for story, not just time. Never alter what someone meant.$t39c$, $t39d$Editing for clarity and emotion$t39d$, $t39e$Edit a 5-minute recording to 3 minutes. Submit both links and a note on your cuts.

**Sharing audio:** upload (unlisted) and paste the link. Audio is checked by a person.$t39e$, $t39f$[{"criterion": "Clear and natural", "max_points": 40, "guidance": "Good."}, {"criterion": "Meaning intact", "max_points": 35, "guidance": "Faithful."}, {"criterion": "Cuts explained", "max_points": 25, "guidance": "Notes."}]$t39f$::jsonb, 20, 'link', false, false),
  (40, $t40a$Audio for video: dialogue, ADR and foley$t40a$, $t40b$Support picture with sound.$t40b$, $t40c$Clean dialogue first, replace bad lines (ADR), add foley for body and object sounds, then ambience and music.$t40c$, $t40d$Audio for video: dialogue, ADR and foley$t40d$, $t40e$Add sound to a silent 20-second clip. Submit link and layer list.

**Sharing audio:** upload (unlisted) and paste the link. Audio is checked by a person.$t40e$, $t40f$[{"criterion": "Convincing", "max_points": 40, "guidance": "Real."}, {"criterion": "Layers listed", "max_points": 30, "guidance": "Notes."}, {"criterion": "Balance", "max_points": 30, "guidance": "Clear."}]$t40f$::jsonb, 20, 'link', false, false),
  (41, $t41a$Mastering and delivery specs$t41a$, $t41b$Deliver to platform standards.$t41b$, $t41c$Master for consistent loudness and tone; check limiter, true peak and formats. Provide stems if requested.$t41c$, $t41d$Mastering and delivery specs$t41d$, $t41e$Master a track and report loudness values and format choices.

**Sharing audio:** upload (unlisted) and paste the link. Audio is checked by a person.$t41e$, $t41f$[{"criterion": "Loudness right", "max_points": 40, "guidance": "Values."}, {"criterion": "Formats", "max_points": 30, "guidance": "Suitable."}, {"criterion": "Quality kept", "max_points": 30, "guidance": "Clean."}]$t41f$::jsonb, 20, 'link', false, false),
  (42, $t42a$Module project: a 5-minute podcast episode$t42a$, $t42b$Deliver a polished episode.$t42b$, $t42c$Show Module 2. Deliver a **5-minute episode** with interview or narration, music, edit, mastering and show notes.

A person reviews your work and can ask for revisions.$t42c$, $t42d$Module project: a 5-minute podcast episode$t42d$, $t42e$Submit link, outline, show notes and licence list.

**Sharing audio:** upload (unlisted) and paste the link. Audio is checked by a person.$t42e$, $t42f$[{"criterion": "Content", "max_points": 30, "guidance": "Engaging."}, {"criterion": "Edit and mix", "max_points": 30, "guidance": "Polished."}, {"criterion": "Show notes", "max_points": 15, "guidance": "Useful."}, {"criterion": "Rights and consent", "max_points": 25, "guidance": "Documented."}]$t42f$::jsonb, 120, 'link', false, true),
  (43, $t43a$Audiobooks and long narration$t43a$, $t43b$Narrate long text consistently.$t43b$, $t43c$Keep voice, pace and pronunciation consistent, use a style sheet for names, record in short sessions and check every chapter. Rights and disclosure of synthetic narration matter.$t43c$, $t43d$Audiobooks and long narration$t43d$, $t43e$Narrate 2 minutes of a public-domain text with a pronunciation sheet.

**Sharing audio:** upload (unlisted) and paste the link. Audio is checked by a person.$t43e$, $t43f$[{"criterion": "Consistent", "max_points": 40, "guidance": "Even."}, {"criterion": "Pronunciation sheet", "max_points": 30, "guidance": "Useful."}, {"criterion": "Rights", "max_points": 30, "guidance": "Public domain."}]$t43f$::jsonb, 35, 'link', false, false),
  (44, $t44a$Jingles and audio branding$t44a$, $t44b$Create a memorable sonic identity.$t44b$, $t44c$Short, simple melodies and distinctive timbres work. Create a logo sting, a bed and a variant. Register or document ownership.$t44c$, $t44d$Jingles and audio branding$t44d$, $t44e$Create a sonic logo with two variants. Submit links and a brief.

**Sharing audio:** upload (unlisted) and paste the link. Audio is checked by a person.$t44e$, $t44f$[{"criterion": "Memorable", "max_points": 40, "guidance": "Simple."}, {"criterion": "Variants", "max_points": 30, "guidance": "Useful."}, {"criterion": "Ownership documented", "max_points": 30, "guidance": "Rights."}]$t44f$::jsonb, 20, 'link', false, false),
  (45, $t45a$Spatial and interactive audio basics$t45a$, $t45b$Understand audio for games and apps.$t45b$, $t45c$Loops, layers and triggers respond to actions. Make loops seamless and adaptive layers switch smoothly.$t45c$, $t45d$Spatial and interactive audio basics$t45d$, $t45e$Create a seamless 10-second loop with an optional layer. Submit links.

**Sharing audio:** upload (unlisted) and paste the link. Audio is checked by a person.$t45e$, $t45f$[{"criterion": "Seamless loop", "max_points": 45, "guidance": "No click."}, {"criterion": "Layer adds", "max_points": 30, "guidance": "Works."}, {"criterion": "Notes", "max_points": 25, "guidance": "Explained."}]$t45f$::jsonb, 20, 'link', false, false),
  (46, $t46a$Localisation and dubbing at scale$t46a$, $t46b$Adapt audio for other languages.$t46b$, $t46c$Translate with a native reviewer, match timing, keep tone, get voice consent and label synthetic voices.$t46c$, $t46d$Localisation and dubbing at scale$t46d$, $t46e$Localise a 30-word script into one language with reviewer notes.$t46e$, $t46f$[{"criterion": "Reviewed by speaker", "max_points": 40, "guidance": "Real."}, {"criterion": "Timing and tone", "max_points": 30, "guidance": "Considered."}, {"criterion": "Consent and labels", "max_points": 30, "guidance": "Handled."}]$t46f$::jsonb, 20, 'text', false, false),
  (47, $t47a$Restoration and cleanup$t47a$, $t47b$Rescue poor recordings.$t47b$, $t47c$Reduce noise, hum and reverb carefully, fix clipping where possible and know when to re-record.$t47c$, $t47d$Restoration and cleanup$t47d$, $t47e$Restore a poor recording. Submit before and after links and steps.

**Sharing audio:** upload (unlisted) and paste the link. Audio is checked by a person.$t47e$, $t47f$[{"criterion": "Improvement", "max_points": 45, "guidance": "Clear."}, {"criterion": "Natural", "max_points": 30, "guidance": "Not over-processed."}, {"criterion": "Steps", "max_points": 25, "guidance": "Listed."}]$t47f$::jsonb, 20, 'link', false, false),
  (48, $t48a$Module project: a branded audio package$t48a$, $t48b$Deliver sonic branding and a narrated piece.$t48b$, $t48c$Show Module 3. Deliver a **branded audio package**: sonic logo, bed, narrated piece and localised line.

A person reviews your work and can ask for revisions.$t48c$, $t48d$Module project: a branded audio package$t48d$, $t48e$Submit links, brief, reviewer notes and licence list.

**Sharing audio:** upload (unlisted) and paste the link. Audio is checked by a person.$t48e$, $t48f$[{"criterion": "Brand consistency", "max_points": 30, "guidance": "One identity."}, {"criterion": "Quality", "max_points": 30, "guidance": "Clean."}, {"criterion": "Localisation", "max_points": 15, "guidance": "Reviewed."}, {"criterion": "Rights", "max_points": 25, "guidance": "Documented."}]$t48f$::jsonb, 120, 'link', false, true),
  (49, $t49a$Pricing and contracts for audio work$t49a$, $t49b$Quote and protect your work.$t49b$, $t49c$Scope by length, edits, revisions, rights and formats. State ownership, AI-tool use and credit in writing.$t49c$, $t49d$Pricing and contracts for audio work$t49d$, $t49e$Write a scope and terms for a 5-minute podcast edit.$t49e$, $t49f$[{"criterion": "Scope clear", "max_points": 40, "guidance": "Precise."}, {"criterion": "Rights and AI use", "max_points": 35, "guidance": "Stated."}, {"criterion": "Price logic", "max_points": 25, "guidance": "Reasoned."}]$t49f$::jsonb, 30, 'text', false, false),
  (50, $t50a$Ethics: voice likeness and deepfakes$t50a$, $t50b$Protect people and yourself.$t50b$, $t50c$Never deceive with cloned voices. Written consent, clear limits on use, labels and takedown handling. Know your platform's synthetic media rules and local laws.$t50c$, $t50d$Ethics: voice likeness and deepfakes$t50d$, $t50e$Write a voice consent form and use policy.$t50e$, $t50f$[{"criterion": "Consent specific", "max_points": 40, "guidance": "Clear."}, {"criterion": "Limits and revocation", "max_points": 35, "guidance": "Defined."}, {"criterion": "Labelling", "max_points": 25, "guidance": "Included."}]$t50f$::jsonb, 20, 'text', false, false),
  (51, $t51a$Accessibility: transcripts, audio description$t51a$, $t51b$Make audio inclusive.$t51b$, $t51c$Provide accurate transcripts, captions and audio description where visuals matter. Use plain language.$t51c$, $t51d$Accessibility: transcripts, audio description$t51d$, $t51e$Create a transcript and an audio-description script for a short piece.$t51e$, $t51f$[{"criterion": "Transcript accurate", "max_points": 45, "guidance": "Proofread."}, {"criterion": "Description useful", "max_points": 35, "guidance": "Helpful."}, {"criterion": "Plain language", "max_points": 20, "guidance": "Clear."}]$t51f$::jsonb, 20, 'text', false, false),
  (52, $t52a$Growing an audience$t52a$, $t52b$Get listeners.$t52b$, $t52c$Consistent schedule, clear promise, useful titles and descriptions, guest and cross-promotion. Read analytics for drop-off points.$t52c$, $t52d$Growing an audience$t52d$, $t52e$Publish or plan three episodes and analyse drop-off points.$t52e$, $t52f$[{"criterion": "Plan realistic", "max_points": 35, "guidance": "Cadence."}, {"criterion": "Analytics used", "max_points": 40, "guidance": "Insight."}, {"criterion": "Titles honest", "max_points": 25, "guidance": "Not clickbait."}]$t52f$::jsonb, 20, 'text', false, false),
  (53, $t53a$Feedback and quality assurance$t53a$, $t53b$Check before release.$t53b$, $t53c$Listen on headphones, speakers and a phone, at night and day; check levels, clicks, pronunciation and rights. Use a release checklist.$t53c$, $t53d$Feedback and quality assurance$t53d$, $t53e$Create a release checklist and apply it to a piece.$t53e$, $t53f$[{"criterion": "Checklist complete", "max_points": 45, "guidance": "Thorough."}, {"criterion": "Applied", "max_points": 35, "guidance": "Evidence."}, {"criterion": "Fixes", "max_points": 20, "guidance": "Made."}]$t53f$::jsonb, 20, 'text', false, false),
  (54, $t54a$Module project: a sellable audio product$t54a$, $t54b$Deliver a product with contract and rights.$t54b$, $t54c$Show Module 4. Deliver an **audio product** (podcast episode or ad set) with terms, consent forms, accessibility files and a release checklist.

A person reviews your work and can ask for revisions.$t54c$, $t54d$Module project: a sellable audio product$t54d$, $t54e$Submit links, terms, consent form, transcript and checklist.

**Sharing audio:** upload (unlisted) and paste the link. Audio is checked by a person.$t54e$, $t54f$[{"criterion": "Audio quality", "max_points": 30, "guidance": "Polished."}, {"criterion": "Ethics and consent", "max_points": 25, "guidance": "Handled."}, {"criterion": "Accessibility", "max_points": 20, "guidance": "Provided."}, {"criterion": "Professionalism", "max_points": 25, "guidance": "Complete."}]$t54f$::jsonb, 120, 'link', false, true),
  (55, $t55a$Pro capstone 1: brief and audience$t55a$, $t55b$Scope an audio project for a client.$t55b$, $t55c$Write the brief: audience, goal, deliverables, formats and schedule.$t55c$, $t55d$Pro capstone 1: brief and audience$t55d$, $t55e$Submit the brief.$t55e$, $t55f$[{"criterion": "Brief clear", "max_points": 50, "guidance": "Complete."}, {"criterion": "Deliverables realistic", "max_points": 30, "guidance": "Doable."}, {"criterion": "Goal measurable", "max_points": 20, "guidance": "Metric."}]$t55f$::jsonb, 30, 'text', false, false),
  (56, $t56a$Pro capstone 2: scripts, briefs and consent$t56a$, $t56b$Prepare content and permissions.$t56b$, $t56c$Write scripts, sound and music briefs, and consent forms for any voices.$t56c$, $t56d$Pro capstone 2: scripts, briefs and consent$t56d$, $t56e$Submit all documents.$t56e$, $t56f$[{"criterion": "Scripts speakable", "max_points": 35, "guidance": "Natural."}, {"criterion": "Briefs specific", "max_points": 35, "guidance": "Detailed."}, {"criterion": "Consent", "max_points": 30, "guidance": "Complete."}]$t56f$::jsonb, 20, 'text', false, false),
  (57, $t57a$Pro capstone 3: produce and record$t57a$, $t57b$Create raw assets.$t57b$, $t57c$Record or generate voice, generate music and design sound.$t57c$, $t57d$Pro capstone 3: produce and record$t57d$, $t57e$Submit asset links and licences.

**Sharing audio:** upload (unlisted) and paste the link. Audio is checked by a person.$t57e$, $t57f$[{"criterion": "Quality assets", "max_points": 45, "guidance": "Clean."}, {"criterion": "On brief", "max_points": 30, "guidance": "Suitable."}, {"criterion": "Licences", "max_points": 25, "guidance": "Documented."}]$t57f$::jsonb, 100, 'link', false, false),
  (58, $t58a$Pro capstone 4: mix and master$t58a$, $t58b$Finish the sound.$t58b$, $t58c$Mix, master and export deliverables with loudness values.$t58c$, $t58d$Pro capstone 4: mix and master$t58d$, $t58e$Submit final links and values.

**Sharing audio:** upload (unlisted) and paste the link. Audio is checked by a person.$t58e$, $t58f$[{"criterion": "Clarity", "max_points": 40, "guidance": "Clean."}, {"criterion": "Loudness right", "max_points": 30, "guidance": "Values."}, {"criterion": "Deliverables", "max_points": 30, "guidance": "Complete."}]$t58f$::jsonb, 100, 'link', false, false),
  (59, $t59a$Pro capstone 5: accessibility, QA and feedback$t59a$, $t59b$Add inclusivity and check.$t59b$, $t59c$Provide transcript, run the release checklist and gather three listeners' feedback.$t59c$, $t59d$Pro capstone 5: accessibility, QA and feedback$t59d$, $t59e$Submit transcript, checklist and feedback with fixes.$t59e$, $t59f$[{"criterion": "Transcript accurate", "max_points": 30, "guidance": "Proofread."}, {"criterion": "Checklist applied", "max_points": 35, "guidance": "Done."}, {"criterion": "Feedback used", "max_points": 35, "guidance": "Fixes."}]$t59f$::jsonb, 20, 'text', false, false),
  (60, $t60a$Pro capstone 6: deliver and present$t60a$, $t60b$Deliver the audio package.$t60b$, $t60c$Deliver the package, usage guide, rights and consent records, and present the decisions. Share in the Discord and ask for one piece of feedback.

A person reviews your work and can ask for revisions.$t60c$, $t60d$Pro capstone 6: deliver and present$t60d$, $t60e$Submit links, usage guide, rights records and a cover note.

**Sharing audio:** upload (unlisted) and paste the link. Audio is checked by a person.$t60e$, $t60f$[{"criterion": "Fits the brief", "max_points": 25, "guidance": "Meets goals."}, {"criterion": "Sound craft", "max_points": 30, "guidance": "Polished."}, {"criterion": "Ethics and rights", "max_points": 25, "guidance": "Handled."}, {"criterion": "Delivery", "max_points": 20, "guidance": "Organised."}]$t60f$::jsonb, 100, 'link', false, true)
) as v(n, title, objective, lesson_md, skill_focus, assignment_md, rubric, est_minutes, submission_type, ai_evaluate, requires_review)
where t.slug = 'audio'
on conflict (track_id, day_number) do nothing;
