-- Research & data, Basic tier (days 1-30). Authored content, UNPUBLISHED until a person reviews it in Admin.
insert into public.day
  (track_id, tier_id, day_number, title, objective, lesson_md, skill_focus, assignment_md, rubric,
   est_minutes, is_published, credit_budget, submission_type, ai_evaluate, requires_review)
select t.id, ti.id, v.n, v.title, v.objective, v.lesson_md, v.skill_focus, v.assignment_md, v.rubric,
       v.est_minutes, false, null, v.submission_type, v.ai_evaluate, v.requires_review
from public.track t
join public.tier ti on ti.track_id = t.id and ti.slug = 'basic'
cross join (values
  (1, $t1a$What AI research help is (and is not)$t1a$, $t1b$Know where AI helps research and where it fails.$t1b$, $t1c$AI is good at explaining, summarising, comparing and planning. It is bad at being a source: it can invent facts and citations. Your rule: **AI finds and explains; you verify.**

Use [CREAO](https://agent.creao.ai/@Sonofpeace) (referral link) as a recommended workspace for research workflows, alongside tools with live search and citations such as Perplexity, Google's NotebookLM, Consensus and ChatGPT search. Always open the sources.$t1c$, $t1d$What AI research help is (and is not)$t1d$, $t1e$Ask an AI a factual question in a topic you know well. Submit the question, the answer, and any errors you found.$t1e$, $t1f$[{"criterion": "Question tests knowledge", "max_points": 30, "guidance": "Something you can check."}, {"criterion": "Errors found or verified", "max_points": 45, "guidance": "Honest check."}, {"criterion": "Lesson stated", "max_points": 25, "guidance": "What you learned."}]$t1f$::jsonb, 15, 'text', false, false),
  (2, $t2a$Ask better research questions$t2a$, $t2b$Turn a vague topic into a researchable question.$t2b$, $t2c$Good research questions are specific, answerable and bounded by time, place or group. Break big questions into sub-questions and decide what evidence would answer each.$t2c$, $t2d$Ask better research questions$t2d$, $t2e$Turn a vague topic into one main question and four sub-questions, with the evidence type for each.$t2e$, $t2f$[{"criterion": "Question is specific", "max_points": 40, "guidance": "Bounded."}, {"criterion": "Sub-questions useful", "max_points": 35, "guidance": "Cover the topic."}, {"criterion": "Evidence identified", "max_points": 25, "guidance": "Types listed."}]$t2f$::jsonb, 20, 'text', false, false),
  (3, $t3a$Finding and judging sources$t3a$, $t3b$Rate a source's reliability.$t3b$, $t3c$Check who wrote it, when, how they know, whether they have a stake and whether others confirm it. Primary sources (data, papers, official documents) beat commentary. Prefer recent for fast-moving fields.$t3c$, $t3d$Finding and judging sources$t3d$, $t3e$Find five sources for your question. Rate each (author, date, evidence, bias) and mark the best two.$t3e$, $t3f$[{"criterion": "Real, working sources", "max_points": 35, "guidance": "Links."}, {"criterion": "Ratings reasoned", "max_points": 40, "guidance": "Specific."}, {"criterion": "Best two chosen", "max_points": 25, "guidance": "Justified."}]$t3f$::jsonb, 20, 'text', false, false),
  (4, $t4a$Citations and verification$t4a$, $t4b$Never trust an AI citation you have not opened.$t4b$, $t4c$AI can produce fake citations. For each claim: open the source, find the passage, confirm it says what is claimed. Keep a log: claim, source, quote, verified yes/no.$t4c$, $t4d$Citations and verification$t4d$, $t4e$Ask AI for five cited claims on your topic. Verify each and submit your log with results.$t4e$, $t4f$[{"criterion": "Log complete", "max_points": 35, "guidance": "All five."}, {"criterion": "Verification honest", "max_points": 45, "guidance": "Includes failures."}, {"criterion": "Method clear", "max_points": 20, "guidance": "Explained."}]$t4f$::jsonb, 20, 'text', false, false),
  (5, $t5a$Reading papers and reports quickly$t5a$, $t5b$Extract the key points from a long document.$t5b$, $t5c$Read in order: abstract, conclusions, figures, methods. Ask what was studied, on whom, how big the effect, how sure and what limits. Use AI to explain difficult parts, then confirm in the text.$t5c$, $t5d$Reading papers and reports quickly$t5d$, $t5e$Summarise one paper or report in 150 words with question, method, finding, limits. Include the link.$t5e$, $t5f$[{"criterion": "Accurate", "max_points": 45, "guidance": "Matches source."}, {"criterion": "Includes limits", "max_points": 30, "guidance": "Honest."}, {"criterion": "Clear", "max_points": 25, "guidance": "Plain language."}]$t5f$::jsonb, 20, 'text', false, false),
  (6, $t6a$Module project: a sourced one-page briefing$t6a$, $t6b$Deliver a briefing you can defend.$t6b$, $t6c$Show Module 1. Produce a **one-page briefing** on a question: key findings, evidence with verified sources, limits and a recommendation.

Your work is scored on the rubric below. You can revise and resubmit.$t6c$, $t6d$Module project: a sourced one-page briefing$t6d$, $t6e$Submit the briefing, the source list with links, and your verification log.$t6e$, $t6f$[{"criterion": "Answers the question", "max_points": 25, "guidance": "Focused."}, {"criterion": "Evidence verified", "max_points": 35, "guidance": "Real sources."}, {"criterion": "Limits honest", "max_points": 20, "guidance": "Stated."}, {"criterion": "Clarity", "max_points": 20, "guidance": "Easy to read."}]$t6f$::jsonb, 60, 'text', true, false),
  (7, $t7a$Data basics: rows, columns, types$t7a$, $t7b$Read a dataset like a researcher.$t7b$, $t7c$A dataset has rows (things), columns (facts about them) and types (number, text, date). Check what each column means, units, missing values and how it was collected.$t7c$, $t7d$Data basics: rows, columns, types$t7d$, $t7e$Find a public dataset, describe its rows, columns, units, missing values and source.$t7e$, $t7f$[{"criterion": "Dataset described", "max_points": 45, "guidance": "Complete."}, {"criterion": "Units and gaps noted", "max_points": 35, "guidance": "Detailed."}, {"criterion": "Source credited", "max_points": 20, "guidance": "Link."}]$t7f$::jsonb, 20, 'text', false, false),
  (8, $t8a$Cleaning data$t8a$, $t8b$Fix common problems before analysis.$t8b$, $t8c$Common problems: duplicates, inconsistent spellings, wrong types, outliers, blanks. Always keep the original and document each change.$t8c$, $t8d$Cleaning data$t8d$, $t8e$Clean a small dataset (30+ rows). Submit a change log with counts (rows before and after, fixes).$t8e$, $t8f$[{"criterion": "Real cleaning", "max_points": 40, "guidance": "Specific fixes."}, {"criterion": "Log with counts", "max_points": 35, "guidance": "Numbers."}, {"criterion": "Original kept", "max_points": 25, "guidance": "Confirmed."}]$t8f$::jsonb, 20, 'text', false, false),
  (9, $t9a$Summary statistics and simple charts$t9a$, $t9b$Describe data honestly.$t9b$, $t9c$Use count, mean, median, min, max and a simple chart. Median resists outliers. Use bar charts for comparisons, lines for time. Start axes at zero for bars.$t9c$, $t9d$Summary statistics and simple charts$t9d$, $t9e$Compute five summary numbers and make two charts from your dataset. Submit results and what each chart shows.$t9e$, $t9f$[{"criterion": "Numbers correct", "max_points": 40, "guidance": "Verify."}, {"criterion": "Charts appropriate", "max_points": 35, "guidance": "Suitable."}, {"criterion": "Interpretation honest", "max_points": 25, "guidance": "Not overclaimed."}]$t9f$::jsonb, 20, 'text', false, false),
  (10, $t10a$Correlation is not causation$t10a$, $t10b$Avoid the classic reasoning traps.$t10b$, $t10c$Two things moving together may share a cause, be coincidence or be reversed. Watch for selection bias, small samples and cherry-picked dates. Ask: what else could explain this?$t10c$, $t10d$Correlation is not causation$t10d$, $t10e$Find a claim in the news that confuses correlation with causation. Explain the flaw and two alternative explanations.$t10e$, $t10f$[{"criterion": "Claim real", "max_points": 25, "guidance": "Sourced."}, {"criterion": "Flaw explained", "max_points": 45, "guidance": "Specific."}, {"criterion": "Alternatives plausible", "max_points": 30, "guidance": "Two."}]$t10f$::jsonb, 20, 'text', false, false),
  (11, $t11a$Using AI to analyse data safely$t11a$, $t11b$Use AI for analysis without leaking or trusting blindly.$t11b$, $t11c$Never upload private or sensitive data to tools you have not checked. Ask AI to show its method and code, then verify results by hand on a sample. Save the steps.$t11c$, $t11d$Using AI to analyse data safely$t11d$, $t11e$Analyse a public dataset with AI help. Submit prompts, results, and a hand-check of at least three numbers.$t11e$, $t11f$[{"criterion": "Method shown", "max_points": 30, "guidance": "Prompts."}, {"criterion": "Hand-check", "max_points": 45, "guidance": "Three numbers."}, {"criterion": "Data safe", "max_points": 25, "guidance": "Public data."}]$t11f$::jsonb, 20, 'text', false, false),
  (12, $t12a$Module project: a data story$t12a$, $t12b$Answer a question with data and charts.$t12b$, $t12c$Show Module 2. Produce a **data story**: question, cleaned public dataset, three findings with charts, limits.

Your work is scored on the rubric below. You can revise and resubmit.$t12c$, $t12d$Module project: a data story$t12d$, $t12e$Submit the question, dataset link, cleaning log, findings (with chart descriptions) and limits.$t12e$, $t12f$[{"criterion": "Question and data fit", "max_points": 25, "guidance": "Suitable."}, {"criterion": "Analysis correct", "max_points": 30, "guidance": "Checked."}, {"criterion": "Honest limits", "max_points": 25, "guidance": "Stated."}, {"criterion": "Clarity", "max_points": 20, "guidance": "Readable."}]$t12f$::jsonb, 75, 'text', true, false),
  (13, $t13a$Comparing options with criteria$t13a$, $t13b$Build a fair comparison table.$t13b$, $t13c$List options, choose criteria that matter, weight them and score with evidence. Show your weights so others can change them.$t13c$, $t13d$Comparing options with criteria$t13d$, $t13e$Compare three options for a real decision using at least four criteria with evidence.$t13e$, $t13f$[{"criterion": "Criteria relevant", "max_points": 35, "guidance": "Sensible."}, {"criterion": "Evidence for each score", "max_points": 40, "guidance": "Cited."}, {"criterion": "Weights shown", "max_points": 25, "guidance": "Transparent."}]$t13f$::jsonb, 20, 'text', false, false),
  (14, $t14a$Competitor and market scans$t14a$, $t14b$Scan a market quickly and accurately.$t14b$, $t14c$List players, offers, prices, strengths and gaps from public sources. Note the date. Do not scrape sites that forbid it and do not use private information.$t14c$, $t14d$Competitor and market scans$t14d$, $t14e$Scan five competitors for a real or made-up product. Submit a table with source links and dates.$t14e$, $t14f$[{"criterion": "Sources public and linked", "max_points": 40, "guidance": "Verified."}, {"criterion": "Table useful", "max_points": 35, "guidance": "Clear."}, {"criterion": "Gaps identified", "max_points": 25, "guidance": "Insights."}]$t14f$::jsonb, 20, 'text', false, false),
  (15, $t15a$Interviews and surveys$t15a$, $t15b$Collect first-hand information well.$t15b$, $t15c$Ask open, neutral questions, avoid leading, sample the people you want to understand and get consent. Summarise patterns, not anecdotes.$t15c$, $t15d$Interviews and surveys$t15d$, $t15e$Write eight interview or survey questions, run three conversations and summarise the patterns.$t15e$, $t15f$[{"criterion": "Questions neutral", "max_points": 35, "guidance": "Open."}, {"criterion": "Real conversations", "max_points": 35, "guidance": "Three."}, {"criterion": "Patterns found", "max_points": 30, "guidance": "Summarised."}]$t15f$::jsonb, 20, 'text', false, false),
  (16, $t16a$Synthesis: from notes to insight$t16a$, $t16b$Combine sources into a point of view.$t16b$, $t16c$Group notes into themes, look for agreement and conflict, then write the insight: what is true, what it means, what to do. Say how confident you are.$t16c$, $t16d$Synthesis: from notes to insight$t16d$, $t16e$Synthesise at least six notes into three insights with confidence levels.$t16e$, $t16f$[{"criterion": "Themes sound", "max_points": 35, "guidance": "Grouped."}, {"criterion": "Insights actionable", "max_points": 40, "guidance": "So what."}, {"criterion": "Confidence stated", "max_points": 25, "guidance": "Honest."}]$t16f$::jsonb, 20, 'text', false, false),
  (17, $t17a$Writing for decision-makers$t17a$, $t17b$Make findings easy to act on.$t17b$, $t17c$Lead with the answer, then evidence, then limits and next steps. One page, plain words, one chart. Give options with trade-offs.$t17c$, $t17d$Writing for decision-makers$t17d$, $t17e$Rewrite a research summary for a busy decision-maker in under 250 words.$t17e$, $t17f$[{"criterion": "Answer first", "max_points": 40, "guidance": "Clear."}, {"criterion": "Concise", "max_points": 30, "guidance": "Tight."}, {"criterion": "Next steps", "max_points": 30, "guidance": "Actionable."}]$t17f$::jsonb, 20, 'text', false, false),
  (18, $t18a$Module project: a decision brief$t18a$, $t18b$Deliver a brief that supports a real choice.$t18b$, $t18c$Show Module 3. Produce a **decision brief**: options, criteria, evidence, insight and recommendation with confidence.

Your work is scored on the rubric below. You can revise and resubmit.$t18c$, $t18d$Module project: a decision brief$t18d$, $t18e$Submit the brief, comparison table, and source list with links.$t18e$, $t18f$[{"criterion": "Fair comparison", "max_points": 30, "guidance": "Transparent."}, {"criterion": "Evidence quality", "max_points": 30, "guidance": "Verified."}, {"criterion": "Recommendation clear", "max_points": 20, "guidance": "Actionable."}, {"criterion": "Confidence and limits", "max_points": 20, "guidance": "Honest."}]$t18f$::jsonb, 75, 'text', true, false),
  (19, $t19a$Research ethics and privacy$t19a$, $t19b$Protect people in your research.$t19b$, $t19c$Get consent, protect identities, store data securely, delete what you do not need and follow the rules of your country and platforms.$t19c$, $t19d$Research ethics and privacy$t19d$, $t19e$Write an ethics checklist (six items) and apply it to one project.$t19e$, $t19f$[{"criterion": "Checklist concrete", "max_points": 40, "guidance": "Six."}, {"criterion": "Applied", "max_points": 35, "guidance": "Real project."}, {"criterion": "Data handling", "max_points": 25, "guidance": "Considered."}]$t19f$::jsonb, 20, 'text', false, false),
  (20, $t20a$Bias and fairness in sources and AI$t20a$, $t20b$Spot and reduce bias.$t20b$, $t20c$Bias enters through who is included, how questions are asked and how AI was trained. Check whose voices are missing and test with different framings.$t20c$, $t20d$Bias and fairness in sources and AI$t20d$, $t20e$Ask an AI the same question three ways and compare answers. Note differences and what they reveal.$t20e$, $t20f$[{"criterion": "Three framings", "max_points": 30, "guidance": "Different."}, {"criterion": "Differences noted", "max_points": 40, "guidance": "Specific."}, {"criterion": "Mitigation", "max_points": 30, "guidance": "What you'd do."}]$t20f$::jsonb, 20, 'text', false, false),
  (21, $t21a$Fact-checking claims fast$t21a$, $t21b$Verify viral claims.$t21b$, $t21c$Trace to the original source, check date and context, search for independent confirmation and reverse-image search for pictures.$t21c$, $t21d$Fact-checking claims fast$t21d$, $t21e$Fact-check one viral claim. Submit the claim, steps, sources and a verdict.$t21e$, $t21f$[{"criterion": "Traced to source", "max_points": 40, "guidance": "Original."}, {"criterion": "Independent confirmation", "max_points": 30, "guidance": "Multiple."}, {"criterion": "Verdict fair", "max_points": 30, "guidance": "Justified."}]$t21f$::jsonb, 20, 'text', false, false),
  (22, $t22a$Tracking topics: alerts and notes$t22a$, $t22b$Keep research organised over time.$t22b$, $t22c$Set up alerts, a notes system with source, date and tags, and a weekly review. Keep a running list of open questions.$t22c$, $t22d$Tracking topics: alerts and notes$t22d$, $t22e$Design your research system: tools, note template, weekly routine.$t22e$, $t22f$[{"criterion": "System practical", "max_points": 45, "guidance": "Usable."}, {"criterion": "Template good", "max_points": 30, "guidance": "Source and date."}, {"criterion": "Routine realistic", "max_points": 25, "guidance": "Sustainable."}]$t22f$::jsonb, 20, 'text', false, false),
  (23, $t23a$Presenting research visually$t23a$, $t23b$Make findings clear at a glance.$t23b$, $t23c$One message per slide or chart, clear labels, honest axes, source line. Remove clutter.$t23c$, $t23d$Presenting research visually$t23d$, $t23e$Present three findings as three clear charts or slides. Submit descriptions with source lines.$t23e$, $t23f$[{"criterion": "Clear messages", "max_points": 40, "guidance": "One each."}, {"criterion": "Honest visuals", "max_points": 35, "guidance": "Axes."}, {"criterion": "Sources shown", "max_points": 25, "guidance": "Credited."}]$t23f$::jsonb, 20, 'text', false, false),
  (24, $t24a$Module project: a research pack$t24a$, $t24b$Deliver a mini research pack on a real question.$t24b$, $t24c$Show Module 4. Produce a **research pack**: question, methods, verified sources, data findings, ethics note and a one-page summary.

Your work is scored on the rubric below. You can revise and resubmit.$t24c$, $t24d$Module project: a research pack$t24d$, $t24e$Submit the pack contents in one document or linked pages.$t24e$, $t24f$[{"criterion": "Rigour", "max_points": 30, "guidance": "Verified."}, {"criterion": "Ethics and bias", "max_points": 25, "guidance": "Handled."}, {"criterion": "Clarity", "max_points": 25, "guidance": "Readable."}, {"criterion": "Usefulness", "max_points": 20, "guidance": "Actionable."}]$t24f$::jsonb, 80, 'text', true, false),
  (25, $t25a$Capstone 1: choose a real question$t25a$, $t25b$Pick a question someone needs answered.$t25b$, $t25c$Choose a real question from a person or organisation (with permission) or a public issue. Define the decision it supports.$t25c$, $t25d$Capstone 1: choose a real question$t25d$, $t25e$Submit the question, the decision and who benefits.$t25e$, $t25f$[{"criterion": "Question real and specific", "max_points": 45, "guidance": "Bounded."}, {"criterion": "Decision defined", "max_points": 30, "guidance": "Clear."}, {"criterion": "Feasible", "max_points": 25, "guidance": "Doable."}]$t25f$::jsonb, 20, 'text', false, false),
  (26, $t26a$Capstone 2: plan the research$t26a$, $t26b$Plan sources, data and methods.$t26b$, $t26c$List sub-questions, sources, data and how you will verify. Include an ethics check.$t26c$, $t26d$Capstone 2: plan the research$t26d$, $t26e$Submit the research plan.$t26e$, $t26f$[{"criterion": "Plan complete", "max_points": 40, "guidance": "All parts."}, {"criterion": "Verification planned", "max_points": 35, "guidance": "Method."}, {"criterion": "Ethics", "max_points": 25, "guidance": "Included."}]$t26f$::jsonb, 20, 'text', false, false),
  (27, $t27a$Capstone 3: collect and verify$t27a$, $t27b$Gather evidence and check it.$t27b$, $t27c$Collect sources, data and interviews. Keep a verification log.$t27c$, $t27d$Capstone 3: collect and verify$t27d$, $t27e$Submit your evidence table and verification log.$t27e$, $t27f$[{"criterion": "Evidence relevant", "max_points": 35, "guidance": "On question."}, {"criterion": "Verified", "max_points": 45, "guidance": "Log."}, {"criterion": "Gaps noted", "max_points": 20, "guidance": "Honest."}]$t27f$::jsonb, 60, 'text', false, false),
  (28, $t28a$Capstone 4: analyse and synthesise$t28a$, $t28b$Turn evidence into insight.$t28b$, $t28c$Analyse data, compare options and synthesise three insights with confidence.$t28c$, $t28d$Capstone 4: analyse and synthesise$t28d$, $t28e$Submit your analysis, charts descriptions and insights.$t28e$, $t28f$[{"criterion": "Analysis correct", "max_points": 40, "guidance": "Checked."}, {"criterion": "Insights actionable", "max_points": 35, "guidance": "So what."}, {"criterion": "Confidence honest", "max_points": 25, "guidance": "Stated."}]$t28f$::jsonb, 60, 'text', false, false),
  (29, $t29a$Capstone 5: write the briefing$t29a$, $t29b$Write for the decision-maker.$t29b$, $t29c$Write a one-page briefing: answer, evidence, options, limits, next steps.$t29c$, $t29d$Capstone 5: write the briefing$t29d$, $t29e$Submit the briefing draft and a peer's feedback.$t29e$, $t29f$[{"criterion": "Answer first", "max_points": 35, "guidance": "Clear."}, {"criterion": "Evidence used well", "max_points": 35, "guidance": "Cited."}, {"criterion": "Feedback used", "max_points": 30, "guidance": "Improved."}]$t29f$::jsonb, 20, 'text', false, false),
  (30, $t30a$Capstone 6: deliver and defend$t30a$, $t30b$Deliver the final pack and defend it.$t30b$, $t30c$Deliver the pack and write a short Q and A defending three choices you made. Share in the Discord and ask for one piece of feedback.

Your work is scored on the rubric below. You can revise and resubmit.$t30c$, $t30d$Capstone 6: deliver and defend$t30d$, $t30e$Submit the final research pack (briefing, evidence table, verification log, ethics note) and the Q and A.$t30e$, $t30f$[{"criterion": "Answers the question", "max_points": 25, "guidance": "Focused."}, {"criterion": "Rigour and verification", "max_points": 30, "guidance": "Checked."}, {"criterion": "Honesty about limits", "max_points": 20, "guidance": "Stated."}, {"criterion": "Clarity and usefulness", "max_points": 25, "guidance": "Actionable."}]$t30f$::jsonb, 90, 'text', true, false)
) as v(n, title, objective, lesson_md, skill_focus, assignment_md, rubric, est_minutes, submission_type, ai_evaluate, requires_review)
where t.slug = 'research'
on conflict (track_id, day_number) do nothing;
