-- Research & data, Pro tier (days 31-60). Authored content, UNPUBLISHED until a person reviews it in Admin.
insert into public.day
  (track_id, tier_id, day_number, title, objective, lesson_md, skill_focus, assignment_md, rubric,
   est_minutes, is_published, credit_budget, submission_type, ai_evaluate, requires_review)
select t.id, ti.id, v.n, v.title, v.objective, v.lesson_md, v.skill_focus, v.assignment_md, v.rubric,
       v.est_minutes, false, null, v.submission_type, v.ai_evaluate, v.requires_review
from public.track t
join public.tier ti on ti.track_id = t.id and ti.slug = 'pro'
cross join (values
  (31, $t31a$Systematic searching$t31a$, $t31b$Search a topic so you do not miss key evidence.$t31b$, $t31c$Plan searches: keywords and synonyms, sources (databases, official sites, preprints), date range and inclusion rules. Record what you searched and found. Using AI to suggest search terms helps; you still run and check the searches.$t31c$, $t31d$Systematic searching$t31d$, $t31e$Run a documented search on a question. Submit the terms, sources searched, dates and the ten most relevant results.$t31e$, $t31f$[{"criterion": "Search planned", "max_points": 35, "guidance": "Terms and sources."}, {"criterion": "Documented", "max_points": 35, "guidance": "Reproducible."}, {"criterion": "Results relevant", "max_points": 30, "guidance": "Ten."}]$t31f$::jsonb, 40, 'text', false, false),
  (32, $t32a$Evaluating evidence quality$t32a$, $t32b$Rank evidence by strength.$t32b$, $t32c$Strong evidence: large, well-designed studies, systematic reviews, official statistics. Weak: anecdotes, single small studies, undisclosed methods. Note sample size, method, funding and conflicts.$t32c$, $t32d$Evaluating evidence quality$t32d$, $t32e$Grade six sources by strength with reasons and a summary of what the strongest say.$t32e$, $t32f$[{"criterion": "Grading reasoned", "max_points": 45, "guidance": "Criteria."}, {"criterion": "Conflicts noted", "max_points": 25, "guidance": "Considered."}, {"criterion": "Summary accurate", "max_points": 30, "guidance": "Faithful."}]$t32f$::jsonb, 20, 'text', false, false),
  (33, $t33a$Comparing conflicting sources$t33a$, $t33b$Handle disagreement honestly.$t33b$, $t33c$When sources disagree, compare definitions, populations, dates and methods. Do not average blindly; explain why they differ and which you trust more.$t33c$, $t33d$Comparing conflicting sources$t33d$, $t33e$Find two conflicting sources and explain the disagreement and your judgement.$t33e$, $t33f$[{"criterion": "Real conflict", "max_points": 25, "guidance": "Genuine."}, {"criterion": "Reasons found", "max_points": 45, "guidance": "Method differences."}, {"criterion": "Judgement fair", "max_points": 30, "guidance": "Justified."}]$t33f$::jsonb, 20, 'text', false, false),
  (34, $t34a$Statistics for non-statisticians$t34a$, $t34b$Read numbers critically.$t34b$, $t34c$Know averages vs medians, percent vs percentage points, absolute vs relative risk, confidence intervals and sample size. Always ask: compared with what?$t34c$, $t34d$Statistics for non-statisticians$t34d$, $t34e$Analyse a news statistic: what it says, what it hides, and the right comparison.$t34e$, $t34f$[{"criterion": "Correct concepts", "max_points": 40, "guidance": "Accurate."}, {"criterion": "Hidden context found", "max_points": 35, "guidance": "Insight."}, {"criterion": "Clear explanation", "max_points": 25, "guidance": "Plain."}]$t34f$::jsonb, 20, 'text', false, false),
  (35, $t35a$Spreadsheets and simple analysis$t35a$, $t35b$Analyse data with sorting, pivots and formulas.$t35b$, $t35c$Use pivots to group and summarise, formulas for percentages and growth, and charts to check patterns. Keep raw data on its own sheet.$t35c$, $t35d$Spreadsheets and simple analysis$t35d$, $t35e$Analyse a public dataset with a pivot and two formulas. Submit the steps and findings.$t35e$, $t35f$[{"criterion": "Steps reproducible", "max_points": 40, "guidance": "Clear."}, {"criterion": "Numbers correct", "max_points": 40, "guidance": "Checked."}, {"criterion": "Raw data kept", "max_points": 20, "guidance": "Confirmed."}]$t35f$::jsonb, 20, 'text', false, false),
  (36, $t36a$Module project: an evidence review$t36a$, $t36b$Deliver a graded review of evidence on a question.$t36b$, $t36c$Show Module 1. Deliver an **evidence review**: search log, graded sources, conflicts, key numbers and a conclusion with confidence.

Your work is scored on the rubric below. You can revise and resubmit.$t36c$, $t36d$Module project: an evidence review$t36d$, $t36e$Submit the review with search log and source table (with links).$t36e$, $t36f$[{"criterion": "Search rigour", "max_points": 25, "guidance": "Documented."}, {"criterion": "Grading and conflicts", "max_points": 30, "guidance": "Reasoned."}, {"criterion": "Conclusion calibrated", "max_points": 25, "guidance": "Confidence."}, {"criterion": "Clarity", "max_points": 20, "guidance": "Readable."}]$t36f$::jsonb, 90, 'text', true, false),
  (37, $t37a$Designing a survey$t37a$, $t37b$Write a survey that measures what you mean.$t37b$, $t37c$Define what you want to know, ask one thing per question, avoid leading or loaded words, pilot with five people and keep it short. Consider who will not respond.$t37c$, $t37d$Designing a survey$t37d$, $t37e$Write a 10-question survey, pilot it with five people and submit the changes you made.$t37e$, $t37f$[{"criterion": "Questions neutral", "max_points": 40, "guidance": "Clear."}, {"criterion": "Pilot done", "max_points": 35, "guidance": "Five."}, {"criterion": "Bias considered", "max_points": 25, "guidance": "Non-response."}]$t37f$::jsonb, 40, 'text', false, false),
  (38, $t38a$Sampling and bias$t38a$, $t38b$Know who your results speak for.$t38b$, $t38c$Random samples generalise; convenience samples may not. Note who is missing, weight if you can and say plainly what your results do not show.$t38c$, $t38d$Sampling and bias$t38d$, $t38e$Describe your sample, its biases and what claims it supports and does not.$t38e$, $t38f$[{"criterion": "Bias identified", "max_points": 45, "guidance": "Specific."}, {"criterion": "Claims scoped", "max_points": 35, "guidance": "Limits."}, {"criterion": "Sample described", "max_points": 20, "guidance": "Clear."}]$t38f$::jsonb, 20, 'text', false, false),
  (39, $t39a$Qualitative analysis$t39a$, $t39b$Find themes in interviews and comments.$t39b$, $t39c$Read all material, code segments with short labels, group into themes and keep quotes as evidence. Use AI to propose themes, then check them against the text yourself.$t39c$, $t39d$Qualitative analysis$t39d$, $t39e$Analyse ten comments or interview notes. Submit codes, themes and supporting quotes.$t39e$, $t39f$[{"criterion": "Themes grounded", "max_points": 45, "guidance": "Quotes."}, {"criterion": "AI checked by you", "max_points": 30, "guidance": "Verified."}, {"criterion": "Balanced", "max_points": 25, "guidance": "Dissent noted."}]$t39f$::jsonb, 20, 'text', false, false),
  (40, $t40a$Working with messy data$t40a$, $t40b$Clean and combine datasets.$t40b$, $t40c$Standardise names, dates and units; match records carefully; keep a log and count rows before and after. Check for duplicates created by merges.$t40c$, $t40d$Working with messy data$t40d$, $t40e$Merge two datasets and submit a log with counts and problems found.$t40e$, $t40f$[{"criterion": "Merge correct", "max_points": 40, "guidance": "Verified."}, {"criterion": "Log with counts", "max_points": 35, "guidance": "Numbers."}, {"criterion": "Problems found", "max_points": 25, "guidance": "Honest."}]$t40f$::jsonb, 20, 'text', false, false),
  (41, $t41a$Visualising uncertainty$t41a$, $t41b$Show what you do not know.$t41b$, $t41c$Use ranges, error bars, notes on data quality and plain-language caveats. Avoid false precision.$t41c$, $t41d$Visualising uncertainty$t41d$, $t41e$Make a chart with uncertainty shown and a caption stating the limits.$t41e$, $t41f$[{"criterion": "Uncertainty visible", "max_points": 45, "guidance": "Shown."}, {"criterion": "Caption honest", "max_points": 35, "guidance": "Limits."}, {"criterion": "Readable", "max_points": 20, "guidance": "Clear."}]$t41f$::jsonb, 20, 'text', false, false),
  (42, $t42a$Module project: a primary research study$t42a$, $t42b$Run a small survey or interview study.$t42b$, $t42c$Show Module 2. Run a **small study** (survey or interviews, at least 15 responses) and report method, results and limits.

Your work is scored on the rubric below. You can revise and resubmit.$t42c$, $t42d$Module project: a primary research study$t42d$, $t42e$Submit questions, sample description, results, themes or charts and limits.$t42e$, $t42f$[{"criterion": "Method sound", "max_points": 30, "guidance": "Neutral."}, {"criterion": "Analysis accurate", "max_points": 30, "guidance": "Correct."}, {"criterion": "Limits honest", "max_points": 20, "guidance": "Stated."}, {"criterion": "Clarity", "max_points": 20, "guidance": "Readable."}]$t42f$::jsonb, 100, 'text', true, false),
  (43, $t43a$Forecasting and scenarios$t43a$, $t43b$Think about the future with humility.$t43b$, $t43c$Base rates first, then adjustments. Write scenarios (low, medium, high) with assumptions and what would change your mind. Track forecasts and score them later.$t43c$, $t43d$Forecasting and scenarios$t43d$, $t43e$Make three forecasts with probabilities and reasons, and set a date to score them.$t43e$, $t43f$[{"criterion": "Base rates used", "max_points": 35, "guidance": "Considered."}, {"criterion": "Scenarios clear", "max_points": 35, "guidance": "Assumptions."}, {"criterion": "Scoring planned", "max_points": 30, "guidance": "Dates."}]$t43f$::jsonb, 35, 'text', false, false),
  (44, $t44a$Market and trend analysis$t44a$, $t44b$Size a market honestly.$t44b$, $t44c$Estimate from the bottom up (customers times price), cross-check top-down, show assumptions and ranges, and cite sources with dates.$t44c$, $t44d$Market and trend analysis$t44d$, $t44e$Estimate the size of a small market bottom-up with a range and sources.$t44e$, $t44f$[{"criterion": "Method sound", "max_points": 40, "guidance": "Bottom-up."}, {"criterion": "Assumptions shown", "max_points": 35, "guidance": "Explicit."}, {"criterion": "Sources dated", "max_points": 25, "guidance": "Cited."}]$t44f$::jsonb, 20, 'text', false, false),
  (45, $t45a$Cost-benefit and decision analysis$t45a$, $t45b$Support a choice with numbers.$t45b$, $t45c$List options, costs and benefits (including risks and time), use ranges and run a what-if. Say what you could not quantify.$t45c$, $t45d$Cost-benefit and decision analysis$t45d$, $t45e$Compare two options with costs, benefits, ranges and a sensitivity test.$t45e$, $t45f$[{"criterion": "Fair comparison", "max_points": 35, "guidance": "Both sides."}, {"criterion": "Ranges and sensitivity", "max_points": 40, "guidance": "Tested."}, {"criterion": "Unquantified noted", "max_points": 25, "guidance": "Honest."}]$t45f$::jsonb, 20, 'text', false, false),
  (46, $t46a$Research workflows with AI$t46a$, $t46b$Build a repeatable process.$t46b$, $t46c$Define stages: question, search, screen, extract, verify, synthesise, write. Use AI at stages where errors are cheap, humans where they matter, and log every AI use.$t46c$, $t46d$Research workflows with AI$t46d$, $t46e$Document your workflow with AI-use log and verification points for one project.$t46e$, $t46f$[{"criterion": "Stages clear", "max_points": 35, "guidance": "Complete."}, {"criterion": "Verification placed", "max_points": 40, "guidance": "Right spots."}, {"criterion": "AI log", "max_points": 25, "guidance": "Recorded."}]$t46f$::jsonb, 20, 'text', false, false),
  (47, $t47a$Peer review and critique$t47a$, $t47b$Critique research fairly and improve your own.$t47b$, $t47c$Check question fit, method, evidence, alternative explanations and overclaiming. Give specific, kind feedback and respond to critique without defensiveness.$t47c$, $t47d$Peer review and critique$t47d$, $t47e$Critique a report (yours or a public one) with five specific points and suggested fixes.$t47e$, $t47f$[{"criterion": "Specific critique", "max_points": 45, "guidance": "Points."}, {"criterion": "Fair", "max_points": 30, "guidance": "Balanced."}, {"criterion": "Fixes suggested", "max_points": 25, "guidance": "Practical."}]$t47f$::jsonb, 20, 'text', false, false),
  (48, $t48a$Module project: a forecast and decision memo$t48a$, $t48b$Deliver a memo with scenarios and a recommendation.$t48b$, $t48c$Show Module 3. Deliver a **decision memo**: options, cost-benefit with ranges, scenarios, recommendation and what would change it.

Your work is scored on the rubric below. You can revise and resubmit.$t48c$, $t48d$Module project: a forecast and decision memo$t48d$, $t48e$Submit the memo with assumptions and sources.$t48e$, $t48f$[{"criterion": "Analysis quality", "max_points": 30, "guidance": "Sound."}, {"criterion": "Uncertainty handled", "max_points": 30, "guidance": "Ranges."}, {"criterion": "Recommendation clear", "max_points": 20, "guidance": "Actionable."}, {"criterion": "Sources", "max_points": 20, "guidance": "Verified."}]$t48f$::jsonb, 90, 'text', true, false),
  (49, $t49a$Reproducibility and documentation$t49a$, $t49b$Let others check your work.$t49b$, $t49c$Keep raw data, a change log, method notes and versions. Someone else should get your result from your files.$t49c$, $t49d$Reproducibility and documentation$t49d$, $t49e$Package one analysis so a peer can reproduce it. Submit the file list and the steps.$t49e$, $t49f$[{"criterion": "Reproducible steps", "max_points": 45, "guidance": "Clear."}, {"criterion": "Files organised", "max_points": 30, "guidance": "Tidy."}, {"criterion": "Peer test", "max_points": 25, "guidance": "Tried."}]$t49f$::jsonb, 35, 'text', false, false),
  (50, $t50a$Ethics: consent, harm and data protection$t50a$, $t50b$Do research that respects people.$t50b$, $t50c$Informed consent, anonymisation, secure storage, minimal collection and a plan for sensitive findings. Know when an ethics review is needed.$t50c$, $t50d$Ethics: consent, harm and data protection$t50d$, $t50e$Write an ethics plan for a study involving people (consent text, storage, anonymisation).$t50e$, $t50f$[{"criterion": "Consent clear", "max_points": 35, "guidance": "Plain."}, {"criterion": "Data protected", "max_points": 40, "guidance": "Concrete."}, {"criterion": "Harm considered", "max_points": 25, "guidance": "Thought through."}]$t50f$::jsonb, 20, 'text', false, false),
  (51, $t51a$Communicating uncertainty to non-experts$t51a$, $t51b$Explain confidence honestly.$t51b$, $t51c$Use plain words for uncertainty (likely, uncertain), give numbers where possible, and separate what is known, likely and unknown.$t51c$, $t51d$Communicating uncertainty to non-experts$t51d$, $t51e$Rewrite a technical finding for a public audience with confidence levels.$t51e$, $t51f$[{"criterion": "Plain language", "max_points": 40, "guidance": "Clear."}, {"criterion": "Confidence clear", "max_points": 35, "guidance": "Levels."}, {"criterion": "Accurate", "max_points": 25, "guidance": "Faithful."}]$t51f$::jsonb, 20, 'text', false, false),
  (52, $t52a$Data storytelling$t52a$, $t52b$Turn results into a narrative.$t52b$, $t52c$Structure: context, question, finding, meaning, action. One message per chart, honest scales, sources shown.$t52c$, $t52d$Data storytelling$t52d$, $t52e$Create a five-part data story from your analysis with sources.$t52e$, $t52f$[{"criterion": "Story structure", "max_points": 35, "guidance": "Clear."}, {"criterion": "Charts honest", "max_points": 40, "guidance": "Accurate."}, {"criterion": "Action stated", "max_points": 25, "guidance": "Next step."}]$t52f$::jsonb, 20, 'text', false, false),
  (53, $t53a$Presenting to stakeholders$t53a$, $t53b$Handle questions and challenge.$t53b$, $t53c$Lead with the answer, prepare for the three hardest questions, be honest about limits and follow up in writing.$t53c$, $t53d$Presenting to stakeholders$t53d$, $t53e$Write a five-minute briefing and the three hardest questions with answers.$t53e$, $t53f$[{"criterion": "Answer first", "max_points": 35, "guidance": "Clear."}, {"criterion": "Hard questions real", "max_points": 40, "guidance": "Tough."}, {"criterion": "Honest limits", "max_points": 25, "guidance": "Stated."}]$t53f$::jsonb, 20, 'text', false, false),
  (54, $t54a$Module project: a stakeholder report$t54a$, $t54b$Deliver a report ready for decision-makers.$t54b$, $t54c$Show Module 4. Deliver a **stakeholder report**: summary, method, findings with uncertainty, ethics note, reproducibility pack.

Your work is scored on the rubric below. You can revise and resubmit.$t54c$, $t54d$Module project: a stakeholder report$t54d$, $t54e$Submit the report and the file list for reproducing your analysis.$t54e$, $t54f$[{"criterion": "Findings sound", "max_points": 30, "guidance": "Accurate."}, {"criterion": "Communication", "max_points": 25, "guidance": "Clear."}, {"criterion": "Ethics and reproducibility", "max_points": 25, "guidance": "Handled."}, {"criterion": "Uncertainty", "max_points": 20, "guidance": "Honest."}]$t54f$::jsonb, 100, 'text', true, false),
  (55, $t55a$Pro capstone 1: define the study$t55a$, $t55b$Scope a real research project.$t55b$, $t55c$Choose a real question for a client or community, define the decision and scope.$t55c$, $t55d$Pro capstone 1: define the study$t55d$, $t55e$Submit question, decision, scope and ethics considerations.$t55e$, $t55f$[{"criterion": "Question real", "max_points": 40, "guidance": "Specific."}, {"criterion": "Decision defined", "max_points": 30, "guidance": "Clear."}, {"criterion": "Ethics considered", "max_points": 30, "guidance": "Noted."}]$t55f$::jsonb, 20, 'text', false, false),
  (56, $t56a$Pro capstone 2: method and plan$t56a$, $t56b$Design the method.$t56b$, $t56c$Write methods: sources, sampling, analysis, verification and timeline.$t56c$, $t56d$Pro capstone 2: method and plan$t56d$, $t56e$Submit the method plan.$t56e$, $t56f$[{"criterion": "Method appropriate", "max_points": 45, "guidance": "Suited."}, {"criterion": "Verification planned", "max_points": 30, "guidance": "Defined."}, {"criterion": "Feasible", "max_points": 25, "guidance": "Realistic."}]$t56f$::jsonb, 20, 'text', false, false),
  (57, $t57a$Pro capstone 3: collect and analyse$t57a$, $t57b$Gather and analyse.$t57b$, $t57c$Collect data or evidence and analyse it with a documented process.$t57c$, $t57d$Pro capstone 3: collect and analyse$t57d$, $t57e$Submit data summary and analysis log.$t57e$, $t57f$[{"criterion": "Data quality", "max_points": 35, "guidance": "Checked."}, {"criterion": "Analysis correct", "max_points": 40, "guidance": "Verified."}, {"criterion": "Log", "max_points": 25, "guidance": "Reproducible."}]$t57f$::jsonb, 80, 'text', false, false),
  (58, $t58a$Pro capstone 4: interpret and stress-test$t58a$, $t58b$Challenge your own conclusion.$t58b$, $t58c$List alternative explanations, test sensitivity and note what would change your conclusion.$t58c$, $t58d$Pro capstone 4: interpret and stress-test$t58d$, $t58e$Submit the challenge log and revised conclusion.$t58e$, $t58f$[{"criterion": "Alternatives real", "max_points": 40, "guidance": "Considered."}, {"criterion": "Sensitivity tested", "max_points": 35, "guidance": "Done."}, {"criterion": "Conclusion calibrated", "max_points": 25, "guidance": "Honest."}]$t58f$::jsonb, 20, 'text', false, false),
  (59, $t59a$Pro capstone 5: write and review$t59a$, $t59b$Draft the report and get critique.$t59b$, $t59c$Draft the report and have one person critique it. Revise.$t59c$, $t59d$Pro capstone 5: write and review$t59d$, $t59e$Submit the critique and your revisions.$t59e$, $t59f$[{"criterion": "Critique real", "max_points": 35, "guidance": "Specific."}, {"criterion": "Revisions", "max_points": 40, "guidance": "Applied."}, {"criterion": "Clarity", "max_points": 25, "guidance": "Better."}]$t59f$::jsonb, 20, 'text', false, false),
  (60, $t60a$Pro capstone 6: deliver and defend$t60a$, $t60b$Deliver the report and defend your choices.$t60b$, $t60c$Deliver the final report, reproducibility pack and a Q and A defending three decisions. Share in the Discord and ask for one piece of feedback.

Your work is scored on the rubric below. You can revise and resubmit.$t60c$, $t60d$Pro capstone 6: deliver and defend$t60d$, $t60e$Submit the final report, file list and Q and A.$t60e$, $t60f$[{"criterion": "Rigour", "max_points": 30, "guidance": "Sound."}, {"criterion": "Honesty about uncertainty", "max_points": 25, "guidance": "Stated."}, {"criterion": "Ethics and reproducibility", "max_points": 25, "guidance": "Handled."}, {"criterion": "Usefulness", "max_points": 20, "guidance": "Actionable."}]$t60f$::jsonb, 100, 'text', true, false)
) as v(n, title, objective, lesson_md, skill_focus, assignment_md, rubric, est_minutes, submission_type, ai_evaluate, requires_review)
where t.slug = 'research'
on conflict (track_id, day_number) do nothing;
