-- AI film & video, Pro tier (days 31-60). Authored content, UNPUBLISHED until a person reviews it in Admin.
insert into public.day
  (track_id, tier_id, day_number, title, objective, lesson_md, skill_focus, assignment_md, rubric,
   est_minutes, is_published, credit_budget, submission_type, ai_evaluate, requires_review)
select t.id, ti.id, v.n, v.title, v.objective, v.lesson_md, v.skill_focus, v.assignment_md, v.rubric,
       v.est_minutes, false, null, v.submission_type, v.ai_evaluate, v.requires_review
from public.track t
join public.tier ti on ti.track_id = t.id and ti.slug = 'pro'
cross join (values
  (31, $t31a$Screenwriting for short form$t31a$, $t31b$Write tight scenes that carry a story.$t31b$, $t31c$Short film needs one character, one want, one turning point. Open late, end early, show through action. Cut any line that does not move the story. Use AI to brainstorm options and test dialogue aloud; the choices are yours.$t31c$, $t31d$Screenwriting for short form$t31d$, $t31e$Write a 2-page script with a clear want, obstacle and turn. Submit the script.$t31e$, $t31f$[{"criterion": "Clear want and turn", "max_points": 40, "guidance": "Story works."}, {"criterion": "Visual and economical", "max_points": 35, "guidance": "Shown."}, {"criterion": "Dialogue natural", "max_points": 25, "guidance": "Speakable."}]$t31f$::jsonb, 40, 'text', false, false),
  (32, $t32a$Directing AI: shot language and continuity$t32a$, $t32b$Keep space, direction and time consistent.$t32b$, $t32c$Respect screen direction, eyelines and continuity of costume and props. Use establishing shots then closer coverage. Continuity errors break belief faster than visual flaws.$t32c$, $t32d$Directing AI: shot language and continuity$t32d$, $t32e$Plan a two-person scene as a shot list with screen direction notes and continuity checks.$t32e$, $t32f$[{"criterion": "Coverage planned", "max_points": 40, "guidance": "Varied."}, {"criterion": "Direction consistent", "max_points": 35, "guidance": "Noted."}, {"criterion": "Continuity checks", "max_points": 25, "guidance": "Listed."}]$t32f$::jsonb, 20, 'text', false, false),
  (33, $t33a$Performance, faces and emotion$t33a$, $t33b$Get believable emotion from generated characters.$t33b$, $t33c$Describe subtle expressions and small actions rather than big emotion. Keep faces at a distance or in profile when models struggle. Reference stills help maintain identity.$t33c$, $t33d$Performance, faces and emotion$t33d$, $t33e$Generate three emotional beats and critique realism. Submit prompts, links and critique.

**Sharing video:** upload (unlisted) and paste the link. Video is checked by a person.$t33e$, $t33f$[{"criterion": "Prompts subtle", "max_points": 35, "guidance": "Specific."}, {"criterion": "Beats readable", "max_points": 35, "guidance": "Emotion clear."}, {"criterion": "Critique honest", "max_points": 30, "guidance": "Flaws named."}]$t33f$::jsonb, 20, 'text', false, false),
  (34, $t34a$Camera movement and lens choices$t34a$, $t34b$Use movement with purpose.$t34b$, $t34c$Push-ins build tension, pans reveal, handheld feels urgent, wide lenses show space and long lenses compress it. Choose one movement per shot and avoid drifting for no reason.$t34c$, $t34d$Camera movement and lens choices$t34d$, $t34e$Create four shots with different movements and note the intended effect of each.

**Sharing video:** upload (unlisted) and paste the link. Video is checked by a person.$t34e$, $t34f$[{"criterion": "Movement purposeful", "max_points": 45, "guidance": "Reasoned."}, {"criterion": "Variety", "max_points": 25, "guidance": "Distinct."}, {"criterion": "Result judged", "max_points": 30, "guidance": "Honest."}]$t34f$::jsonb, 20, 'text', false, false),
  (35, $t35a$Hybrid workflows: mixing real footage and AI$t35a$, $t35b$Combine filmed and generated material.$t35b$, $t35c$Mix your own footage with generated shots (inserts, backgrounds, effects). Match colour, grain and lens feel, and keep the real and generated separate in your project for control. Disclose where needed.$t35c$, $t35d$Hybrid workflows: mixing real footage and AI$t35d$, $t35e$Combine one filmed clip with one generated shot in a matched sequence. Submit the link and matching notes.

**Sharing video:** upload (unlisted) and paste the link. Video is checked by a person.$t35e$, $t35f$[{"criterion": "Matched look", "max_points": 45, "guidance": "Seamless."}, {"criterion": "Notes clear", "max_points": 30, "guidance": "Steps."}, {"criterion": "Disclosure considered", "max_points": 25, "guidance": "Stated."}]$t35f$::jsonb, 20, 'text', false, false),
  (36, $t36a$Module project: a scripted two-minute scene$t36a$, $t36b$Deliver a scripted scene with continuity.$t36b$, $t36c$Show Module 1. Deliver a **2-minute scripted scene** with shot list, continuity checks and consistent characters.

A person reviews your work and can ask for revisions.$t36c$, $t36d$Module project: a scripted two-minute scene$t36d$, $t36e$Submit script, shot list, final link and continuity notes.

**Sharing video:** upload (unlisted) and paste the link. Video is checked by a person.$t36e$, $t36f$[{"criterion": "Story and script", "max_points": 30, "guidance": "Clear."}, {"criterion": "Continuity", "max_points": 25, "guidance": "Consistent."}, {"criterion": "Craft", "max_points": 25, "guidance": "Polished."}, {"criterion": "Planning", "max_points": 20, "guidance": "Shot list."}]$t36f$::jsonb, 120, 'link', false, true),
  (37, $t37a$Sound design for film$t37a$, $t37b$Build a layered soundtrack.$t37b$, $t37c$Layer dialogue, ambience, effects and score. Sound placement sells space. Leave silence for impact and mix dialogue clearly.$t37c$, $t37d$Sound design for film$t37d$, $t37e$Design and mix sound for a 30-second scene. Submit link and layer list.

**Sharing video:** upload (unlisted) and paste the link. Video is checked by a person.$t37e$, $t37f$[{"criterion": "Layers purposeful", "max_points": 40, "guidance": "Clear."}, {"criterion": "Dialogue clear", "max_points": 35, "guidance": "Intelligible."}, {"criterion": "Rights", "max_points": 25, "guidance": "Documented."}]$t37f$::jsonb, 45, 'text', false, false),
  (38, $t38a$Editing rhythm and story structure$t38a$, $t38b$Shape pace and emotion in the edit.$t38b$, $t38c$Cut for story: establish, build, turn, resolve. Vary shot length, hold on emotion, cut away early on boring moments. Watch on a phone and a big screen.$t38c$, $t38d$Editing rhythm and story structure$t38d$, $t38e$Re-edit a sequence for two different paces and compare.

**Sharing video:** upload (unlisted) and paste the link. Video is checked by a person.$t38e$, $t38f$[{"criterion": "Two edits distinct", "max_points": 40, "guidance": "Different."}, {"criterion": "Story clear", "max_points": 35, "guidance": "Works."}, {"criterion": "Analysis", "max_points": 25, "guidance": "Explains."}]$t38f$::jsonb, 20, 'text', false, false),
  (39, $t39a$Colour grading and look$t39a$, $t39b$Create a consistent cinematic look.$t39b$, $t39c$Set contrast, colour balance and saturation, use a limited palette and match shots. Add subtle grain to unify generated footage. Do not over-grade.$t39c$, $t39d$Colour grading and look$t39d$, $t39e$Grade a scene to a defined look (three words). Submit before and after and settings.

**Sharing video:** upload (unlisted) and paste the link. Video is checked by a person.$t39e$, $t39f$[{"criterion": "Look defined", "max_points": 30, "guidance": "Clear."}, {"criterion": "Shots matched", "max_points": 45, "guidance": "Consistent."}, {"criterion": "Restraint", "max_points": 25, "guidance": "Natural."}]$t39f$::jsonb, 20, 'text', false, false),
  (40, $t40a$Voice, dialogue and lip-sync realities$t40a$, $t40b$Know what works and what does not.$t40b$, $t40c$Lip-sync is difficult; cover with cutaways, off-screen dialogue or voiceover. Use consented voices and disclose synthetic voice where expected.$t40c$, $t40d$Voice, dialogue and lip-sync realities$t40d$, $t40e$Create a dialogue moment using cutaways or voiceover. Submit the link and rights notes.

**Sharing video:** upload (unlisted) and paste the link. Video is checked by a person.$t40e$, $t40f$[{"criterion": "Works convincingly", "max_points": 40, "guidance": "Believable."}, {"criterion": "Workaround smart", "max_points": 30, "guidance": "Cutaway."}, {"criterion": "Consent and rights", "max_points": 30, "guidance": "Documented."}]$t40f$::jsonb, 20, 'text', false, false),
  (41, $t41a$Titles, credits and finishing$t41a$, $t41b$Finish like a professional.$t41b$, $t41c$Clean title cards, readable credits (including tools and music sources), captions, safe margins and exports for platform.$t41c$, $t41d$Titles, credits and finishing$t41d$, $t41e$Add titles, credits and captions to a piece. Submit link and credits list.

**Sharing video:** upload (unlisted) and paste the link. Video is checked by a person.$t41e$, $t41f$[{"criterion": "Readable", "max_points": 40, "guidance": "Clear."}, {"criterion": "Credits complete", "max_points": 35, "guidance": "Sources."}, {"criterion": "Captions right", "max_points": 25, "guidance": "Accurate."}]$t41f$::jsonb, 20, 'text', false, false),
  (42, $t42a$Module project: a polished three-minute short$t42a$, $t42b$Deliver a finished short with sound and grade.$t42b$, $t42c$Show Module 2. Deliver a **3-minute short** with mixed sound, colour grade, captions and credits.

A person reviews your work and can ask for revisions.$t42c$, $t42d$Module project: a polished three-minute short$t42d$, $t42e$Submit final link, script, rights list and a note on what you would change.

**Sharing video:** upload (unlisted) and paste the link. Video is checked by a person.$t42e$, $t42f$[{"criterion": "Story", "max_points": 30, "guidance": "Clear."}, {"criterion": "Sound and grade", "max_points": 30, "guidance": "Polished."}, {"criterion": "Finishing", "max_points": 20, "guidance": "Captions, credits."}, {"criterion": "Rights", "max_points": 20, "guidance": "Documented."}]$t42f$::jsonb, 150, 'link', false, true),
  (43, $t43a$Documentary and explainer formats$t43a$, $t43b$Tell true stories responsibly.$t43b$, $t43c$Non-fiction demands accuracy: verify facts, do not fabricate scenes or quotes, label reconstructions and AI imagery clearly, and get permission from real subjects.$t43c$, $t43d$Documentary and explainer formats$t43d$, $t43e$Outline a 2-minute explainer with a verification list and labels for any synthetic visuals.$t43e$, $t43f$[{"criterion": "Facts verified", "max_points": 40, "guidance": "Sourced."}, {"criterion": "Labels honest", "max_points": 35, "guidance": "AI labelled."}, {"criterion": "Structure clear", "max_points": 25, "guidance": "Works."}]$t43f$::jsonb, 35, 'text', false, false),
  (44, $t44a$Ads and brand films$t44a$, $t44b$Make promo video that respects the audience.$t44b$, $t44c$Hook in three seconds, one message, proof, clear call to action. Follow advertising rules; do not mislead with AI visuals of the product.$t44c$, $t44d$Ads and brand films$t44d$, $t44e$Storyboard a 20-second brand ad with hook, message and CTA plus a claims check.$t44e$, $t44f$[{"criterion": "Hook and message", "max_points": 40, "guidance": "Clear."}, {"criterion": "Claims honest", "max_points": 35, "guidance": "Checked."}, {"criterion": "CTA", "max_points": 25, "guidance": "Clear."}]$t44f$::jsonb, 20, 'text', false, false),
  (45, $t45a$Music videos and visual rhythm$t45a$, $t45b$Cut to music.$t45b$, $t45c$Map beats and sections, match visual energy, use repeating motifs. Use licensed music.$t45c$, $t45d$Music videos and visual rhythm$t45d$, $t45e$Cut a 30-second visual to music. Submit link and licence.

**Sharing video:** upload (unlisted) and paste the link. Video is checked by a person.$t45e$, $t45f$[{"criterion": "Sync to beat", "max_points": 40, "guidance": "Tight."}, {"criterion": "Motifs", "max_points": 30, "guidance": "Coherent."}, {"criterion": "Licence", "max_points": 30, "guidance": "Documented."}]$t45f$::jsonb, 20, 'text', false, false),
  (46, $t46a$Client work: briefs, approvals, revisions$t46a$, $t46b$Deliver video for clients.$t46b$, $t46c$Get storyboard approval before generating, limit revision rounds, keep versions and deliver in agreed formats with a rights statement.$t46c$, $t46d$Client work: briefs, approvals, revisions$t46d$, $t46e$Write a video project brief, approval steps and revision terms.$t46e$, $t46f$[{"criterion": "Approval gates", "max_points": 40, "guidance": "Placed."}, {"criterion": "Revision terms", "max_points": 30, "guidance": "Clear."}, {"criterion": "Rights statement", "max_points": 30, "guidance": "Included."}]$t46f$::jsonb, 20, 'text', false, false),
  (47, $t47a$Distribution and audience$t47a$, $t47b$Get films seen.$t47b$, $t47c$Pick platforms, write titles and thumbnails honestly, post consistently and read retention data to learn.$t47c$, $t47d$Distribution and audience$t47d$, $t47e$Publish a piece and report views, retention and one lesson.$t47e$, $t47f$[{"criterion": "Published", "max_points": 30, "guidance": "Real."}, {"criterion": "Numbers real", "max_points": 40, "guidance": "Reported."}, {"criterion": "Lesson", "max_points": 30, "guidance": "Applied."}]$t47f$::jsonb, 20, 'text', false, false),
  (48, $t48a$Module project: a client-style promo$t48a$, $t48b$Deliver a promo from brief to final.$t48b$, $t48c$Show Module 3. Deliver a **client-style promo** with brief, storyboard approval, final video and rights statement.

A person reviews your work and can ask for revisions.$t48c$, $t48d$Module project: a client-style promo$t48d$, $t48e$Submit brief, storyboard links, final link, rights and claims check.

**Sharing video:** upload (unlisted) and paste the link. Video is checked by a person.$t48e$, $t48f$[{"criterion": "Meets brief", "max_points": 30, "guidance": "On target."}, {"criterion": "Craft", "max_points": 25, "guidance": "Polished."}, {"criterion": "Honest claims", "max_points": 25, "guidance": "Checked."}, {"criterion": "Process", "max_points": 20, "guidance": "Approvals."}]$t48f$::jsonb, 120, 'link', false, true),
  (49, $t49a$Advanced consistency: characters across a film$t49a$, $t49b$Maintain identity across many shots.$t49b$, $t49c$Use character sheets, reference images, fixed wording and shot-to-shot checks. Reuse successful seeds and settings. Accept limits and design around them.$t49c$, $t49d$Advanced consistency: characters across a film$t49d$, $t49e$Keep one character consistent across eight shots. Submit sheet, links and checks.

**Sharing video:** upload (unlisted) and paste the link. Video is checked by a person.$t49e$, $t49f$[{"criterion": "Consistency", "max_points": 50, "guidance": "Recognisable."}, {"criterion": "Method documented", "max_points": 30, "guidance": "Steps."}, {"criterion": "Limits handled", "max_points": 20, "guidance": "Workarounds."}]$t49f$::jsonb, 45, 'text', false, false),
  (50, $t50a$Efficiency: pipelines and batching$t50a$, $t50b$Produce faster without losing quality.$t50b$, $t50c$Plan in stills, batch prompts, name files, keep a shot tracker and a credit ledger. Stop when good enough.$t50c$, $t50d$Efficiency: pipelines and batching$t50d$, $t50e$Create a shot tracker for a 10-shot film with status, attempts and credits.$t50e$, $t50f$[{"criterion": "Tracker useful", "max_points": 40, "guidance": "Complete."}, {"criterion": "Credits logged", "max_points": 30, "guidance": "Numbers."}, {"criterion": "Efficiency ideas", "max_points": 30, "guidance": "Practical."}]$t50f$::jsonb, 20, 'text', false, false),
  (51, $t51a$Legal and ethical clearance$t51a$, $t51b$Clear rights before release.$t51b$, $t51c$Audit music, voices, faces, brands, generated assets and tool terms. Get releases from real people. Label synthetic media per platform rules.$t51c$, $t51d$Legal and ethical clearance$t51d$, $t51e$Complete a clearance sheet for a film.$t51e$, $t51f$[{"criterion": "Every asset covered", "max_points": 45, "guidance": "Complete."}, {"criterion": "Releases", "max_points": 30, "guidance": "Handled."}, {"criterion": "Labelling", "max_points": 25, "guidance": "Planned."}]$t51f$::jsonb, 20, 'text', false, false),
  (52, $t52a$Festival and portfolio strategy$t52a$, $t52b$Position your work.$t52b$, $t52c$Pick festivals or showcases that accept AI-assisted work, check rules and fees, prepare a logline, stills and a director's statement that is honest about tools.$t52c$, $t52d$Festival and portfolio strategy$t52d$, $t52e$Prepare a submission pack: logline, statement, stills and target list with rules noted.$t52e$, $t52f$[{"criterion": "Pack complete", "max_points": 40, "guidance": "All parts."}, {"criterion": "Statement honest", "max_points": 35, "guidance": "Tools stated."}, {"criterion": "Targets researched", "max_points": 25, "guidance": "Rules."}]$t52f$::jsonb, 20, 'text', false, false),
  (53, $t53a$Audience testing$t53a$, $t53b$Learn from viewers.$t53b$, $t53c$Screen for five viewers and ask what they understood, felt and wanted. Do not defend; note patterns.$t53c$, $t53d$Audience testing$t53d$, $t53e$Run a screening and submit notes, patterns and two changes.$t53e$, $t53f$[{"criterion": "Real screening", "max_points": 35, "guidance": "Five."}, {"criterion": "Patterns found", "max_points": 35, "guidance": "Insight."}, {"criterion": "Changes", "max_points": 30, "guidance": "Made."}]$t53f$::jsonb, 20, 'text', false, false),
  (54, $t54a$Module project: a festival-ready short$t54a$, $t54b$Deliver a short with clearance and submission pack.$t54b$, $t54c$Show Module 4. Deliver a **festival-ready short** with clearance sheet, submission pack and audience-test changes.

A person reviews your work and can ask for revisions.$t54c$, $t54d$Module project: a festival-ready short$t54d$, $t54e$Submit film link, clearance sheet, submission pack and screening notes.

**Sharing video:** upload (unlisted) and paste the link. Video is checked by a person.$t54e$, $t54f$[{"criterion": "Film quality", "max_points": 30, "guidance": "Polished."}, {"criterion": "Clearance", "max_points": 25, "guidance": "Complete."}, {"criterion": "Pack", "max_points": 20, "guidance": "Professional."}, {"criterion": "Audience learning", "max_points": 25, "guidance": "Applied."}]$t54f$::jsonb, 150, 'link', false, true),
  (55, $t55a$Pro capstone 1: pitch$t55a$, $t55b$Pitch a 3 to 5 minute film.$t55b$, $t55c$Write a pitch: logline, synopsis, audience, look and feasibility with budget.$t55c$, $t55d$Pro capstone 1: pitch$t55d$, $t55e$Submit the pitch and feasibility notes.$t55e$, $t55f$[{"criterion": "Story clear", "max_points": 40, "guidance": "Strong."}, {"criterion": "Look defined", "max_points": 30, "guidance": "Specific."}, {"criterion": "Feasible", "max_points": 30, "guidance": "Realistic."}]$t55f$::jsonb, 35, 'text', false, false),
  (56, $t56a$Pro capstone 2: script and boards$t56a$, $t56b$Prepare production.$t56b$, $t56c$Write the script, shot list and storyboard and character sheets.$t56c$, $t56d$Pro capstone 2: script and boards$t56d$, $t56e$Submit all with image links.

**Sharing video:** upload (unlisted) and paste the link. Video is checked by a person.$t56e$, $t56f$[{"criterion": "Script and shots aligned", "max_points": 40, "guidance": "Consistent."}, {"criterion": "Boards clear", "max_points": 30, "guidance": "Readable."}, {"criterion": "Character sheets", "max_points": 30, "guidance": "Usable."}]$t56f$::jsonb, 20, 'link', false, false),
  (57, $t57a$Pro capstone 3: produce the shots$t57a$, $t57b$Generate and film shots.$t57b$, $t57c$Produce all shots with a tracker and credit ledger.$t57c$, $t57d$Pro capstone 3: produce the shots$t57d$, $t57e$Submit tracker and clip links.

**Sharing video:** upload (unlisted) and paste the link. Video is checked by a person.$t57e$, $t57f$[{"criterion": "Shots match plan", "max_points": 40, "guidance": "Faithful."}, {"criterion": "Tracker", "max_points": 30, "guidance": "Complete."}, {"criterion": "Selects", "max_points": 30, "guidance": "Best takes."}]$t57f$::jsonb, 120, 'text', false, false),
  (58, $t58a$Pro capstone 4: edit, sound and grade$t58a$, $t58b$Assemble and polish.$t58b$, $t58c$Edit, mix, grade, caption and add credits.$t58c$, $t58d$Pro capstone 4: edit, sound and grade$t58d$, $t58e$Submit the cut link and notes.

**Sharing video:** upload (unlisted) and paste the link. Video is checked by a person.$t58e$, $t58f$[{"criterion": "Pace and story", "max_points": 35, "guidance": "Works."}, {"criterion": "Sound and grade", "max_points": 40, "guidance": "Polished."}, {"criterion": "Captions and credits", "max_points": 25, "guidance": "Complete."}]$t58f$::jsonb, 120, 'text', false, false),
  (59, $t59a$Pro capstone 5: screening and clearance$t59a$, $t59b$Test and clear.$t59b$, $t59c$Screen for five viewers, apply changes and complete the clearance sheet.$t59c$, $t59d$Pro capstone 5: screening and clearance$t59d$, $t59e$Submit notes, changes and the clearance sheet.$t59e$, $t59f$[{"criterion": "Feedback used", "max_points": 40, "guidance": "Changes."}, {"criterion": "Clearance complete", "max_points": 40, "guidance": "Every asset."}, {"criterion": "Reflection", "max_points": 20, "guidance": "Honest."}]$t59f$::jsonb, 20, 'text', false, false),
  (60, $t60a$Pro capstone 6: release package$t60a$, $t60b$Release with a full package.$t60b$, $t60c$Deliver the film, credits, statement, clearance sheet and distribution plan. Share in the Discord and ask for one piece of feedback.

A person reviews your work and can ask for revisions.$t60c$, $t60d$Pro capstone 6: release package$t60d$, $t60e$Submit film link, statement, clearance and distribution plan.

**Sharing video:** upload (unlisted) and paste the link. Video is checked by a person.$t60e$, $t60f$[{"criterion": "Film quality", "max_points": 35, "guidance": "Strong."}, {"criterion": "Clearance and ethics", "max_points": 25, "guidance": "Handled."}, {"criterion": "Package", "max_points": 20, "guidance": "Professional."}, {"criterion": "Distribution plan", "max_points": 20, "guidance": "Realistic."}]$t60f$::jsonb, 150, 'link', false, true)
) as v(n, title, objective, lesson_md, skill_focus, assignment_md, rubric, est_minutes, submission_type, ai_evaluate, requires_review)
where t.slug = 'film'
on conflict (track_id, day_number) do nothing;
