-- Second expansion round: 5 more prompts per existing subcategory (5 -> 10,
-- 145 new prompts across all 29 subcategories, 290 total). Broader coverage
-- across writing (academic/professional/social/creative/technical), image
-- (generation/graphic-design/editing/photography-styles/text-in-image), video
-- (shots/camera movement/lighting/drone/style/pacing), and the remaining
-- categories (agents & automation, learning, money & work, audio), so no
-- category is left thin relative to the others.
insert into public.prompts (subcategory_id, title, body, swap_note, difficulty, sort_order)
select s.id, x.title, x.body, x.swap_note, x.difficulty, x.sort_order
from public.prompt_subcategories s
join public.prompt_categories c on c.id = s.category_id
join (values
  -- writing / academic
  ('writing', 'academic', 'Turn research findings into a research question', 'Here are some findings I have: [describe findings]. Help me turn these into one clear, answerable research question.', 'swap: ask for 3 possible research questions if one is not obvious yet.', 'beginner', 6),
  ('writing', 'academic', 'Write an abstract from a finished paper', 'Write a 150-word abstract for this paper, covering the question, method, result, and significance: [paste paper or summary]', 'swap: ask for a shorter version if your target journal has a strict word limit.', 'intermediate', 7),
  ('writing', 'academic', 'Check if a paragraph actually supports the thesis', 'Here is my thesis: [paste it]. Here is a paragraph from my paper: [paste paragraph]. Does this paragraph actually support the thesis, or does it drift?', 'swap: ask for the single sentence that would tie it back if it drifts.', 'intermediate', 8),
  ('writing', 'academic', 'Convert academic writing into a plain-language summary', 'Turn this academic paragraph into something a smart non-expert could understand, without losing the key claim: [paste paragraph]', 'swap: ask for a version short enough for a social media caption.', 'beginner', 9),
  ('writing', 'academic', 'Prepare for likely questions after a presentation', 'I am presenting this argument: [paste argument or summary]. What are the 3 hardest questions an audience might ask, and how should I answer each?', 'swap: ask which question you are least prepared for right now.', 'advanced', 10),
  -- writing / professional
  ('writing', 'professional', 'Draft a difficult one-on-one conversation', 'I need to have a hard conversation with [who] about [topic]. Help me plan how to open it and what to say if they get defensive.', 'swap: ask for a version where you open with a question instead of a statement.', 'intermediate', 6),
  ('writing', 'professional', 'Summarize a long email thread', 'Summarize this email thread into 3 bullet points: what was decided, what is still open, and who owns the next step: [paste thread]', 'swap: ask for a one-line version to forward to someone who has not read the thread.', 'beginner', 7),
  ('writing', 'professional', 'Write a follow-up that actually gets a response', 'I sent this and got no reply: [paste original message]. Write a short, low-pressure follow-up.', 'swap: ask for a version that includes a specific, easy-to-answer question instead of a general check-in.', 'beginner', 8),
  ('writing', 'professional', 'Turn meeting notes into action items', 'Turn these rough meeting notes into a clear list of action items, each with an owner if mentioned: [paste notes]', 'swap: ask it to flag any action item that has no clear owner.', 'intermediate', 9),
  ('writing', 'professional', 'Rewrite feedback to be kinder but still clear', 'This feedback feels too harsh as written: [paste feedback]. Rewrite it to be kind but keep it just as clear, not vaguer.', 'swap: ask for a version that opens with something genuinely positive first.', 'advanced', 10),
  -- writing / social
  ('writing', 'social', 'Write a post that teaches one specific thing', 'Write a short post that teaches one specific, useful thing about [topic], structured as problem, then the fix.', 'swap: ask for a version that opens with the fix and explains the problem after.', 'beginner', 6),
  ('writing', 'social', 'Turn a comment section question into a post', 'People keep asking me this in comments: [paste question]. Turn it into a short post-worthy answer.', 'swap: ask for a version that also invites more questions at the end.', 'intermediate', 7),
  ('writing', 'social', 'Write a post announcing something without sounding like an ad', 'I am announcing [thing]. Write a post about it that does not sound like a sales pitch.', 'swap: ask what specifically would make it sound like a sales pitch, so you can avoid that pattern in future posts.', 'intermediate', 8),
  ('writing', 'social', 'Repurpose a long-form piece into a short post', 'Here is a longer piece I wrote: [paste it]. Pull out the single best idea and turn it into a short standalone post.', 'swap: ask for a second post pulling out a different idea from the same piece.', 'beginner', 9),
  ('writing', 'social', 'Diagnose why a post underperformed', 'This post did worse than expected: [paste post]. Based on the text alone, what is the most likely reason it did not land?', 'swap: ask what you would change about just the first line.', 'advanced', 10),
  -- writing / creative
  ('writing', 'creative', 'Find the emotional core of a story idea', 'Here is a story idea: [describe it]. What is the emotional core this story is really about, underneath the plot?', 'swap: ask how a scene you already have connects to that core, or does not.', 'beginner', 6),
  ('writing', 'creative', 'Raise the stakes in a scene', 'This scene works but feels low-stakes: [paste scene]. What could raise the stakes without changing the basic plot?', 'swap: ask for the smallest possible change that would raise the stakes.', 'intermediate', 7),
  ('writing', 'creative', 'Write a first line that earns the second', 'Write 5 possible first lines for a piece about [topic], each one built to make a reader want the second line.', 'swap: ask which one makes the boldest promise, since that is often the strongest.', 'beginner', 8),
  ('writing', 'creative', 'Check if a twist actually works', 'Here is my twist: [describe twist]. Does it feel earned based on what came before, or does it feel like it comes from nowhere?', 'swap: ask what detail you would need to plant earlier to make it feel earned.', 'advanced', 9),
  ('writing', 'creative', 'Write in a voice that is not your own', 'Rewrite this passage in the voice of someone who is [describe the voice, e.g. blunt and impatient, warm and rambling]: [paste passage]', 'swap: ask for the same passage in the opposite voice, for contrast.', 'intermediate', 10),
  -- writing / technical
  ('writing', 'technical', 'Turn a bug report into a reproducible case', 'Here is a vague bug report: [paste report]. What information is missing to actually reproduce this bug?', 'swap: ask for the exact questions you should ask the person who reported it.', 'beginner', 6),
  ('writing', 'technical', 'Explain a tradeoff to a non-technical stakeholder', 'I need to explain this technical tradeoff to someone non-technical: [describe the tradeoff]. Explain it in terms of what they actually care about.', 'swap: ask for a version that avoids technical jargon entirely.', 'intermediate', 7),
  ('writing', 'technical', 'Get a plain-English summary of an error', 'Summarize what this error is actually about in one sentence, before I dig into fixing it: [paste error]', 'swap: ask if this is a common error with a common cause.', 'beginner', 8),
  ('writing', 'technical', 'Compare two technical approaches for your specific case', 'I am choosing between [approach A] and [approach B] for [your specific situation]. Do not give me a generic comparison, tell me which fits my situation and why.', 'swap: mention your constraints, such as time or team size, so the answer accounts for them.', 'advanced', 9),
  ('writing', 'technical', 'Write a changelog entry a user would actually understand', 'Here is what changed in this update: [describe the change technically]. Write a changelog entry a non-technical user would understand.', 'swap: ask for a version that also explains why the change matters to them.', 'intermediate', 10),

  -- image / generation
  ('image', 'generation', 'Build a prompt from a vague idea', 'I have a vague idea: [describe it loosely]. Ask me 3 questions that would help turn this into a specific, generateable prompt.', 'swap: answer the 3 questions, then ask for the full prompt built from your answers.', 'beginner', 6),
  ('image', 'generation', 'Simplify an overloaded prompt', 'This prompt is not working, probably because it is trying to do too much: [paste prompt]. Simplify it to the 2 most important ideas.', 'swap: ask which of the 2 ideas is more important, in case you need to cut to just one.', 'intermediate', 7),
  ('image', 'generation', 'Generate a series with a consistent thread', 'I want 4 images that feel like they belong to the same series, all showing [subject], each in a different [setting/pose]. Write the 4 prompts with a consistent thread.', 'swap: ask what one element should stay identical across all 4 to hold the series together.', 'advanced', 8),
  ('image', 'generation', 'Get more specific without over-describing', 'This prompt is too vague: [paste prompt]. Add specificity, but keep it under 25 words.', 'swap: ask which single word addition would make the biggest difference.', 'beginner', 9),
  ('image', 'generation', 'Recover from a failed generation without starting over', 'This generation failed in this specific way: [describe what went wrong]. What is the smallest change to the prompt likely to fix just that, without changing everything else?', 'swap: ask for 2 small changes to try, in case the first does not work.', 'intermediate', 10),
  -- image / graphic-design
  ('image', 'graphic-design', 'Choose a font pairing for a specific feel', 'I need a heading and body font pairing that feels [describe feel, e.g. modern and trustworthy]. Suggest a pairing and explain why it fits.', 'swap: ask for an alternative pairing in case the fonts you have access to differ.', 'beginner', 6),
  ('image', 'graphic-design', 'Simplify a cluttered layout', 'This layout feels cluttered: [describe the layout and its elements]. What would you remove or group to simplify it?', 'swap: ask what the single most important element is, so everything else can support it.', 'intermediate', 7),
  ('image', 'graphic-design', 'Choose a color palette for a specific mood', 'I need a color palette that feels [mood]. Suggest 3 to 4 colors and explain the role each one plays.', 'swap: ask for a version that would still work in grayscale, to test if the design relies too much on color.', 'beginner', 8),
  ('image', 'graphic-design', 'Check if a design is accessible', 'Review this design for accessibility: [describe the design, including colors and text sizes]. What is the biggest risk for someone with low vision or color blindness?', 'swap: ask for the single easiest fix to address that risk.', 'advanced', 9),
  ('image', 'graphic-design', 'Explain a design decision to a client', 'A client is questioning why I made [specific design choice]. Help me explain the reasoning in terms of what it does for them, not just aesthetics.', 'swap: ask for a version that also offers a compromise, in case they still disagree.', 'intermediate', 10),
  -- image / editing
  ('image', 'editing', 'Decide what to crop without losing the story', 'I am cropping this photo: [describe the full photo]. What should stay in frame to keep the story of the image intact?', 'swap: ask what the crop would lose if you go tighter than that.', 'beginner', 6),
  ('image', 'editing', 'Edit a batch consistently', 'I have a batch of photos from the same shoot that need to look consistent: [describe the shoot]. What settings should stay identical across all of them?', 'swap: ask what is allowed to vary slightly, like exposure, if lighting changed during the shoot.', 'intermediate', 7),
  ('image', 'editing', 'Fix a photo without it looking edited', 'I want to fix [specific issue] in this photo without it being obvious that it was edited. What is the risk of overdoing this fix?', 'swap: ask for the maximum amount of correction that would still look natural.', 'advanced', 8),
  ('image', 'editing', 'Decide between a few edit options', 'I have a few edit directions for this photo: [describe options]. Which one best serves the purpose of the photo, such as a product listing or a portrait?', 'swap: ask how the answer would change if the purpose were different.', 'beginner', 9),
  ('image', 'editing', 'Match an edit to an existing brand look', 'Here is the general look of my past edits: [describe it]. Edit this new photo to match that same look.', 'swap: ask what specifically makes the look consistent, so you can apply it yourself next time.', 'intermediate', 10),
  -- image / photography-styles
  ('image', 'photography-styles', 'Choose a style that fits the subject', 'I am photographing [subject]. What photography style would suit this subject best, and why?', 'swap: ask for a second, more unexpected style option too.', 'beginner', 6),
  ('image', 'photography-styles', 'Avoid a style that fights the subject', 'I am considering [style] for [subject], but I am not sure it fits. Would this style work against the subject rather than for it?', 'swap: ask what style would work better if this one does not fit.', 'intermediate', 7),
  ('image', 'photography-styles', 'Combine a style with a specific mood', 'I want [style] but with a [mood] feeling rather than its usual mood. How do I keep the style recognizable while shifting the mood?', 'swap: ask which element, light or color, does more work to shift the mood.', 'intermediate', 8),
  ('image', 'photography-styles', 'Study what makes a style recognizable', 'What are the 3 most defining technical choices that make [style] recognizable as that style, not just similar to it?', 'swap: ask which one of the 3 is most often missed by beginners.', 'advanced', 9),
  ('image', 'photography-styles', 'Adapt a style for a different subject', 'I usually shoot [subject A] in [style]. How would that same style need to adapt for [subject B]?', 'swap: ask what would stay exactly the same regardless of subject.', 'beginner', 10),
  -- image / text-in-image
  ('image', 'text-in-image', 'Choose type treatment for a headline graphic', 'I need a headline graphic with the text "[your text]". Should the type be bold and large, or smaller and refined, given the context, such as a sale banner or a quote card?', 'swap: ask how the answer would change for a different platform.', 'beginner', 6),
  ('image', 'text-in-image', 'Fix low-contrast text on a busy background', 'The text "[your text]" is hard to read against this background: [describe background]. What would improve contrast without covering the background entirely?', 'swap: ask about adding a subtle overlay or shadow behind just the text.', 'intermediate', 7),
  ('image', 'text-in-image', 'Decide how much text is too much', 'I am considering putting this much text in an image: [paste the text]. Is that too much for a single graphic?', 'swap: ask for the single most important part to keep if you need to cut it down.', 'beginner', 8),
  ('image', 'text-in-image', 'Design a consistent text style across a series', 'I am making a series of graphics with different text each time. Describe a consistent text treatment, sizing, placement, style, that would work across all of them.', 'swap: ask what should be allowed to vary, like text length, without breaking consistency.', 'advanced', 9),
  ('image', 'text-in-image', 'Choose between text-in-image and a caption', 'I am deciding whether "[your text]" should be baked into the image or left as a caption instead. What is the tradeoff?', 'swap: ask specifically about the platform you are posting to, since that changes the answer.', 'intermediate', 10),

  -- video / shot-types-camera-angles
  ('video', 'shot-types-camera-angles', 'Match shot type to information, not just mood', 'I need the audience to notice [specific detail] in this shot: [describe scene]. What shot type makes that detail clear without over-explaining it?', 'swap: ask what shot type would make the detail too subtle to notice.', 'beginner', 6),
  ('video', 'shot-types-camera-angles', 'Choose an angle that reflects power dynamics', 'This scene involves a power imbalance between [character A] and [character B]. What camera angle for each would reflect that imbalance?', 'swap: ask how the angles should shift if the power balance changes later in the scene.', 'intermediate', 7),
  ('video', 'shot-types-camera-angles', 'Plan coverage for a dialogue scene', 'This is a dialogue scene between 2 people: [describe it]. What shots do I need to cover it properly in the edit: masters, singles, reactions?', 'swap: ask which shot is most essential if you can only get 2.', 'advanced', 8),
  ('video', 'shot-types-camera-angles', 'Avoid an angle that feels like a cliche', 'I am planning to use [angle] for [this kind of moment]. Is this angle overused for this kind of moment, and is there a fresher option?', 'swap: ask what makes the cliche version feel tired, so you know what to avoid repeating.', 'intermediate', 9),
  ('video', 'shot-types-camera-angles', 'Use an unconventional angle on purpose', 'I want to shoot [subject] from an angle that feels different from the obvious choice. Suggest an unconventional angle and what it would communicate.', 'swap: ask what risk comes with that unconventional choice.', 'beginner', 10),
  -- video / camera-movement
  ('video', 'camera-movement', 'Choose between a cut and a move', 'I am deciding whether to cut between 2 shots or use one continuous camera move to connect them: [describe the shots]. Which serves the scene better?', 'swap: ask what the continuous move would cost in terms of production time or complexity.', 'beginner', 6),
  ('video', 'camera-movement', 'Use movement to hide or reveal information', 'I want the camera movement to gradually reveal [what you want revealed] rather than showing it all at once. Describe a movement that does that.', 'swap: ask for a version that reveals it faster, in case the slow reveal drags.', 'intermediate', 7),
  ('video', 'camera-movement', 'Diagnose movement that feels shaky instead of intentional', 'This movement was supposed to feel [intentional quality], but it reads as shaky or amateurish instead: [describe the shot]. What is the likely cause?', 'swap: ask what camera support or technique would fix that specific issue.', 'advanced', 8),
  ('video', 'camera-movement', 'Choose movement speed for the right energy', 'This moment needs [energy level]: [describe moment]. How fast should the camera movement be to match that energy?', 'swap: ask what happens if the movement is slightly slower than that.', 'beginner', 9),
  ('video', 'camera-movement', 'Plan movement that motivates a cut', 'I want this camera movement to lead naturally into a cut to the next shot: [describe the movement and the next shot]. How should the movement be timed to make that cut feel smooth?', 'swap: ask what would make the cut feel jarring instead, so you can avoid it.', 'intermediate', 10),
  -- video / lighting
  ('video', 'lighting', 'Choose lighting that suggests time of day', 'I need this shot to clearly read as [time of day] without a clock or window in frame: [describe scene]. What lighting choices communicate that?', 'swap: ask how the color temperature specifically should shift for that time of day.', 'beginner', 6),
  ('video', 'lighting', 'Fix lighting that flattens a face', 'This lighting setup is flattening the face of the subject: [describe setup]. What adjustment would add dimension back?', 'swap: ask specifically about adding a subtle side light versus adjusting the key light angle.', 'intermediate', 7),
  ('video', 'lighting', 'Use lighting to separate a subject from the background', 'The subject is blending into the background in this shot: [describe the scene]. What lighting technique would separate them?', 'swap: ask about a rim or edge light specifically, if a simple exposure fix does not solve it.', 'intermediate', 8),
  ('video', 'lighting', 'Plan lighting continuity across a scene', 'This scene is shot across a long time span, such as several hours or several days. What do I need to track to keep the lighting looking continuous?', 'swap: ask what the single biggest risk to continuity is in your specific situation.', 'advanced', 9),
  ('video', 'lighting', 'Choose hard versus soft light for the mood', 'Should this moment use hard or soft lighting, given the mood I want: [describe mood]? Explain the difference in feeling, not just the technical setup.', 'swap: ask what a mix of both would communicate instead of choosing one.', 'beginner', 10),
  -- video / drone-aerial
  ('video', 'drone-aerial', 'Decide if a shot actually needs to be aerial', 'I am considering an aerial shot for this moment: [describe moment]. Does this moment actually benefit from being aerial, or would a ground shot work as well?', 'swap: ask what specifically an aerial shot would add that a ground shot could not.', 'beginner', 6),
  ('video', 'drone-aerial', 'Plan for wind and weather in an aerial shot', 'I am planning an aerial shot in [describe conditions]. What should I account for in the plan given those conditions?', 'swap: ask for a backup plan in case conditions are worse than expected on the day.', 'intermediate', 7),
  ('video', 'drone-aerial', 'Use aerial movement to build tension', 'I want this aerial sequence to build tension as it approaches [subject or moment]. Describe how the movement should change as it builds.', 'swap: ask where exactly the tension should peak relative to the sequences length.', 'advanced', 8),
  ('video', 'drone-aerial', 'Choose the right subject size in frame for an aerial shot', 'In this aerial shot, should [subject] be small in a wide frame, or should the shot get closer? Consider what the shot is trying to say.', 'swap: ask how that answer would change if the goal were scale versus intimacy.', 'beginner', 9),
  ('video', 'drone-aerial', 'Combine aerial and ground shots in one sequence', 'I want to cut between an aerial shot and a ground-level shot of the same subject: [describe subject]. What would make that cut feel connected rather than jarring?', 'swap: ask about matching movement direction or speed between the two shots.', 'intermediate', 10),
  -- video / style-mood
  ('video', 'style-mood', 'Choose a color grade direction before shooting', 'I am planning to grade this project toward [describe mood]. What should I be thinking about on set to make that grade easier later?', 'swap: ask specifically about lighting choices that would support that grade.', 'beginner', 6),
  ('video', 'style-mood', 'Avoid a mood that contradicts the story', 'My visual mood is [describe mood], but the story beat here is [describe the story beat]. Do these work together or contradict each other?', 'swap: ask what visual adjustment would resolve the contradiction if there is one.', 'intermediate', 7),
  ('video', 'style-mood', 'Build a visual identity across a whole project', 'I want this whole project to feel visually cohesive, not just individual shots. What are the 3 to 4 visual rules I should apply consistently throughout?', 'swap: ask which rule is most important to protect if you have to break one under time pressure.', 'advanced', 8),
  ('video', 'style-mood', 'Shift mood gradually across a project', 'I want the visual mood to shift gradually from [starting mood] to [ending mood] across the project. How should that shift be paced?', 'swap: ask where the midpoint should sit, visually, between the two moods.', 'intermediate', 9),
  ('video', 'style-mood', 'Match style to genre expectations, or deliberately break them', 'This project is in the [genre] genre. What visual style does that genre usually use, and would breaking that expectation help or hurt this project?', 'swap: ask for an example of a project that broke the expectation successfully.', 'beginner', 10),
  -- video / motion-pacing
  ('video', 'motion-pacing', 'Choose cut length for a specific feeling', 'I want this section to feel [feeling]. Roughly how long should each cut be to support that feeling?', 'swap: ask how that changes if the feeling shifts partway through the section.', 'beginner', 6),
  ('video', 'motion-pacing', 'Use a pacing change to signal a shift', 'I want a pacing change to signal that something is about to shift in this scene: [describe scene]. Where should the pacing change happen, and how?', 'swap: ask if the change should be sudden or gradual, given the tone of the moment.', 'intermediate', 7),
  ('video', 'motion-pacing', 'Diagnose an edit that feels rushed', 'This edit feels rushed even though the individual shots are fine: [describe the edit]. What is the likely cause?', 'swap: ask whether the fix is longer cuts, fewer cuts, or added breathing room between beats.', 'advanced', 8),
  ('video', 'motion-pacing', 'Plan pacing for a montage', 'I am cutting a montage covering [describe what the montage shows]. How should the pacing evolve from the first cut to the last?', 'swap: ask where the single most important beat should land in the montage.', 'intermediate', 9),
  ('video', 'motion-pacing', 'Match pacing to a specific reference feeling', 'I want this edit to feel like [describe a reference feeling, not a specific title]. What pacing pattern usually creates that feeling?', 'swap: ask for the opposite pacing pattern too, so you can see the contrast.', 'beginner', 10),

  -- agents-automation / building-agents
  ('agents-automation', 'building-agents', 'Decide what an agent should never be allowed to do', 'My agent does [task]. What should this agent explicitly never be allowed to do, even if asked?', 'swap: ask how the agent should respond if asked to do one of those things.', 'beginner', 6),
  ('agents-automation', 'building-agents', 'Write a clear success condition for an agent', 'My agent does [task]. Write a clear, checkable definition of what counts as the agent succeeding versus failing.', 'swap: ask for an example input and what a successful output would look like.', 'intermediate', 7),
  ('agents-automation', 'building-agents', 'Reduce scope to make an agent more reliable', 'My agent tries to handle a broad range of cases: [describe them]. What is the smaller, more reliable version of this agent that handles the most common case really well?', 'swap: ask what percentage of real cases that smaller scope would actually cover.', 'advanced', 8),
  ('agents-automation', 'building-agents', 'Give an agent a way to say it does not know', 'My agent currently always gives an answer, even when it should not be confident. How should it express uncertainty instead of guessing?', 'swap: ask what the agent should do next after expressing uncertainty, not just how to phrase it.', 'beginner', 9),
  ('agents-automation', 'building-agents', 'Plan how a human reviews an agent output', 'My agent produces [type of output]. What should a human specifically check before trusting that output?', 'swap: ask which part of the output is riskiest to leave unchecked.', 'intermediate', 10),
  -- agents-automation / workflows
  ('agents-automation', 'workflows', 'Spot a workflow that only works when things go well', 'Walk through this workflow with me: [describe it]. At which step would this workflow struggle if something unexpected happened?', 'swap: ask for the most likely unexpected thing to happen at that step.', 'beginner', 6),
  ('agents-automation', 'workflows', 'Reduce handoffs in a workflow', 'This workflow passes through several different people or tools: [describe it]. Where could handoffs be reduced without losing quality?', 'swap: ask what quality risk comes with reducing that specific handoff.', 'intermediate', 7),
  ('agents-automation', 'workflows', 'Design a workflow that degrades gracefully', 'If a specific part of this workflow failed, what should happen so the whole process does not just stop: [describe workflow]?', 'swap: ask how someone would find out that the degraded path was used.', 'advanced', 8),
  ('agents-automation', 'workflows', 'Turn a one-time process into a repeatable workflow', 'I did [task] once, manually. Help me turn what I did into a repeatable workflow I could hand to someone else.', 'swap: ask what part of what you did was actually judgment, not a repeatable step.', 'beginner', 9),
  ('agents-automation', 'workflows', 'Estimate whether automating a workflow is worth it', 'This workflow currently takes [time] and happens [frequency]. Is automating it worth the setup effort, roughly?', 'swap: give it your actual setup time estimate for a more specific answer.', 'intermediate', 10),
  -- agents-automation / integrations
  ('agents-automation', 'integrations', 'Decide what data actually needs to sync', 'I am connecting [tool A] and [tool B]. What data actually needs to sync between them, versus what would just add complexity?', 'swap: ask what happens if you sync less than you initially planned.', 'beginner', 6),
  ('agents-automation', 'integrations', 'Plan for what happens when an integration goes down', 'If the connection between [tool A] and [tool B] went down for a day, what would break, and what is the safest fallback?', 'swap: ask how you would know it went down, if there is no obvious alert.', 'intermediate', 7),
  ('agents-automation', 'integrations', 'Avoid building an integration you will regret maintaining', 'I am about to build an integration between [tool A] and [tool B]. What is the maintenance burden likely to look like a year from now?', 'swap: ask what would make this integration low-maintenance versus high-maintenance.', 'advanced', 8),
  ('agents-automation', 'integrations', 'Test an integration before relying on it', 'I just connected [tool A] and [tool B]. What should I test to make sure the integration is actually working correctly, not just appearing to work?', 'swap: ask for the trickiest edge case to test, not just the obvious happy path.', 'beginner', 9),
  ('agents-automation', 'integrations', 'Choose the order to build multiple integrations', 'I want to eventually connect [tool A], [tool B], and [tool C]. What order should I build these in, and why?', 'swap: mention which connection would save you the most time right now, since that may change the order.', 'intermediate', 10),

  -- learning / self-teaching
  ('learning', 'self-teaching', 'Turn a course or book into an action plan', 'I just finished a course, book, or resource on [topic]. Help me turn the key ideas into 3 things I should actually go do.', 'swap: ask which of the 3 is the most important to do first.', 'beginner', 6),
  ('learning', 'self-teaching', 'Diagnose why a topic is not sticking', 'I keep forgetting or struggling with [topic] even after studying it. What is the most likely reason it is not sticking?', 'swap: ask for a different learning method to try, based on that reason.', 'intermediate', 7),
  ('learning', 'self-teaching', 'Build a feedback loop into self-teaching', 'I am teaching myself [topic] with no instructor. How can I get feedback on whether I am actually doing it right, not just whether it feels right?', 'swap: ask for a way to get that feedback without needing another person.', 'advanced', 8),
  ('learning', 'self-teaching', 'Decide when you know enough to move on', 'I am learning [topic] before moving on to [next topic]. How do I know when I know enough of the first to move on, rather than over-preparing?', 'swap: ask for one quick test that would confirm you are ready.', 'beginner', 9),
  ('learning', 'self-teaching', 'Relearn something you forgot faster the second time', 'I learned [topic] before and forgot most of it. What is the fastest way to relearn it, given that some of it is probably still there?', 'swap: ask what usually stays versus what usually fades first, so you know where to focus.', 'intermediate', 10),
  -- learning / quizzing-yourself
  ('learning', 'quizzing-yourself', 'Get quizzed in a way that mimics real use', 'Instead of a standard quiz, test me on [topic] the way I would actually need to use it in real life.', 'swap: ask for a harder, more realistic version once the first one feels easy.', 'beginner', 6),
  ('learning', 'quizzing-yourself', 'Use spaced repetition without special software', 'Help me build a simple spaced repetition plan for [topic] using just quizzing over the next few weeks, no special app.', 'swap: ask how the plan should change if you miss a scheduled review.', 'intermediate', 7),
  ('learning', 'quizzing-yourself', 'Quiz yourself on a mistake until it stops happening', 'I keep making this specific mistake: [describe mistake]. Quiz me repeatedly on exactly the situation where I make it, until I stop.', 'swap: ask for a slightly different version of the situation each time, so you are not just memorizing one case.', 'advanced', 8),
  ('learning', 'quizzing-yourself', 'Turn a wrong answer into 2 more questions', 'I got this question wrong: [paste question and your wrong answer]. Ask me 2 follow-up questions that would confirm whether I actually understand it now.', 'swap: ask for an explanation of exactly why your original answer was wrong, not just the right answer.', 'beginner', 9),
  ('learning', 'quizzing-yourself', 'Quiz on application, not just recall', 'Do not ask me to define [topic]. Instead, give me a short scenario where I have to apply it and explain my reasoning.', 'swap: ask for feedback on your reasoning, not just whether the final answer was right.', 'intermediate', 10),
  -- learning / explaining-hard-concepts
  ('learning', 'explaining-hard-concepts', 'Explain a concept using only what you already know', 'Explain [hard concept] using only comparisons to things I already understand: [list what you know].', 'swap: ask for a comparison that intentionally breaks down at some point, since knowing where it breaks helps too.', 'beginner', 6),
  ('learning', 'explaining-hard-concepts', 'Build a concept up from first principles', 'Instead of jumping to the full explanation, build up to [concept] starting from the most basic idea it depends on.', 'swap: ask it to have you explain each step back before moving to the next, to confirm it landed.', 'intermediate', 7),
  ('learning', 'explaining-hard-concepts', 'Explain why a common misconception is wrong', 'Most people think [common misconception] about [concept]. Explain specifically why that is wrong, not just what the right answer is.', 'swap: ask why the misconception is so common in the first place.', 'advanced', 8),
  ('learning', 'explaining-hard-concepts', 'Teach a concept as if preparing you to teach someone else', 'Explain [concept] to me as if I will need to teach it to someone else in an hour. Flag the parts most likely to confuse a beginner.', 'swap: after the explanation, try explaining it back and ask for corrections.', 'intermediate', 9),
  ('learning', 'explaining-hard-concepts', 'Use a bad explanation to build a better one', 'Here is an explanation of [concept] that did not make sense to me: [paste it]. What is it missing, and can you explain it better?', 'swap: ask specifically which part of the bad explanation was the most confusing, so the new one avoids it.', 'beginner', 10),

  -- money-work / freelancing
  ('money-work', 'freelancing', 'Decide how many clients you can actually handle', 'I currently have this workload: [describe it]. How do I know if I am at capacity, or if I have room for more work?', 'swap: mention how many hours you actually want to work, since capacity is not just about time available.', 'beginner', 6),
  ('money-work', 'freelancing', 'Turn a one-off client into repeat work', 'I just finished a project for a client who seemed happy: [describe the project]. What could I say or offer to open the door to more work?', 'swap: ask for a version that does not feel like you are asking for more work directly.', 'intermediate', 7),
  ('money-work', 'freelancing', 'Set boundaries with a demanding client', 'This client is asking for things outside our agreement: [describe the pattern]. Help me set a clear boundary without damaging the relationship.', 'swap: decide what you are actually willing to tolerate before drafting the message.', 'advanced', 8),
  ('money-work', 'freelancing', 'Decide when to let a client go', 'This client relationship has these problems: [describe them]. Is this a client I should let go of, or is this fixable?', 'swap: ask what would need to change for it to be fixable, so you have a clear line.', 'intermediate', 9),
  ('money-work', 'freelancing', 'Plan for slow periods', 'My freelance income is unpredictable, with slow periods: [describe them]. What should I be doing during a slow period besides worrying?', 'swap: mention how much runway you currently have, since that changes the urgency.', 'beginner', 10),
  -- money-work / proposals
  ('money-work', 'proposals', 'Write a proposal that is easy to say yes to', 'Here is my proposal: [paste it]. What would make it easier for the client to say yes quickly, rather than needing to think it over?', 'swap: ask if removing an option would help, since too many choices can slow a decision.', 'beginner', 6),
  ('money-work', 'proposals', 'Decide how much detail a proposal actually needs', 'This proposal feels either too thin or too long: [paste it]. What level of detail actually helps the client decide, versus what is just filler?', 'swap: ask what a client at this budget level typically expects to see.', 'intermediate', 7),
  ('money-work', 'proposals', 'Turn a rejected proposal into a lesson', 'This proposal was rejected: [paste it]. Without knowing exactly why, what is the most likely weak point?', 'swap: if you do know why it was rejected, share that so the analysis is more accurate.', 'advanced', 8),
  ('money-work', 'proposals', 'Write a proposal for a project with unclear scope', 'The client has not fully defined what they need: [describe what they have told you]. How do I write a proposal that accounts for that uncertainty?', 'swap: ask about proposing a smaller paid discovery phase first instead of a full scope guess.', 'intermediate', 9),
  ('money-work', 'proposals', 'Follow up on a proposal without being pushy', 'I sent this proposal a while ago and have not heard back: [paste proposal]. Write a follow-up that does not feel pushy.', 'swap: ask for a version that gives them an easy out if they have gone another direction.', 'beginner', 10),
  -- money-work / pricing
  ('money-work', 'pricing', 'Raise your prices for new clients only', 'I want to raise my rate for new clients but keep my current clients at their existing rate for now. How do I think about the transition?', 'swap: ask when it makes sense to eventually raise existing clients too.', 'beginner', 6),
  ('money-work', 'pricing', 'Price a project you have never done before', 'I am pricing a type of project I have not done before: [describe it]. How should I think about pricing it given the uncertainty?', 'swap: ask about adding a buffer or a scope boundary to protect against the unknowns.', 'intermediate', 7),
  ('money-work', 'pricing', 'Decide between a flat fee and hourly for one project', 'For this specific project: [describe it], should I charge a flat fee or hourly? Argue both sides, then recommend one.', 'swap: mention how well-defined the scope is, since that usually decides it.', 'advanced', 8),
  ('money-work', 'pricing', 'Explain pricing to a client who compares you to someone cheaper', 'A client mentioned a cheaper alternative: [describe it]. Help me respond without trashing the competitor or sounding defensive.', 'swap: ask for a version that focuses entirely on what you specifically deliver.', 'beginner', 9),
  ('money-work', 'pricing', 'Decide if a discount is a good idea', 'A client asked for a discount on [project]. What should I consider before saying yes or no?', 'swap: mention what you would want in return for the discount, like a testimonial or referral.', 'intermediate', 10),
  -- money-work / finding-clients
  ('money-work', 'finding-clients', 'Choose where to spend limited outreach time', 'I have limited time for finding clients each week. Given my niche and options: [describe them], where should I focus that time?', 'swap: mention what has worked even a little in the past, since that is worth doubling down on.', 'beginner', 6),
  ('money-work', 'finding-clients', 'Turn a satisfied client into referrals', 'This client seems happy with my work: [describe the situation]. How do I ask for a referral without it feeling awkward?', 'swap: ask for a version you could send by message instead of asking in person.', 'intermediate', 7),
  ('money-work', 'finding-clients', 'Build authority in a niche without a big following', 'I do not have a large following yet, but I want to build credibility in [niche]. What is a realistic way to do that?', 'swap: ask what a small following can still credibly do that a large one is not actually needed for.', 'advanced', 8),
  ('money-work', 'finding-clients', 'Decide if a lead is worth pursuing', 'Here is a potential client lead: [describe it]. What questions should I ask before deciding if this is worth pursuing?', 'swap: ask which of those questions is the single most important dealbreaker.', 'beginner', 9),
  ('money-work', 'finding-clients', 'Recover from a slow period with no leads', 'I have had no new leads in a while. What should I actually do differently, versus just waiting it out?', 'swap: mention what you have tried already so the advice does not repeat it.', 'intermediate', 10),

  -- audio / voiceover
  ('audio', 'voiceover', 'Decide on pacing for information-heavy scripts', 'This script is information-heavy: [paste script]. How should the pacing differ from a normal conversational read?', 'swap: ask where specifically to slow down versus where it is safe to move quickly.', 'beginner', 6),
  ('audio', 'voiceover', 'Write a script that sounds good even without visuals', 'This voiceover needs to make sense even for someone not watching the visuals: [describe context]. What does the script need to include?', 'swap: ask what can be safely left out because the visuals will carry it.', 'intermediate', 7),
  ('audio', 'voiceover', 'Match voiceover energy to a brand', 'This voiceover needs to sound like a specific brand personality: [describe it]. Describe the vocal qualities, pace and tone, that would achieve that.', 'swap: ask for a contrasting example of a delivery that would NOT fit the brand, so you know what to avoid.', 'advanced', 8),
  ('audio', 'voiceover', 'Shorten a script without losing the point', 'This script is too long: [paste script]. Shorten it while keeping the core message intact.', 'swap: ask what the single most important sentence is, in case you need to cut further.', 'beginner', 9),
  ('audio', 'voiceover', 'Write a script for a specific runtime', 'I need this script to run almost exactly a set length when read at a normal pace: [state the length]. Write it to fit that length, covering: [describe the content it needs to cover]', 'swap: ask for a slightly shorter backup version in case the read runs long.', 'intermediate', 10),
  -- audio / sound-design
  ('audio', 'sound-design', 'Decide what sound should draw attention versus stay in the background', 'In this scene, what sounds should the audience consciously notice, and what should just sit in the background: [describe scene]?', 'swap: ask what happens if a background sound accidentally becomes too noticeable.', 'beginner', 6),
  ('audio', 'sound-design', 'Use sound to hint at something offscreen', 'I want a sound to hint at something happening offscreen: [describe what]. What sound would communicate that without showing it?', 'swap: ask how loud or subtle that sound should be to hint rather than announce.', 'intermediate', 7),
  ('audio', 'sound-design', 'Diagnose a mix that feels muddy', 'This sound mix feels muddy or unclear: [describe the elements in it]. What is likely competing for the same space?', 'swap: ask which single element you should pull back first to test.', 'advanced', 8),
  ('audio', 'sound-design', 'Choose sound design that matches a genre convention', 'This project is in [genre]. What are the sound design conventions of that genre I should know about?', 'swap: ask if breaking one of those conventions could work in your favor here.', 'beginner', 9),
  ('audio', 'sound-design', 'Build tension using sound alone', 'I want to build tension in this moment using sound, with minimal or no music: [describe the moment]. What sound design choices would create that tension?', 'swap: ask how the tension should resolve, sound-wise, once the moment passes.', 'intermediate', 10),
  -- audio / music
  ('audio', 'music', 'Decide if a scene needs music at all', 'I am not sure this scene needs music: [describe scene]. What is the case for leaving it without music?', 'swap: ask what the scene would lose specifically if music were added.', 'beginner', 6),
  ('audio', 'music', 'Choose instrumentation for a specific feeling', 'I want this piece to feel [feeling]. What instrumentation would support that, and what would work against it?', 'swap: ask for a stripped-down version using fewer instruments, in case the full version feels too busy.', 'intermediate', 7),
  ('audio', 'music', 'Use a key or tempo change to mark a shift', 'I want a change in the music, key or tempo, to mark this shift in the story: [describe the shift]. How should that change be introduced so it does not feel abrupt?', 'swap: ask for a version where the change IS meant to feel abrupt, in case that serves the moment better.', 'advanced', 8),
  ('audio', 'music', 'Match music energy to editing pace', 'The edit in this section has a specific pace: [describe it]. What music energy would match that pace without fighting it?', 'swap: ask what would happen if the music energy were deliberately mismatched, in case that tension is useful.', 'beginner', 9),
  ('audio', 'music', 'Decide where music should be loudest', 'Across this whole sequence, where should the music be at its most prominent, and where should it recede: [describe the sequence]?', 'swap: ask what should happen to the music at the very end of the sequence specifically.', 'intermediate', 10)
) as x(cat_slug, sub_slug, title, body, swap_note, difficulty, sort_order)
  on x.cat_slug = c.slug and x.sub_slug = s.slug;
