-- Apps & tools, Expert tier (days 61-80). Authored content, UNPUBLISHED until a person reviews it in Admin.
insert into public.day
  (track_id, tier_id, day_number, title, objective, lesson_md, skill_focus, assignment_md, rubric,
   est_minutes, is_published, credit_budget, submission_type, ai_evaluate, requires_review)
select t.id, ti.id, v.n, v.title, v.objective, v.lesson_md, v.skill_focus, v.assignment_md, v.rubric,
       v.est_minutes, false, null, v.submission_type, v.ai_evaluate, v.requires_review
from public.track t
join public.tier ti on ti.track_id = t.id and ti.slug = 'expert'
cross join (values
  (61, $t61a$Architecture: choosing what to build and what to buy$t61a$, $t61b$Decide build vs buy with evidence.$t61b$, $t61c$Every feature can be built, bought or borrowed (a service, template or open tool). Compare cost, control, risk, lock-in and time. Build only what makes your product different.$t61c$, $t61d$Architecture: choosing what to build and what to buy$t61d$, $t61e$Choose five features of a product. For each decide build, buy or borrow with cost, risk and exit plan.$t61e$, $t61f$[{"criterion": "Reasoned decisions", "max_points": 40, "guidance": "Trade-offs."}, {"criterion": "Costs and lock-in", "max_points": 35, "guidance": "Considered."}, {"criterion": "Exit plan", "max_points": 25, "guidance": "Defined."}]$t61f$::jsonb, 45, 'text', false, false),
  (62, $t62a$Data modelling for change$t62a$, $t62b$Design data that survives new features.$t62b$, $t62c$Plan for change: stable ids, audit fields, soft deletes, versioned records and migrations. Test that you can add a field without breaking anything.$t62c$, $t62d$Data modelling for change$t62d$, $t62e$Design a schema for a product with audit fields and describe two migrations you would make later.$t62e$, $t62f$[{"criterion": "Stable design", "max_points": 40, "guidance": "Ids and audit."}, {"criterion": "Migrations planned", "max_points": 35, "guidance": "Safe."}, {"criterion": "Simple", "max_points": 25, "guidance": "Not overbuilt."}]$t62f$::jsonb, 45, 'text', false, false),
  (63, $t63a$Security review: threat modelling$t63a$, $t63b$Find how your app could be attacked.$t63b$, $t63c$List assets, who might attack, how (guessing ids, abusing uploads, leaking keys) and what stops them. Rank by likelihood and impact. Fix the top three.$t63c$, $t63d$Security review: threat modelling$t63d$, $t63e$Threat-model your app: ten threats ranked, top three fixed with evidence.

**Evidence:** paste *direct* links to screenshots (.png/.jpg/.webp), one per line, and describe them.$t63e$, $t63f$[{"criterion": "Threats realistic", "max_points": 35, "guidance": "Specific."}, {"criterion": "Ranked", "max_points": 25, "guidance": "Reasoned."}, {"criterion": "Fixes verified", "max_points": 40, "guidance": "Evidence."}]$t63f$::jsonb, 45, 'link', false, false),
  (64, $t64a$Reliability and testing strategy$t64a$, $t64b$Test what matters automatically.$t64b$, $t64c$Write tests for the riskiest flows: sign-up, payment, permissions. Add a smoke test after each release. Track defects and their causes.$t64c$, $t64d$Reliability and testing strategy$t64d$, $t64e$Define ten tests for critical flows, run them and report results and gaps.$t64e$, $t64f$[{"criterion": "Critical flows covered", "max_points": 40, "guidance": "Right ones."}, {"criterion": "Results honest", "max_points": 35, "guidance": "Reported."}, {"criterion": "Gaps listed", "max_points": 25, "guidance": "Known."}]$t64f$::jsonb, 45, 'text', false, false),
  (65, $t65a$Expert project 1: a hardened product$t65a$, $t65b$Deliver a secure, tested build.$t65b$, $t65c$Show Module 1. Deliver a **hardened product**: build-vs-buy record, data model, threat model with fixes and a tested critical flow.

Your work is scored on the rubric below. You can revise and resubmit.$t65c$, $t65d$Expert project 1: a hardened product$t65d$, $t65e$Submit all four with screenshots of fixes and test results.

**Evidence:** paste *direct* links to screenshots (.png/.jpg/.webp), one per line, and describe them.$t65e$, $t65f$[{"criterion": "Architecture decisions", "max_points": 25, "guidance": "Reasoned."}, {"criterion": "Security", "max_points": 30, "guidance": "Verified."}, {"criterion": "Testing", "max_points": 25, "guidance": "Real."}, {"criterion": "Honesty", "max_points": 20, "guidance": "Known gaps."}]$t65f$::jsonb, 120, 'link', true, false),
  (66, $t66a$Pricing, packaging and unit economics$t66a$, $t66b$Know whether the product can make money.$t66b$, $t66c$Calculate cost per user (hosting, AI, support), price tiers and margin. Test willingness to pay with real people before building billing.$t66c$, $t66d$Pricing, packaging and unit economics$t66d$, $t66e$Build a unit-economics sheet with three price options and evidence from five potential customers.$t66e$, $t66f$[{"criterion": "Costs complete", "max_points": 35, "guidance": "AI included."}, {"criterion": "Options compared", "max_points": 35, "guidance": "Three."}, {"criterion": "Real evidence", "max_points": 30, "guidance": "Five people."}]$t66f$::jsonb, 45, 'text', false, false),
  (67, $t67a$Growth loops and retention$t67a$, $t67b$Design why users return.$t67b$, $t67c$Retention beats acquisition. Find the moment users get value, shorten the path to it, remind them well and measure week-4 retention.$t67c$, $t67d$Growth loops and retention$t67d$, $t67e$Define your activation moment, three retention tactics and how you will measure them.$t67e$, $t67f$[{"criterion": "Activation clear", "max_points": 40, "guidance": "Specific."}, {"criterion": "Tactics relevant", "max_points": 35, "guidance": "Sensible."}, {"criterion": "Measurement", "max_points": 25, "guidance": "Defined."}]$t67f$::jsonb, 45, 'text', false, false),
  (68, $t68a$Product analytics and decisions$t68a$, $t68b$Use data to choose what to build next.$t68b$, $t68c$Track funnels, cohorts and feedback themes. Decide with a simple scorecard (impact, effort, confidence). Record what you decided not to build.$t68c$, $t68d$Product analytics and decisions$t68d$, $t68e$Score ten backlog ideas and choose three with reasons.$t68e$, $t68f$[{"criterion": "Scorecard used", "max_points": 35, "guidance": "Consistent."}, {"criterion": "Reasons clear", "max_points": 40, "guidance": "Data."}, {"criterion": "Rejections recorded", "max_points": 25, "guidance": "Honest."}]$t68f$::jsonb, 45, 'text', false, false),
  (69, $t69a$Support, incidents and postmortems$t69a$, $t69b$Handle failure professionally.$t69b$, $t69c$When it breaks: acknowledge, fix, communicate, learn. A blameless postmortem records timeline, cause, impact and prevention.$t69c$, $t69d$Support, incidents and postmortems$t69d$, $t69e$Write a postmortem for a real or simulated incident.$t69e$, $t69f$[{"criterion": "Timeline and cause", "max_points": 40, "guidance": "Accurate."}, {"criterion": "Communication", "max_points": 30, "guidance": "Plan."}, {"criterion": "Prevention", "max_points": 30, "guidance": "Concrete."}]$t69f$::jsonb, 45, 'text', false, false),
  (70, $t70a$Expert project 2: a business-ready product$t70a$, $t70b$Show it can sustain itself.$t70b$, $t70c$Show Module 2. Deliver a **business case**: unit economics, activation and retention plan, analytics, decision scorecard and incident plan.

Your work is scored on the rubric below. You can revise and resubmit.$t70c$, $t70d$Expert project 2: a business-ready product$t70d$, $t70e$Submit all parts with real numbers or clearly labelled estimates.$t70e$, $t70f$[{"criterion": "Economics sound", "max_points": 30, "guidance": "Numbers."}, {"criterion": "Retention plan", "max_points": 25, "guidance": "Grounded."}, {"criterion": "Operations", "max_points": 25, "guidance": "Ready."}, {"criterion": "Honesty", "max_points": 20, "guidance": "Labelled."}]$t70f$::jsonb, 120, 'text', true, false),
  (71, $t71a$AI features at production quality$t71a$, $t71b$Make AI reliable for real users.$t71b$, $t71c$Add evaluation sets, monitoring of cost and quality, fallbacks when the model fails and a way for users to report bad outputs.$t71c$, $t71d$AI features at production quality$t71d$, $t71e$Set up evaluation for an AI feature: test set, metrics, fallback and report route.$t71e$, $t71f$[{"criterion": "Evaluation real", "max_points": 40, "guidance": "Test set."}, {"criterion": "Fallback", "max_points": 30, "guidance": "Works."}, {"criterion": "Reporting", "max_points": 30, "guidance": "Route."}]$t71f$::jsonb, 45, 'text', false, false),
  (72, $t72a$Privacy engineering and compliance$t72a$, $t72b$Build privacy into the product.$t72b$, $t72c$Minimise data, encrypt in transit and at rest, honour deletion and export requests, keep processor agreements and log access. Get legal advice for regulated data. This course is not legal advice.$t72c$, $t72d$Privacy engineering and compliance$t72d$, $t72e$Design deletion and export flows and a data inventory.$t72e$, $t72f$[{"criterion": "Inventory complete", "max_points": 35, "guidance": "Data mapped."}, {"criterion": "Flows work", "max_points": 40, "guidance": "Described or shown."}, {"criterion": "Advice limits", "max_points": 25, "guidance": "Stated."}]$t72f$::jsonb, 45, 'text', false, false),
  (73, $t73a$Accessibility and inclusive UX$t73a$, $t73b$Make the product usable by everyone.$t73b$, $t73c$Keyboard navigation, contrast, labels, focus states and clear language. Test with a screen reader and with keyboard only.$t73c$, $t73d$Accessibility and inclusive UX$t73d$, $t73e$Audit five screens and fix the top five issues.

**Evidence:** paste *direct* links to screenshots (.png/.jpg/.webp), one per line, and describe them.$t73e$, $t73f$[{"criterion": "Issues real", "max_points": 35, "guidance": "Specific."}, {"criterion": "Fixes applied", "max_points": 40, "guidance": "Shown."}, {"criterion": "Tested", "max_points": 25, "guidance": "Method."}]$t73f$::jsonb, 45, 'link', false, false),
  (74, $t74a$Performance at scale$t74a$, $t74b$Keep it fast as it grows.$t74b$, $t74c$Measure, find the slowest queries and pages, add caching and limits, and load-test a critical flow.$t74c$, $t74d$Performance at scale$t74d$, $t74e$Measure three bottlenecks and improve one with before and after numbers.$t74e$, $t74f$[{"criterion": "Measured", "max_points": 40, "guidance": "Numbers."}, {"criterion": "Improvement real", "max_points": 35, "guidance": "Shown."}, {"criterion": "Limits set", "max_points": 25, "guidance": "Defined."}]$t74f$::jsonb, 45, 'text', false, false),
  (75, $t75a$Expert project 3: production readiness review$t75a$, $t75b$Prove it is ready for real users.$t75b$, $t75c$Show Module 3. Deliver a **readiness review**: AI evaluation, privacy inventory and flows, accessibility fixes and performance results.

Your work is scored on the rubric below. You can revise and resubmit.$t75c$, $t75d$Expert project 3: production readiness review$t75d$, $t75e$Submit each with evidence.

**Evidence:** paste *direct* links to screenshots (.png/.jpg/.webp), one per line, and describe them.$t75e$, $t75f$[{"criterion": "AI quality", "max_points": 25, "guidance": "Evaluated."}, {"criterion": "Privacy", "max_points": 25, "guidance": "Handled."}, {"criterion": "Accessibility and performance", "max_points": 30, "guidance": "Fixed."}, {"criterion": "Honesty", "max_points": 20, "guidance": "Gaps stated."}]$t75f$::jsonb, 120, 'link', true, false),
  (76, $t76a$Flagship: define and validate$t76a$, $t76b$Start a product with paying-customer evidence.$t76b$, $t76c$Find ten target users, test the problem, and secure at least three commitments (pre-orders, pilots or letters of intent).$t76c$, $t76d$Flagship: define and validate$t76d$, $t76e$Submit interview summary and commitments (labelled real).$t76e$, $t76f$[{"criterion": "Real validation", "max_points": 45, "guidance": "Evidence."}, {"criterion": "Commitments", "max_points": 30, "guidance": "Genuine."}, {"criterion": "Honest", "max_points": 25, "guidance": "Not inflated."}]$t76f$::jsonb, 45, 'text', false, false),
  (77, $t77a$Flagship: build the core$t77a$, $t77b$Ship the core with quality.$t77b$, $t77c$Build with tests, security and accessibility from day one.$t77c$, $t77d$Flagship: build the core$t77d$, $t77e$Submit screenshots and test results.

**Evidence:** paste *direct* links to screenshots (.png/.jpg/.webp), one per line, and describe them.$t77e$, $t77f$[{"criterion": "Core works", "max_points": 45, "guidance": "Shown."}, {"criterion": "Quality practices", "max_points": 35, "guidance": "Applied."}, {"criterion": "Scope disciplined", "max_points": 20, "guidance": "Small."}]$t77f$::jsonb, 120, 'link', false, false),
  (78, $t78a$Flagship: pilot and iterate$t78a$, $t78b$Learn from real users.$t78b$, $t78c$Run a pilot with at least five users for two weeks and iterate weekly.$t78c$, $t78d$Flagship: pilot and iterate$t78d$, $t78e$Submit pilot data, changes and outcomes.$t78e$, $t78f$[{"criterion": "Pilot real", "max_points": 35, "guidance": "Five users."}, {"criterion": "Iterations", "max_points": 40, "guidance": "Evidence."}, {"criterion": "Outcomes measured", "max_points": 25, "guidance": "Numbers."}]$t78f$::jsonb, 90, 'text', false, false),
  (79, $t79a$Flagship: launch and operate$t79a$, $t79b$Go live and keep it running.$t79b$, $t79c$Launch, monitor, support and handle at least one issue. Record the numbers.$t79c$, $t79d$Flagship: launch and operate$t79d$, $t79e$Submit launch evidence, monitoring and an issue log.

**Evidence:** paste *direct* links to screenshots (.png/.jpg/.webp), one per line, and describe them.$t79e$, $t79f$[{"criterion": "Launched", "max_points": 30, "guidance": "Live."}, {"criterion": "Operations", "max_points": 40, "guidance": "Monitoring and support."}, {"criterion": "Issue handled", "max_points": 30, "guidance": "Log."}]$t79f$::jsonb, 90, 'link', false, false),
  (80, $t80a$Expert project 4: the flagship product$t80a$, $t80b$Deliver a real product with users and results.$t80b$, $t80c$Show Module 4. Deliver the **flagship product** with validation, build, pilot data, launch and operating evidence.

Your work is scored on the rubric below. You can revise and resubmit.$t80c$, $t80d$Expert project 4: the flagship product$t80d$, $t80e$Submit a case study with evidence, results and lessons.

**Evidence:** paste *direct* links to screenshots (.png/.jpg/.webp), one per line, and describe them.$t80e$, $t80f$[{"criterion": "Validation and results", "max_points": 30, "guidance": "Evidence."}, {"criterion": "Product quality", "max_points": 30, "guidance": "Strong."}, {"criterion": "Operations and safety", "max_points": 25, "guidance": "Ready."}, {"criterion": "Honesty", "max_points": 15, "guidance": "Frank."}]$t80f$::jsonb, 200, 'link', true, false)
) as v(n, title, objective, lesson_md, skill_focus, assignment_md, rubric, est_minutes, submission_type, ai_evaluate, requires_review)
where t.slug = 'apps'
on conflict (track_id, day_number) do nothing;
