-- Business & freelancing, Pro tier (days 31-60). Authored content, UNPUBLISHED until a person reviews it in Admin.
insert into public.day
  (track_id, tier_id, day_number, title, objective, lesson_md, skill_focus, assignment_md, rubric,
   est_minutes, is_published, credit_budget, submission_type, ai_evaluate, requires_review)
select t.id, ti.id, v.n, v.title, v.objective, v.lesson_md, v.skill_focus, v.assignment_md, v.rubric,
       v.est_minutes, false, null, v.submission_type, v.ai_evaluate, v.requires_review
from public.track t
join public.tier ti on ti.track_id = t.id and ti.slug = 'pro'
cross join (values
  (31, $t31a$Positioning: why you and not someone else$t31a$, $t31b$State a position clients can remember.$t31b$, $t31c$Positioning is who you help, the result you deliver and why you are different in a way clients care about. Test it: can a stranger repeat it after one reading? Avoid claims you cannot prove.$t31c$, $t31d$Positioning: why you and not someone else$t31d$, $t31e$Write your positioning statement and three proof points that are true and checkable.$t31e$, $t31f$[{"criterion": "Specific position", "max_points": 40, "guidance": "Clear."}, {"criterion": "Proof true", "max_points": 40, "guidance": "Checkable."}, {"criterion": "Memorable", "max_points": 20, "guidance": "Repeatable."}]$t31f$::jsonb, 30, 'text', false, false),
  (32, $t32a$Packaging services into tiers$t32a$, $t32b$Create three clear packages.$t32b$, $t32c$Offer a small, standard and premium package with clear inclusions and prices. The middle option should suit most clients. Make differences obvious and avoid choice overload.$t32c$, $t32d$Packaging services into tiers$t32d$, $t32e$Design three packages with inclusions, prices and who each is for.$t32e$, $t32f$[{"criterion": "Packages distinct", "max_points": 40, "guidance": "Clear."}, {"criterion": "Pricing logical", "max_points": 35, "guidance": "Reasoned."}, {"criterion": "Audience per tier", "max_points": 25, "guidance": "Named."}]$t32f$::jsonb, 20, 'text', false, false),
  (33, $t33a$Value-based pricing$t33a$, $t33b$Price by the value you create.$t33b$, $t33c$Estimate what the result is worth to the client (time saved, revenue gained), price a fraction, and show your reasoning. Confirm numbers with the client rather than inventing them.$t33c$, $t33d$Value-based pricing$t33d$, $t33e$Build a value case for one client scenario with sourced assumptions.$t33e$, $t33f$[{"criterion": "Value logic sound", "max_points": 40, "guidance": "Reasoned."}, {"criterion": "Assumptions honest", "max_points": 35, "guidance": "Clear."}, {"criterion": "Price fair", "max_points": 25, "guidance": "Fraction."}]$t33f$::jsonb, 20, 'text', false, false),
  (34, $t34a$Discovery that uncovers real needs$t34a$, $t34b$Ask questions that reveal the real problem.$t34b$, $t34c$Ask about goals, past attempts, constraints, decision makers, budget and deadlines. Find the problem behind the request. Summarise back to confirm.$t34c$, $t34d$Discovery that uncovers real needs$t34d$, $t34e$Run a discovery call and submit notes: real problem, constraints and the summary you sent.$t34e$, $t34f$[{"criterion": "Questions probing", "max_points": 35, "guidance": "Deep."}, {"criterion": "Real problem found", "max_points": 40, "guidance": "Insight."}, {"criterion": "Summary sent", "max_points": 25, "guidance": "Confirmed."}]$t34f$::jsonb, 20, 'text', false, false),
  (35, $t35a$Writing a winning proposal$t35a$, $t35b$Write proposals clients say yes to.$t35b$, $t35c$Mirror the client's words, state outcomes, scope, timeline, price, terms and one next step. Keep to two pages, include options and give a deadline for the offer.$t35c$, $t35d$Writing a winning proposal$t35d$, $t35e$Write a proposal from your discovery notes with three options.$t35e$, $t35f$[{"criterion": "Mirrors client", "max_points": 30, "guidance": "Their words."}, {"criterion": "Scope and price clear", "max_points": 40, "guidance": "Precise."}, {"criterion": "Next step", "max_points": 30, "guidance": "Clear."}]$t35f$::jsonb, 20, 'text', false, false),
  (36, $t36a$Module project: a sales pack$t36a$, $t36b$Deliver positioning, packages, value case and a proposal.$t36b$, $t36c$Show Module 1. Deliver a **sales pack**: positioning, three packages, value case and a proposal for a real or realistic client.

Your work is scored on the rubric below. You can revise and resubmit.$t36c$, $t36d$Module project: a sales pack$t36d$, $t36e$Submit all four items.$t36e$, $t36f$[{"criterion": "Positioning and packages", "max_points": 30, "guidance": "Clear."}, {"criterion": "Value case honest", "max_points": 25, "guidance": "Sound."}, {"criterion": "Proposal quality", "max_points": 25, "guidance": "Persuasive."}, {"criterion": "Ethics", "max_points": 20, "guidance": "No invented claims."}]$t36f$::jsonb, 80, 'text', true, false),
  (37, $t37a$Project scoping and change control$t37a$, $t37b$Prevent scope creep.$t37b$, $t37c$Define deliverables, exclusions, assumptions and acceptance criteria. Use a change request process with price and time impact.$t37c$, $t37d$Project scoping and change control$t37d$, $t37e$Write a scope with exclusions, acceptance criteria and a change request form.$t37e$, $t37f$[{"criterion": "Exclusions clear", "max_points": 35, "guidance": "Explicit."}, {"criterion": "Acceptance criteria", "max_points": 35, "guidance": "Testable."}, {"criterion": "Change process", "max_points": 30, "guidance": "Defined."}]$t37f$::jsonb, 35, 'text', false, false),
  (38, $t38a$Project plans and milestones$t38a$, $t38b$Plan delivery realistically.$t38b$, $t38c$Break work into milestones with dates, dependencies and buffers. Share the plan and update it weekly.$t38c$, $t38d$Project plans and milestones$t38d$, $t38e$Create a milestone plan with buffers and client approval points.$t38e$, $t38f$[{"criterion": "Milestones clear", "max_points": 40, "guidance": "Dated."}, {"criterion": "Buffers", "max_points": 30, "guidance": "Included."}, {"criterion": "Approvals", "max_points": 30, "guidance": "Placed."}]$t38f$::jsonb, 20, 'text', false, false),
  (39, $t39a$Quality control and review$t39a$, $t39b$Deliver work you can stand behind.$t39b$, $t39c$Use checklists, a second review pass, and test everything as the client would. Keep a record of checks.$t39c$, $t39d$Quality control and review$t39d$, $t39e$Build a QA checklist (ten items) for your service and apply it to a deliverable.$t39e$, $t39f$[{"criterion": "Checklist real", "max_points": 40, "guidance": "Ten."}, {"criterion": "Applied", "max_points": 35, "guidance": "Evidence."}, {"criterion": "Issues found", "max_points": 25, "guidance": "Honest."}]$t39f$::jsonb, 20, 'text', false, false),
  (40, $t40a$Managing difficult clients$t40a$, $t40b$Handle conflict professionally.$t40b$, $t40c$Stay calm, restate the goal, refer to the agreement, offer options and know when to end a project. Document everything.$t40c$, $t40d$Managing difficult clients$t40d$, $t40e$Write responses to three difficult scenarios (late payment, endless changes, rude message).$t40e$, $t40f$[{"criterion": "Professional tone", "max_points": 40, "guidance": "Calm."}, {"criterion": "Uses agreement", "max_points": 35, "guidance": "Referenced."}, {"criterion": "Options offered", "max_points": 25, "guidance": "Constructive."}]$t40f$::jsonb, 20, 'text', false, false),
  (41, $t41a$Client reporting$t41a$, $t41b$Show results simply.$t41b$, $t41c$Report what was done, results versus goals, learnings and next steps on one page. Use real numbers only.$t41c$, $t41d$Client reporting$t41d$, $t41e$Write a one-page monthly report for a real or realistic project.$t41e$, $t41f$[{"criterion": "Results vs goals", "max_points": 40, "guidance": "Clear."}, {"criterion": "Real numbers", "max_points": 35, "guidance": "Honest."}, {"criterion": "Next steps", "max_points": 25, "guidance": "Actionable."}]$t41f$::jsonb, 20, 'text', false, false),
  (42, $t42a$Module project: a delivery system$t42a$, $t42b$Deliver scoping, plan, QA and reporting templates.$t42b$, $t42c$Show Module 2. Deliver a **delivery system**: scope template, milestone plan, QA checklist, difficult-client scripts and a report.

Your work is scored on the rubric below. You can revise and resubmit.$t42c$, $t42d$Module project: a delivery system$t42d$, $t42e$Submit all templates with one filled example.$t42e$, $t42f$[{"criterion": "Completeness", "max_points": 25, "guidance": "All parts."}, {"criterion": "Practical", "max_points": 30, "guidance": "Usable."}, {"criterion": "Client protection", "max_points": 25, "guidance": "Fair."}, {"criterion": "Quality", "max_points": 20, "guidance": "Clear."}]$t42f$::jsonb, 90, 'text', true, false),
  (43, $t43a$Automating your business with agents$t43a$, $t43b$Automate admin safely.$t43b$, $t43c$Automate reminders, invoices, onboarding and reporting; keep client communication personal. Use approvals, never share confidential data with unvetted tools and record what is automated.$t43c$, $t43d$Automating your business with agents$t43d$, $t43e$Map five admin tasks, mark what to automate, and list the safeguards.$t43e$, $t43f$[{"criterion": "Tasks sensible", "max_points": 35, "guidance": "Suitable."}, {"criterion": "Safeguards", "max_points": 40, "guidance": "Confidential data."}, {"criterion": "Personal touch kept", "max_points": 25, "guidance": "Balanced."}]$t43f$::jsonb, 35, 'text', false, false),
  (44, $t44a$Building a content engine$t44a$, $t44b$Create useful content consistently.$t44b$, $t44c$Turn each project into a case study, lesson or example (with permission). Use a simple calendar and repurpose. Quality and honesty beat volume.$t44c$, $t44d$Building a content engine$t44d$, $t44e$Plan four weeks of content from one project with permission notes.$t44e$, $t44f$[{"criterion": "Useful content", "max_points": 40, "guidance": "Helpful."}, {"criterion": "Permission", "max_points": 30, "guidance": "Considered."}, {"criterion": "Sustainable", "max_points": 30, "guidance": "Realistic."}]$t44f$::jsonb, 20, 'text', false, false),
  (45, $t45a$Partnerships and referrals$t45a$, $t45b$Grow through relationships.$t45b$, $t45c$Find complementary providers, offer value first, agree referral terms in writing and disclose commissions where required.$t45c$, $t45d$Partnerships and referrals$t45d$, $t45e$Identify five partner types, a value offer to each and referral terms.$t45e$, $t45f$[{"criterion": "Partners fit", "max_points": 35, "guidance": "Complementary."}, {"criterion": "Value first", "max_points": 35, "guidance": "Offer."}, {"criterion": "Terms and disclosure", "max_points": 30, "guidance": "Clear."}]$t45f$::jsonb, 20, 'text', false, false),
  (46, $t46a$Retention and retainers$t46a$, $t46b$Keep clients and steady income.$t46b$, $t46c$Offer ongoing packages with clear monthly value, review results quarterly and ask what else they need. Never lock clients in unfairly.$t46c$, $t46d$Retention and retainers$t46d$, $t46e$Design a retainer offer with deliverables, price, review cadence and exit terms.$t46e$, $t46f$[{"criterion": "Monthly value clear", "max_points": 40, "guidance": "Defined."}, {"criterion": "Fair terms", "max_points": 35, "guidance": "Exit."}, {"criterion": "Review cadence", "max_points": 25, "guidance": "Set."}]$t46f$::jsonb, 20, 'text', false, false),
  (47, $t47a$Metrics and business health$t47a$, $t47b$Track the numbers that matter.$t47b$, $t47c$Track leads, conversion, average project value, hours, margin and cash. Review monthly and decide one action.$t47c$, $t47d$Metrics and business health$t47d$, $t47e$Create a monthly dashboard with example data and one decision.$t47e$, $t47f$[{"criterion": "Metrics right", "max_points": 40, "guidance": "Relevant."}, {"criterion": "Data realistic", "max_points": 30, "guidance": "Plausible."}, {"criterion": "Decision made", "max_points": 30, "guidance": "Action."}]$t47f$::jsonb, 20, 'text', false, false),
  (48, $t48a$Module project: a growth plan$t48a$, $t48b$Deliver a plan for the next 6 months.$t48b$, $t48c$Show Module 3. Deliver a **6-month growth plan**: target clients, channels, content, partnerships, retainers and metrics.

Your work is scored on the rubric below. You can revise and resubmit.$t48c$, $t48d$Module project: a growth plan$t48d$, $t48e$Submit the plan with targets and risks.$t48e$, $t48f$[{"criterion": "Realistic targets", "max_points": 30, "guidance": "Numbers."}, {"criterion": "Channels and content", "max_points": 25, "guidance": "Coherent."}, {"criterion": "Metrics and risks", "max_points": 25, "guidance": "Defined."}, {"criterion": "Ethics", "max_points": 20, "guidance": "Honest marketing."}]$t48f$::jsonb, 80, 'text', true, false),
  (49, $t49a$Contracts in more detail$t49a$, $t49b$Understand key clauses.$t49b$, $t49c$Key clauses: scope, payment, IP ownership, confidentiality, liability limits, termination and dispute resolution. Get a lawyer to review your template. This course is not legal advice.$t49c$, $t49d$Contracts in more detail$t49d$, $t49e$Explain eight clauses in plain language and note which you would ask a lawyer to review.$t49e$, $t49f$[{"criterion": "Clauses explained", "max_points": 45, "guidance": "Plain."}, {"criterion": "Realistic", "max_points": 30, "guidance": "Applied."}, {"criterion": "Advice noted", "max_points": 25, "guidance": "Limits."}]$t49f$::jsonb, 35, 'text', false, false),
  (50, $t50a$Intellectual property and AI-generated work$t50a$, $t50b$Know who owns what.$t50b$, $t50c$Rules on AI-generated work vary by country and tool terms. Check what you can transfer, disclose AI use where required and never pass off others' work as yours.$t50c$, $t50d$Intellectual property and AI-generated work$t50d$, $t50e$Write your IP and AI-use clause and list three checks before delivery.$t50e$, $t50f$[{"criterion": "Clause clear", "max_points": 40, "guidance": "Precise."}, {"criterion": "Checks practical", "max_points": 35, "guidance": "Three."}, {"criterion": "Honest", "max_points": 25, "guidance": "Limits."}]$t50f$::jsonb, 20, 'text', false, false),
  (51, $t51a$Taxes, records and money$t51a$, $t51b$Stay organised.$t51b$, $t51c$Keep invoices and receipts, separate business money, set aside tax and know your local rules. Get an accountant's advice. This is not tax advice.$t51c$, $t51d$Taxes, records and money$t51d$, $t51e$Design your money system: accounts, records, set-aside rate and monthly routine.$t51e$, $t51f$[{"criterion": "System practical", "max_points": 45, "guidance": "Usable."}, {"criterion": "Records", "max_points": 30, "guidance": "Kept."}, {"criterion": "Advice noted", "max_points": 25, "guidance": "Limits."}]$t51f$::jsonb, 20, 'text', false, false),
  (52, $t52a$Insurance, risk and backups$t52a$, $t52b$Reduce business risk.$t52b$, $t52c$Consider professional liability cover, backups of work, contracts with subcontractors and a plan for illness or loss of tools.$t52c$, $t52d$Insurance, risk and backups$t52d$, $t52e$Write a risk plan with five risks, likelihood, impact and protection.$t52e$, $t52f$[{"criterion": "Risks real", "max_points": 40, "guidance": "Specific."}, {"criterion": "Protection concrete", "max_points": 40, "guidance": "Actions."}, {"criterion": "Backups", "max_points": 20, "guidance": "Included."}]$t52f$::jsonb, 20, 'text', false, false),
  (53, $t53a$Ethics in marketing$t53a$, $t53b$Sell honestly.$t53b$, $t53c$No fake reviews, invented results, dark patterns or misleading before-and-afters. Disclose AI use and paid relationships as required. Reputation compounds.$t53c$, $t53d$Ethics in marketing$t53d$, $t53e$Audit your marketing claims: list each claim, its proof and any change you make.$t53e$, $t53f$[{"criterion": "Claims audited", "max_points": 45, "guidance": "All."}, {"criterion": "Proof real", "max_points": 35, "guidance": "Verified."}, {"criterion": "Changes made", "max_points": 20, "guidance": "Honest."}]$t53f$::jsonb, 20, 'text', false, false),
  (54, $t54a$Module project: a compliant business kit$t54a$, $t54b$Deliver contracts, IP, money and risk plans.$t54b$, $t54c$Show Module 4. Deliver a **compliance kit**: contract outline, IP clause, money system, risk plan and marketing claims audit.

Your work is scored on the rubric below. You can revise and resubmit.$t54c$, $t54d$Module project: a compliant business kit$t54d$, $t54e$Submit all five parts.$t54e$, $t54f$[{"criterion": "Completeness", "max_points": 25, "guidance": "All parts."}, {"criterion": "Practicality", "max_points": 25, "guidance": "Usable."}, {"criterion": "Honesty", "max_points": 30, "guidance": "Claims verified."}, {"criterion": "Risk awareness", "max_points": 20, "guidance": "Realistic."}]$t54f$::jsonb, 80, 'text', true, false),
  (55, $t55a$Pro capstone 1: choose your client segment$t55a$, $t55b$Pick and research a segment.$t55b$, $t55c$Interview five potential clients in one segment about problems, budgets and buying process.$t55c$, $t55d$Pro capstone 1: choose your client segment$t55d$, $t55e$Submit interview summaries and segment choice.$t55e$, $t55f$[{"criterion": "Interviews real", "max_points": 40, "guidance": "Five."}, {"criterion": "Insights", "max_points": 35, "guidance": "Useful."}, {"criterion": "Segment chosen", "max_points": 25, "guidance": "Reasoned."}]$t55f$::jsonb, 20, 'text', false, false),
  (56, $t56a$Pro capstone 2: design the offer system$t56a$, $t56b$Design offers, pricing and process.$t56b$, $t56c$Create positioning, packages, pricing, scope template and delivery process.$t56c$, $t56d$Pro capstone 2: design the offer system$t56d$, $t56e$Submit all parts.$t56e$, $t56f$[{"criterion": "Coherent offer", "max_points": 40, "guidance": "Consistent."}, {"criterion": "Pricing reasoned", "max_points": 30, "guidance": "Value."}, {"criterion": "Process clear", "max_points": 30, "guidance": "Steps."}]$t56f$::jsonb, 20, 'text', false, false),
  (57, $t57a$Pro capstone 3: build proof and content$t57a$, $t57b$Create case studies and content.$t57b$, $t57c$Deliver a pilot for a real client and turn it into a case study.$t57c$, $t57d$Pro capstone 3: build proof and content$t57d$, $t57e$Submit case study and client feedback.$t57e$, $t57f$[{"criterion": "Result shown", "max_points": 40, "guidance": "Evidence."}, {"criterion": "Honest", "max_points": 30, "guidance": "Accurate."}, {"criterion": "Feedback real", "max_points": 30, "guidance": "Client."}]$t57f$::jsonb, 75, 'text', false, false),
  (58, $t58a$Pro capstone 4: outreach and sales$t58a$, $t58b$Run a real outreach campaign.$t58b$, $t58c$Contact 20 prospects, hold discovery calls and send proposals.$t58c$, $t58d$Pro capstone 4: outreach and sales$t58d$, $t58e$Submit outreach numbers, notes and proposals sent.$t58e$, $t58f$[{"criterion": "Real outreach", "max_points": 35, "guidance": "Twenty."}, {"criterion": "Calls and proposals", "max_points": 40, "guidance": "Evidence."}, {"criterion": "Learning", "max_points": 25, "guidance": "Applied."}]$t58f$::jsonb, 75, 'text', false, false),
  (59, $t59a$Pro capstone 5: systems and compliance$t59a$, $t59b$Set up contracts, money and risk basics.$t59b$, $t59c$Prepare contract, invoice, records, risk plan and privacy practices.$t59c$, $t59d$Pro capstone 5: systems and compliance$t59d$, $t59e$Submit each item.$t59e$, $t59f$[{"criterion": "Contract and invoice", "max_points": 40, "guidance": "Ready."}, {"criterion": "Money and records", "max_points": 30, "guidance": "System."}, {"criterion": "Risk and privacy", "max_points": 30, "guidance": "Considered."}]$t59f$::jsonb, 20, 'text', false, false),
  (60, $t60a$Pro capstone 6: business plan and launch review$t60a$, $t60b$Present a 6-month plan with evidence.$t60b$, $t60c$Present your evidence, systems and six-month plan with metrics and risks. Share in the Discord and ask for one piece of feedback.

Your work is scored on the rubric below. You can revise and resubmit.$t60c$, $t60d$Pro capstone 6: business plan and launch review$t60d$, $t60e$Submit the plan, evidence summary and a one-page review of what you learned.$t60e$, $t60f$[{"criterion": "Evidence of demand", "max_points": 30, "guidance": "Real."}, {"criterion": "Systems and compliance", "max_points": 25, "guidance": "Ready."}, {"criterion": "Plan realism", "max_points": 25, "guidance": "Numbers."}, {"criterion": "Ethics and honesty", "max_points": 20, "guidance": "Clear."}]$t60f$::jsonb, 90, 'text', true, false)
) as v(n, title, objective, lesson_md, skill_focus, assignment_md, rubric, est_minutes, submission_type, ai_evaluate, requires_review)
where t.slug = 'business'
on conflict (track_id, day_number) do nothing;
