-- Graphics & design, Expert tier (days 61-80). Authored content, UNPUBLISHED until a person reviews it in Admin.
insert into public.day
  (track_id, tier_id, day_number, title, objective, lesson_md, skill_focus, assignment_md, rubric,
   est_minutes, is_published, credit_budget, submission_type, ai_evaluate, requires_review)
select t.id, ti.id, v.n, v.title, v.objective, v.lesson_md, v.skill_focus, v.assignment_md, v.rubric,
       v.est_minutes, false, null, v.submission_type, v.ai_evaluate, v.requires_review
from public.track t
join public.tier ti on ti.track_id = t.id and ti.slug = 'expert'
cross join (values
  (61, $t61a$Design strategy and brand positioning$t61a$, $t61b$Turn a business goal into a design direction.$t61b$, $t61c$Design strategy starts with the audience and the market, not the mood board. Define who you serve, what you replace, and the one feeling and idea the brand owns. Then translate them into visual principles you can test.

**Sharing images:** paste *direct* links ending .png/.jpg/.webp, one per line.$t61c$, $t61d$Design strategy and brand positioning$t61d$, $t61e$For a real or realistic brand, submit a one-page strategy: audience, positioning, three design principles and what they rule out.$t61e$, $t61f$[{"criterion": "Positioning clear", "max_points": 35, "guidance": "Distinct."}, {"criterion": "Principles testable", "max_points": 40, "guidance": "Actionable."}, {"criterion": "Rules out options", "max_points": 25, "guidance": "Trade-offs."}]$t61f$::jsonb, 50, 'text', false, false),
  (62, $t62a$Design systems: tokens, components, rules$t62a$, $t62b$Build a system that keeps a team consistent.$t62b$, $t62c$A design system is shared decisions: tokens (colour, type, spacing), components (buttons, cards, posts) and rules (when to use what). Name things by purpose, not appearance, and document with examples.

**Sharing images:** paste *direct* links ending .png/.jpg/.webp, one per line.$t62c$, $t62d$Design systems: tokens, components, rules$t62d$, $t62e$Create a token set and three components with usage rules. Submit direct links to the system sheet and examples.$t62e$, $t62f$[{"criterion": "Tokens organised", "max_points": 30, "guidance": "Purpose names."}, {"criterion": "Components consistent", "max_points": 40, "guidance": "Usable."}, {"criterion": "Rules documented", "max_points": 30, "guidance": "Clear."}]$t62f$::jsonb, 90, 'link', false, false),
  (63, $t63a$Accessibility in visual design$t63a$, $t63b$Design for everyone.$t63b$, $t63c$Follow contrast guidance, do not rely on colour alone, keep text sizes readable, provide alt text and test with simulations for colour blindness. Accessibility improves clarity for all.

**Sharing images:** paste *direct* links ending .png/.jpg/.webp, one per line.$t63c$, $t63d$Accessibility in visual design$t63d$, $t63e$Audit one design against five accessibility checks and fix it. Submit before and after links and the audit table.$t63e$, $t63f$[{"criterion": "Checks real", "max_points": 35, "guidance": "Five."}, {"criterion": "Fixes effective", "max_points": 40, "guidance": "Better."}, {"criterion": "Documented", "max_points": 25, "guidance": "Table."}]$t63f$::jsonb, 60, 'link', false, false),
  (64, $t64a$AI pipelines for design production at scale$t64a$, $t64b$Produce many on-brand assets reliably.$t64b$, $t64c$Build a pipeline: brief template, style prompt block, reference images, generation, QA checklist, edit, export and naming. Track failure rate and cost per approved asset.

**Sharing images:** paste *direct* links ending .png/.jpg/.webp, one per line.$t64c$, $t64d$AI pipelines for design production at scale$t64d$, $t64e$Produce ten assets through a documented pipeline. Submit the pipeline, direct links to five of them and the approval rate and cost.$t64e$, $t64f$[{"criterion": "Pipeline documented", "max_points": 30, "guidance": "Steps."}, {"criterion": "Consistent output", "max_points": 40, "guidance": "On brand."}, {"criterion": "Metrics real", "max_points": 30, "guidance": "Rate and cost."}]$t64f$::jsonb, 90, 'link', false, false),
  (65, $t65a$Expert project 1: a design system for a brand$t65a$, $t65b$Deliver a system a team can use.$t65b$, $t65c$Show Module 1. Deliver a **design system**: strategy, tokens, components, accessibility audit and an AI production pipeline with samples.

Your work is scored on the rubric below. You can revise and resubmit.

**Sharing images:** paste *direct* links ending .png/.jpg/.webp, one per line.$t65c$, $t65d$Expert project 1: a design system for a brand$t65d$, $t65e$Submit direct links to the system sheets and sample assets, plus the strategy and pipeline notes.$t65e$, $t65f$[{"criterion": "Strategy to system logic", "max_points": 25, "guidance": "Coherent."}, {"criterion": "System quality", "max_points": 30, "guidance": "Usable."}, {"criterion": "Accessibility", "max_points": 20, "guidance": "Handled."}, {"criterion": "Pipeline and samples", "max_points": 25, "guidance": "Consistent."}]$t65f$::jsonb, 150, 'link', true, false),
  (66, $t66a$Advanced typography$t66a$, $t66b$Set type with precision.$t66b$, $t66c$Control line length (45 to 75 characters), leading, tracking, hierarchy and rag. Pair by contrast and shared proportions. Test at small sizes and on mobile.

**Sharing images:** paste *direct* links ending .png/.jpg/.webp, one per line.$t66c$, $t66d$Advanced typography$t66d$, $t66e$Design a typographic page with clear hierarchy and annotate five decisions. Submit direct links.$t66e$, $t66f$[{"criterion": "Hierarchy and rhythm", "max_points": 40, "guidance": "Clear."}, {"criterion": "Legibility", "max_points": 35, "guidance": "Tested."}, {"criterion": "Decisions explained", "max_points": 25, "guidance": "Annotated."}]$t66f$::jsonb, 60, 'link', false, false),
  (67, $t67a$Art directing photography and imagery$t67a$, $t67b$Direct AI and real photos toward one look.$t67b$, $t67c$Write a shot list with subject, framing, light, palette and mood. Use consistent references and grade for unity. Reject shots that do not serve the story, however pretty.

**Sharing images:** paste *direct* links ending .png/.jpg/.webp, one per line.$t67c$, $t67d$Art directing photography and imagery$t67d$, $t67e$Create a six-image set from a shot list. Submit direct links, the shot list and your rejection criteria.$t67e$, $t67f$[{"criterion": "Look consistent", "max_points": 40, "guidance": "Unified."}, {"criterion": "Shot list purposeful", "max_points": 30, "guidance": "Reasoned."}, {"criterion": "Curation", "max_points": 30, "guidance": "Selective."}]$t67f$::jsonb, 90, 'link', false, false),
  (68, $t68a$Illustration and style development$t68a$, $t68b$Create a distinctive, repeatable illustration style.$t68b$, $t68c$Define shape language, line, colour limits, texture and character proportion. Produce a style sheet and a set of variants; check that others could reproduce it.

**Sharing images:** paste *direct* links ending .png/.jpg/.webp, one per line.$t68c$, $t68d$Illustration and style development$t68d$, $t68e$Create a style sheet and four illustrations. Submit direct links and the reusable prompt block.$t68e$, $t68f$[{"criterion": "Distinct style", "max_points": 35, "guidance": "Recognisable."}, {"criterion": "Consistent set", "max_points": 40, "guidance": "Cohesive."}, {"criterion": "Reproducible", "max_points": 25, "guidance": "Prompt block."}]$t68f$::jsonb, 90, 'link', false, false),
  (69, $t69a$Editorial and multi-page layout$t69a$, $t69b$Design for reading across pages.$t69b$, $t69c$Use a grid, baseline rhythm, consistent styles and pacing (full-bleed image, text, pull quote). Plan spreads together and check the flow.

**Sharing images:** paste *direct* links ending .png/.jpg/.webp, one per line.$t69c$, $t69d$Editorial and multi-page layout$t69d$, $t69e$Design a four-page layout. Submit direct links to each page and the grid notes.$t69e$, $t69f$[{"criterion": "Flow and pacing", "max_points": 35, "guidance": "Works."}, {"criterion": "Grid discipline", "max_points": 35, "guidance": "Consistent."}, {"criterion": "Typography", "max_points": 30, "guidance": "Readable."}]$t69f$::jsonb, 90, 'link', false, false),
  (70, $t70a$Expert project 2: a complete brand identity$t70a$, $t70b$Deliver an identity with logo, type, colour, imagery and applications.$t70b$, $t70c$Show Module 2. Deliver a **brand identity**: logo (vectorised), palette, type, illustration or photo style and five applications.

Your work is scored on the rubric below. You can revise and resubmit.

**Sharing images:** paste *direct* links ending .png/.jpg/.webp, one per line.$t70c$, $t70d$Expert project 2: a complete brand identity$t70d$, $t70e$Submit direct links to the identity sheet and five applications, with your rationale (200 words).$t70e$, $t70f$[{"criterion": "Distinct and appropriate", "max_points": 30, "guidance": "Fits brief."}, {"criterion": "System coherence", "max_points": 30, "guidance": "Consistent."}, {"criterion": "Craft", "max_points": 25, "guidance": "Refined."}, {"criterion": "Rationale", "max_points": 15, "guidance": "Reasoned."}]$t70f$::jsonb, 180, 'link', true, false),
  (71, $t71a$Pricing and packaging design services$t71a$, $t71b$Charge for value and scope.$t71b$, $t71c$Price by deliverable and outcome, define revisions, licences and usage rights, and separate strategy from production. Explain AI use to clients where relevant.$t71c$, $t71d$Pricing and packaging design services$t71d$, $t71e$Write a proposal for a brand identity: scope, phases, price, revision limits and usage rights.$t71e$, $t71f$[{"criterion": "Scope clear", "max_points": 35, "guidance": "Precise."}, {"criterion": "Rights defined", "max_points": 35, "guidance": "Usage."}, {"criterion": "Price logic", "max_points": 30, "guidance": "Reasoned."}]$t71f$::jsonb, 45, 'text', false, false),
  (72, $t72a$IP, licensing and AI imagery risk$t72a$, $t72b$Deliver work that is safe to use.$t72b$, $t72c$Check tool terms for commercial use, avoid resemblance to protected marks and characters, keep records of prompts and edits, and know the limits of what you can promise about ownership. Get legal advice for high-stakes work. This course is not legal advice.$t72c$, $t72d$IP, licensing and AI imagery risk$t72d$, $t72e$Create a delivery checklist for rights and originality (eight items) and apply it to one asset.$t72e$, $t72f$[{"criterion": "Checklist real", "max_points": 40, "guidance": "Specific."}, {"criterion": "Applied", "max_points": 35, "guidance": "Evidence."}, {"criterion": "Limits stated", "max_points": 25, "guidance": "Honest."}]$t72f$::jsonb, 45, 'text', false, false),
  (73, $t73a$Critique and art direction language$t73a$, $t73b$Give direction that improves work.$t73b$, $t73c$Critique the work against the goal, not personal taste. Use specific language (hierarchy, contrast, rhythm), point to the location and suggest options. Ask questions before prescribing.$t73c$, $t73d$Critique and art direction language$t73d$, $t73e$Critique three designs (yours or public) in 100 words each with one prioritised change.$t73e$, $t73f$[{"criterion": "Specific vocabulary", "max_points": 35, "guidance": "Precise."}, {"criterion": "Tied to goals", "max_points": 35, "guidance": "Purposeful."}, {"criterion": "Prioritised change", "max_points": 30, "guidance": "Actionable."}]$t73f$::jsonb, 45, 'text', false, false),
  (74, $t74a$Running a design review$t74a$, $t74b$Lead a review that ends with decisions.$t74b$, $t74c$Share context and goals first, review against criteria, record decisions and owners and set the next review. Keep it short and respectful.$t74c$, $t74d$Running a design review$t74d$, $t74e$Write a review agenda, criteria list and decision log template, and run one review with a peer.$t74e$, $t74f$[{"criterion": "Structure clear", "max_points": 35, "guidance": "Agenda."}, {"criterion": "Criteria and log", "max_points": 35, "guidance": "Practical."}, {"criterion": "Run for real", "max_points": 30, "guidance": "Peer review."}]$t74f$::jsonb, 45, 'text', false, false),
  (75, $t75a$Expert project 3: art direction of a set$t75a$, $t75b$Direct a team-style set to one standard.$t75b$, $t75c$Show Module 3. Art-direct a **set of eight assets** to a brief: write the direction, produce or generate the assets, critique them and revise.

Your work is scored on the rubric below. You can revise and resubmit.

**Sharing images:** paste *direct* links ending .png/.jpg/.webp, one per line.$t75c$, $t75d$Expert project 3: art direction of a set$t75d$, $t75e$Submit direct links to before and after for three assets, the direction brief, your critique notes and the final set.$t75e$, $t75f$[{"criterion": "Direction clear", "max_points": 25, "guidance": "Specific."}, {"criterion": "Set consistent", "max_points": 30, "guidance": "Unified."}, {"criterion": "Critique and revision", "max_points": 25, "guidance": "Improved."}, {"criterion": "Rights and accessibility", "max_points": 20, "guidance": "Handled."}]$t75f$::jsonb, 150, 'link', true, false),
  (76, $t76a$Flagship campaign: research and concept$t76a$, $t76b$Start a campaign with insight.$t76b$, $t76c$Research the audience, competitors and context. Find one insight and a big idea that dramatises it. Write the concept in a sentence and test it on five people.

**Sharing images:** paste *direct* links ending .png/.jpg/.webp, one per line.$t76c$, $t76d$Flagship campaign: research and concept$t76d$, $t76e$Submit research notes, the insight, the big idea and five tester reactions.$t76e$, $t76f$[{"criterion": "Insight real", "max_points": 40, "guidance": "Grounded."}, {"criterion": "Idea strong", "max_points": 35, "guidance": "Clear."}, {"criterion": "Tested", "max_points": 25, "guidance": "Five reactions."}]$t76f$::jsonb, 90, 'text', false, false),
  (77, $t77a$Flagship campaign: design language and key visual$t77a$, $t77b$Create the anchor visual.$t77b$, $t77c$Build the key visual and the rules that let it extend: layout, type, colour, imagery, tone of voice. Test at social, print and screen sizes.

**Sharing images:** paste *direct* links ending .png/.jpg/.webp, one per line.$t77c$, $t77d$Flagship campaign: design language and key visual$t77d$, $t77e$Submit direct links to the key visual and its rule sheet.$t77e$, $t77f$[{"criterion": "Key visual strong", "max_points": 40, "guidance": "Striking."}, {"criterion": "Rules extensible", "max_points": 35, "guidance": "Scalable."}, {"criterion": "Tested at sizes", "max_points": 25, "guidance": "Works."}]$t77f$::jsonb, 120, 'link', false, false),
  (78, $t78a$Flagship campaign: the full set$t78a$, $t78b$Produce the campaign across channels.$t78b$, $t78c$Extend the key visual to social, ad, email header, print and a landing hero. Keep messages consistent and check specs.

**Sharing images:** paste *direct* links ending .png/.jpg/.webp, one per line.$t78c$, $t78d$Flagship campaign: the full set$t78d$, $t78e$Submit direct links to at least six pieces across four formats.$t78e$, $t78f$[{"criterion": "Consistency", "max_points": 40, "guidance": "One campaign."}, {"criterion": "Format fit", "max_points": 35, "guidance": "Correct."}, {"criterion": "Message clear", "max_points": 25, "guidance": "Coherent."}]$t78f$::jsonb, 150, 'link', false, false),
  (79, $t79a$Flagship campaign: launch and measure$t79a$, $t79b$Publish and learn.$t79b$, $t79c$Launch a small real or simulated version, define success metrics, collect results and note what to change.

**Sharing images:** paste *direct* links ending .png/.jpg/.webp, one per line.$t79c$, $t79d$Flagship campaign: launch and measure$t79d$, $t79e$Submit launch evidence (links or screenshots), metrics and lessons.$t79e$, $t79f$[{"criterion": "Launched", "max_points": 30, "guidance": "Real."}, {"criterion": "Metrics honest", "max_points": 40, "guidance": "Numbers."}, {"criterion": "Lessons useful", "max_points": 30, "guidance": "Applied."}]$t79f$::jsonb, 90, 'link', false, false),
  (80, $t80a$Expert project 4: the flagship campaign$t80a$, $t80b$Deliver a campaign with proof of thinking and results.$t80b$, $t80c$Show Module 4. Deliver a **flagship campaign**: research, big idea, key visual, full set, accessibility and rights checks, and results.

Your work is scored on the rubric below. You can revise and resubmit.

**Sharing images:** paste *direct* links ending .png/.jpg/.webp, one per line.$t80c$, $t80d$Expert project 4: the flagship campaign$t80d$, $t80e$Submit direct links to the key visual and campaign set (one per line), plus the brief, insight, results and a 200-word rationale.$t80e$, $t80f$[{"criterion": "Insight and idea", "max_points": 25, "guidance": "Strong."}, {"criterion": "Visual craft and consistency", "max_points": 30, "guidance": "Excellent."}, {"criterion": "Accessibility and rights", "max_points": 20, "guidance": "Handled."}, {"criterion": "Results and honesty", "max_points": 25, "guidance": "Measured."}]$t80f$::jsonb, 200, 'link', true, false)
) as v(n, title, objective, lesson_md, skill_focus, assignment_md, rubric, est_minutes, submission_type, ai_evaluate, requires_review)
where t.slug = 'graphics'
on conflict (track_id, day_number) do nothing;
