-- Apps & tools, Pro tier (days 31-60). Authored content, UNPUBLISHED until a person reviews it in Admin.
insert into public.day
  (track_id, tier_id, day_number, title, objective, lesson_md, skill_focus, assignment_md, rubric,
   est_minutes, is_published, credit_budget, submission_type, ai_evaluate, requires_review)
select t.id, ti.id, v.n, v.title, v.objective, v.lesson_md, v.skill_focus, v.assignment_md, v.rubric,
       v.est_minutes, false, null, v.submission_type, v.ai_evaluate, v.requires_review
from public.track t
join public.tier ti on ti.track_id = t.id and ti.slug = 'pro'
cross join (values
  (31, $t31a$Find a problem worth solving$t31a$, $t31b$Validate that people want a tool before building it.$t31b$, $t31c$Most tools fail because nobody needed them. Before building, find five people with the problem, ask how they solve it today, and what it costs them in time or money. Look for people already using spreadsheets, email threads or paper.$t31c$, $t31d$Find a problem worth solving$t31d$, $t31e$Interview five people. Submit their current workaround, the pain (time/money) and whether they would use a tool.$t31e$, $t31f$[{"criterion": "Real conversations", "max_points": 40, "guidance": "Five."}, {"criterion": "Pain quantified", "max_points": 35, "guidance": "Numbers."}, {"criterion": "Honest verdict", "max_points": 25, "guidance": "Includes doubts."}]$t31f$::jsonb, 40, 'text', false, false),
  (32, $t32a$Define the smallest useful version$t32a$, $t32b$Cut a product to its core.$t32b$, $t32c$A minimum viable product does one job end to end. List every feature you imagine, mark each must/should/could, and build only the musts. Write what success looks like in numbers (for example 10 users complete the task).$t32c$, $t32d$Define the smallest useful version$t32d$, $t32e$Submit a MoSCoW feature list, the v1 scope and a success measure.$t32e$, $t32f$[{"criterion": "Ruthless scope", "max_points": 40, "guidance": "Small v1."}, {"criterion": "Priorities reasoned", "max_points": 30, "guidance": "Clear."}, {"criterion": "Measurable success", "max_points": 30, "guidance": "Numbers."}]$t32f$::jsonb, 20, 'text', false, false),
  (33, $t33a$User flows and wireframes$t33a$, $t33b$Plan screens before generating them.$t33b$, $t33c$Draw the flow from the first click to done. Sketch each screen with the main action obvious. Test the wireframe on paper with a friend before building.$t33c$, $t33d$User flows and wireframes$t33d$, $t33e$Submit a user flow and wireframes (direct image links) and what a tester struggled with.

**Evidence:** paste *direct* links to screenshots (ending .png/.jpg/.webp), one per line, and describe what they show.$t33e$, $t33f$[{"criterion": "Flow is complete", "max_points": 40, "guidance": "Start to finish."}, {"criterion": "Screens clear", "max_points": 30, "guidance": "Main action obvious."}, {"criterion": "Tested", "max_points": 30, "guidance": "Real tester."}]$t33f$::jsonb, 20, 'link', false, false),
  (34, $t34a$Prompt specs for builders$t34a$, $t34b$Write a spec an AI builder can execute reliably.$t34b$, $t34c$A spec lists screens, components, data, rules, edge cases and acceptance tests ("When a user submits an empty form, show an error and keep the data"). Build screen by screen and check each against its tests.$t34c$, $t34d$Prompt specs for builders$t34d$, $t34e$Write a spec for one feature with five acceptance tests, build it and record pass/fail.$t34e$, $t34f$[{"criterion": "Spec precise", "max_points": 35, "guidance": "Unambiguous."}, {"criterion": "Acceptance tests", "max_points": 40, "guidance": "Five with results."}, {"criterion": "Honest results", "max_points": 25, "guidance": "Failures noted."}]$t34f$::jsonb, 20, 'text', false, false),
  (35, $t35a$Version control and safe changes$t35a$, $t35b$Change apps without breaking them.$t35b$, $t35c$Keep a copy or version history before big changes. Change one thing, test, then continue. Write a changelog. If the platform offers rollback, practise it once.$t35c$, $t35d$Version control and safe changes$t35d$, $t35e$Make three changes with a changelog, and practise one rollback. Submit the log.$t35e$, $t35f$[{"criterion": "Changelog clear", "max_points": 40, "guidance": "Dated."}, {"criterion": "Rollback practised", "max_points": 35, "guidance": "Shown."}, {"criterion": "Small steps", "max_points": 25, "guidance": "One change at a time."}]$t35f$::jsonb, 20, 'text', false, false),
  (36, $t36a$Module project: a validated v1$t36a$, $t36b$Ship a v1 based on real interviews.$t36b$, $t36c$Show Module 1. Deliver a **v1 tool** built from validated need: interviews, scoped features, wireframes, spec with acceptance tests.

Your work is scored on the rubric below. You can revise and resubmit.$t36c$, $t36d$Module project: a validated v1$t36d$, $t36e$Submit interview summary, v1 scope, wireframe links, acceptance test results and screenshots.

**Evidence:** paste *direct* links to screenshots (ending .png/.jpg/.webp), one per line, and describe what they show.$t36e$, $t36f$[{"criterion": "Need validated", "max_points": 25, "guidance": "Real evidence."}, {"criterion": "Scope disciplined", "max_points": 25, "guidance": "Small."}, {"criterion": "Acceptance tests", "max_points": 30, "guidance": "Results."}, {"criterion": "Tool works", "max_points": 20, "guidance": "Screenshots."}]$t36f$::jsonb, 75, 'link', true, false),
  (37, $t37a$Relational data: linking tables$t37a$, $t37b$Model relationships between things.$t37b$, $t37c$Real apps link tables: customers have orders, orders have items. Use ids to link, avoid repeating data, and decide what happens when something is deleted. Draw the relationships.$t37c$, $t37d$Relational data: linking tables$t37d$, $t37e$Design three linked tables with fields, keys and delete rules. Submit a diagram or list.$t37e$, $t37f$[{"criterion": "Relationships correct", "max_points": 45, "guidance": "Links sensible."}, {"criterion": "No duplication", "max_points": 30, "guidance": "Normalised."}, {"criterion": "Delete rules", "max_points": 25, "guidance": "Considered."}]$t37f$::jsonb, 20, 'text', false, false),
  (38, $t38a$Sign-in and accounts$t38a$, $t38b$Add authentication the safe way.$t38b$, $t38c$Use the platform's sign-in (email link, Google), never build your own password storage. Decide what logged-out visitors can see. Add password reset and sign-out. Test as two different users.$t38c$, $t38d$Sign-in and accounts$t38d$, $t38e$Add sign-in. Submit screenshots of logged-out, user A and user B views, showing they cannot see each other's data.

**Evidence:** paste *direct* links to screenshots (ending .png/.jpg/.webp), one per line, and describe what they show.$t38e$, $t38f$[{"criterion": "Sign-in works", "max_points": 30, "guidance": "Shown."}, {"criterion": "Data separated", "max_points": 50, "guidance": "A cannot see B."}, {"criterion": "Logged-out rules", "max_points": 20, "guidance": "Correct."}]$t38f$::jsonb, 20, 'link', false, false),
  (39, $t39a$Files and images in apps$t39a$, $t39b$Handle uploads safely.$t39b$, $t39c$Limit file types and sizes, store files in the platform's storage, never trust file names and consider privacy of uploads. Show upload progress and errors.$t39c$, $t39d$Files and images in apps$t39d$, $t39e$Add an upload feature with limits. Submit screenshots of success and of a rejected file.

**Evidence:** paste *direct* links to screenshots (ending .png/.jpg/.webp), one per line, and describe what they show.$t39e$, $t39f$[{"criterion": "Upload works", "max_points": 35, "guidance": "Shown."}, {"criterion": "Limits enforced", "max_points": 40, "guidance": "Rejection shown."}, {"criterion": "Privacy considered", "max_points": 25, "guidance": "Access explained."}]$t39f$::jsonb, 20, 'link', false, false),
  (40, $t40a$Payments and pricing (concepts)$t40a$, $t40b$Understand how to charge safely.$t40b$, $t40c$Use a payment provider (never handle card numbers yourself). Decide free, one-off or subscription, taxes and refunds. Test with the provider's test mode only.$t40c$, $t40d$Payments and pricing (concepts)$t40d$, $t40e$Design a pricing and payment flow (plans, checkout steps, refund policy) without collecting real card data.$t40e$, $t40f$[{"criterion": "Flow complete", "max_points": 35, "guidance": "Steps."}, {"criterion": "Provider used safely", "max_points": 40, "guidance": "No card handling."}, {"criterion": "Policies clear", "max_points": 25, "guidance": "Refunds, tax."}]$t40f$::jsonb, 20, 'text', false, false),
  (41, $t41a$Analytics that respect people$t41a$, $t41b$Measure use without spying.$t41b$, $t41c$Track a few events (signed up, completed task) with privacy-friendly analytics, explain it in your privacy note and honour consent rules. Decide which numbers change decisions.$t41c$, $t41d$Analytics that respect people$t41d$, $t41e$Define five events, the question each answers and how you respect privacy.$t41e$, $t41f$[{"criterion": "Events useful", "max_points": 40, "guidance": "Answer questions."}, {"criterion": "Privacy respected", "max_points": 40, "guidance": "Consent."}, {"criterion": "Decisions linked", "max_points": 20, "guidance": "Actionable."}]$t41f$::jsonb, 20, 'text', false, false),
  (42, $t42a$Module project: a multi-user app$t42a$, $t42b$Build an app with accounts, linked data and uploads.$t42b$, $t42c$Show Module 2. Deliver a **multi-user app** with sign-in, linked tables, data separation and one file feature.

Your work is scored on the rubric below. You can revise and resubmit.$t42c$, $t42d$Module project: a multi-user app$t42d$, $t42e$Submit data diagram, screenshots for two users, upload evidence and privacy note.

**Evidence:** paste *direct* links to screenshots (ending .png/.jpg/.webp), one per line, and describe what they show.$t42e$, $t42f$[{"criterion": "Data model", "max_points": 25, "guidance": "Sound."}, {"criterion": "Accounts and separation", "max_points": 35, "guidance": "Proven."}, {"criterion": "File handling", "max_points": 20, "guidance": "Safe."}, {"criterion": "Privacy", "max_points": 20, "guidance": "Stated."}]$t42f$::jsonb, 90, 'link', true, false),
  (43, $t43a$AI features that earn their place$t43a$, $t43b$Choose where AI truly helps users.$t43b$, $t43c$Good AI features save clear time: drafting, summarising, classifying, extracting. Bad ones are gimmicks. For each idea ask: what does the user do today, how good must the AI be, what if it is wrong?$t43c$, $t43d$AI features that earn their place$t43d$, $t43e$Evaluate three AI feature ideas for your app with these questions and pick one.$t43e$, $t43f$[{"criterion": "Honest evaluation", "max_points": 45, "guidance": "Includes risks."}, {"criterion": "Wrong-answer plan", "max_points": 30, "guidance": "Fallback."}, {"criterion": "Choice reasoned", "max_points": 25, "guidance": "Justified."}]$t43f$::jsonb, 20, 'text', false, false),
  (44, $t44a$Prompts as product code$t44a$, $t44b$Treat prompts as versioned, tested assets.$t44b$, $t44c$Store prompts with versions, add examples, define the output format (for example JSON) and test on a set of 10 real inputs. Track failures and change one thing at a time.$t44c$, $t44d$Prompts as product code$t44d$, $t44e$Submit a prompt (v1 and v2), ten test inputs with pass/fail and what changed.$t44e$, $t44f$[{"criterion": "Versioned", "max_points": 25, "guidance": "Two."}, {"criterion": "Test set real", "max_points": 40, "guidance": "Ten."}, {"criterion": "Improvement shown", "max_points": 35, "guidance": "Better."}]$t44f$::jsonb, 20, 'text', false, false),
  (45, $t45a$Guardrails and abuse prevention$t45a$, $t45b$Stop misuse of AI features.$t45b$, $t45c$Users may try to make your AI do harmful things or leak instructions. Limit scope in the prompt, validate outputs, rate limit, log, and never put secrets in prompts. Test with hostile inputs.$t45c$, $t45d$Guardrails and abuse prevention$t45d$, $t45e$Test your AI feature with five hostile inputs. Submit inputs, results and protections added.$t45e$, $t45f$[{"criterion": "Hostile tests real", "max_points": 40, "guidance": "Five."}, {"criterion": "Protections added", "max_points": 40, "guidance": "Concrete."}, {"criterion": "Honest results", "max_points": 20, "guidance": "Failures reported."}]$t45f$::jsonb, 20, 'text', false, false),
  (46, $t46a$Cost control for AI features$t46a$, $t46b$Keep AI spend predictable.$t46b$, $t46c$Estimate cost per use, cache repeated answers, use smaller models where possible, cap per-user usage and alert on spikes.$t46c$, $t46d$Cost control for AI features$t46d$, $t46e$Calculate cost per use and per 1,000 users and list three controls you will add.$t46e$, $t46f$[{"criterion": "Calculation sensible", "max_points": 40, "guidance": "Numbers."}, {"criterion": "Controls practical", "max_points": 40, "guidance": "Three."}, {"criterion": "Assumptions stated", "max_points": 20, "guidance": "Clear."}]$t46f$::jsonb, 20, 'text', false, false),
  (47, $t47a$Evaluating quality of AI output$t47a$, $t47b$Measure whether the AI feature works.$t47b$, $t47c$Define what good looks like, build a small scoring sheet, sample outputs weekly and track user edits or thumbs down.$t47c$, $t47d$Evaluating quality of AI output$t47d$, $t47e$Create a quality rubric (four criteria) and score ten outputs. Submit the sheet.$t47e$, $t47f$[{"criterion": "Rubric clear", "max_points": 35, "guidance": "Four criteria."}, {"criterion": "Scores honest", "max_points": 40, "guidance": "Ten."}, {"criterion": "Action taken", "max_points": 25, "guidance": "Improvement."}]$t47f$::jsonb, 20, 'text', false, false),
  (48, $t48a$Module project: an AI-powered feature$t48a$, $t48b$Ship an AI feature with guardrails and evaluation.$t48b$, $t48c$Show Module 3. Deliver an **AI feature** with a versioned prompt, guardrails, cost estimate and quality evaluation.

Your work is scored on the rubric below. You can revise and resubmit.$t48c$, $t48d$Module project: an AI-powered feature$t48d$, $t48e$Submit prompt versions, hostile tests, cost estimate, quality scores and screenshots.

**Evidence:** paste *direct* links to screenshots (ending .png/.jpg/.webp), one per line, and describe what they show.$t48e$, $t48f$[{"criterion": "Feature useful", "max_points": 20, "guidance": "Solves a job."}, {"criterion": "Guardrails tested", "max_points": 30, "guidance": "Evidence."}, {"criterion": "Cost and quality", "max_points": 30, "guidance": "Measured."}, {"criterion": "Honest limits", "max_points": 20, "guidance": "Stated."}]$t48f$::jsonb, 90, 'link', true, false),
  (49, $t49a$Onboarding and first-run experience$t49a$, $t49b$Get users to value fast.$t49b$, $t49c$New users need to reach their first success quickly. Reduce steps, show an example, explain in one sentence and remove anything not needed on day one.$t49c$, $t49d$Onboarding and first-run experience$t49d$, $t49e$Redesign your first-run flow and measure steps-to-first-success before and after.

**Evidence:** paste *direct* links to screenshots (ending .png/.jpg/.webp), one per line, and describe what they show.$t49e$, $t49f$[{"criterion": "Fewer steps", "max_points": 40, "guidance": "Measured."}, {"criterion": "Clear guidance", "max_points": 30, "guidance": "Helpful."}, {"criterion": "Tested", "max_points": 30, "guidance": "Real users."}]$t49f$::jsonb, 20, 'link', false, false),
  (50, $t50a$Reliability: monitoring and backups$t50a$, $t50b$Know when it breaks and recover.$t50b$, $t50c$Set uptime checks, error alerts and regular backups of data. Practise restoring. Write what you do if the app goes down.$t50c$, $t50d$Reliability: monitoring and backups$t50d$, $t50e$Set up monitoring and a backup, write an incident note template and describe a restore test.$t50e$, $t50f$[{"criterion": "Monitoring in place", "max_points": 35, "guidance": "Evidence."}, {"criterion": "Backup and restore", "max_points": 40, "guidance": "Tested."}, {"criterion": "Incident plan", "max_points": 25, "guidance": "Written."}]$t50f$::jsonb, 20, 'text', false, false),
  (51, $t51a$Support and feedback loops$t51a$, $t51b$Handle users after launch.$t51b$, $t51c$Give an easy way to report problems, respond within a stated time, tag feedback by theme and review weekly. Close the loop by telling users what you fixed.$t51c$, $t51d$Support and feedback loops$t51d$, $t51e$Set up a feedback channel and triage ten items into themes with actions.$t51e$, $t51f$[{"criterion": "Channel easy", "max_points": 30, "guidance": "Simple."}, {"criterion": "Triage useful", "max_points": 40, "guidance": "Themes."}, {"criterion": "Loop closed", "max_points": 30, "guidance": "Users told."}]$t51f$::jsonb, 20, 'text', false, false),
  (52, $t52a$Legal basics for tool builders$t52a$, $t52b$Cover terms, privacy and licences.$t52b$, $t52c$Publish terms and a privacy policy, check licences of libraries and assets, and know duties around personal data in your users' countries. Get legal advice for anything significant. This course is not legal advice.$t52c$, $t52d$Legal basics for tool builders$t52d$, $t52e$Draft terms and privacy summaries for your tool (one page each) and list third-party licences.$t52e$, $t52f$[{"criterion": "Terms and privacy clear", "max_points": 45, "guidance": "Plain."}, {"criterion": "Licences listed", "max_points": 30, "guidance": "Real."}, {"criterion": "Advice noted", "max_points": 25, "guidance": "Limits known."}]$t52f$::jsonb, 20, 'text', false, false),
  (53, $t53a$Distribution: getting your first users$t53a$, $t53b$Reach people who need it.$t53b$, $t53c$Go where the problem is discussed, offer to solve it for a few people personally, ask for feedback and referrals. Avoid spam.$t53c$, $t53d$Distribution: getting your first users$t53d$, $t53e$Write a distribution plan for 20 first users with channels and a message.$t53e$, $t53f$[{"criterion": "Channels appropriate", "max_points": 40, "guidance": "Where users are."}, {"criterion": "Message honest", "max_points": 35, "guidance": "No spam."}, {"criterion": "Measurable", "max_points": 25, "guidance": "Targets."}]$t53f$::jsonb, 20, 'text', false, false),
  (54, $t54a$Module project: launch a public beta$t54a$, $t54b$Launch to real users with support and monitoring.$t54b$, $t54c$Show Module 4. Launch a **public beta**: onboarding, monitoring, feedback channel, legal basics and 10 real users.

Your work is scored on the rubric below. You can revise and resubmit.$t54c$, $t54d$Module project: launch a public beta$t54d$, $t54e$Submit screenshots, user counts, feedback themes, the monitoring setup and what you changed after launch.

**Evidence:** paste *direct* links to screenshots (ending .png/.jpg/.webp), one per line, and describe what they show.$t54e$, $t54f$[{"criterion": "Real users", "max_points": 30, "guidance": "Evidence."}, {"criterion": "Operations ready", "max_points": 25, "guidance": "Monitoring, support."}, {"criterion": "Learning applied", "max_points": 25, "guidance": "Changes."}, {"criterion": "Legal and privacy", "max_points": 20, "guidance": "Handled."}]$t54f$::jsonb, 90, 'link', true, false),
  (55, $t55a$Pro capstone 1: pick and validate$t55a$, $t55b$Choose a product opportunity with evidence.$t55b$, $t55c$Pick a real problem, interview ten people and write a one-page product brief.$t55c$, $t55d$Pro capstone 1: pick and validate$t55d$, $t55e$Submit interview summary and the brief.$t55e$, $t55f$[{"criterion": "Evidence", "max_points": 40, "guidance": "Ten interviews."}, {"criterion": "Brief clear", "max_points": 35, "guidance": "Complete."}, {"criterion": "Realistic", "max_points": 25, "guidance": "Feasible."}]$t55f$::jsonb, 20, 'text', false, false),
  (56, $t56a$Pro capstone 2: design and data$t56a$, $t56b$Plan screens, data and permissions.$t56b$, $t56c$Create wireframes, a data model and a permissions table.$t56c$, $t56d$Pro capstone 2: design and data$t56d$, $t56e$Submit all three.

**Evidence:** paste *direct* links to screenshots (ending .png/.jpg/.webp), one per line, and describe what they show.$t56e$, $t56f$[{"criterion": "Coherent design", "max_points": 40, "guidance": "Consistent."}, {"criterion": "Data and permissions", "max_points": 40, "guidance": "Correct."}, {"criterion": "Simple", "max_points": 20, "guidance": "Not overbuilt."}]$t56f$::jsonb, 20, 'link', false, false),
  (57, $t57a$Pro capstone 3: build v1$t57a$, $t57b$Build the core with accounts.$t57b$, $t57c$Build v1 with sign-in, core flow and data separation.$t57c$, $t57d$Pro capstone 3: build v1$t57d$, $t57e$Submit screenshots and acceptance test results.

**Evidence:** paste *direct* links to screenshots (ending .png/.jpg/.webp), one per line, and describe what they show.$t57e$, $t57f$[{"criterion": "Core works", "max_points": 45, "guidance": "Shown."}, {"criterion": "Accounts safe", "max_points": 35, "guidance": "Separated."}, {"criterion": "Tests", "max_points": 20, "guidance": "Results."}]$t57f$::jsonb, 75, 'link', false, false),
  (58, $t58a$Pro capstone 4: AI feature and guardrails$t58a$, $t58b$Add an AI feature safely.$t58b$, $t58c$Add one AI feature with guardrails, cost limits and a quality check.$t58c$, $t58d$Pro capstone 4: AI feature and guardrails$t58d$, $t58e$Submit prompt, guardrail tests, cost estimate and quality scores.$t58e$, $t58f$[{"criterion": "Useful", "max_points": 30, "guidance": "Solves a job."}, {"criterion": "Guardrails", "max_points": 40, "guidance": "Tested."}, {"criterion": "Cost and quality", "max_points": 30, "guidance": "Measured."}]$t58f$::jsonb, 60, 'text', false, false),
  (59, $t59a$Pro capstone 5: beta with real users$t59a$, $t59b$Launch to ten users and learn.$t59b$, $t59c$Launch to at least ten real users, collect feedback and fix the top issues.$t59c$, $t59d$Pro capstone 5: beta with real users$t59d$, $t59e$Submit user feedback themes, changes made and usage numbers.$t59e$, $t59f$[{"criterion": "Real users", "max_points": 40, "guidance": "Ten."}, {"criterion": "Fixes", "max_points": 35, "guidance": "Specific."}, {"criterion": "Numbers", "max_points": 25, "guidance": "Recorded."}]$t59f$::jsonb, 20, 'text', false, false),
  (60, $t60a$Pro capstone 6: case study and handover$t60a$, $t60b$Document the product and its operation.$t60b$, $t60c$Write a case study and an operations page: monitoring, backups, support, costs, roadmap. Share in the Discord and ask for one piece of feedback.

Your work is scored on the rubric below. You can revise and resubmit.$t60c$, $t60d$Pro capstone 6: case study and handover$t60d$, $t60e$Submit the case study (problem, evidence, build, results, lessons) and the operations page.$t60e$, $t60f$[{"criterion": "Evidence and results", "max_points": 30, "guidance": "Numbers."}, {"criterion": "Operations and safety", "max_points": 30, "guidance": "Ready."}, {"criterion": "Honest lessons", "max_points": 20, "guidance": "Frank."}, {"criterion": "Clarity", "max_points": 20, "guidance": "Well written."}]$t60f$::jsonb, 90, 'text', true, false)
) as v(n, title, objective, lesson_md, skill_focus, assignment_md, rubric, est_minutes, submission_type, ai_evaluate, requires_review)
where t.slug = 'apps'
on conflict (track_id, day_number) do nothing;
