-- Audio, music & voice, Basic tier (days 1-30). Authored content, UNPUBLISHED until a person reviews it in Admin.
insert into public.day
  (track_id, tier_id, day_number, title, objective, lesson_md, skill_focus, assignment_md, rubric,
   est_minutes, is_published, credit_budget, submission_type, ai_evaluate, requires_review)
select t.id, ti.id, v.n, v.title, v.objective, v.lesson_md, v.skill_focus, v.assignment_md, v.rubric,
       v.est_minutes, false, null, v.submission_type, v.ai_evaluate, v.requires_review
from public.track t
join public.tier ti on ti.track_id = t.id and ti.slug = 'basic'
cross join (values
  (1, $t1a$How AI makes voice and music$t1a$, $t1b$Explain what audio AI can do, and what it must not do.$t1b$, $t1c$AI can turn text into speech, generate music, clean noise, translate and change voices. It can also imitate real people, which creates legal and ethical limits. Learn the craft first: clear script, good pacing, clean sound.

Start with [CREAO](https://agent.creao.ai/@Sonofpeace) (referral link) for scripts and planning, then voice and music tools such as ElevenLabs, Suno, Udio, Adobe Podcast and Audacity for editing. Always read each tool's commercial-use terms.$t1c$, $t1d$How AI makes voice and music$t1d$, $t1e$List five audio jobs you could do (for example narration, podcast intro, jingle). For each name the tool type and one rule you must follow.$t1e$, $t1f$[{"criterion": "Realistic jobs", "max_points": 35, "guidance": "Practical."}, {"criterion": "Tool types correct", "max_points": 30, "guidance": "Sensible."}, {"criterion": "Rules identified", "max_points": 35, "guidance": "Consent, licence or disclosure."}]$t1f$::jsonb, 15, 'text', false, false),
  (2, $t2a$Write for the ear$t2a$, $t2b$Turn writing into speakable script.$t2b$, $t2c$Spoken words need short sentences, simple words, contractions and rhythm. Read aloud, mark breaths and stresses. Numbers and names need pronunciation notes.$t2c$, $t2d$Write for the ear$t2d$, $t2e$Rewrite a 120-word written paragraph for speaking. Submit both and mark three changes.$t2e$, $t2f$[{"criterion": "Sounds natural", "max_points": 45, "guidance": "Speakable."}, {"criterion": "Changes marked", "max_points": 30, "guidance": "Three."}, {"criterion": "Meaning kept", "max_points": 25, "guidance": "Faithful."}]$t2f$::jsonb, 20, 'text', false, false),
  (3, $t3a$Text to speech: choosing a voice and pacing$t3a$, $t3b$Generate clear narration.$t3b$, $t3c$Pick a voice that suits the audience, control pace with punctuation and short paragraphs, and generate in chunks. Listen to the whole thing. Fix mispronunciations with phonetic spelling.$t3c$, $t3d$Text to speech: choosing a voice and pacing$t3d$, $t3e$Generate a 45-second narration. Submit the link, script and three pronunciation or pacing fixes.

**Sharing audio:** upload to SoundCloud, Google Drive or similar (unlisted) and paste the link. Audio is checked by a person.$t3e$, $t3f$[{"criterion": "Clear and natural", "max_points": 40, "guidance": "Sounds good."}, {"criterion": "Fixes documented", "max_points": 35, "guidance": "Three."}, {"criterion": "Voice suits audience", "max_points": 25, "guidance": "Reasoned."}]$t3f$::jsonb, 20, 'link', false, true),
  (4, $t4a$Voice consent and cloning ethics$t4a$, $t4b$Know when you may and may not use a voice.$t4b$, $t4c$Never clone or imitate a real person's voice without their clear, written consent. Use voices your tool licenses to you. Disclose synthetic voice where required or expected. Do not create deceptive audio.$t4c$, $t4d$Voice consent and cloning ethics$t4d$, $t4e$Write a consent checklist for voice use (five items) and apply it to one planned project.$t4e$, $t4f$[{"criterion": "Checklist concrete", "max_points": 40, "guidance": "Five items."}, {"criterion": "Applied", "max_points": 35, "guidance": "Real project."}, {"criterion": "Disclosure covered", "max_points": 25, "guidance": "Included."}]$t4f$::jsonb, 20, 'text', false, false),
  (5, $t5a$Recording and cleaning audio$t5a$, $t5b$Record clean sound and remove noise.$t5b$, $t5c$Record in a quiet, soft room, mouth a hand-width from the mic, then trim, reduce noise and normalise loudness. Do not over-process.$t5c$, $t5d$Recording and cleaning audio$t5d$, $t5e$Record 30 seconds, clean it, and submit before and after links and the steps you used.

**Sharing audio:** upload to SoundCloud, Google Drive or similar (unlisted) and paste the link. Audio is checked by a person.$t5e$, $t5f$[{"criterion": "Clear improvement", "max_points": 45, "guidance": "After is better."}, {"criterion": "Not over-processed", "max_points": 30, "guidance": "Natural."}, {"criterion": "Steps listed", "max_points": 25, "guidance": "Clear."}]$t5f$::jsonb, 20, 'link', false, true),
  (6, $t6a$Module project: a 60-second narrated piece$t6a$, $t6b$Produce a clean narrated audio.$t6b$, $t6c$Show Module 1. Produce a **60-second narration** from a written script with clean sound and documented rights.

A person reviews your work and can ask for revisions.$t6c$, $t6d$Module project: a 60-second narrated piece$t6d$, $t6e$Submit the script, audio link, tool and licence notes, and pronunciation fixes.

**Sharing audio:** upload to SoundCloud, Google Drive or similar (unlisted) and paste the link. Audio is checked by a person.$t6e$, $t6f$[{"criterion": "Clarity and pacing", "max_points": 35, "guidance": "Easy to follow."}, {"criterion": "Sound quality", "max_points": 25, "guidance": "Clean."}, {"criterion": "Script for the ear", "max_points": 20, "guidance": "Speakable."}, {"criterion": "Rights", "max_points": 20, "guidance": "Documented."}]$t6f$::jsonb, 70, 'link', false, true),
  (7, $t7a$Music basics for non-musicians$t7a$, $t7b$Describe music in terms AI understands.$t7b$, $t7c$Describe genre, mood, tempo (BPM), instruments and structure (intro, verse, chorus). Keep the brief specific: "calm lo-fi, 80 BPM, soft piano, no vocals, 30 seconds".$t7c$, $t7d$Music basics for non-musicians$t7d$, $t7e$Write three music briefs for three uses and generate one. Submit briefs and the link.

**Sharing audio:** upload to SoundCloud, Google Drive or similar (unlisted) and paste the link. Audio is checked by a person.$t7e$, $t7f$[{"criterion": "Briefs specific", "max_points": 40, "guidance": "All parts."}, {"criterion": "Fit the use", "max_points": 30, "guidance": "Suitable."}, {"criterion": "Result judged", "max_points": 30, "guidance": "Honest."}]$t7f$::jsonb, 20, 'link', false, true),
  (8, $t8a$Generating and choosing music$t8a$, $t8b$Generate options and pick with criteria.$t8b$, $t8c$Generate several versions, compare against the brief and pick using criteria: mood fit, energy, loop points, no distracting elements. Check that the licence allows your use.$t8c$, $t8d$Generating and choosing music$t8d$, $t8e$Generate five options. Submit links, your criteria and your choice with licence notes.

**Sharing audio:** upload to SoundCloud, Google Drive or similar (unlisted) and paste the link. Audio is checked by a person.$t8e$, $t8f$[{"criterion": "Criteria used", "max_points": 40, "guidance": "Stated."}, {"criterion": "Choice justified", "max_points": 30, "guidance": "Reasoned."}, {"criterion": "Licence checked", "max_points": 30, "guidance": "Documented."}]$t8f$::jsonb, 20, 'link', false, true),
  (9, $t9a$Mixing voice and music$t9a$, $t9b$Balance layers so speech stays clear.$t9b$, $t9c$Duck music under speech (about 15 to 20 dB lower), keep dynamics gentle and check on headphones and a phone speaker.$t9c$, $t9d$Mixing voice and music$t9d$, $t9e$Mix your narration with music. Submit the link and the levels you set.

**Sharing audio:** upload to SoundCloud, Google Drive or similar (unlisted) and paste the link. Audio is checked by a person.$t9e$, $t9f$[{"criterion": "Speech clear", "max_points": 50, "guidance": "Intelligible."}, {"criterion": "Balance", "max_points": 30, "guidance": "Good."}, {"criterion": "Levels stated", "max_points": 20, "guidance": "Numbers."}]$t9f$::jsonb, 20, 'link', false, true),
  (10, $t10a$Sound effects and ambience$t10a$, $t10b$Add depth with effects.$t10b$, $t10c$Ambience places the listener; effects mark moments. Less is more. Use licensed effects.$t10c$, $t10d$Sound effects and ambience$t10d$, $t10e$Add ambience and two effects to a scene. Submit the link and sources.

**Sharing audio:** upload to SoundCloud, Google Drive or similar (unlisted) and paste the link. Audio is checked by a person.$t10e$, $t10f$[{"criterion": "Adds depth", "max_points": 40, "guidance": "Purposeful."}, {"criterion": "Restrained", "max_points": 30, "guidance": "Not cluttered."}, {"criterion": "Licences", "max_points": 30, "guidance": "Documented."}]$t10f$::jsonb, 20, 'link', false, true),
  (11, $t11a$Loudness and export$t11a$, $t11b$Deliver audio at the right level and format.$t11b$, $t11c$Podcasts and video commonly target around -16 LUFS (check the platform), peaks below -1 dB. Export WAV for editing, MP3/AAC for delivery.$t11c$, $t11d$Loudness and export$t11d$, $t11e$Normalise and export a mix. Submit link, LUFS/peak values and format.

**Sharing audio:** upload to SoundCloud, Google Drive or similar (unlisted) and paste the link. Audio is checked by a person.$t11e$, $t11f$[{"criterion": "Correct loudness", "max_points": 45, "guidance": "Values given."}, {"criterion": "Format right", "max_points": 30, "guidance": "Suitable."}, {"criterion": "Explained", "max_points": 25, "guidance": "Reasoned."}]$t11f$::jsonb, 20, 'link', false, true),
  (12, $t12a$Module project: a jingle or intro with voice$t12a$, $t12b$Create a 20-second branded audio.$t12b$, $t12c$Show Module 2. Create a **20-second brand intro** with music, voice and effects, mixed and exported.

A person reviews your work and can ask for revisions.$t12c$, $t12d$Module project: a jingle or intro with voice$t12d$, $t12e$Submit the link, brief, licence notes and levels.

**Sharing audio:** upload to SoundCloud, Google Drive or similar (unlisted) and paste the link. Audio is checked by a person.$t12e$, $t12f$[{"criterion": "Brand fit", "max_points": 30, "guidance": "Suits brand."}, {"criterion": "Mix", "max_points": 30, "guidance": "Clear."}, {"criterion": "Rights", "max_points": 20, "guidance": "Documented."}, {"criterion": "Delivery", "max_points": 20, "guidance": "Right format."}]$t12f$::jsonb, 70, 'link', false, true),
  (13, $t13a$Podcast planning$t13a$, $t13b$Plan a show that can continue.$t13b$, $t13c$Define audience, promise, format, length, cadence and episode template. Plan five episodes.$t13c$, $t13d$Podcast planning$t13d$, $t13e$Submit a one-page podcast plan with five episode ideas.$t13e$, $t13f$[{"criterion": "Clear promise", "max_points": 35, "guidance": "Specific."}, {"criterion": "Sustainable", "max_points": 35, "guidance": "Realistic."}, {"criterion": "Template", "max_points": 30, "guidance": "Structure."}]$t13f$::jsonb, 20, 'text', false, false),
  (14, $t14a$Scripting an episode$t14a$, $t14b$Write an outline with talking points.$t14b$, $t14c$Use an outline, not a full script, for natural speech. Hook, points, story, call to action. Write the intro and outro fully.$t14c$, $t14d$Scripting an episode$t14d$, $t14e$Write an outline for a 5-minute episode plus intro and outro scripts.$t14e$, $t14f$[{"criterion": "Structure", "max_points": 40, "guidance": "Hook to CTA."}, {"criterion": "Natural", "max_points": 30, "guidance": "Speakable."}, {"criterion": "Focused", "max_points": 30, "guidance": "One idea."}]$t14f$::jsonb, 20, 'text', false, false),
  (15, $t15a$Editing dialogue$t15a$, $t15b$Cut silences and mistakes cleanly.$t15b$, $t15c$Remove long pauses and stumbles but keep breaths. Do not edit meaning. Smooth transitions with short fades.$t15c$, $t15d$Editing dialogue$t15d$, $t15e$Edit a 2-minute recording. Submit before and after links and time saved.

**Sharing audio:** upload to SoundCloud, Google Drive or similar (unlisted) and paste the link. Audio is checked by a person.$t15e$, $t15f$[{"criterion": "Clean edits", "max_points": 45, "guidance": "Smooth."}, {"criterion": "Meaning intact", "max_points": 35, "guidance": "Faithful."}, {"criterion": "Documented", "max_points": 20, "guidance": "Explained."}]$t15f$::jsonb, 20, 'link', false, true),
  (16, $t16a$Translation and dubbing with consent$t16a$, $t16b$Reach new audiences responsibly.$t16b$, $t16c$AI can translate and dub. Have a fluent speaker review. Get consent for voice use and disclose synthetic dubbing.$t16c$, $t16d$Translation and dubbing with consent$t16d$, $t16e$Translate a 60-word script, have it checked by a speaker and note the corrections.$t16e$, $t16f$[{"criterion": "Reviewed by a speaker", "max_points": 40, "guidance": "Real check."}, {"criterion": "Corrections noted", "max_points": 35, "guidance": "Specific."}, {"criterion": "Consent and disclosure", "max_points": 25, "guidance": "Addressed."}]$t16f$::jsonb, 20, 'text', false, false),
  (17, $t17a$Accessibility: transcripts and captions$t17a$, $t17b$Provide text for audio.$t17b$, $t17c$Transcripts help everyone. Generate one, then proofread names, numbers and jargon.$t17c$, $t17d$Accessibility: transcripts and captions$t17d$, $t17e$Create and proofread a transcript for a 2-minute audio. Submit it with three corrections.$t17e$, $t17f$[{"criterion": "Accurate", "max_points": 45, "guidance": "Proofread."}, {"criterion": "Corrections noted", "max_points": 30, "guidance": "Three."}, {"criterion": "Readable format", "max_points": 25, "guidance": "Clear."}]$t17f$::jsonb, 20, 'text', false, false),
  (18, $t18a$Module project: a short podcast episode$t18a$, $t18b$Produce a 3-minute episode.$t18b$, $t18c$Show Module 3. Produce a **3-minute episode** with intro, content, outro, clean edit and transcript.

A person reviews your work and can ask for revisions.$t18c$, $t18d$Module project: a short podcast episode$t18d$, $t18e$Submit audio link, outline, transcript and licence notes.

**Sharing audio:** upload to SoundCloud, Google Drive or similar (unlisted) and paste the link. Audio is checked by a person.$t18e$, $t18f$[{"criterion": "Content and structure", "max_points": 30, "guidance": "Clear."}, {"criterion": "Sound and edit", "max_points": 30, "guidance": "Clean."}, {"criterion": "Transcript", "max_points": 20, "guidance": "Accurate."}, {"criterion": "Rights", "max_points": 20, "guidance": "Documented."}]$t18f$::jsonb, 100, 'link', false, true),
  (19, $t19a$Publishing and RSS basics$t19a$, $t19b$Publish audio where people listen.$t19b$, $t19c$Hosts create an RSS feed that podcast apps read. Prepare cover art (3000x3000), title, description and category.$t19c$, $t19d$Publishing and RSS basics$t19d$, $t19e$Prepare a publishing pack: title, description, cover art link and category.$t19e$, $t19f$[{"criterion": "Complete pack", "max_points": 45, "guidance": "All parts."}, {"criterion": "Description clear", "max_points": 30, "guidance": "Helpful."}, {"criterion": "Cover art suitable", "max_points": 25, "guidance": "Correct size."}]$t19f$::jsonb, 20, 'link', false, false),
  (20, $t20a$Rights, royalties and platform rules$t20a$, $t20b$Avoid takedowns and disputes.$t20b$, $t20c$Check licence terms for music and voice, keep proof, and know that platforms scan for copyrighted audio. Do not use famous songs or voices.$t20c$, $t20d$Rights, royalties and platform rules$t20d$, $t20e$Audit one audio project: every asset, source, licence and proof link.$t20e$, $t20f$[{"criterion": "Complete audit", "max_points": 45, "guidance": "Every asset."}, {"criterion": "Licences real", "max_points": 35, "guidance": "Checked."}, {"criterion": "Proof saved", "max_points": 20, "guidance": "Links."}]$t20f$::jsonb, 20, 'text', false, false),
  (21, $t21a$Sound for video and games$t21a$, $t21b$Deliver audio for other media.$t21b$, $t21c$Provide stems (voice, music, effects) so editors can adjust. Name files clearly and match frame rate and sample rate.$t21c$, $t21d$Sound for video and games$t21d$, $t21e$Export stems for a project and submit the file list with formats.$t21e$, $t21f$[{"criterion": "Stems provided", "max_points": 40, "guidance": "Separated."}, {"criterion": "Naming clear", "max_points": 30, "guidance": "Organised."}, {"criterion": "Formats right", "max_points": 30, "guidance": "Suitable."}]$t21f$::jsonb, 20, 'text', false, false),
  (22, $t22a$Feedback and iteration$t22a$, $t22b$Improve using listener feedback.$t22b$, $t22c$Ask three listeners: where did you lose interest, what was unclear, was the sound comfortable? Fix the top two.$t22c$, $t22d$Feedback and iteration$t22d$, $t22e$Submit feedback from three listeners and the two fixes.$t22e$, $t22f$[{"criterion": "Real feedback", "max_points": 40, "guidance": "Three."}, {"criterion": "Prioritised", "max_points": 30, "guidance": "Top two."}, {"criterion": "Fixed", "max_points": 30, "guidance": "Specific."}]$t22f$::jsonb, 20, 'text', false, false),
  (23, $t23a$Pricing audio work$t23a$, $t23b$Scope a small audio job.$t23b$, $t23c$Scope by length, edits, revisions, rights and delivery formats. Clarify who owns the final and any AI tool terms.$t23c$, $t23d$Pricing audio work$t23d$, $t23e$Write a scope for a 2-minute narrated ad.$t23e$, $t23f$[{"criterion": "Clear scope", "max_points": 40, "guidance": "Complete."}, {"criterion": "Rights covered", "max_points": 35, "guidance": "Ownership."}, {"criterion": "Price basis", "max_points": 25, "guidance": "Reasoned."}]$t23f$::jsonb, 20, 'text', false, false),
  (24, $t24a$Module project: a branded audio kit$t24a$, $t24b$Deliver a brand intro, narration and podcast bumper.$t24b$, $t24c$Show Module 4. Deliver a **branded audio kit**: intro sting, 30-second narration and a bumper, with a rights audit.

A person reviews your work and can ask for revisions.$t24c$, $t24d$Module project: a branded audio kit$t24d$, $t24e$Submit links, brief, and rights audit.

**Sharing audio:** upload to SoundCloud, Google Drive or similar (unlisted) and paste the link. Audio is checked by a person.$t24e$, $t24f$[{"criterion": "Brand consistency", "max_points": 30, "guidance": "One identity."}, {"criterion": "Sound quality", "max_points": 30, "guidance": "Clean."}, {"criterion": "Rights audit", "max_points": 20, "guidance": "Complete."}, {"criterion": "Delivery", "max_points": 20, "guidance": "Formats."}]$t24f$::jsonb, 100, 'link', false, true),
  (25, $t25a$Capstone 1: audio brief$t25a$, $t25b$Plan an audio project for a real or made-up client.$t25b$, $t25c$Write a brief: audience, goal, deliverables (narration, music, sting), length, platform.$t25c$, $t25d$Capstone 1: audio brief$t25d$, $t25e$Submit the brief.$t25e$, $t25f$[{"criterion": "Clear brief", "max_points": 50, "guidance": "Complete."}, {"criterion": "Scope realistic", "max_points": 30, "guidance": "Doable."}, {"criterion": "Goal measurable", "max_points": 20, "guidance": "A metric."}]$t25f$::jsonb, 20, 'text', false, false),
  (26, $t26a$Capstone 2: script and music brief$t26a$, $t26b$Prepare the words and sound plan.$t26b$, $t26c$Write the script for the ear and the music and effects brief.$t26c$, $t26d$Capstone 2: script and music brief$t26d$, $t26e$Submit the script and sound brief.$t26e$, $t26f$[{"criterion": "Script speakable", "max_points": 45, "guidance": "Natural."}, {"criterion": "Sound brief specific", "max_points": 35, "guidance": "Detailed."}, {"criterion": "Fits the goal", "max_points": 20, "guidance": "Aligned."}]$t26f$::jsonb, 20, 'text', false, false),
  (27, $t27a$Capstone 3: produce the voice and music$t27a$, $t27b$Create the raw assets.$t27b$, $t27c$Record or generate voice, generate music and effects and keep licence notes.$t27c$, $t27d$Capstone 3: produce the voice and music$t27d$, $t27e$Submit asset links and licence notes.

**Sharing audio:** upload to SoundCloud, Google Drive or similar (unlisted) and paste the link. Audio is checked by a person.$t27e$, $t27f$[{"criterion": "Quality assets", "max_points": 45, "guidance": "Clean."}, {"criterion": "Match brief", "max_points": 30, "guidance": "Suitable."}, {"criterion": "Rights", "max_points": 25, "guidance": "Documented."}]$t27f$::jsonb, 70, 'link', false, true),
  (28, $t28a$Capstone 4: mix and master$t28a$, $t28b$Combine and finish.$t28b$, $t28c$Mix, balance, master to target loudness and export.$t28c$, $t28d$Capstone 4: mix and master$t28d$, $t28e$Submit the mix link and the loudness values.

**Sharing audio:** upload to SoundCloud, Google Drive or similar (unlisted) and paste the link. Audio is checked by a person.$t28e$, $t28f$[{"criterion": "Clarity", "max_points": 40, "guidance": "Speech clear."}, {"criterion": "Loudness right", "max_points": 30, "guidance": "Values."}, {"criterion": "Polish", "max_points": 30, "guidance": "Clean."}]$t28f$::jsonb, 70, 'link', false, true),
  (29, $t29a$Capstone 5: transcript, feedback and fixes$t29a$, $t29b$Make it accessible and improve it.$t29b$, $t29c$Create a transcript, collect feedback from three listeners and fix the top issues.$t29c$, $t29d$Capstone 5: transcript, feedback and fixes$t29d$, $t29e$Submit the transcript, feedback and fixes.$t29e$, $t29f$[{"criterion": "Transcript accurate", "max_points": 35, "guidance": "Proofread."}, {"criterion": "Feedback used", "max_points": 40, "guidance": "Fixes."}, {"criterion": "Reflection", "max_points": 25, "guidance": "Learned."}]$t29f$::jsonb, 20, 'text', false, false),
  (30, $t30a$Capstone 6: deliver and publish$t30a$, $t30b$Deliver the final with a rights audit.$t30b$, $t30c$Deliver final audio, transcript, publishing pack and rights audit. Share in the Discord and ask for one piece of feedback.

A person reviews your work and can ask for revisions.$t30c$, $t30d$Capstone 6: deliver and publish$t30d$, $t30e$Submit the audio link, transcript, publishing pack, rights audit and a short cover note.

**Sharing audio:** upload to SoundCloud, Google Drive or similar (unlisted) and paste the link. Audio is checked by a person.$t30e$, $t30f$[{"criterion": "Fits the brief", "max_points": 25, "guidance": "Meets goals."}, {"criterion": "Sound craft", "max_points": 30, "guidance": "Clean."}, {"criterion": "Rights and ethics", "max_points": 25, "guidance": "Handled."}, {"criterion": "Delivery", "max_points": 20, "guidance": "Complete."}]$t30f$::jsonb, 100, 'link', false, true)
) as v(n, title, objective, lesson_md, skill_focus, assignment_md, rubric, est_minutes, submission_type, ai_evaluate, requires_review)
where t.slug = 'audio'
on conflict (track_id, day_number) do nothing;
