-- AI film & video, Expert tier (days 61-80). Authored content, UNPUBLISHED until a person reviews it in Admin.
insert into public.day
  (track_id, tier_id, day_number, title, objective, lesson_md, skill_focus, assignment_md, rubric,
   est_minutes, is_published, credit_budget, submission_type, ai_evaluate, requires_review)
select t.id, ti.id, v.n, v.title, v.objective, v.lesson_md, v.skill_focus, v.assignment_md, v.rubric,
       v.est_minutes, false, null, v.submission_type, v.ai_evaluate, v.requires_review
from public.track t
join public.tier ti on ti.track_id = t.id and ti.slug = 'expert'
cross join (values
  (61, $t61a$Directing for a point of view$t61a$, $t61b$Define a style that is recognisably yours.$t61b$, $t61c$A director's voice shows in choices: framing, pace, colour, sound, subject. Study three filmmakers you admire, list their repeated choices and decide which you will adopt or reject.$t61c$, $t61d$Directing for a point of view$t61d$, $t61e$Write a director's statement (250 words) and a look book of six frames (direct image links or clip link).$t61e$, $t61f$[{"criterion": "Point of view clear", "max_points": 40, "guidance": "Distinct."}, {"criterion": "Choices specific", "max_points": 35, "guidance": "Concrete."}, {"criterion": "Influences honest", "max_points": 25, "guidance": "Not copying."}]$t61f$::jsonb, 60, 'text', false, false),
  (62, $t62a$Advanced continuity and consistency systems$t62a$, $t62b$Keep a whole film coherent.$t62b$, $t62c$Maintain a bible: characters, wardrobe, locations, palette, prompt blocks and reference images. Check every new shot against it.$t62c$, $t62d$Advanced continuity and consistency systems$t62d$, $t62e$Create a production bible for a five-minute film and show eight shots that follow it.

**Sharing video:** upload (unlisted) and paste the link. Video is checked by a person.$t62e$, $t62f$[{"criterion": "Bible complete", "max_points": 40, "guidance": "Usable."}, {"criterion": "Shots consistent", "max_points": 40, "guidance": "Follow it."}, {"criterion": "Method documented", "max_points": 20, "guidance": "Clear."}]$t62f$::jsonb, 90, 'link', false, false),
  (63, $t63a$Sound and music supervision$t63a$, $t63b$Direct the full soundtrack.$t63b$, $t63c$Spot the film for sound: where music enters, where silence works, what each scene needs. Keep a cue sheet with sources and licences.$t63c$, $t63d$Sound and music supervision$t63d$, $t63e$Create a cue sheet and mix a two-minute scene.

**Sharing video:** upload (unlisted) and paste the link. Video is checked by a person.$t63e$, $t63f$[{"criterion": "Spotting purposeful", "max_points": 35, "guidance": "Reasoned."}, {"criterion": "Cue sheet complete", "max_points": 35, "guidance": "Licences."}, {"criterion": "Mix clear", "max_points": 30, "guidance": "Clean."}]$t63f$::jsonb, 60, 'link', false, false),
  (64, $t64a$Colour and finishing to broadcast spec$t64a$, $t64b$Deliver technically correct video.$t64b$, $t64c$Check levels, safe areas, loudness, frame rate, captions and delivery codecs for each platform. Use scopes and reference monitors where possible.$t64c$, $t64d$Colour and finishing to broadcast spec$t64d$, $t64e$Deliver a piece to two platform specs with a technical checklist.

**Sharing video:** upload (unlisted) and paste the link. Video is checked by a person.$t64e$, $t64f$[{"criterion": "Specs correct", "max_points": 40, "guidance": "Verified."}, {"criterion": "Checklist", "max_points": 30, "guidance": "Complete."}, {"criterion": "Quality kept", "max_points": 30, "guidance": "Clean."}]$t64f$::jsonb, 60, 'link', false, false),
  (65, $t65a$Expert project 1: a directed short with a bible$t65a$, $t65b$Deliver a coherent short with your voice.$t65b$, $t65c$Show Module 1. Deliver a **4-minute short** with director's statement, production bible, cue sheet and platform-spec checklist.

A person reviews your work and can ask for revisions.$t65c$, $t65d$Expert project 1: a directed short with a bible$t65d$, $t65e$Submit the film, statement, bible, cue sheet and checklist.

**Sharing video:** upload (unlisted) and paste the link. Video is checked by a person.$t65e$, $t65f$[{"criterion": "Vision and story", "max_points": 30, "guidance": "Clear."}, {"criterion": "Consistency", "max_points": 25, "guidance": "Coherent."}, {"criterion": "Sound and finishing", "max_points": 25, "guidance": "Professional."}, {"criterion": "Documentation", "max_points": 20, "guidance": "Complete."}]$t65f$::jsonb, 240, 'link', false, true),
  (66, $t66a$Producing: budgets, schedules, risk$t66a$, $t66b$Plan a production professionally.$t66b$, $t66c$Break down the script, budget credits, time and tools, schedule with buffers and list risks (rights, tool failure, deadlines).$t66c$, $t66d$Producing: budgets, schedules, risk$t66d$, $t66e$Produce a budget, schedule and risk list for a 5-minute film.$t66e$, $t66f$[{"criterion": "Budget realistic", "max_points": 35, "guidance": "Numbers."}, {"criterion": "Schedule buffers", "max_points": 35, "guidance": "Included."}, {"criterion": "Risks", "max_points": 30, "guidance": "Concrete."}]$t66f$::jsonb, 60, 'text', false, false),
  (67, $t67a$Working with actors, voices and consent$t67a$, $t67b$Handle people responsibly.$t67b$, $t67c$Written consent for likeness and voice, clear usage terms, pay, credit and revocation. Never synthesise a real person without agreement.$t67c$, $t67d$Working with actors, voices and consent$t67d$, $t67e$Write a talent agreement with consent, usage, credit and revocation.$t67e$, $t67f$[{"criterion": "Consent specific", "max_points": 40, "guidance": "Clear."}, {"criterion": "Usage limited", "max_points": 30, "guidance": "Defined."}, {"criterion": "Fair terms", "max_points": 30, "guidance": "Balanced."}]$t67f$::jsonb, 60, 'text', false, false),
  (68, $t68a$Hybrid production: live action plus AI$t68a$, $t68b$Combine footage and generation professionally.$t68b$, $t68c$Plan which shots are filmed and which generated, match look and record provenance for each asset. Disclose as required.$t68c$, $t68d$Hybrid production: live action plus AI$t68d$, $t68e$Produce a two-minute hybrid sequence with a provenance log.

**Sharing video:** upload (unlisted) and paste the link. Video is checked by a person.$t68e$, $t68f$[{"criterion": "Seamless look", "max_points": 40, "guidance": "Matched."}, {"criterion": "Provenance log", "max_points": 35, "guidance": "Complete."}, {"criterion": "Disclosure", "max_points": 25, "guidance": "Planned."}]$t68f$::jsonb, 120, 'link', false, false),
  (69, $t69a$Post-production workflow and version control$t69a$, $t69b$Keep large projects organised.$t69b$, $t69c$Folder structure, naming, backups, versions, review links with time-coded notes and a locked cut before finishing.$t69c$, $t69d$Post-production workflow and version control$t69d$, $t69e$Document your post workflow and show one versioned review cycle.

**Sharing video:** upload (unlisted) and paste the link. Video is checked by a person.$t69e$, $t69f$[{"criterion": "Structure clear", "max_points": 35, "guidance": "Organised."}, {"criterion": "Versioning", "max_points": 35, "guidance": "Real."}, {"criterion": "Review cycle", "max_points": 30, "guidance": "Shown."}]$t69f$::jsonb, 60, 'link', false, false),
  (70, $t70a$Expert project 2: a produced piece for a client brief$t70a$, $t70b$Deliver on time and on budget.$t70b$, $t70c$Show Module 2. Deliver a **client-style production** with budget, schedule, talent agreement, hybrid provenance log and locked-cut review.

A person reviews your work and can ask for revisions.$t70c$, $t70d$Expert project 2: a produced piece for a client brief$t70d$, $t70e$Submit the film and all documents.

**Sharing video:** upload (unlisted) and paste the link. Video is checked by a person.$t70e$, $t70f$[{"criterion": "Meets brief", "max_points": 30, "guidance": "On target."}, {"criterion": "Production management", "max_points": 25, "guidance": "Sound."}, {"criterion": "Ethics and consent", "max_points": 25, "guidance": "Handled."}, {"criterion": "Quality", "max_points": 20, "guidance": "Polished."}]$t70f$::jsonb, 240, 'link', false, true),
  (71, $t71a$Documentary and factual work with synthetic media$t71a$, $t71b$Keep truth intact.$t71b$, $t71c$Never fabricate evidence. Label reconstructions and illustrations, verify facts and give subjects right of reply where appropriate.$t71c$, $t71d$Documentary and factual work with synthetic media$t71d$, $t71e$Outline a factual film with a verification and labelling plan.$t71e$, $t71f$[{"criterion": "Verification", "max_points": 40, "guidance": "Real."}, {"criterion": "Labels honest", "max_points": 35, "guidance": "Clear."}, {"criterion": "Fairness", "max_points": 25, "guidance": "Considered."}]$t71f$::jsonb, 60, 'text', false, false),
  (72, $t72a$Advertising and branded content regulation$t72a$, $t72b$Comply with advertising rules.$t72b$, $t72c$Endorsements, disclosures, substantiation of claims and children's content rules vary by country. Keep evidence for every claim. Get advice for regulated sectors.$t72c$, $t72d$Advertising and branded content regulation$t72d$, $t72e$Audit a promo script for claims and disclosures.$t72e$, $t72f$[{"criterion": "Claims audited", "max_points": 45, "guidance": "Each."}, {"criterion": "Disclosures", "max_points": 30, "guidance": "Proper."}, {"criterion": "Advice noted", "max_points": 25, "guidance": "Limits."}]$t72f$::jsonb, 60, 'text', false, false),
  (73, $t73a$Distribution and monetisation strategy$t73a$, $t73b$Plan the film's life.$t73b$, $t73c$Channels, windows, licensing, sponsorship and audience building. Set realistic goals and measure retention.$t73c$, $t73d$Distribution and monetisation strategy$t73d$, $t73e$Write a distribution plan with goals, channels and a 90-day calendar.$t73e$, $t73f$[{"criterion": "Channels fit", "max_points": 35, "guidance": "Suitable."}, {"criterion": "Goals measurable", "max_points": 35, "guidance": "Numbers."}, {"criterion": "Calendar", "max_points": 30, "guidance": "Real."}]$t73f$::jsonb, 60, 'text', false, false),
  (74, $t74a$Festival strategy and pitching$t74a$, $t74b$Prepare for professional submission.$t74b$, $t74c$Rules on AI-assisted work vary. Research fits, prepare logline, one-sheet, stills and press kit with honest tool disclosure.$t74c$, $t74d$Festival strategy and pitching$t74d$, $t74e$Prepare a submission pack for two festivals with their AI policies noted.$t74e$, $t74f$[{"criterion": "Pack complete", "max_points": 40, "guidance": "All parts."}, {"criterion": "Policies checked", "max_points": 35, "guidance": "Real."}, {"criterion": "Honest disclosure", "max_points": 25, "guidance": "Stated."}]$t74f$::jsonb, 60, 'text', false, false),
  (75, $t75a$Expert project 3: a distribution-ready package$t75a$, $t75b$Deliver the business side of a film.$t75b$, $t75c$Show Module 3. Deliver a **release package**: factual/label plan, advertising audit, distribution plan and submission pack for your film.

A person reviews your work and can ask for revisions.$t75c$, $t75d$Expert project 3: a distribution-ready package$t75d$, $t75e$Submit all documents and the film link.

**Sharing video:** upload (unlisted) and paste the link. Video is checked by a person.$t75e$, $t75f$[{"criterion": "Compliance", "max_points": 30, "guidance": "Careful."}, {"criterion": "Distribution plan", "max_points": 25, "guidance": "Realistic."}, {"criterion": "Submission pack", "max_points": 25, "guidance": "Professional."}, {"criterion": "Honesty", "max_points": 20, "guidance": "Clear."}]$t75f$::jsonb, 120, 'link', false, true),
  (76, $t76a$Flagship: development$t76a$, $t76b$Develop a 6-minute film.$t76b$, $t76c$Write treatment, script, look book, bible, budget and schedule.$t76c$, $t76d$Flagship: development$t76d$, $t76e$Submit all development documents.$t76e$, $t76f$[{"criterion": "Story strong", "max_points": 35, "guidance": "Clear."}, {"criterion": "Plan complete", "max_points": 40, "guidance": "Feasible."}, {"criterion": "Consent and rights", "max_points": 25, "guidance": "Handled."}]$t76f$::jsonb, 120, 'text', false, false),
  (77, $t77a$Flagship: production$t77a$, $t77b$Produce the shots.$t77b$, $t77c$Generate and film shots with tracker and provenance log.$t77c$, $t77d$Flagship: production$t77d$, $t77e$Submit tracker, log and selected clips.

**Sharing video:** upload (unlisted) and paste the link. Video is checked by a person.$t77e$, $t77f$[{"criterion": "Shots match plan", "max_points": 40, "guidance": "Faithful."}, {"criterion": "Provenance", "max_points": 30, "guidance": "Logged."}, {"criterion": "Selects", "max_points": 30, "guidance": "Best."}]$t77f$::jsonb, 240, 'link', false, false),
  (78, $t78a$Flagship: post-production$t78a$, $t78b$Edit, sound, grade.$t78b$, $t78c$Edit, mix, grade, caption and finish to spec.$t78c$, $t78d$Flagship: post-production$t78d$, $t78e$Submit the locked cut and notes.

**Sharing video:** upload (unlisted) and paste the link. Video is checked by a person.$t78e$, $t78f$[{"criterion": "Story and pace", "max_points": 35, "guidance": "Works."}, {"criterion": "Sound and grade", "max_points": 40, "guidance": "Polished."}, {"criterion": "Specs", "max_points": 25, "guidance": "Correct."}]$t78f$::jsonb, 240, 'link', false, false),
  (79, $t79a$Flagship: screening and release$t79a$, $t79b$Screen, revise and release.$t79b$, $t79c$Screen for ten viewers, revise and release with credits and disclosure.$t79c$, $t79d$Flagship: screening and release$t79d$, $t79e$Submit screening notes, changes and release links.

**Sharing video:** upload (unlisted) and paste the link. Video is checked by a person.$t79e$, $t79f$[{"criterion": "Audience feedback", "max_points": 35, "guidance": "Ten."}, {"criterion": "Revisions", "max_points": 40, "guidance": "Real."}, {"criterion": "Release", "max_points": 25, "guidance": "Done."}]$t79f$::jsonb, 90, 'link', false, false),
  (80, $t80a$Expert project 4: the flagship film$t80a$, $t80b$Deliver your best film with its full record.$t80b$, $t80c$Show Module 4. Deliver the **flagship film** with development documents, provenance log, clearance, screening results and release plan.

A person reviews your work and can ask for revisions.$t80c$, $t80d$Expert project 4: the flagship film$t80d$, $t80e$Submit the film and the package.

**Sharing video:** upload (unlisted) and paste the link. Video is checked by a person.$t80e$, $t80f$[{"criterion": "Film quality", "max_points": 35, "guidance": "Excellent."}, {"criterion": "Rights and ethics", "max_points": 25, "guidance": "Clean."}, {"criterion": "Process record", "max_points": 20, "guidance": "Complete."}, {"criterion": "Audience results", "max_points": 20, "guidance": "Honest."}]$t80f$::jsonb, 300, 'link', false, true)
) as v(n, title, objective, lesson_md, skill_focus, assignment_md, rubric, est_minutes, submission_type, ai_evaluate, requires_review)
where t.slug = 'film'
on conflict (track_id, day_number) do nothing;
