-- Apps & tools, Grandmaster tier (days 81-90). Authored content, UNPUBLISHED until a person reviews it in Admin.
insert into public.day
  (track_id, tier_id, day_number, title, objective, lesson_md, skill_focus, assignment_md, rubric,
   est_minutes, is_published, credit_budget, submission_type, ai_evaluate, requires_review)
select t.id, ti.id, v.n, v.title, v.objective, v.lesson_md, v.skill_focus, v.assignment_md, v.rubric,
       v.est_minutes, false, null, v.submission_type, v.ai_evaluate, v.requires_review
from public.track t
join public.tier ti on ti.track_id = t.id and ti.slug = 'grandmaster'
cross join (values
  (81, $t81a$Teach a product-building skill$t81a$, $t81b$Explain one skill so a beginner can do it.$t81b$, $t81c$Choose a skill (writing a brief, testing a flow). Write a lesson with worked example, practice task and success check.$t81c$, $t81d$Teach a product-building skill$t81d$, $t81e$Submit the lesson.$t81e$, $t81f$[{"criterion": "Clear", "max_points": 35, "guidance": "Beginner-friendly."}, {"criterion": "Worked example", "max_points": 35, "guidance": "Real."}, {"criterion": "Practice and check", "max_points": 30, "guidance": "Usable."}]$t81f$::jsonb, 60, 'text', false, false),
  (82, $t82a$Product critique clinic$t82a$, $t82b$Review three products precisely.$t82b$, $t82c$Review three tools: who is it for, the top problem, the fix and how to test it.$t82c$, $t82d$Product critique clinic$t82d$, $t82e$Submit three reviews with one prioritised fix each.$t82e$, $t82f$[{"criterion": "Diagnosis precise", "max_points": 40, "guidance": "Insight."}, {"criterion": "Prioritised", "max_points": 30, "guidance": "Focused."}, {"criterion": "Testable fixes", "max_points": 30, "guidance": "Practical."}]$t82f$::jsonb, 60, 'text', false, false),
  (83, $t83a$Open-source or template contribution$t83a$, $t83b$Share something reusable.$t83b$, $t83c$Publish a template, checklist or component with docs and licence so others can use it.$t83c$, $t83d$Open-source or template contribution$t83d$, $t83e$Submit the link, docs and licence.$t83e$, $t83f$[{"criterion": "Useful", "max_points": 35, "guidance": "Reusable."}, {"criterion": "Documented", "max_points": 35, "guidance": "Clear."}, {"criterion": "Licence right", "max_points": 30, "guidance": "Stated."}]$t83f$::jsonb, 90, 'text', false, false),
  (84, $t84a$Case study: build to outcome$t84a$, $t84b$Document a product honestly.$t84b$, $t84c$Case study: problem, options, decisions, results and mistakes, with real numbers.$t84c$, $t84d$Case study: build to outcome$t84d$, $t84e$Submit the case study.$t84e$, $t84f$[{"criterion": "Numbers real", "max_points": 40, "guidance": "Honest."}, {"criterion": "Mistakes included", "max_points": 30, "guidance": "Frank."}, {"criterion": "Clear", "max_points": 30, "guidance": "Structured."}]$t84f$::jsonb, 60, 'text', false, false),
  (85, $t85a$Grandmaster project 1: body-of-work plan$t85a$, $t85b$Plan a visible portfolio.$t85b$, $t85c$Deliver a **plan**: point of view, three products or case studies, one teaching resource, one open contribution and six-month schedule.

Your work is scored on the rubric below. You can revise and resubmit.$t85c$, $t85d$Grandmaster project 1: body-of-work plan$t85d$, $t85e$Submit the plan with measures.$t85e$, $t85f$[{"criterion": "Point of view", "max_points": 30, "guidance": "Distinct."}, {"criterion": "Pieces valuable", "max_points": 30, "guidance": "Strong."}, {"criterion": "Realistic", "max_points": 20, "guidance": "Feasible."}, {"criterion": "Measures", "max_points": 20, "guidance": "Clear."}]$t85f$::jsonb, 90, 'text', true, false),
  (86, $t86a$Mentor a builder$t86a$, $t86b$Review a peer's product.$t86b$, $t86c$Review a peer's project against the rubric with evidence per criterion and one exercise.$t86c$, $t86d$Mentor a builder$t86d$, $t86e$Submit the scored review.$t86e$, $t86f$[{"criterion": "Scores justified", "max_points": 40, "guidance": "Evidence."}, {"criterion": "Fair and kind", "max_points": 30, "guidance": "Balanced."}, {"criterion": "Exercise helpful", "max_points": 30, "guidance": "Practical."}]$t86f$::jsonb, 60, 'text', false, false),
  (87, $t87a$Build a course module$t87a$, $t87b$Package your know-how.$t87b$, $t87c$Design outcomes, five lessons, practice tasks, a project and rubric; test with a learner.$t87c$, $t87d$Build a course module$t87d$, $t87e$Submit outline, one lesson and learner feedback.$t87e$, $t87f$[{"criterion": "Outcomes", "max_points": 30, "guidance": "Measurable."}, {"criterion": "Lesson quality", "max_points": 40, "guidance": "Strong."}, {"criterion": "Tested", "max_points": 30, "guidance": "Real learner."}]$t87f$::jsonb, 120, 'text', false, false),
  (88, $t88a$Ethics and standards for builders$t88a$, $t88b$State your principles.$t88b$, $t88c$Publish how you handle user data, AI, safety, honesty about limits and mistakes.$t88c$, $t88d$Ethics and standards for builders$t88d$, $t88e$Submit your public standards.$t88e$, $t88f$[{"criterion": "Specific", "max_points": 40, "guidance": "Concrete."}, {"criterion": "Accountability", "max_points": 35, "guidance": "Corrections."}, {"criterion": "Honest about AI", "max_points": 25, "guidance": "Clear."}]$t88f$::jsonb, 45, 'text', false, false),
  (89, $t89a$Impact audit$t89a$, $t89b$Show what your products did.$t89b$, $t89c$Collect evidence: users, outcomes, time saved, feedback, with limits.$t89c$, $t89d$Impact audit$t89d$, $t89e$Submit the impact report.$t89e$, $t89f$[{"criterion": "Evidence real", "max_points": 45, "guidance": "Collected."}, {"criterion": "Honest", "max_points": 35, "guidance": "Limits."}, {"criterion": "Next steps", "max_points": 20, "guidance": "Clear."}]$t89f$::jsonb, 60, 'text', false, false),
  (90, $t90a$Grandmaster capstone: portfolio, teaching and impact$t90a$, $t90b$Prove mastery.$t90b$, $t90c$The final assessment. Deliver a **portfolio**: flagship product case study, open contribution, teaching resource with learner feedback, peer review, standards and impact report.

Your work is scored on the rubric below. You can revise and resubmit.$t90c$, $t90d$Grandmaster capstone: portfolio, teaching and impact$t90d$, $t90e$Submit the portfolio with links and a one-page reflection.

**Evidence:** paste *direct* links to screenshots (.png/.jpg/.webp), one per line, and describe them.$t90e$, $t90f$[{"criterion": "Product craft", "max_points": 30, "guidance": "Excellent."}, {"criterion": "Rigour and honesty", "max_points": 25, "guidance": "Verified."}, {"criterion": "Teaching and mentoring", "max_points": 25, "guidance": "Effective."}, {"criterion": "Impact and reflection", "max_points": 20, "guidance": "Evidenced."}]$t90f$::jsonb, 180, 'link', true, false)
) as v(n, title, objective, lesson_md, skill_focus, assignment_md, rubric, est_minutes, submission_type, ai_evaluate, requires_review)
where t.slug = 'apps'
on conflict (track_id, day_number) do nothing;
