-- AI film & video, Basic tier (days 1-30). Authored content, UNPUBLISHED until a person reviews it in Admin.
insert into public.day
  (track_id, tier_id, day_number, title, objective, lesson_md, skill_focus, assignment_md, rubric,
   est_minutes, is_published, credit_budget, submission_type, ai_evaluate, requires_review)
select t.id, ti.id, v.n, v.title, v.objective, v.lesson_md, v.skill_focus, v.assignment_md, v.rubric,
       v.est_minutes, false, null, v.submission_type, v.ai_evaluate, v.requires_review
from public.track t
join public.tier ti on ti.track_id = t.id and ti.slug = 'basic'
cross join (values
  (1, $t1a$Story before tools: idea, audience, length$t1a$, $t1b$Turn an idea into a one-sentence story a viewer can follow.$t1b$, $t1c$Video is story. Before any tool, write the **logline**: who wants what, what stands in the way, what happens. Choose the audience and the length (15 to 60 seconds is a good start).

Tools: [CREAO](https://agent.creao.ai/@Sonofpeace) (referral link) is our recommended first tool for planning and generating. Others include Runway, Kling, Veo, Luma and Pika. Video tools change quickly, so learn the craft, not just the buttons.$t1c$, $t1d$Story before tools: idea, audience, length$t1d$, $t1e$Write a logline, the audience and the target length for a short film idea.$t1e$, $t1f$[{"criterion": "Logline has who/want/obstacle", "max_points": 50, "guidance": "All parts."}, {"criterion": "Audience defined", "max_points": 25, "guidance": "Specific."}, {"criterion": "Length realistic", "max_points": 25, "guidance": "Achievable."}]$t1f$::jsonb, 15, 'text', false, false),
  (2, $t2a$Script and shot list$t2a$, $t2b$Write a one-page script and break it into shots.$t2b$, $t2c$Write what we **see** and **hear**. Then a shot list: number, framing (wide, medium, close), action, duration and sound. Six to ten shots is plenty for 30 seconds. Each shot needs a reason to exist.$t2c$, $t2d$Script and shot list$t2d$, $t2e$Submit a one-page script and a shot list for a 30-second piece.$t2e$, $t2f$[{"criterion": "Script is visual", "max_points": 35, "guidance": "Shows, does not tell."}, {"criterion": "Shot list complete", "max_points": 40, "guidance": "Framing, action, duration."}, {"criterion": "Each shot has purpose", "max_points": 25, "guidance": "Reasoned."}]$t2f$::jsonb, 20, 'text', false, false),
  (3, $t3a$Storyboard with images$t3a$, $t3b$Plan shots as still images before spending video credits.$t3b$, $t3c$Stills are cheaper than video. Generate one image per shot to check composition, character and light. Fix problems here, not in video.$t3c$, $t3d$Storyboard with images$t3d$, $t3e$Generate a storyboard of six stills. Submit direct image links, the prompt for each, and one shot you changed after seeing it.

Paste *direct* image links ending .png/.jpg/.webp.$t3e$, $t3f$[{"criterion": "Stills match the shot list", "max_points": 40, "guidance": "Correct framing."}, {"criterion": "Consistent look", "max_points": 30, "guidance": "Same style."}, {"criterion": "Iterated", "max_points": 30, "guidance": "A real change."}]$t3f$::jsonb, 20, 'link', false, false),
  (4, $t4a$Prompting a shot: camera, subject, motion$t4a$, $t4b$Describe a shot the way a director would.$t4b$, $t4c$A shot prompt: **camera** (angle, lens, movement), **subject and action**, **setting and light**, **style** and **duration**. Keep motion simple: one clear movement per shot. Complex actions and many characters often fail.$t4c$, $t4d$Prompting a shot: camera, subject, motion$t4d$, $t4e$Write six shot prompts (camera, subject, motion, light, style, duration) and note which you expect to be hard and why.$t4e$, $t4f$[{"criterion": "Prompts are directed", "max_points": 45, "guidance": "Camera and motion stated."}, {"criterion": "Simple motion", "max_points": 30, "guidance": "Realistic."}, {"criterion": "Risk noticed", "max_points": 25, "guidance": "Predicts problems."}]$t4f$::jsonb, 20, 'text', false, false),
  (5, $t5a$Your first generated clip$t5a$, $t5b$Generate and judge a short clip.$t5b$, $t5c$Generate a 4 to 8 second clip from one storyboard still. Watch it three times: check faces, hands, physics, flicker. Note what is usable.$t5c$, $t5d$Your first generated clip$t5d$, $t5e$Submit the clip link, the prompt and a critique with three specific flaws and one thing that worked.

**Sharing video:** upload to YouTube (unlisted), Google Drive or similar and paste the link. Video is checked by a person.$t5e$, $t5f$[{"criterion": "Clip supports the shot", "max_points": 30, "guidance": "On brief."}, {"criterion": "Critique is specific", "max_points": 45, "guidance": "Real flaws."}, {"criterion": "Prompt recorded", "max_points": 25, "guidance": "Given."}]$t5f$::jsonb, 20, 'link', false, true),
  (6, $t6a$Module project: a 15-second scene$t6a$, $t6b$Produce a short scene from script to clip.$t6b$, $t6c$Show Module 1. Produce a **15-second scene**: logline, script, shot list, storyboard and final clip.

A person reviews your work and can ask for revisions.$t6c$, $t6d$Module project: a 15-second scene$t6d$, $t6e$Submit: the logline, script, shot list, storyboard image links, the clip link and a note on what you changed from the plan.

**Sharing video:** upload to YouTube (unlisted), Google Drive or similar and paste the link. Video is checked by a person.$t6e$, $t6f$[{"criterion": "Story is clear", "max_points": 30, "guidance": "Follows the logline."}, {"criterion": "Planning shows", "max_points": 25, "guidance": "Script, shots, storyboard."}, {"criterion": "Visual quality", "max_points": 25, "guidance": "Consistent, few flaws."}, {"criterion": "Honest process note", "max_points": 20, "guidance": "What changed."}]$t6f$::jsonb, 90, 'link', false, true),
  (7, $t7a$Framing and shot types$t7a$, $t7b$Choose shots that tell the story.$t7b$, $t7c$Wide shows place, medium shows action, close-up shows emotion, over-the-shoulder shows relationship. Alternate them. Hold each shot long enough to read but short enough to stay lively.$t7c$, $t7d$Framing and shot types$t7d$, $t7e$Plan a five-shot sequence using at least four shot types with a reason for each.$t7e$, $t7f$[{"criterion": "Variety with purpose", "max_points": 50, "guidance": "Four types."}, {"criterion": "Story progresses", "max_points": 30, "guidance": "Clear flow."}, {"criterion": "Timing reasoned", "max_points": 20, "guidance": "Durations."}]$t7f$::jsonb, 20, 'text', false, false),
  (8, $t8a$Consistent characters and settings$t8a$, $t8b$Keep a character recognisable across shots.$t8b$, $t8c$Create a character sheet (description plus reference image) and reuse the same wording and reference for every shot. Keep clothing and colours simple. Check every shot against the sheet.$t8c$, $t8d$Consistent characters and settings$t8d$, $t8e$Create a character sheet and show the character in four shots. Submit the sheet, image links and the drift you fixed.

Paste *direct* image links.$t8e$, $t8f$[{"criterion": "Recognisable across shots", "max_points": 50, "guidance": "Same character."}, {"criterion": "Sheet usable", "max_points": 25, "guidance": "Clear."}, {"criterion": "Drift fixed", "max_points": 25, "guidance": "Explained."}]$t8f$::jsonb, 20, 'link', false, false),
  (9, $t9a$Image-to-video and control$t9a$, $t9b$Animate stills and steer movement.$t9b$, $t9c$Starting from a still gives control over look. Add movement in the prompt: camera push, pan, a subtle action. Small motion looks better than big motion.$t9c$, $t9d$Image-to-video and control$t9d$, $t9e$Animate three stills with different camera movements. Submit links, prompts and which worked best.

**Sharing video:** upload to YouTube (unlisted), Google Drive or similar and paste the link. Video is checked by a person.$t9e$, $t9f$[{"criterion": "Three movements tried", "max_points": 35, "guidance": "Distinct."}, {"criterion": "Prompts recorded", "max_points": 30, "guidance": "Given."}, {"criterion": "Judgment", "max_points": 35, "guidance": "Which and why."}]$t9f$::jsonb, 20, 'link', false, true),
  (10, $t10a$Lighting, colour and mood on screen$t10a$, $t10b$Use light and colour to carry emotion.$t10b$, $t10c$Warm and soft is safe and inviting; cold and hard is tense. Keep one palette across the film. Colour grading in the edit can unify shots from different generations.$t10c$, $t10d$Lighting, colour and mood on screen$t10d$, $t10e$Define a colour and light plan (three colours, light style, mood) and show two matching stills.

Paste *direct* image links.$t10e$, $t10f$[{"criterion": "Plan is specific", "max_points": 45, "guidance": "Colours and light."}, {"criterion": "Stills match", "max_points": 35, "guidance": "Consistent."}, {"criterion": "Mood fits story", "max_points": 20, "guidance": "Reasoned."}]$t10f$::jsonb, 20, 'link', false, false),
  (11, $t11a$Fixing bad generations$t11a$, $t11b$Decide to reroll, edit or replan.$t11b$, $t11c$Common fixes: reroll with a simpler prompt, change the start image, shorten the clip, cover a flaw with a cutaway or a cut. Budget credits: plan for several attempts per shot.$t11c$, $t11d$Fixing bad generations$t11d$, $t11e$Choose two flawed clips and document your fix for each with before and after links.

**Sharing video:** upload to YouTube (unlisted), Google Drive or similar and paste the link. Video is checked by a person.$t11e$, $t11f$[{"criterion": "Correct diagnosis", "max_points": 40, "guidance": "Names the problem."}, {"criterion": "Effective fix", "max_points": 40, "guidance": "Better."}, {"criterion": "Credit awareness", "max_points": 20, "guidance": "Attempts counted."}]$t11f$::jsonb, 20, 'link', false, true),
  (12, $t12a$Module project: a 30-second sequence$t12a$, $t12b$Produce a consistent sequence with a character.$t12b$, $t12c$Show Module 2. Produce a **30-second sequence** with one consistent character, planned shots and colour plan.

A person reviews your work and can ask for revisions.$t12c$, $t12d$Module project: a 30-second sequence$t12d$, $t12e$Submit the character sheet, shot list, colour plan, final clip link and a list of fixes you made.

**Sharing video:** upload to YouTube (unlisted), Google Drive or similar and paste the link. Video is checked by a person.$t12e$, $t12f$[{"criterion": "Consistency", "max_points": 30, "guidance": "Character and look."}, {"criterion": "Shot variety and flow", "max_points": 25, "guidance": "Story reads."}, {"criterion": "Technical quality", "max_points": 25, "guidance": "Few artefacts."}, {"criterion": "Process notes", "max_points": 20, "guidance": "Fixes described."}]$t12f$::jsonb, 90, 'link', false, true),
  (13, $t13a$Editing basics: cut on action, pace and rhythm$t13a$, $t13b$Assemble clips into a sequence that flows.$t13b$, $t13c$Editing is where the film is made. Cut on action, keep shots 2 to 5 seconds, trim the start and end of each clip and vary rhythm. Use a free editor (CapCut, DaVinci Resolve, Clipchamp).$t13c$, $t13d$Editing basics: cut on action, pace and rhythm$t13d$, $t13e$Edit five clips into a 20-second sequence. Submit the link and three edit decisions with reasons.

**Sharing video:** upload to YouTube (unlisted), Google Drive or similar and paste the link. Video is checked by a person.$t13e$, $t13f$[{"criterion": "Flows well", "max_points": 40, "guidance": "Cuts feel natural."}, {"criterion": "Decisions explained", "max_points": 35, "guidance": "Reasons."}, {"criterion": "Length and pace", "max_points": 25, "guidance": "Suitable."}]$t13f$::jsonb, 20, 'link', false, true),
  (14, $t14a$Sound: voice, music and effects$t14a$, $t14b$Add sound that carries emotion.$t14b$, $t14c$Half of film is sound. Layers: voice, music, effects and ambience. Use music you have the right to use. Keep voice clear and music lower. Silence is a tool.$t14c$, $t14d$Sound: voice, music and effects$t14d$, $t14e$Add three sound layers to your sequence. Submit the link, a list of sources with licences and the volume balance you chose.

**Sharing video:** upload to YouTube (unlisted), Google Drive or similar and paste the link. Video is checked by a person.$t14e$, $t14f$[{"criterion": "Sound supports story", "max_points": 35, "guidance": "Purposeful."}, {"criterion": "Licences documented", "max_points": 40, "guidance": "Rights."}, {"criterion": "Balance", "max_points": 25, "guidance": "Clear voice."}]$t14f$::jsonb, 20, 'link', false, true),
  (15, $t15a$Voiceover and dialogue$t15a$, $t15b$Write and record a script for speaking.$t15b$, $t15c$Write for the ear: short sentences, contractions. Use your own voice or a synthetic voice with the right permissions. Never clone a real person's voice without clear consent.$t15c$, $t15d$Voiceover and dialogue$t15d$, $t15e$Write a 60-word voiceover and record or generate it. Submit the script, link and how you obtained rights for the voice.

**Sharing video:** upload to YouTube (unlisted), Google Drive or similar and paste the link. Video is checked by a person.$t15e$, $t15f$[{"criterion": "Written for speaking", "max_points": 40, "guidance": "Natural."}, {"criterion": "Delivery clear", "max_points": 30, "guidance": "Understandable."}, {"criterion": "Consent and rights", "max_points": 30, "guidance": "Documented."}]$t15f$::jsonb, 20, 'link', false, true),
  (16, $t16a$Titles, captions and accessibility$t16a$, $t16b$Make video watchable without sound.$t16b$, $t16c$Most social video is watched muted. Add captions, large readable titles and check contrast. Proofread every word.$t16c$, $t16d$Titles, captions and accessibility$t16d$, $t16e$Add captions and a title card to a clip. Submit the link and the caption text.

**Sharing video:** upload to YouTube (unlisted), Google Drive or similar and paste the link. Video is checked by a person.$t16e$, $t16f$[{"criterion": "Captions accurate", "max_points": 45, "guidance": "Correct."}, {"criterion": "Readable design", "max_points": 30, "guidance": "Contrast."}, {"criterion": "Title effective", "max_points": 25, "guidance": "Clear."}]$t16f$::jsonb, 20, 'link', false, true),
  (17, $t17a$Colour and finishing$t17a$, $t17b$Unify the look and export properly.$t17b$, $t17c$Apply consistent colour adjustments, remove flicker where you can, and export at the right resolution, frame rate and format for the platform.$t17c$, $t17d$Colour and finishing$t17d$, $t17e$Colour-match a sequence and export it. Submit the link and the export settings you chose.

**Sharing video:** upload to YouTube (unlisted), Google Drive or similar and paste the link. Video is checked by a person.$t17e$, $t17f$[{"criterion": "Unified look", "max_points": 45, "guidance": "Consistent."}, {"criterion": "Export suitable", "max_points": 30, "guidance": "Correct settings."}, {"criterion": "Explained", "max_points": 25, "guidance": "Reasons."}]$t17f$::jsonb, 20, 'link', false, true),
  (18, $t18a$Module project: a 45-second edited piece$t18a$, $t18b$Deliver an edited piece with sound and captions.$t18b$, $t18c$Show Module 3. Deliver a **45-second edited piece** with voiceover or music, captions and consistent colour.

A person reviews your work and can ask for revisions.$t18c$, $t18d$Module project: a 45-second edited piece$t18d$, $t18e$Submit the final link, script, sound sources with licences and export settings.

**Sharing video:** upload to YouTube (unlisted), Google Drive or similar and paste the link. Video is checked by a person.$t18e$, $t18f$[{"criterion": "Story and pace", "max_points": 30, "guidance": "Engaging."}, {"criterion": "Sound and captions", "max_points": 25, "guidance": "Clear."}, {"criterion": "Rights", "max_points": 20, "guidance": "Documented."}, {"criterion": "Polish", "max_points": 25, "guidance": "Consistent."}]$t18f$::jsonb, 100, 'link', false, true),
  (19, $t19a$Formats and platforms$t19a$, $t19b$Deliver in the right shape.$t19b$, $t19c$Vertical 9:16 for shorts and reels, 16:9 for YouTube, 1:1 for some feeds. The first 3 seconds decide whether people stay.$t19c$, $t19d$Formats and platforms$t19d$, $t19e$Re-cut one piece in two formats. Submit both links and what you changed.

**Sharing video:** upload to YouTube (unlisted), Google Drive or similar and paste the link. Video is checked by a person.$t19e$, $t19f$[{"criterion": "Correct ratios", "max_points": 40, "guidance": "Both right."}, {"criterion": "Hook in three seconds", "max_points": 35, "guidance": "Clear."}, {"criterion": "Adaptation", "max_points": 25, "guidance": "Explained."}]$t19f$::jsonb, 20, 'link', false, true),
  (20, $t20a$Ethics of synthetic media$t20a$, $t20b$Use realistic video responsibly.$t20b$, $t20c$Do not make misleading videos of real people or events. Do not use someone's face or voice without consent. Label synthetic content where required. Consider who could be harmed.$t20c$, $t20d$Ethics of synthetic media$t20d$, $t20e$Write five rules for your own synthetic video work and apply them to a decision you made.$t20e$, $t20f$[{"criterion": "Rules are concrete", "max_points": 40, "guidance": "Followable."}, {"criterion": "Applied to a real decision", "max_points": 35, "guidance": "Example."}, {"criterion": "Covers consent and labelling", "max_points": 25, "guidance": "Mentioned."}]$t20f$::jsonb, 20, 'text', false, false),
  (21, $t21a$Copyright, licences and platform rules$t21a$, $t21b$Stay on the right side of rights.$t21b$, $t21c$Check the tool's licence for commercial use, use licensed music, do not copy characters or brands, and follow each platform's synthetic-media disclosure rules, which change over time.$t21c$, $t21d$Copyright, licences and platform rules$t21d$, $t21e$Audit one of your videos: list every asset, its source and licence, and the disclosure you will use.$t21e$, $t21f$[{"criterion": "Complete audit", "max_points": 45, "guidance": "Every asset."}, {"criterion": "Licences real", "max_points": 35, "guidance": "Checked."}, {"criterion": "Disclosure planned", "max_points": 20, "guidance": "Stated."}]$t21f$::jsonb, 20, 'text', false, false),
  (22, $t22a$Cost and workflow$t22a$, $t22b$Plan credits and time.$t22b$, $t22c$Estimate cost per shot including retries. Batch work, reuse assets, and keep a project folder with naming. Decide when to stop polishing.$t22c$, $t22d$Cost and workflow$t22d$, $t22e$Create a budget and schedule for a 60-second film: credits per shot, retries, hours by stage.$t22e$, $t22f$[{"criterion": "Realistic budget", "max_points": 40, "guidance": "Retries included."}, {"criterion": "Schedule", "max_points": 30, "guidance": "Hours."}, {"criterion": "Workflow organised", "max_points": 30, "guidance": "Files and naming."}]$t22f$::jsonb, 20, 'text', false, false),
  (23, $t23a$Feedback and improvement$t23a$, $t23b$Get useful feedback on a cut.$t23b$, $t23c$Show a rough cut to three viewers with questions: what did you understand, where were you bored, what confused you? Fix the top two.$t23c$, $t23d$Feedback and improvement$t23d$, $t23e$Submit feedback from three viewers and the two fixes you made.$t23e$, $t23f$[{"criterion": "Real feedback", "max_points": 40, "guidance": "Three viewers."}, {"criterion": "Prioritised", "max_points": 30, "guidance": "Top two."}, {"criterion": "Fixes made", "max_points": 30, "guidance": "Specific."}]$t23f$::jsonb, 20, 'text', false, false),
  (24, $t24a$Module project: a platform-ready short$t24a$, $t24b$Deliver a polished short in the right format with rights checked.$t24b$, $t24c$Show Module 4. Deliver a **platform-ready 30 to 45 second short** with captions, rights audit and a disclosure line.

A person reviews your work and can ask for revisions.$t24c$, $t24d$Module project: a platform-ready short$t24d$, $t24e$Submit the final link, rights audit, disclosure line, and feedback used.

**Sharing video:** upload to YouTube (unlisted), Google Drive or similar and paste the link. Video is checked by a person.$t24e$, $t24f$[{"criterion": "Quality and story", "max_points": 30, "guidance": "Engaging."}, {"criterion": "Rights and ethics", "max_points": 30, "guidance": "Audited."}, {"criterion": "Platform fit", "max_points": 20, "guidance": "Right format."}, {"criterion": "Feedback used", "max_points": 20, "guidance": "Improved."}]$t24f$::jsonb, 100, 'link', false, true),
  (25, $t25a$Capstone 1: concept and brief$t25a$, $t25b$Plan a 60-second short film or promo.$t25b$, $t25c$Choose a story or a promo for a real or made-up brand. Write the brief: audience, goal, length, platform and tone.$t25c$, $t25d$Capstone 1: concept and brief$t25d$, $t25e$Submit the brief and logline.$t25e$, $t25f$[{"criterion": "Brief is clear", "max_points": 45, "guidance": "Complete."}, {"criterion": "Logline works", "max_points": 30, "guidance": "Who/want/obstacle."}, {"criterion": "Scope realistic", "max_points": 25, "guidance": "Doable."}]$t25f$::jsonb, 20, 'text', false, false),
  (26, $t26a$Capstone 2: script, shot list and storyboard$t26a$, $t26b$Plan every shot.$t26b$, $t26c$Write the script, shot list and storyboard stills.$t26c$, $t26d$Capstone 2: script, shot list and storyboard$t26d$, $t26e$Submit the script, shot list and storyboard image links.

Paste *direct* image links.$t26e$, $t26f$[{"criterion": "Script and shots aligned", "max_points": 40, "guidance": "Consistent."}, {"criterion": "Storyboard clear", "max_points": 35, "guidance": "Readable."}, {"criterion": "Consistent look", "max_points": 25, "guidance": "Same style."}]$t26f$::jsonb, 20, 'link', false, false),
  (27, $t27a$Capstone 3: generate the shots$t27a$, $t27b$Produce and select the best takes.$t27b$, $t27c$Generate the shots, keep the best takes and note credits used.$t27c$, $t27d$Capstone 3: generate the shots$t27d$, $t27e$Submit links to the selected clips and a credit log.

**Sharing video:** upload to YouTube (unlisted), Google Drive or similar and paste the link. Video is checked by a person.$t27e$, $t27f$[{"criterion": "Shots match plan", "max_points": 40, "guidance": "Follows storyboard."}, {"criterion": "Selected well", "max_points": 30, "guidance": "Best takes."}, {"criterion": "Credit log", "max_points": 30, "guidance": "Recorded."}]$t27f$::jsonb, 90, 'link', false, true),
  (28, $t28a$Capstone 4: edit, sound and titles$t28a$, $t28b$Assemble the film.$t28b$, $t28c$Edit, add voice or music, captions and titles, and grade colour.$t28c$, $t28d$Capstone 4: edit, sound and titles$t28d$, $t28e$Submit the rough cut link and the list of sound sources with licences.

**Sharing video:** upload to YouTube (unlisted), Google Drive or similar and paste the link. Video is checked by a person.$t28e$, $t28f$[{"criterion": "Edit flows", "max_points": 35, "guidance": "Pace."}, {"criterion": "Sound and captions", "max_points": 35, "guidance": "Clear."}, {"criterion": "Rights", "max_points": 30, "guidance": "Documented."}]$t28f$::jsonb, 90, 'link', false, true),
  (29, $t29a$Capstone 5: feedback and final polish$t29a$, $t29b$Improve with feedback and finish.$t29b$, $t29c$Show the rough cut to three people, fix the top issues and export the final.$t29c$, $t29d$Capstone 5: feedback and final polish$t29d$, $t29e$Submit the feedback and the fixes you made.$t29e$, $t29f$[{"criterion": "Real feedback", "max_points": 40, "guidance": "Three viewers."}, {"criterion": "Fixes", "max_points": 40, "guidance": "Specific."}, {"criterion": "Final export ready", "max_points": 20, "guidance": "Right settings."}]$t29f$::jsonb, 20, 'text', false, false),
  (30, $t30a$Capstone 6: release and reflect$t30a$, $t30b$Publish and write the making-of.$t30b$, $t30c$Publish your film, add a disclosure line, and write a short making-of: what worked, what failed, credits used. Share in the Discord and ask for one piece of feedback.

A person reviews your work and can ask for revisions.$t30c$, $t30d$Capstone 6: release and reflect$t30d$, $t30e$Submit the final link, disclosure line, rights audit and the making-of note.

**Sharing video:** upload to YouTube (unlisted), Google Drive or similar and paste the link. Video is checked by a person.$t30e$, $t30f$[{"criterion": "Story and craft", "max_points": 30, "guidance": "Engaging."}, {"criterion": "Consistency and polish", "max_points": 25, "guidance": "Professional."}, {"criterion": "Rights and ethics", "max_points": 25, "guidance": "Handled."}, {"criterion": "Reflection", "max_points": 20, "guidance": "Honest."}]$t30f$::jsonb, 90, 'link', false, true)
) as v(n, title, objective, lesson_md, skill_focus, assignment_md, rubric, est_minutes, submission_type, ai_evaluate, requires_review)
where t.slug = 'film'
on conflict (track_id, day_number) do nothing;
