-- Business & freelancing, Grandmaster tier (days 81-90). Authored content, UNPUBLISHED until a person reviews it in Admin.
insert into public.day
  (track_id, tier_id, day_number, title, objective, lesson_md, skill_focus, assignment_md, rubric,
   est_minutes, is_published, credit_budget, submission_type, ai_evaluate, requires_review)
select t.id, ti.id, v.n, v.title, v.objective, v.lesson_md, v.skill_focus, v.assignment_md, v.rubric,
       v.est_minutes, false, null, v.submission_type, v.ai_evaluate, v.requires_review
from public.track t
join public.tier ti on ti.track_id = t.id and ti.slug = 'grandmaster'
cross join (values
  (81, $t81a$Teach a business skill$t81a$, $t81b$Explain one skill to a beginner.$t81b$, $t81c$Write a lesson with worked example, practice task and success check.$t81c$, $t81d$Teach a business skill$t81d$, $t81e$Submit the lesson.$t81e$, $t81f$[{"criterion": "Clear", "max_points": 35, "guidance": "Beginner-friendly."}, {"criterion": "Example", "max_points": 35, "guidance": "Real."}, {"criterion": "Practice", "max_points": 30, "guidance": "Usable."}]$t81f$::jsonb, 60, 'text', false, false),
  (82, $t82a$Offer critique clinic$t82a$, $t82b$Review three offers.$t82b$, $t82c$Review three offers: clarity, honesty, top fix and test.$t82c$, $t82d$Offer critique clinic$t82d$, $t82e$Submit three reviews.$t82e$, $t82f$[{"criterion": "Diagnosis", "max_points": 40, "guidance": "Precise."}, {"criterion": "Prioritised", "max_points": 30, "guidance": "Focused."}, {"criterion": "Honest", "max_points": 30, "guidance": "Fair."}]$t82f$::jsonb, 60, 'text', false, false),
  (83, $t83a$Publish a template kit$t83a$, $t83b$Share reusable tools.$t83b$, $t83c$Publish proposal, contract outline and onboarding templates with guidance and disclaimers.$t83c$, $t83d$Publish a template kit$t83d$, $t83e$Submit the kit.$t83e$, $t83f$[{"criterion": "Useful", "max_points": 35, "guidance": "Reusable."}, {"criterion": "Guidance", "max_points": 35, "guidance": "Clear."}, {"criterion": "Disclaimers", "max_points": 30, "guidance": "Present."}]$t83f$::jsonb, 90, 'text', false, false),
  (84, $t84a$Case study: client outcome$t84a$, $t84b$Document a client result honestly.$t84b$, $t84c$Situation, work, result and lessons with permission and real numbers.$t84c$, $t84d$Case study: client outcome$t84d$, $t84e$Submit the case study.$t84e$, $t84f$[{"criterion": "Numbers real", "max_points": 40, "guidance": "Honest."}, {"criterion": "Permission", "max_points": 30, "guidance": "Noted."}, {"criterion": "Clear", "max_points": 30, "guidance": "Structured."}]$t84f$::jsonb, 60, 'text', false, false),
  (85, $t85a$Grandmaster project 1: body-of-work plan$t85a$, $t85b$Plan your public work.$t85b$, $t85c$Deliver a **plan**: point of view, three case studies, one teaching resource, one template kit and six-month schedule.

Your work is scored on the rubric below. You can revise and resubmit.$t85c$, $t85d$Grandmaster project 1: body-of-work plan$t85d$, $t85e$Submit the plan with measures.$t85e$, $t85f$[{"criterion": "Point of view", "max_points": 30, "guidance": "Distinct."}, {"criterion": "Pieces valuable", "max_points": 30, "guidance": "Strong."}, {"criterion": "Realistic", "max_points": 20, "guidance": "Feasible."}, {"criterion": "Measures", "max_points": 20, "guidance": "Clear."}]$t85f$::jsonb, 90, 'text', true, false),
  (86, $t86a$Mentor a freelancer$t86a$, $t86b$Review a peer's business pack.$t86b$, $t86c$Review a peer's offer, proposal and pricing with evidence.$t86c$, $t86d$Mentor a freelancer$t86d$, $t86e$Submit the scored review.$t86e$, $t86f$[{"criterion": "Justified", "max_points": 40, "guidance": "Evidence."}, {"criterion": "Fair", "max_points": 30, "guidance": "Balanced."}, {"criterion": "Exercise", "max_points": 30, "guidance": "Practical."}]$t86f$::jsonb, 60, 'text', false, false),
  (87, $t87a$Build a course module$t87a$, $t87b$Package your know-how.$t87b$, $t87c$Outcomes, five lessons, tasks, project and rubric; test with a learner.$t87c$, $t87d$Build a course module$t87d$, $t87e$Submit outline, lesson and feedback.$t87e$, $t87f$[{"criterion": "Outcomes", "max_points": 30, "guidance": "Measurable."}, {"criterion": "Lesson", "max_points": 40, "guidance": "Strong."}, {"criterion": "Tested", "max_points": 30, "guidance": "Learner."}]$t87f$::jsonb, 120, 'text', false, false),
  (88, $t88a$Business ethics and standards$t88a$, $t88b$State your principles.$t88b$, $t88c$Publish how you price, market, use AI, protect data and handle mistakes.$t88c$, $t88d$Business ethics and standards$t88d$, $t88e$Submit your standards.$t88e$, $t88f$[{"criterion": "Specific", "max_points": 40, "guidance": "Concrete."}, {"criterion": "Accountability", "max_points": 35, "guidance": "Corrections."}, {"criterion": "AI honesty", "max_points": 25, "guidance": "Clear."}]$t88f$::jsonb, 45, 'text', false, false),
  (89, $t89a$Impact audit$t89a$, $t89b$Show what your business created.$t89b$, $t89c$Client outcomes, revenue, learning shared, with limits.$t89c$, $t89d$Impact audit$t89d$, $t89e$Submit the impact report.$t89e$, $t89f$[{"criterion": "Evidence real", "max_points": 45, "guidance": "Collected."}, {"criterion": "Honest", "max_points": 35, "guidance": "Limits."}, {"criterion": "Next steps", "max_points": 20, "guidance": "Clear."}]$t89f$::jsonb, 60, 'text', false, false),
  (90, $t90a$Grandmaster capstone: portfolio, teaching and impact$t90a$, $t90b$Prove mastery.$t90b$, $t90c$The final assessment. Deliver a **portfolio**: flagship business case study, template kit, teaching resource with learner feedback, peer review, standards and impact report.

Your work is scored on the rubric below. You can revise and resubmit.$t90c$, $t90d$Grandmaster capstone: portfolio, teaching and impact$t90d$, $t90e$Submit the portfolio and a one-page reflection.$t90e$, $t90f$[{"criterion": "Business results", "max_points": 30, "guidance": "Evidenced."}, {"criterion": "Integrity", "max_points": 25, "guidance": "Verified."}, {"criterion": "Teaching and mentoring", "max_points": 25, "guidance": "Effective."}, {"criterion": "Impact and reflection", "max_points": 20, "guidance": "Evidenced."}]$t90f$::jsonb, 180, 'text', true, false)
) as v(n, title, objective, lesson_md, skill_focus, assignment_md, rubric, est_minutes, submission_type, ai_evaluate, requires_review)
where t.slug = 'business'
on conflict (track_id, day_number) do nothing;
