-- AI agents & automation, Expert tier (days 61-80). Authored content, UNPUBLISHED until a person reviews it in Admin.
insert into public.day
  (track_id, tier_id, day_number, title, objective, lesson_md, skill_focus, assignment_md, rubric,
   est_minutes, is_published, credit_budget, submission_type, ai_evaluate, requires_review)
select t.id, ti.id, v.n, v.title, v.objective, v.lesson_md, v.skill_focus, v.assignment_md, v.rubric,
       v.est_minutes, false, null, v.submission_type, v.ai_evaluate, v.requires_review
from public.track t
join public.tier ti on ti.track_id = t.id and ti.slug = 'expert'
cross join (values
  (61, $t61a$Agent architectures compared$t61a$, $t61b$Choose between single, pipeline, supervisor and swarm designs.$t61b$, $t61c$Single agents are simplest; pipelines suit fixed stages; supervisors delegate to specialists; loosely coupled swarms are hardest to control. Pick by risk, need for parallel work and how much you must audit.$t61c$, $t61d$Agent architectures compared$t61d$, $t61e$Recommend an architecture for three real tasks with trade-offs and audit needs.$t61e$, $t61f$[{"criterion": "Reasoned choices", "max_points": 40, "guidance": "Trade-offs."}, {"criterion": "Audit considered", "max_points": 30, "guidance": "Traceable."}, {"criterion": "Simplicity valued", "max_points": 30, "guidance": "Not overbuilt."}]$t61f$::jsonb, 45, 'text', false, false),
  (62, $t62a$Evaluation harnesses$t62a$, $t62b$Automate testing of agent behaviour.$t62b$, $t62c$Build a harness that runs your test set, scores results (rules and model-graded), tracks regressions and stores traces. Calibrate any model grader against human grading.$t62c$, $t62d$Evaluation harnesses$t62d$, $t62e$Describe and run a harness on 20 tasks; report pass rate and grader agreement with a human sample.$t62e$, $t62f$[{"criterion": "Harness works", "max_points": 35, "guidance": "Runs."}, {"criterion": "Calibrated grader", "max_points": 40, "guidance": "Compared to human."}, {"criterion": "Regressions tracked", "max_points": 25, "guidance": "Recorded."}]$t62f$::jsonb, 60, 'text', false, false),
  (63, $t63a$Red-teaming your agent$t63a$, $t63b$Attack your own system.$t63b$, $t63c$Try prompt injection, data exfiltration, tool abuse, jailbreaks and social engineering. Record each attack, result and fix. Never test against systems you do not own.$t63c$, $t63d$Red-teaming your agent$t63d$, $t63e$Run ten attacks on your own agent. Submit attacks, outcomes and fixes.$t63e$, $t63f$[{"criterion": "Attacks realistic", "max_points": 35, "guidance": "Varied."}, {"criterion": "Fixes effective", "max_points": 40, "guidance": "Retested."}, {"criterion": "Scope ethical", "max_points": 25, "guidance": "Own systems."}]$t63f$::jsonb, 60, 'text', false, false),
  (64, $t64a$Permissions, secrets and sandboxes$t64a$, $t64b$Contain what an agent can do.$t64b$, $t64c$Per-task credentials, expiring tokens, sandboxed execution, allow-lists for tools and domains, and spending caps. Rotate secrets and never place them in prompts or logs.$t64c$, $t64d$Permissions, secrets and sandboxes$t64d$, $t64e$Write a containment design: credentials, sandbox, allow-lists, caps and rotation.$t64e$, $t64f$[{"criterion": "Least privilege", "max_points": 40, "guidance": "Applied."}, {"criterion": "Secrets handled", "max_points": 35, "guidance": "Safe."}, {"criterion": "Caps", "max_points": 25, "guidance": "Defined."}]$t64f$::jsonb, 45, 'text', false, false),
  (65, $t65a$Expert project 1: a secured, evaluated agent$t65a$, $t65b$Show it is safe and measured.$t65b$, $t65c$Show Module 1. Deliver an agent with an **architecture rationale, evaluation results, red-team log and containment design**.

Your work is scored on the rubric below. You can revise and resubmit.$t65c$, $t65d$Expert project 1: a secured, evaluated agent$t65d$, $t65e$Submit all four with data.$t65e$, $t65f$[{"criterion": "Architecture", "max_points": 20, "guidance": "Reasoned."}, {"criterion": "Evaluation", "max_points": 30, "guidance": "Real."}, {"criterion": "Red-team and containment", "max_points": 30, "guidance": "Effective."}, {"criterion": "Honesty", "max_points": 20, "guidance": "Gaps."}]$t65f$::jsonb, 120, 'text', true, false),
  (66, $t66a$Multi-agent coordination$t66a$, $t66b$Make agents work together without chaos.$t66b$, $t66c$Define shared state, message formats, ownership of decisions, conflict resolution and a stop condition. Log every message.$t66c$, $t66d$Multi-agent coordination$t66d$, $t66e$Design a two-agent workflow with message schema, ownership and stop rules.$t66e$, $t66f$[{"criterion": "Ownership clear", "max_points": 35, "guidance": "Defined."}, {"criterion": "Schema", "max_points": 35, "guidance": "Precise."}, {"criterion": "Stop rules", "max_points": 30, "guidance": "Present."}]$t66f$::jsonb, 45, 'text', false, false),
  (67, $t67a$Long-running and asynchronous workflows$t67a$, $t67b$Handle tasks that take hours or days.$t67b$, $t67c$Persist state, resume after failure, use queues and timeouts, notify humans of progress and support cancellation.$t67c$, $t67d$Long-running and asynchronous workflows$t67d$, $t67e$Design a long-running workflow with state, retries, timeouts and cancellation.$t67e$, $t67f$[{"criterion": "State persisted", "max_points": 35, "guidance": "Resumable."}, {"criterion": "Retries and timeouts", "max_points": 35, "guidance": "Sensible."}, {"criterion": "Cancellation", "max_points": 30, "guidance": "Supported."}]$t67f$::jsonb, 45, 'text', false, false),
  (68, $t68a$Human oversight at scale$t68a$, $t68b$Keep people in control when volume grows.$t68b$, $t68c$Sample-based review, confidence thresholds, escalation queues and reviewer training. Track reviewer agreement and override rates.$t68c$, $t68d$Human oversight at scale$t68d$, $t68e$Design an oversight plan with thresholds, sampling rates and metrics.$t68e$, $t68f$[{"criterion": "Thresholds justified", "max_points": 35, "guidance": "Reasoned."}, {"criterion": "Sampling", "max_points": 35, "guidance": "Defined."}, {"criterion": "Metrics", "max_points": 30, "guidance": "Tracked."}]$t68f$::jsonb, 45, 'text', false, false),
  (69, $t69a$Cost engineering$t69a$, $t69b$Cut cost without cutting quality.$t69b$, $t69c$Route easy work to small models, cache, shorten context, batch and stop early. Measure cost per successful task.$t69c$, $t69d$Cost engineering$t69d$, $t69e$Reduce cost per task by at least 20 percent on a test set. Submit before and after quality and cost.$t69e$, $t69f$[{"criterion": "Measured", "max_points": 40, "guidance": "Numbers."}, {"criterion": "Quality kept", "max_points": 35, "guidance": "Verified."}, {"criterion": "Methods", "max_points": 25, "guidance": "Named."}]$t69f$::jsonb, 45, 'text', false, false),
  (70, $t70a$Expert project 2: a scalable workflow$t70a$, $t70b$Deliver coordination, async and oversight.$t70b$, $t70c$Show Module 2. Deliver a **scalable workflow** with coordination design, long-running handling, oversight plan and cost results.

Your work is scored on the rubric below. You can revise and resubmit.$t70c$, $t70d$Expert project 2: a scalable workflow$t70d$, $t70e$Submit all with evidence.$t70e$, $t70f$[{"criterion": "Coordination", "max_points": 25, "guidance": "Sound."}, {"criterion": "Reliability", "max_points": 25, "guidance": "Resumable."}, {"criterion": "Oversight", "max_points": 25, "guidance": "Planned."}, {"criterion": "Cost evidence", "max_points": 25, "guidance": "Measured."}]$t70f$::jsonb, 120, 'text', true, false),
  (71, $t71a$Domain agents: customer operations$t71a$, $t71b$Automate service work responsibly.$t71b$, $t71c$Ticket triage, drafts and knowledge search with strict handoff rules, tone checks and no unapproved promises. Measure resolution time and customer satisfaction.$t71c$, $t71d$Domain agents: customer operations$t71d$, $t71e$Design a service agent and define five success and five harm metrics.$t71e$, $t71f$[{"criterion": "Metrics balanced", "max_points": 40, "guidance": "Success and harm."}, {"criterion": "Handoff rules", "max_points": 35, "guidance": "Clear."}, {"criterion": "Customer protection", "max_points": 25, "guidance": "Considered."}]$t71f$::jsonb, 45, 'text', false, false),
  (72, $t72a$Domain agents: analysis and reporting$t72a$, $t72b$Produce reliable analysis.$t72b$, $t72c$Reproducible queries, data validation, saved code and human sign-off on conclusions. Log data versions.$t72c$, $t72d$Domain agents: analysis and reporting$t72d$, $t72e$Design a reporting agent with validation and sign-off steps.$t72e$, $t72f$[{"criterion": "Reproducible", "max_points": 40, "guidance": "Logged."}, {"criterion": "Validation", "max_points": 35, "guidance": "Present."}, {"criterion": "Sign-off", "max_points": 25, "guidance": "Human."}]$t72f$::jsonb, 45, 'text', false, false),
  (73, $t73a$Regulation, liability and documentation$t73a$, $t73b$Know your obligations.$t73b$, $t73c$Requirements vary by country and use (employment, finance, health). Keep records of purpose, data, testing, oversight and incidents. Seek legal advice. This course is not legal advice.$t73c$, $t73d$Regulation, liability and documentation$t73d$, $t73e$Write a model documentation sheet for your agent and list where legal advice is needed.$t73e$, $t73f$[{"criterion": "Documentation", "max_points": 45, "guidance": "Complete."}, {"criterion": "Risk areas", "max_points": 35, "guidance": "Identified."}, {"criterion": "Advice noted", "max_points": 20, "guidance": "Limits."}]$t73f$::jsonb, 45, 'text', false, false),
  (74, $t74a$Change management and adoption$t74a$, $t74b$Get people to use it well.$t74b$, $t74c$Involve users early, train them, set expectations, start with a pilot and collect feedback. Address job concerns honestly.$t74c$, $t74d$Change management and adoption$t74d$, $t74e$Write an adoption plan with training, pilot, feedback and communication.$t74e$, $t74f$[{"criterion": "Users involved", "max_points": 35, "guidance": "Early."}, {"criterion": "Pilot and feedback", "max_points": 35, "guidance": "Planned."}, {"criterion": "Honest communication", "max_points": 30, "guidance": "Transparent."}]$t74f$::jsonb, 45, 'text', false, false),
  (75, $t75a$Expert project 3: a domain deployment plan$t75a$, $t75b$Plan a real deployment.$t75b$, $t75c$Show Module 3. Deliver a **deployment plan**: domain agent design, metrics, documentation, regulatory notes and adoption plan.

Your work is scored on the rubric below. You can revise and resubmit.$t75c$, $t75d$Expert project 3: a domain deployment plan$t75d$, $t75e$Submit the plan.$t75e$, $t75f$[{"criterion": "Domain fit", "max_points": 25, "guidance": "Suitable."}, {"criterion": "Metrics and safeguards", "max_points": 30, "guidance": "Balanced."}, {"criterion": "Documentation and compliance", "max_points": 25, "guidance": "Complete."}, {"criterion": "Adoption", "max_points": 20, "guidance": "Realistic."}]$t75f$::jsonb, 120, 'text', true, false),
  (76, $t76a$Flagship: baseline and design$t76a$, $t76b$Start with measured baseline.$t76b$, $t76c$Pick a real workflow, measure it for two weeks and design the system with risk register.$t76c$, $t76d$Flagship: baseline and design$t76d$, $t76e$Submit baseline data and design.$t76e$, $t76f$[{"criterion": "Baseline real", "max_points": 40, "guidance": "Measured."}, {"criterion": "Design", "max_points": 35, "guidance": "Sound."}, {"criterion": "Risk register", "max_points": 25, "guidance": "Complete."}]$t76f$::jsonb, 90, 'text', false, false),
  (77, $t77a$Flagship: build and evaluate$t77a$, $t77b$Build with an evaluation harness.$t77b$, $t77c$Build the system and run the harness on real cases.$t77c$, $t77d$Flagship: build and evaluate$t77d$, $t77e$Submit harness results and fixes.$t77e$, $t77f$[{"criterion": "Works", "max_points": 40, "guidance": "Evidence."}, {"criterion": "Harness", "max_points": 35, "guidance": "Used."}, {"criterion": "Fixes", "max_points": 25, "guidance": "Applied."}]$t77f$::jsonb, 120, 'text', false, false),
  (78, $t78a$Flagship: pilot with oversight$t78a$, $t78b$Run with real users under supervision.$t78b$, $t78c$Pilot for two weeks with oversight metrics and incident log.$t78c$, $t78d$Flagship: pilot with oversight$t78d$, $t78e$Submit pilot report.$t78e$, $t78f$[{"criterion": "Real pilot", "max_points": 35, "guidance": "Users."}, {"criterion": "Oversight metrics", "max_points": 35, "guidance": "Tracked."}, {"criterion": "Incidents", "max_points": 30, "guidance": "Logged."}]$t78f$::jsonb, 90, 'text', false, false),
  (79, $t79a$Flagship: measure against baseline$t79a$, $t79b$Prove the value.$t79b$, $t79c$Compare pilot results to baseline on time, quality, cost and harm.$t79c$, $t79d$Flagship: measure against baseline$t79d$, $t79e$Submit comparison with honest analysis.$t79e$, $t79f$[{"criterion": "Comparison valid", "max_points": 40, "guidance": "Fair."}, {"criterion": "Numbers real", "max_points": 35, "guidance": "Data."}, {"criterion": "Harms considered", "max_points": 25, "guidance": "Included."}]$t79f$::jsonb, 60, 'text', false, false),
  (80, $t80a$Expert project 4: the flagship system$t80a$, $t80b$Deliver a system with proof.$t80b$, $t80c$Show Module 4. Deliver the **flagship system** with baseline, evaluation, pilot, results, documentation and handover.

Your work is scored on the rubric below. You can revise and resubmit.$t80c$, $t80d$Expert project 4: the flagship system$t80d$, $t80e$Submit a case study with evidence and lessons.$t80e$, $t80f$[{"criterion": "Results vs baseline", "max_points": 30, "guidance": "Measured."}, {"criterion": "Safety and oversight", "max_points": 30, "guidance": "Strong."}, {"criterion": "Documentation", "max_points": 20, "guidance": "Clear."}, {"criterion": "Honesty", "max_points": 20, "guidance": "Frank."}]$t80f$::jsonb, 200, 'text', true, false)
) as v(n, title, objective, lesson_md, skill_focus, assignment_md, rubric, est_minutes, submission_type, ai_evaluate, requires_review)
where t.slug = 'agents'
on conflict (track_id, day_number) do nothing;
