-- Third expansion: 4 new subcategories covering gaps the existing taxonomy did
-- not fit well (video consistency/realism, video types, natural writing voice,
-- full marketing-graphic ad concepts), plus a few bonus prompts added to two
-- existing subcategories (shot-types-camera-angles, academic) for depth.
--
-- Note on "writing/natural-voice": framed around writing that sounds genuinely
-- human (cutting robotic AI patterns, natural rhythm, a real persons voice) —
-- the same underlying skill members actually want for emails, posts, and
-- business writing — rather than as "bypass AI detectors," since that framing
-- is mostly associated with passing off AI work as ones own in contexts like
-- school where that would be dishonest. The prompts here serve the legitimate
-- craft goal without teaching detection evasion for that purpose.
--
-- Note on "image/marketing-graphics": the 5 core templates are refined and
-- genericized from real ad concepts the user shared, with all product/brand
-- specifics replaced by [your product] / [brand] placeholders so any member
-- can apply them to their own business, not a specific third-party product.

-- ── new subcategories ────────────────────────────────────────────────────
insert into public.prompt_subcategories (category_id, slug, name, sort_order)
select c.id, x.sub_slug, x.sub_name, x.sub_sort
from public.prompt_categories c
join (values
  ('video', 'consistency-realism', 'Consistency & realism', 7),
  ('video', 'video-types', 'Video types', 8),
  ('writing', 'natural-voice', 'Natural voice', 6),
  ('image', 'marketing-graphics', 'Marketing graphics', 6)
) as x(cat_slug, sub_slug, sub_name, sub_sort) on x.cat_slug = c.slug;

-- ── prompts for the new subcategories, plus bonus prompts for 2 existing ──
insert into public.prompts (subcategory_id, title, body, swap_note, difficulty, sort_order)
select s.id, x.title, x.body, x.swap_note, x.difficulty, x.sort_order
from public.prompt_subcategories s
join public.prompt_categories c on c.id = s.category_id
join (values
  -- video / consistency-realism
  ('video', 'consistency-realism', 'Keep a character consistent across shots', 'I am generating multiple shots of the same character: [describe character in detail: face, hair, outfit, build]. Repeat this exact description in every prompt, word for word, so the model has the same anchor each time.', 'swap: if the character still drifts, generate a single reference image first and describe that reference in later prompts.', 'beginner', 1),
  ('video', 'consistency-realism', 'Stop AI video from looking generic', 'This generation looks generic and could be stock footage of anyone: [describe the generic result]. Add one specific, unusual detail about the subject or setting that a stock clip would not have.', 'swap: ask what makes it feel generic in the first place, so you know what to change.', 'intermediate', 2),
  ('video', 'consistency-realism', 'Get a more realistic, less artificial motion', 'This motion looks artificial or floaty: [describe the motion]. Describe the motion in terms of real physical weight and momentum instead of just the action.', 'swap: reference a real-world comparison, such as how a specific object actually moves, for a more grounded result.', 'beginner', 3),
  ('video', 'consistency-realism', 'Keep the environment consistent across cuts', 'I am cutting between multiple shots in the same location: [describe location]. What details about the environment do I need to repeat in every prompt so it does not look like a different place each time?', 'swap: list the 3 most identifying features of the location and lock those first.', 'intermediate', 4),
  ('video', 'consistency-realism', 'Avoid the uncanny valley in a realistic human subject', 'This generated person looks almost real but slightly off: [describe what feels wrong, e.g. eyes, skin, movement]. What is the likely cause, and how do I prompt around it?', 'swap: ask if a slightly more stylized, less photoreal target would sidestep the issue entirely.', 'advanced', 5),
  ('video', 'consistency-realism', 'Keep outfit and appearance locked across a sequence', 'I need this character to wear the exact same outfit and look the same in every shot: [describe outfit and appearance in full detail]. Write that description once, then reuse it unchanged in every subsequent prompt.', 'swap: ask what part of the description is most likely to drift first, so you can double-check that detail specifically.', 'beginner', 6),
  ('video', 'consistency-realism', 'Diagnose why consecutive generations look inconsistent', 'These 2 generations were supposed to be the same subject but look different: [describe both]. What likely changed between the 2 prompts that caused the drift?', 'swap: paste both exact prompts so the diagnosis can point to the specific wording that shifted.', 'intermediate', 7),
  ('video', 'consistency-realism', 'Build a reusable character sheet for repeated generations', 'I will be generating this character many times across a project: [describe character]. Write a single, precise character description block I can paste unchanged into every future prompt.', 'swap: ask for a shorter version too, in case some tools have a prompt length limit.', 'advanced', 8),
  ('video', 'consistency-realism', 'Get realistic lighting instead of an obviously synthetic look', 'This lighting looks synthetic and flat: [describe the lighting]. What would make it read as real, natural light instead?', 'swap: describe a specific real light source, like late afternoon sun through a window, instead of a vague lighting request.', 'beginner', 9),
  ('video', 'consistency-realism', 'Prevent a background from changing between shots', 'The background keeps shifting slightly between shots that are supposed to be the same location: [describe the issue]. What should I lock in the prompt to prevent that?', 'swap: ask specifically about camera position and framing, since small framing changes can make the same background look different.', 'intermediate', 10),

  -- video / video-types
  ('video', 'video-types', 'Prompt a product demo shot', 'I need a product demo shot showing [product] being used for [its main benefit]. Describe the shot so it reads clearly as a demo, not just a generic product shot.', 'swap: ask what single detail would make it obvious the product is actually working, not just sitting there.', 'beginner', 1),
  ('video', 'video-types', 'Prompt a cinematic trailer-style shot', 'I want a shot that feels like a movie trailer moment for [subject or brand]. Describe the shot with trailer-style drama: framing, pacing implied, and a sense of anticipation.', 'swap: ask for a calmer, less dramatic version too, in case the trailer style feels overdone for your use.', 'intermediate', 2),
  ('video', 'video-types', 'Prompt a UGC or testimonial-style shot', 'I want this to feel like a real person filmed it on their phone, not a professional production: [describe the subject or moment]. Describe the shot with that casual, handheld, authentic quality.', 'swap: ask what specifically makes footage look overly polished, so you avoid it.', 'beginner', 3),
  ('video', 'video-types', 'Prompt an explainer or tutorial-style shot', 'I need a clear, instructional shot showing [action or process] so a viewer can actually follow it. Describe the framing and clarity needed for that.', 'swap: ask whether a close-up insert shot would help clarify the process further.', 'intermediate', 4),
  ('video', 'video-types', 'Prompt a short social ad hook shot', 'I need the opening shot of a short social ad about [product or idea] that stops someone from scrolling in the first second. Describe a shot built specifically to grab attention immediately.', 'swap: ask for 3 different opening-shot ideas so you can compare which hooks hardest.', 'beginner', 5),
  ('video', 'video-types', 'Prompt lifestyle or b-roll footage', 'I need simple b-roll of [subject or setting] that feels natural and unstaged, meant to sit in the background of an edit. Describe the shot so it does not feel like the main focus of a scene.', 'swap: ask for a version with more visible motion, since static b-roll can feel dead in an edit.', 'intermediate', 6),
  ('video', 'video-types', 'Prompt a brand story or emotional narrative shot', 'I want a shot that communicates [brand value or feeling] without any dialogue or text, purely through visuals. Describe a shot that carries that meaning on its own.', 'swap: ask what visual metaphor could represent that value more specifically than a literal scene.', 'advanced', 7),
  ('video', 'video-types', 'Prompt a behind-the-scenes style shot', 'I want this to feel like a candid behind-the-scenes moment of [process or event], not a finished polished shot. Describe the rawer, more observational quality that needs.', 'swap: ask what would make it look too staged, so you can avoid that.', 'beginner', 8),
  ('video', 'video-types', 'Prompt a before-and-after transformation shot', 'I need to show a clear before-and-after transformation of [subject]. Describe how to frame both states so the change is unmistakable.', 'swap: ask whether a single continuous shot or a hard cut between the 2 states would communicate the change better.', 'intermediate', 9),
  ('video', 'video-types', 'Choose the right video type for the goal, not just the trend', 'I am trying to achieve [specific goal, e.g. build trust, drive a sale, explain a feature]. Which type of video, demo, testimonial-style, cinematic, or explainer, actually serves that goal best?', 'swap: ask what type would be the worst fit for this goal, so you know what to avoid.', 'advanced', 10),

  -- writing / natural-voice
  ('writing', 'natural-voice', 'Cut common AI-sounding filler words', 'Rewrite this to remove words and phrases that make writing sound like generic AI output, such as unnecessary hedging, empty transitions, and overused buzzwords: [paste text]', 'swap: ask for the specific list of words it removed, so you learn to spot them yourself.', 'beginner', 1),
  ('writing', 'natural-voice', 'Vary sentence rhythm so it does not sound robotic', 'This text has a repetitive sentence rhythm that sounds robotic: [paste text]. Rewrite it with more natural variation in sentence length.', 'swap: ask it to check whether the rewrite now reads like natural speech if read aloud.', 'intermediate', 2),
  ('writing', 'natural-voice', 'Replace generic claims with specific detail', 'This writing makes broad, generic claims instead of specific ones: [paste text]. Rewrite it replacing the vague parts with concrete, specific detail.', 'swap: give it one real detail or example to work into the rewrite.', 'beginner', 3),
  ('writing', 'natural-voice', 'Write in a specific persons actual voice', 'Here are a few examples of how I actually write: [paste 2 to 3 samples]. Rewrite this piece to match my real voice, not a generic professional tone: [paste piece to rewrite]', 'swap: point out one specific line that does not sound like you yet, so it can be corrected directly.', 'intermediate', 4),
  ('writing', 'natural-voice', 'Remove repetitive sentence openers and transitions', 'This text repeats the same sentence openers or transition words too often: [paste text]. Rewrite it with more natural variety.', 'swap: ask which opener or transition it used the most, so you notice the pattern next time.', 'beginner', 5),
  ('writing', 'natural-voice', 'Diagnose exactly what makes a piece sound AI-generated', 'This piece feels like it was written by AI, but I am not sure why: [paste text]. Point out the specific patterns, not just a general impression, that give it away.', 'swap: ask it to fix only the single most obvious pattern first, so you can compare before and after.', 'advanced', 6),
  ('writing', 'natural-voice', 'Add natural imperfection where it fits', 'This writing is too polished and even to sound like a real person wrote it casually: [paste text]. Loosen it up with the kind of small imperfections a real person naturally includes, without making it sloppy.', 'swap: specify the context, such as a casual social post versus a formal email, since the right amount of imperfection differs.', 'intermediate', 7),
  ('writing', 'natural-voice', 'Use contractions and natural phrasing', 'This text sounds stiff and overly formal: [paste text]. Rewrite it using contractions and more natural, conversational phrasing where appropriate.', 'swap: ask for a version that stays professional but still sounds like a person, if full casualness is not appropriate.', 'beginner', 8),
  ('writing', 'natural-voice', 'Stop over-qualifying every statement', 'This writing hedges almost every sentence with qualifiers like somewhat, arguably, or it could be argued: [paste text]. Rewrite it to state things directly where the hedging is not actually needed.', 'swap: ask which hedges were actually necessary to keep, since some caution is legitimate.', 'intermediate', 9),
  ('writing', 'natural-voice', 'Edit a piece so it reads as authentically yours', 'I used AI to help draft this, and I want to edit it so it genuinely reflects my own thinking and voice before I put my name on it: [paste draft]. Ask me questions about what I actually think, then help me revise it to reflect real answers.', 'swap: answer honestly rather than what sounds good, since the goal is your actual view, not a better-sounding one.', 'advanced', 10),

  -- image / marketing-graphics (refined and genericized templates)
  ('image', 'marketing-graphics', 'Futuristic tech command-center ad', 'Design a promotional graphic for [your product] in a futuristic tech command-center style. Headline: a short, bold statement of the core transformation your product enables, in capital letters. Subheading: one sentence describing what the product does and the range of use cases it covers. CTA: a short action phrase ending in an arrow, such as START BUILDING WITH [BRAND]. Visual direction: floating holographic dashboards, connected workflow nodes, a device with glowing panels, blue or purple neon lighting, subtle motion particles suggesting active automation.', 'swap: swap the neon blue/purple for your own brand colors if they differ.', 'intermediate', 1),
  ('image', 'marketing-graphics', 'Minimal premium SaaS ad', 'Design a promotional graphic for [your product] in a minimal, premium SaaS style. Headline: a short, confident statement of the core value in a few words. Subheading: one sentence listing the main things a user can do with it. CTA: a short, direct action phrase, such as TRY [PRODUCT] TODAY. Visual direction: clean glassmorphism cards, a simple product UI mockup, white and black contrast, soft gradients, generous whitespace, centered composition.', 'swap: ask for a version with the product mockup on the left instead of centered, if your layout needs it.', 'beginner', 2),
  ('image', 'marketing-graphics', 'Founder-focused growth ad', 'Design a promotional graphic for [your product] aimed at solo founders or small teams. Headline: a short statement positioning the product as a force multiplier for one person. Subheading: one sentence naming specific tasks or roles the product replaces or assists. CTA: a short action phrase, such as BUILD YOUR TEAM WITH [PRODUCT]. Visual direction: a person at a desk, multiple floating assistant or feature windows around them, a rising chart in the background, warm cinematic lighting.', 'swap: change the desk setting to match your actual audience, such as a workshop or a phone in hand, if a desk does not fit.', 'intermediate', 3),
  ('image', 'marketing-graphics', 'High-energy viral tech ad', 'Design a promotional graphic for [your product] in a high-energy, viral tech style. Headline: a bold, sweeping statement about the future or a shift your product represents. Subheading: one sentence covering the range of what the product creates or enables. CTA: an energetic action phrase, such as JOIN THE [CATEGORY] REVOLUTION. Visual direction: explosive lighting, a glowing central object representing the product core, energy particles, fast motion streaks, a bold high-contrast color palette.', 'swap: tone down the intensity if your brand is more understated than the high-energy style suggests.', 'advanced', 4),
  ('image', 'marketing-graphics', 'Business automation and enterprise ad', 'Design a promotional graphic for [your product] aimed at businesses. Headline: a short statement about automating or scaling operations with the product. Subheading: one sentence naming specific business functions the product improves. CTA: a short, results-oriented action phrase, such as SCALE FASTER WITH [PRODUCT]. Visual direction: workflow pipelines, automation arrows, a professional dashboard UI, simple assistant or process icons, a professional blue and black color palette, split-screen composition with the illustration on one side and copy on the other.', 'swap: adjust the color palette to your brand if blue and black does not fit.', 'intermediate', 5),
  ('image', 'marketing-graphics', 'Testimonial or social proof ad', 'Design a promotional graphic for [your product] built around a real result or testimonial. Headline: a short, specific outcome a real user got, in their words if possible. Subheading: one sentence of context on who got that result and how. CTA: a short action phrase, such as GET RESULTS LIKE THIS. Visual direction: a simple, credible layout, a quote mark or speech bubble element, a small photo or initials avatar if you have permission to use one, understated design that lets the result speak for itself.', 'swap: never use a real persons name, photo, or words without their permission, even if the result is real.', 'beginner', 6),
  ('image', 'marketing-graphics', 'Before-and-after transformation ad', 'Design a promotional graphic for [your product] built around a clear before-and-after contrast. Headline: a short statement naming the transformation, such as from [before state] to [after state]. Subheading: one sentence on how the product creates that shift. CTA: a short action phrase, such as START YOUR TRANSFORMATION. Visual direction: a clear split or side-by-side composition showing the before state and the after state, a strong visual contrast between the two halves, an arrow or divider marking the change.', 'swap: make sure the before-and-after claim is honest and something your product can actually deliver.', 'intermediate', 7),

  -- bonus / video / shot-types-camera-angles (continuing from sort_order 10)
  ('video', 'shot-types-camera-angles', 'Prompt a dramatic slow-motion effect', 'I want this action to feel dramatic and heightened using slow motion: [describe the action]. Describe how to prompt for that slowed, weighty quality.', 'swap: ask which specific moment within the action deserves the slow motion most, rather than the whole thing.', 'intermediate', 11),
  ('video', 'shot-types-camera-angles', 'Combine an unusual angle with a stylized effect', 'I want to combine an unconventional camera angle with a strong visual effect for [subject or moment]. Describe both together so they reinforce each other instead of competing.', 'swap: ask which of the two, the angle or the effect, should be the dominant choice if they start to fight.', 'advanced', 12),
  ('video', 'shot-types-camera-angles', 'Prompt a striking hero shot', 'I need one striking hero shot that represents [subject or product] at its best. Describe the angle, framing, and one standout visual element that would make this shot memorable.', 'swap: ask for 2 alternative hero shot ideas so you can compare which is strongest.', 'beginner', 13),

  -- bonus / writing / academic (continuing from sort_order 10)
  ('writing', 'academic', 'Synthesize multiple sources into one argument', 'Here are several sources on [topic]: [summarize or paste key points from each]. Synthesize them into one coherent argument, noting where they agree and where they conflict.', 'swap: ask it to flag which source is weakest if you need to prioritize which to cite most heavily.', 'advanced', 11),
  ('writing', 'academic', 'Structure a paper for a specific journal style', 'I am writing for [journal or publication type]. What structure and tone does that venue typically expect, and how does my current draft compare: [paste draft or outline]?', 'swap: ask for the structure alone first if you do not have a draft yet.', 'intermediate', 12),
  ('writing', 'academic', 'Stress-test a research claim before publishing', 'Here is a claim from my research: [paste claim]. What would a rigorous peer reviewer challenge about this claim, and is my evidence strong enough to hold up?', 'swap: ask specifically about the weakest link in your evidence chain.', 'advanced', 13)
) as x(cat_slug, sub_slug, title, body, swap_note, difficulty, sort_order)
  on x.cat_slug = c.slug and x.sub_slug = s.slug;
