-- Content & writing, Expert tier (days 61-80). Authored content, UNPUBLISHED until a person reviews it in Admin.
insert into public.day
  (track_id, tier_id, day_number, title, objective, lesson_md, skill_focus, assignment_md, rubric,
   est_minutes, is_published, credit_budget, submission_type, ai_evaluate, requires_review)
select t.id, ti.id, v.n, v.title, v.objective, v.lesson_md, v.skill_focus, v.assignment_md, v.rubric,
       v.est_minutes, false, null, v.submission_type, v.ai_evaluate, v.requires_review
from public.track t
join public.tier ti on ti.track_id = t.id and ti.slug = 'expert'
cross join (values
  (61, $t61a$Content strategy from business goals$t61a$, $t61b$Connect content to a measurable business outcome.$t61b$, $t61c$Strategy answers: what result do we need, for whom, and why will content produce it? Work backwards from one business goal (leads, retention, trust) to the audience action, then to the content types that prompt it. Every piece should have a job and a metric.$t61c$, $t61d$Content strategy from business goals$t61d$, $t61e$Choose a real or realistic organisation. Submit a one-page strategy: goal, audience action, content roles (attract, convince, retain), and one metric per role.$t61e$, $t61f$[{"criterion": "Goal to content logic", "max_points": 40, "guidance": "Traceable chain."}, {"criterion": "Roles and metrics", "max_points": 35, "guidance": "Specific."}, {"criterion": "Realistic scope", "max_points": 25, "guidance": "Feasible."}]$t61f$::jsonb, 45, 'text', false, false),
  (62, $t62a$Audience research and jobs to be done$t62a$, $t62b$Understand what readers are trying to get done.$t62b$, $t62c$People read to make progress: decide, learn, feel reassured. Interview five readers or customers about the moment they searched or asked for help. Capture their words, alternatives they tried and what made them choose.$t62c$, $t62d$Audience research and jobs to be done$t62d$, $t62e$Submit five interview summaries and three 'job statements' (When I..., I want..., so I can...).$t62e$, $t62f$[{"criterion": "Real interviews", "max_points": 40, "guidance": "Five."}, {"criterion": "Job statements sharp", "max_points": 35, "guidance": "Specific."}, {"criterion": "Insights usable", "max_points": 25, "guidance": "Change content."}]$t62f$::jsonb, 50, 'text', false, false),
  (63, $t63a$Editorial standards and style guides for teams$t63a$, $t63b$Write standards others can apply without you.$t63b$, $t63c$A team guide covers voice, structure templates, sourcing rules, fact-check steps, inclusive language, AI-use rules and the definition of done. Keep it short enough to be used and include examples of good and bad.$t63c$, $t63d$Editorial standards and style guides for teams$t63d$, $t63e$Write a two-page editorial standard including an AI-use policy and a definition of done.$t63e$, $t63f$[{"criterion": "Usable rules", "max_points": 35, "guidance": "Specific."}, {"criterion": "AI policy honest", "max_points": 35, "guidance": "Clear limits."}, {"criterion": "Definition of done", "max_points": 30, "guidance": "Checkable."}]$t63f$::jsonb, 20, 'text', false, false),
  (64, $t64a$AI-assisted content workflows with quality gates$t64a$, $t64b$Design a production line that stays accurate.$t64b$, $t64c$Map stages (brief, research, draft, edit, fact-check, approve, publish). Decide where AI helps and where a human must decide. Add gates: source check, brand check, legal check. Measure error rate at each gate.$t64c$, $t64d$AI-assisted content workflows with quality gates$t64d$, $t64e$Design a workflow diagram or list with gates, owners and an error log template.$t64e$, $t64f$[{"criterion": "Stages and owners", "max_points": 30, "guidance": "Clear."}, {"criterion": "Gates effective", "max_points": 40, "guidance": "Catch errors."}, {"criterion": "Measurement", "max_points": 30, "guidance": "Tracked."}]$t64f$::jsonb, 40, 'text', false, false),
  (65, $t65a$Expert project 1: a content strategy pack$t65a$, $t65b$Deliver a strategy a team could execute.$t65b$, $t65c$Show Module 1. Deliver a **content strategy pack**: goal, audience research, content roles and metrics, editorial standard and workflow with gates.

Your work is scored on the rubric below. You can revise and resubmit.$t65c$, $t65d$Expert project 1: a content strategy pack$t65d$, $t65e$Submit the pack (strategy, research summary, standard, workflow) as one document or linked sections.$t65e$, $t65f$[{"criterion": "Strategy logic", "max_points": 25, "guidance": "Goal to metric."}, {"criterion": "Research grounding", "max_points": 25, "guidance": "Real."}, {"criterion": "Standards and workflow", "max_points": 30, "guidance": "Usable."}, {"criterion": "Honesty and feasibility", "max_points": 20, "guidance": "Realistic."}]$t65f$::jsonb, 120, 'text', true, false),
  (66, $t66a$Search intent and discoverability$t66a$, $t66b$Write for the questions people actually ask.$t66b$, $t66c$Group queries by intent (learn, compare, buy, fix). Study what already ranks and find gaps you can fill with real expertise. Write for people first; do not stuff keywords or publish thin AI pages at scale, which search engines penalise.$t66c$, $t66d$Search intent and discoverability$t66d$, $t66e$Pick a topic. Submit ten queries grouped by intent, an analysis of three ranking pages and the gap you will fill.$t66e$, $t66f$[{"criterion": "Intent grouping", "max_points": 30, "guidance": "Correct."}, {"criterion": "Gap analysis", "max_points": 40, "guidance": "Insight."}, {"criterion": "Quality-first", "max_points": 30, "guidance": "No spam."}]$t66f$::jsonb, 45, 'text', false, false),
  (67, $t67a$Distribution and audience building$t67a$, $t67b$Get work in front of the right people.$t67b$, $t67c$Publishing is not distribution. Plan owned (email), earned (mentions, partners) and paid channels. Adapt the format to each and build relationships before you need them.$t67c$, $t67d$Distribution and audience building$t67d$, $t67e$Create a 30-day distribution plan for one flagship piece with channels, messages and targets.$t67e$, $t67f$[{"criterion": "Channels fit audience", "max_points": 35, "guidance": "Right places."}, {"criterion": "Adapted messages", "max_points": 35, "guidance": "Shaped."}, {"criterion": "Targets measurable", "max_points": 30, "guidance": "Numbers."}]$t67f$::jsonb, 20, 'text', false, false),
  (68, $t68a$Measurement: from vanity to outcomes$t68a$, $t68b$Choose metrics that show real impact.$t68b$, $t68c$Separate reach, engagement and outcomes. Track a few that link to the goal (sign-ups, qualified leads, retention), note attribution limits and avoid over-claiming.$t68c$, $t68d$Measurement: from vanity to outcomes$t68d$, $t68e$Design a measurement plan: three metrics, how each is captured, and the limits of what each proves.$t68e$, $t68f$[{"criterion": "Metrics tied to goal", "max_points": 40, "guidance": "Relevant."}, {"criterion": "Capture method", "max_points": 30, "guidance": "Feasible."}, {"criterion": "Limits stated", "max_points": 30, "guidance": "Honest."}]$t68f$::jsonb, 20, 'text', false, false),
  (69, $t69a$Experiments and learning loops$t69a$, $t69b$Test content changes properly.$t69b$, $t69c$State a hypothesis, change one thing, define success and sample size, run long enough and record the result even if it fails. Do not stop tests early when you like the result.$t69c$, $t69d$Experiments and learning loops$t69d$, $t69e$Design and run a small content test (headline, format or send time). Submit hypothesis, setup, results and what you will do next.$t69e$, $t69f$[{"criterion": "Valid design", "max_points": 40, "guidance": "One variable."}, {"criterion": "Results honest", "max_points": 35, "guidance": "Reported."}, {"criterion": "Decision made", "max_points": 25, "guidance": "Action."}]$t69f$::jsonb, 45, 'text', false, false),
  (70, $t70a$Expert project 2: a measured content experiment$t70a$, $t70b$Run a test and report the truth.$t70b$, $t70c$Show Module 2. Deliver a **measured experiment** on real content with hypothesis, distribution, measurement and conclusions including limits.

Your work is scored on the rubric below. You can revise and resubmit.$t70c$, $t70d$Expert project 2: a measured content experiment$t70d$, $t70e$Submit hypothesis, setup, distribution actions, data and conclusions.$t70e$, $t70f$[{"criterion": "Design validity", "max_points": 30, "guidance": "Sound."}, {"criterion": "Data and honesty", "max_points": 30, "guidance": "Real numbers."}, {"criterion": "Insight and next step", "max_points": 25, "guidance": "Useful."}, {"criterion": "Clarity", "max_points": 15, "guidance": "Readable."}]$t70f$::jsonb, 120, 'text', true, false),
  (71, $t71a$Authorship, ghostwriting and disclosure$t71a$, $t71b$Be clear about who wrote what.$t71b$, $t71c$Ghostwriting is legitimate when the named author agrees and the ideas are theirs. AI use complicates authorship: know client, publisher and platform rules and disclose where required. Never invent quotes, experiences or credentials.$t71c$, $t71d$Authorship, ghostwriting and disclosure$t71d$, $t71e$Write a disclosure and authorship policy for your work (six rules) with two example cases.$t71e$, $t71f$[{"criterion": "Rules clear", "max_points": 40, "guidance": "Practical."}, {"criterion": "Cases applied", "max_points": 35, "guidance": "Examples."}, {"criterion": "No invention", "max_points": 25, "guidance": "Integrity."}]$t71f$::jsonb, 30, 'text', false, false),
  (72, $t72a$Legal and ethical risks in publishing$t72a$, $t72b$Avoid defamation, copyright and privacy problems.$t72b$, $t72c$Know the basics: quoting versus copying, permission for images and text, defamation risk when naming people or firms, health and finance claims, privacy of interviewees. Get legal advice for anything high-risk. This course is not legal advice.$t72c$, $t72d$Legal and ethical risks in publishing$t72d$, $t72e$Audit a draft for risks: list each risky statement, the risk and the fix.$t72e$, $t72f$[{"criterion": "Risks spotted", "max_points": 45, "guidance": "Real."}, {"criterion": "Fixes proper", "max_points": 35, "guidance": "Practical."}, {"criterion": "Advice limits noted", "max_points": 20, "guidance": "Stated."}]$t72f$::jsonb, 20, 'text', false, false),
  (73, $t73a$Editing other people's work$t73a$, $t73b$Give edits that improve without erasing the writer.$t73b$, $t73c$Edit in layers: structure, paragraph, sentence, proof. Explain the why, ask before large changes and keep the writer's voice. Tone matters: be specific and kind.$t73c$, $t73d$Editing other people's work$t73d$, $t73e$Edit a 400-word piece (public or your own old work). Submit before, after and an edit note explaining five changes.$t73e$, $t73f$[{"criterion": "Layered edits", "max_points": 35, "guidance": "Structure to line."}, {"criterion": "Voice preserved", "max_points": 30, "guidance": "Respectful."}, {"criterion": "Reasons explained", "max_points": 35, "guidance": "Helpful."}]$t73f$::jsonb, 20, 'text', false, false),
  (74, $t74a$Managing writers and freelancers$t74a$, $t74b$Brief, manage and pay contributors well.$t74b$, $t74c$A good brief includes goal, audience, angle, sources, length, deadline, and examples. Set revision rounds, payment terms, rights and AI-use expectations in writing.$t74c$, $t74d$Managing writers and freelancers$t74d$, $t74e$Write a freelancer brief and agreement outline for one article.$t74e$, $t74f$[{"criterion": "Brief complete", "max_points": 40, "guidance": "All parts."}, {"criterion": "Terms clear", "max_points": 35, "guidance": "Rights, AI, pay."}, {"criterion": "Fair", "max_points": 25, "guidance": "Reasonable."}]$t74f$::jsonb, 20, 'text', false, false),
  (75, $t75a$Expert project 3: an editorial system for a team$t75a$, $t75b$Deliver the system that lets others produce quality.$t75b$, $t75c$Show Module 3. Deliver an **editorial system**: risk checklist, edit process, freelancer brief and terms, and a quality scorecard.

Your work is scored on the rubric below. You can revise and resubmit.$t75c$, $t75d$Expert project 3: an editorial system for a team$t75d$, $t75e$Submit all four with one worked example.$t75e$, $t75f$[{"criterion": "Completeness", "max_points": 25, "guidance": "All parts."}, {"criterion": "Risk handling", "max_points": 30, "guidance": "Sound."}, {"criterion": "Usable by others", "max_points": 25, "guidance": "Clear."}, {"criterion": "Ethics", "max_points": 20, "guidance": "Honest."}]$t75f$::jsonb, 120, 'text', true, false),
  (76, $t76a$Flagship piece: question and research$t76a$, $t76b$Start a piece that could be the best on its topic.$t76b$, $t76c$Choose a topic where you have or can gather original insight: interviews, data, a test. Define the question and gather primary evidence, not just summaries.$t76c$, $t76d$Flagship piece: question and research$t76d$, $t76e$Submit the question, research plan and first findings with sources.$t76e$, $t76f$[{"criterion": "Original angle", "max_points": 35, "guidance": "Fresh."}, {"criterion": "Evidence primary", "max_points": 40, "guidance": "Real."}, {"criterion": "Plan sound", "max_points": 25, "guidance": "Feasible."}]$t76f$::jsonb, 60, 'text', false, false),
  (77, $t77a$Flagship piece: structure and first draft$t77a$, $t77b$Build and draft the piece.$t77b$, $t77c$Outline the argument, choose the form (guide, essay, report) and draft with AI as assistant only. Keep your evidence and voice central.$t77c$, $t77d$Flagship piece: structure and first draft$t77d$, $t77e$Submit the outline and a 1,000-word first draft.$t77e$, $t77f$[{"criterion": "Argument clear", "max_points": 40, "guidance": "Structured."}, {"criterion": "Evidence used", "max_points": 35, "guidance": "Integrated."}, {"criterion": "Voice", "max_points": 25, "guidance": "Yours."}]$t77f$::jsonb, 90, 'text', false, false),
  (78, $t78a$Flagship piece: revise, verify, polish$t78a$, $t78b$Bring it to a professional standard.$t78b$, $t78c$Revise in layers, fact-check every claim, add sources, cut 10 percent and get one outside critique. Keep a changelog.$t78c$, $t78d$Flagship piece: revise, verify, polish$t78d$, $t78e$Submit the revised piece, verification log and critique notes.$t78e$, $t78f$[{"criterion": "Facts verified", "max_points": 40, "guidance": "Log."}, {"criterion": "Quality of revision", "max_points": 35, "guidance": "Better."}, {"criterion": "Critique used", "max_points": 25, "guidance": "Applied."}]$t78f$::jsonb, 90, 'text', false, false),
  (79, $t79a$Flagship piece: publish and distribute$t79a$, $t79b$Ship it and get it read.$t79b$, $t79c$Publish with strong headline, summary and images (alt text), then execute your distribution plan and record results for two weeks.$t79c$, $t79d$Flagship piece: publish and distribute$t79d$, $t79e$Submit the published link (or full text), distribution actions and early results.$t79e$, $t79f$[{"criterion": "Published well", "max_points": 35, "guidance": "Polished."}, {"criterion": "Distribution executed", "max_points": 40, "guidance": "Real."}, {"criterion": "Results honest", "max_points": 25, "guidance": "Numbers."}]$t79f$::jsonb, 60, 'text', false, false),
  (80, $t80a$Expert project 4: the flagship article with evidence of impact$t80a$, $t80b$Deliver your best piece and show what it did.$t80b$, $t80c$Show Module 4. Deliver a **flagship article** with original evidence, verified sources, distribution and measured results.

Your work is scored on the rubric below. You can revise and resubmit.$t80c$, $t80d$Expert project 4: the flagship article with evidence of impact$t80d$, $t80e$Submit the article, source and verification log, distribution summary and results with honest analysis.$t80e$, $t80f$[{"criterion": "Insight and originality", "max_points": 25, "guidance": "Original."}, {"criterion": "Accuracy and sourcing", "max_points": 30, "guidance": "Verified."}, {"criterion": "Craft and voice", "max_points": 25, "guidance": "Excellent."}, {"criterion": "Impact and honesty", "max_points": 20, "guidance": "Measured."}]$t80f$::jsonb, 150, 'text', true, false)
) as v(n, title, objective, lesson_md, skill_focus, assignment_md, rubric, est_minutes, submission_type, ai_evaluate, requires_review)
where t.slug = 'content'
on conflict (track_id, day_number) do nothing;
